DB-1016 : table_statistics and index_statistics are not updated corre…
percona/percona-server pull request #1091
Opened 2016-10-03 20:57 UTC by georgelorchpercona

…ctly

- Added userstat counter increments in TokuDB codebase
- Split percona_userstat.test into engine agnostic test and engine specific tests, specifically, split out tests for table_statistics and index_statistics into .inc file.
- Created two new engine specific tests, one for innodb and one for tokudb that source the new percona_table_index_statistics test/

2016-10-03 20:58 UTC, georgelorchpercona commented
jenkins here http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1431/

@laurynas-biveinis, please review percona_userstat test changes to see if we are thinking alike or if you prefer a different approach. I'm holding off the merge to 5.7 until we have decided on the best test case layout.

2016-10-10 07:13 UTC, laurynas-biveinis requested changes

2016-10-10 07:13 UTC, laurynas-biveinis commented on mysql-test/include/percona_table_index_statistics.inc
> +DROP TABLE IF EXISTS t1;
This idiom is redundant

2016-10-10 07:13 UTC, laurynas-biveinis commented on storage/tokudb/ha_tokudb.cc
> +#ifdef EXTENDED_FOR_USERSTAT
Please don't add and remove EXTENDED_FOR_USERSTAT macro when you touch it

2016-10-10 07:13 UTC, laurynas-biveinis commented on storage/tokudb/ha_tokudb.cc
>          added_rows++;
Consider pulling this up to handler level

2016-10-17 22:06 UTC, georgelorchpercona commented
new jenkins after pulling all userstat into base handler http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1445/

2016-10-18 05:33 UTC, laurynas-biveinis requested changes
I've been also thinking about a Percona "engines" suite for XtraDB/Toku/Rocks, as you had suggested before. Userstat and kill idle transaction feature I'm working on are good candidates for this. But I'm not sure how to approach this, as the current engines suites need big --mysqld= incantation to work, and only test one engine. Maybe we need an internal-to-MTR loop over engines for selected tests, similar to how binlog tests loop over binlog formats.

2016-10-18 05:33 UTC, laurynas-biveinis commented on sql/handler.cc
> +  if (!result)
Extract a helper method?

2016-10-18 05:33 UTC, laurynas-biveinis commented on sql/handler.cc
> +  if (!result)
IIRC, at the InnoDB level UNIV_UNLIKELY has been added to the corresponding snippet after branch misprediction profiling, i.e. it's useful. Maybe here we should do `if (likely(!result))` as well

2016-10-18 17:08 UTC, george-lorch commented on sql/handler.cc
> +  if (!result)
Good call.

2016-10-18 17:10 UTC, george-lorch commented on sql/handler.cc
> +  if (!result)
I considered one but wasn't sure if it was worth more pollution of the handler class. The Maria implementation uses one. Since you suggest it I assume that pollution isn't too big of an issue, I'll refactor and push.

2016-10-20 21:19 UTC, georgelorchpercona commented
New branch pushed with branch prediction macros and factored out inline function to tickle counters.
jenkins at http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1449/

2016-10-21 06:35 UTC, laurynas-biveinis requested changes
Approved with the three "likely" added

2016-10-21 06:35 UTC, laurynas-biveinis commented on sql/handler.cc
> +  if (!is_fake_change_enabled(ha_thd()))
likely

2016-10-21 06:35 UTC, laurynas-biveinis commented on sql/handler.cc
> +  if (!is_fake_change_enabled(ha_thd()))
likely

2016-10-21 06:35 UTC, laurynas-biveinis commented on sql/handler.cc
> +  if (!is_fake_change_enabled(ha_thd()))
likely

2016-10-21 13:25 UTC, georgelorchpercona commented on sql/handler.cc
> +  if (!is_fake_change_enabled(ha_thd()))
Thanks, I considered that but then if someone is using fake changes (unlikely, heh), they will have 100% branch prediction miss so didn't think it was a good case for it.

2016-10-21 13:33 UTC, laurynas-biveinis commented on sql/handler.cc
> +  if (!is_fake_change_enabled(ha_thd()))
The use case is I/O bound, and we have to consider the needs of 99.95% users who don't use it :)

2016-10-21 13:48 UTC, georgelorchpercona commented on sql/handler.cc
> +  if (!is_fake_change_enabled(ha_thd()))
Fair enough

2016-10-24 08:48 UTC, laurynas-biveinis approved these changes

2016-10-27 18:05 UTC, merged