MYR-7 : myrocks needs extra initialization step during .frm opening
percona/percona-server pull request #1126
Opened 2016-10-22 01:45 UTC by georgelorchpercona

- Added virtual handler call init_with_fields, call from open_binary_frm and pass through partition handler as required by MyRocks and implemented in webscale.

2016-10-22 01:45 UTC, georgelorchpercona commented
https://jira.percona.com/browse/MYR-7
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1454/

2016-10-24 07:52 UTC, laurynas-biveinis commented
It is not entirely clear why this needs to be done - MYR and blueprints say that it "needs", and that's all. A bit of suggestion is in the new field name and in the final diff comment re. HA_PRIMARY_KEY_IN_READ_INDEX - can you please elaborate?

2016-10-24 15:40 UTC, georgelorchpercona commented
The patch originated from Sergei Petrunia here https://github.com/facebook/mysql-5.6/commit/c1f1f0b64eaecd132fc6ec21663faf0510afacaf : Index-only scans do not work for partitioned tables and extended keys

I have added a bit more description in the MYR and blueprint taken from Sergeis original patch.

2016-10-25 09:50 UTC, laurynas-biveinis requested changes

2016-10-25 09:50 UTC, laurynas-biveinis commented on sql/ha_partition.h
> +   /*
This comment is redundant...

2016-10-25 09:50 UTC, laurynas-biveinis commented on sql/handler.h
> +    For MyRocks, secondary initialization that happens after frm is parsed into
... this one is not, and again it should mention as an example that MyRocks uses it to adjust HA_PRIMARY_KEY_IN_READ_INDEX

2016-10-25 09:50 UTC, laurynas-biveinis commented on sql/handler.h
> +    For MyRocks, secondary initialization that happens after frm is parsed into
Return values: false success, true failure

2016-10-25 21:51 UTC, georgelorchpercona commented
Done...

2016-10-26 07:56 UTC, laurynas-biveinis approved these changes

2016-10-27 17:52 UTC, merged