MYR-17 : Improvement for const correctness to my_hash used by myrocks
percona/percona-server pull request #1140
Opened 2016-10-25 23:29 UTC by georgelorchpercona

- Copied in upstream improvement to my_hash for myrocks

2016-10-25 23:29 UTC, georgelorchpercona commented
https://jira.percona.com/browse/MYR-17
https://jira.percona.com/browse/MYR-22
https://blueprints.launchpad.net/percona-server/+spec/myrocks-const-correct-5.6
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1459/

2016-10-26 07:35 UTC, laurynas-biveinis requested changes
Same comment for bug vs blueprint as for MYR-22 (also no change required for that)

2016-10-26 07:35 UTC, laurynas-biveinis commented on mysys/hash.c
> +    return dynamic_element(&hash->array,idx,const HASH_LINK*)->data;
spaces after commas

2016-10-27 18:01 UTC, georgelorchpercona commented on mysys/hash.c
> +    return dynamic_element(&hash->array,idx,const HASH_LINK*)->data;
Done and fixed existing issue just above as well.

2016-10-28 06:46 UTC, laurynas-biveinis approved these changes

2016-10-28 16:35 UTC, merged