Merge compressed columns functionality from 5.6 to 5.7
percona/percona-server pull request #1147
Opened 2016-10-28 14:57 UTC by percona-ysorokin

2016-10-28 15:01 UTC, percona-ysorokin commented
Jenkins build link (with --big-test)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/487/
Fix for 32-bit CentOS is already included - a new Jenkins link will be added when the build is ready.

2016-10-31 10:34 UTC, percona-ysorokin commented
An updated Jenkins build link (with --big-test)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/490/

2016-11-02 10:35 UTC, laurynas-biveinis commented
Is column compression disabled for internal temp tables only, or for CREATE TEMPORARY TABLE too?

2016-11-02 11:07 UTC, percona-ysorokin commented
Yes, for internal temp tables only.
`CREATE TEMPORARY TABLE` behavior wasn't changed

```sql
CREATE TEMPORARY TABLE t1(id INT, a BLOB COLUMN_FORMAT COMPRESSED) ENGINE=InnoDB;
SHOW CREATE TABLE t1;
```
```
Table   Create Table
t1      CREATE TEMPORARY TABLE `t1` (
  `id` int(11) DEFAULT NULL,
  `a` blob /*!50633 COLUMN_FORMAT COMPRESSED */
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

2016-11-02 11:16 UTC, laurynas-biveinis requested changes

2016-11-02 11:16 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/r/xtradb_compressed_columns_alter_table.result
> +*** "a BLOB" -> "a BLOB", ALGOTIRHM=DEFAULT
"ALGOTIRHM"

2016-11-02 11:16 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/r/xtradb_compressed_columns_alter_table.result
> +1
This result file could be shrinked by assert.inc use? (for 5.6 too; not for this PR)

2016-11-02 11:16 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/r/xtradb_compressed_columns_mysqldump.result
> +1
Likewise

2016-11-02 11:16 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/r/xtradb_compressed_columns_with_dictionaries.result
> +1
Likewise

2016-11-02 11:16 UTC, laurynas-biveinis commented on sql/sql_lex.cc
> +const LEX_CSTRING null_lex_cstr= {NULL, 0};
Duplication

2016-11-02 11:16 UTC, laurynas-biveinis commented on sql/sql_lex.h
> +extern const LEX_CSTRING null_lex_cstr;
Duplication

2016-11-02 11:16 UTC, laurynas-biveinis commented on sql/sql_table.cc
> +      DBUG_EXECUTE_IF("enforce_all_compressed_columns",
Please do a enforce_all_compressed_columns / remove_compressed_attributes_for_keys run if you haven't

2016-11-02 11:16 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +	templ->compressed = (field->column_format()
Is it surrounding or patch indentation which is wrong?

2016-11-02 11:16 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +			/* Do not compress blob column while comparing*/
Space after "comparing"

2016-11-02 11:16 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.h
> +
One less empty line

2016-11-02 11:16 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.h
> +typedef std::map<uint16, ulint, std::less<uint16>,
typedefs for uint16 and ulint?

2016-11-02 11:16 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/xtradb_compressed_columns_consistency_antelope_compact.test
> +--source include/big_test.inc
Should these be marked as big in 5.6 too?

2016-11-02 14:36 UTC, percona-ysorokin commented on sql/sql_lex.cc
> +const LEX_CSTRING null_lex_cstr= {NULL, 0};
LEX_**C**STRING (const char *)

2016-11-02 14:38 UTC, percona-ysorokin commented on mysql-test/suite/innodb/r/xtradb_compressed_columns_alter_table.result
> +*** "a BLOB" -> "a BLOB", ALGOTIRHM=DEFAULT
fixed

2016-11-02 14:39 UTC, percona-ysorokin commented on storage/innobase/handler/ha_innodb.cc
> +	templ->compressed = (field->column_format()
fixed (although previous lines use spaces for indentation)

2016-11-02 14:39 UTC, percona-ysorokin commented on storage/innobase/handler/ha_innodb.cc
> +			/* Do not compress blob column while comparing*/
fixed

2016-11-02 14:40 UTC, percona-ysorokin commented on storage/innobase/handler/ha_innodb.h
> +
fixed

2016-11-02 14:45 UTC, percona-ysorokin commented on storage/innobase/handler/ha_innodb.h
> +typedef std::map<uint16, ulint, std::less<uint16>,
`uint16` is exactly how `Field::field_index` is defined
```c++
uint16        field_index;            // field number in fields array
```

2016-11-02 14:45 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/xtradb_compressed_columns_consistency_antelope_compact.test
> +--source include/big_test.inc
on my list

2016-11-23 13:14 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/517/
(Yakkety included)

2016-11-24 10:35 UTC, laurynas-biveinis requested changes

2016-11-24 10:35 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/xtradb_compressed_columns.test
> +# removing STRICT_TRANS_TABLES from sql_mode
Why?

2016-11-24 10:35 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/xtradb_compressed_columns_virtual.test
> +SELECT SLEEP(3);
1) SLEEP is a testcase smell - while here random scheduling will not cause a testcase failure, that would require clarification; 2) it is not safe to update global debug variable while background threads may access it (purge in this instance). Can this be replaced by e.g.

wait for purge to complete;
SET GLOBAL debug="+d,ib_purge_virtual_index_callback";
UPDATE ...
wait for purge to complete;
SET GLOBAL debug="-d,ib_purge_virtual_index_callback";

2016-11-24 10:35 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/xtradb_compressed_columns_with_dictionaries.test
> +# check if tables deleted implicitly via "DROP DATABASE" aslo perform
"also"

2016-11-24 10:35 UTC, laurynas-biveinis commented on sql/field.cc
> +    changing column format to/from compressed or changing assiciated
associated

2016-11-24 10:35 UTC, laurynas-biveinis commented on storage/innobase/handler/handler0alter.cc
> +				/* Skip compressed varchar column when
Why?

2016-11-24 10:35 UTC, laurynas-biveinis commented on storage/innobase/handler/handler0alter.cc
> +	row_prebuilt_t*	prebuilt)
Indentation

2016-11-24 10:35 UTC, laurynas-biveinis commented on storage/innobase/row/row0mysql.cc
> +	/* As micro-SQL does not support int4 == int8 comparisons,
You found its name!

2016-11-24 13:03 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/xtradb_compressed_columns_with_dictionaries.test
> +# check if tables deleted implicitly via "DROP DATABASE" aslo perform
fixed

2016-11-24 13:04 UTC, percona-ysorokin commented on sql/field.cc
> +    changing column format to/from compressed or changing assiciated
fixed

2016-11-24 13:10 UTC, percona-ysorokin commented on storage/innobase/handler/handler0alter.cc
> +	row_prebuilt_t*	prebuilt)
fixed

2016-11-24 13:30 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/xtradb_compressed_columns.test
> +# removing STRICT_TRANS_TABLES from sql_mode
Some checks rely on data truncation being treated as a warning.
Without modifying sql_mode some INSERT statements will generate errors.

2016-11-24 13:31 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/xtradb_compressed_columns.test
> +# removing STRICT_TRANS_TABLES from sql_mode
Can INSERT IGNORE be used for those (I assume only a few) statements?

2016-11-24 15:17 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/xtradb_compressed_columns.test
> +# removing STRICT_TRANS_TABLES from sql_mode
Good Idea.
Reworked with "INSERT IGNORE"

2016-11-24 15:21 UTC, percona-ysorokin commented on storage/innobase/handler/handler0alter.cc
> +				/* Skip compressed varchar column when
It looks like an artifact from the original "compressed columns" patch by Weixiang Zhai.
This code path is never reached.
Fragment removed.

2016-11-24 17:07 UTC, percona-ysorokin commented on mysql-test/suite/innodb/t/xtradb_compressed_columns_virtual.test
> +SELECT SLEEP(3);
Rewritten with `--source include/wait_innodb_all_purged.inc`

2016-11-25 10:42 UTC, percona-ysorokin commented
Jenkins build for commit d142eb0
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/529/
(includes --big-test)

2016-11-28 09:13 UTC, laurynas-biveinis approved these changes

2016-11-28 12:43 UTC, merged