MYR-15 : Optionally block/log queries relying on Gap Locks
percona/percona-server pull request #1162
Opened 2016-11-15 22:47 UTC by georgelorchpercona

- Implemented partial patch to raise error if SE is transactional, does not support gap locks and a gap lock is being attempted.
- Implemented new handler virtual calls for has_gap_locks() in different SEs that need it.
- Imported and adjusted test cases for gap lock errors and added partition test.
- Disabled numerous MyRocks tests as a result of using SQL that invokes 'missing' gap lock functionality and generates new gap lock error.

2016-11-15 22:47 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1469/

2016-11-16 08:19 UTC, laurynas-biveinis requested changes

2016-11-16 08:19 UTC, laurynas-biveinis commented on mysql-test/include/gap_lock_error_cleanup.inc
> +--exec grep "Got error" $MYSQLTEST_VARDIR/log/mysqld.1.err | grep "gap" | wc -l
This is going to be unstable down the road: by default the error log includes all the content from all the preceding tests, thus it can be anything. If you really need to grep the error log, add a temp error log option to mysqld for a testcase (and use include/search_pattern_in_file.inc)

2016-11-16 08:19 UTC, laurynas-biveinis commented on mysql-test/include/gap_lock_error_cleanup.inc
> +flush general logs;
Why do you need this?

2016-11-16 08:19 UTC, laurynas-biveinis commented on mysql-test/include/gap_lock_error_cleanup.inc
> +drop table if exists gap1, gap2, gap3, gap4;
No need for "if exists"? Better to catch testcase bugs early :)

2016-11-16 08:19 UTC, laurynas-biveinis commented on mysql-test/include/gap_lock_error_init.inc
> +--enable_warnings
Obsolete idiom, just remove

2016-11-16 08:19 UTC, laurynas-biveinis commented on mysql-test/t/gap_lock_error_memory_myisam.test
> +let $engine=memory;
File name says myisam, engine says memory

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/ha_partition.cc
> +  } while (*(++file));
Is it not enough to check only the first partition?

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/ha_partition.cc
> +bool ha_partition::has_gap_locks()
Let's make a note somewhere (maybe in the 8.0 blueprint), that when legacy partitioning is dead, this method should move from handler (per-table property) to handlerton (per-SE property), which it fundamentally is, if not ha_partition

2016-11-16 08:19 UTC, laurynas-biveinis commented on mysql-test/include/gap_lock_error_select.inc
> +eval select * from gap3 force index(ui) where value=1 $select_lock;
Add a comment for non-failing cases why they don't fail?

2016-11-16 08:19 UTC, laurynas-biveinis commented on mysql-test/t/gap_lock_error_memory_myisam.test
> +let $engine=myisam;
Duplicated?

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/ha_partition.h
> +  virtual bool has_gap_locks();
const

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/handler.h
> +bool can_hold_read_locks_on_select(THD *thd, thr_lock_type lock_type);
static (looks like a helper method which has little to do with handler, and not that much even with THD)

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/handler.h
> +  bool is_using_full_key(key_part_map keypart_map, uint actual_key_parts);
If possible, move somewhere more applicable, otherwise static

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/handler.h
> +  bool is_using_full_unique_key(uint active_index,
const

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/handler.h
> +bool can_hold_locks_on_trans(THD *thd, thr_lock_type lock_type);
Likewise

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/handler.h
> +  bool is_using_prohibited_gap_locks(TABLE* table,
const

2016-11-16 08:19 UTC, laurynas-biveinis commented on sql/handler.h
> +  virtual bool has_gap_locks() { return false; }
const

2016-11-16 08:19 UTC, laurynas-biveinis commented on storage/tokudb/ha_tokudb.h
> +    bool has_gap_locks() { return true; }
const

2016-11-16 08:19 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.h
> +	bool has_gap_locks() { return true; }
const

2016-11-16 08:19 UTC, laurynas-biveinis commented on storage/blackhole/ha_blackhole.h
> +  bool has_gap_locks() { return true; }
const

2016-11-16 22:34 UTC, georgelorchpercona commented on mysql-test/include/gap_lock_error_cleanup.inc
> +--exec grep "Got error" $MYSQLTEST_VARDIR/log/mysqld.1.err | grep "gap" | wc -l
Makes sense, this was copied/inherited from the upstream test and I didn't think much of it. I might report it to them for the same reasons.

2016-11-16 22:35 UTC, george-lorch commented on mysql-test/include/gap_lock_error_cleanup.inc
> +flush general logs;
Not sure, again, inherited from upstream test and didn't give it a second thought. I wonder if it has something to do with clearing state of the gap lock log that would have been part of that patch. For our purposes I can't see how or where it would be needed at all.

2016-11-16 22:37 UTC, georgelorchpercona commented on mysql-test/t/gap_lock_error_memory_myisam.test
> +let $engine=memory;
Again, inherited from upstream patch. Filename says both myisam and memory, it tests both engines. Maybe should be split up into two different tests.

2016-11-16 22:38 UTC, georgelorchpercona commented on sql/ha_partition.cc
> +bool ha_partition::has_gap_locks()
Yeah, well I would also hope that by then we have gap lock support and can drop this entirely, but then, this still might make sense to keep around.

2016-11-16 22:40 UTC, george-lorch commented on sql/ha_partition.cc
> +  } while (*(++file));
Maybe, but I believed there were conditions where a single partition could be altered to use a different engine than was created with, this is being a bit over conservative based on other behaviors in ha_partition to ensure nothing slips through the cracks.

2016-11-16 23:01 UTC, georgelorchpercona commented on mysql-test/include/gap_lock_error_cleanup.inc
> +--exec grep "Got error" $MYSQLTEST_VARDIR/log/mysqld.1.err | grep "gap" | wc -l
Actually, this is a really good catch. I'm not sure why this is looking into the err log as there is nowhere that anything is ever written to the server error log on a gap lock violation, all errors go to the client and in the upstream patch they are also optionally written to the gap lock log. I believe this serves no useful purpose at all.

2016-11-16 23:48 UTC, georgelorchpercona commented on sql/ha_partition.cc
> +bool ha_partition::has_gap_locks()
Originally I was going to add it just as a handlerton flag, then implement the virtual similar to has_transactions that just returns flagset & flag, but the handlerton flags seems to be getting full and is not possible/practical for the partition handler to accurately reflect what the underlying handlerton supports via the HTON flags. Also as mentioned elsewhere, it is my understanding (perhaps incorrect) that there are some ways to alter the engine of an individual partition within a partitioned table, thus requiring something like this to scan all of the partitions to ensure 100% support.

2016-11-17 00:11 UTC, georgelorchpercona commented on sql/handler.h
> +bool can_hold_read_locks_on_select(THD *thd, thr_lock_type lock_type);
These two actually look like unnecessary refactors and could/should probably just have their logic expanded inline. They are used from one place in handler.cc, the new method is_using_prohibited_gap_locks, and was a factor out of ha_innodb.cc.

2016-11-18 18:34 UTC, georgelorch commented
Some changes made as discussed and new jenkins http://jenkins.percona.com/job/percona-server-5.6-param/1474/

2016-11-21 07:50 UTC, laurynas-biveinis approved these changes

2016-11-22 15:29 UTC, merged