Bug 1641910: Trying to set audit_log_exclude_accounts crashes server
percona/percona-server pull request #1175
Opened 2016-11-21 02:34 UTC by gl-sergei

The root cause of this bug is that logic around filtering variables rely
heavily on the fact that CHECK and UPDATE functions are always called.
This is not true when variables passed via defaults file or set as
command line options.

The fix is add special handling for filtering variables on startup.

http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1477/

2016-11-21 07:41 UTC, laurynas-biveinis requested changes

2016-11-21 07:41 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_acc.test
> +--exec echo "wait" > $MYSQLTEST_VARDIR/tmp/mysqld.1.expect
Here and everywhere please use include/restart_mysqld.inc, it supports restart parameters.

2016-11-21 07:41 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_acc.test
> +# Bug 1641910: Trying to set audit_log_exclude_accounts crashes server.
Use one of the existing test cases?

2016-11-21 07:41 UTC, laurynas-biveinis commented on plugin/audit_log/audit_log.c
> +  if (audit_log_exclude_accounts != NULL && audit_log_include_accounts != NULL)
IMHO this added code belongs to audit_log_filter_init, up to you to consider

2016-11-22 18:44 UTC, gl-sergei commented on plugin/audit_log/audit_log.c
> +  if (audit_log_exclude_accounts != NULL && audit_log_include_accounts != NULL)
audit_log_filer_init located in separate module and doesn't know about plugin variables. This code is aimed to validate plugin variables.

2016-11-22 18:48 UTC, gl-sergei commented on mysql-test/t/audit_log_acc.test
> +# Bug 1641910: Trying to set audit_log_exclude_accounts crashes server.
This test case does a lot of server restarts to test how different variables combinations are tested on startup. We don't have similar test cases currently.

2016-11-22 18:49 UTC, gl-sergei commented on mysql-test/t/audit_log_acc.test
> +# Bug 1641910: Trying to set audit_log_exclude_accounts crashes server.
the name is bad... maybe name it audit_log_bug1641910?

2016-11-22 21:27 UTC, gl-sergei commented on mysql-test/t/audit_log_acc.test
> +--exec echo "wait" > $MYSQLTEST_VARDIR/tmp/mysqld.1.expect
done

2016-11-23 07:34 UTC, laurynas-biveinis requested changes

2016-11-23 07:34 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_acc.test
> +# Bug 1641910: Trying to set audit_log_exclude_accounts crashes server.
audit_log_startup ?

2016-11-24 01:09 UTC, gl-sergei commented
Renamed test case to `audit_log_startup`.
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1489/

2016-11-24 09:03 UTC, laurynas-biveinis approved these changes

2017-01-23 07:29 UTC, merged