Fix bug 1641910 in 5.7
percona/percona-server pull request #1176
Opened 2016-11-21 02:35 UTC by gl-sergei

http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/509/

2016-11-21 07:44 UTC, laurynas-biveinis requested changes

2016-11-21 07:44 UTC, laurynas-biveinis commented on plugin/audit_log/audit_log.c
> +    fprintf(stderr, "Both 'audit_log_exclude_accounts' and "
my_plugin_log_message(... MY_ERROR_LEVEL, ...) ?

2016-11-24 01:09 UTC, gl-sergei commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/521/

2016-11-24 09:04 UTC, laurynas-biveinis approved these changes

2017-01-23 07:29 UTC, merged