Merge branch '5.6-ps-bug728082' into 5.7-ps-bug728082
percona/percona-server pull request #1179
Opened 2016-11-23 03:27 UTC by ihanick

http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/514/

2016-11-23 07:25 UTC, laurynas-biveinis requested changes
Same as 5.5

2016-11-23 09:55 UTC, ihanick commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/516/
- merge with -master.opt change

2016-11-24 02:15 UTC, ihanick commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/520/
merge with 5.6 test split

2016-11-24 08:53 UTC, laurynas-biveinis approved these changes

2016-11-24 09:00 UTC, merged