Fixed lp:1633957 "sql/field.h:918: bool Field::has_associated_compres…
percona/percona-server pull request #1210
Opened 2016-11-28 14:33 UTC by percona-ysorokin

…sion_dictionary() const: Assertion `zip_dict_name.str == 0 || column_format() == COLUMN_FORMAT_TYPE_COMPRESSED' failed"

Backported from 5.7.

2016-11-28 14:34 UTC, percona-ysorokin commented
Not GCA as it does not include "compressed columns" yet.

2016-11-28 18:22 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1498/

2016-11-29 05:14 UTC, laurynas-biveinis requested changes

2016-11-29 05:14 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/r/xtradb_compressed_columns_with_dictionaries.result
> +*** "a BLOB COLUMN_FORMAT COMPRESSED" -> "a BLOB", ALGOTIRHM=DEFAULT
"ALGORITHM"

2016-11-29 16:33 UTC, percona-ysorokin commented
Updated Jenkins build link
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1500/

2016-11-30 05:08 UTC, laurynas-biveinis approved these changes

2016-11-30 12:03 UTC, merged