Merge branch '5.5-ps-bug801989' into 5.6-ps-bug801989
percona/percona-server pull request #1231
Opened 2016-12-09 02:16 UTC by ihanick

#1230 

http://jenkins.percona.com/job/percona-server-5.6-param/1520/

2016-12-09 10:27 UTC, laurynas-biveinis requested changes

2016-12-09 10:27 UTC, laurynas-biveinis commented on storage/innobase/include/os0file.h
> +ibool
C++ "bool" in 5.6+, s/TRUE/true, FALSE/false in the header comment above and in the code

2016-12-11 12:42 UTC, ihanick commented
- using c++ bool
http://jenkins.percona.com/job/percona-server-5.6-param/1524/

2016-12-12 07:10 UTC, laurynas-biveinis approved these changes

2016-12-13 08:15 UTC, merged