Merge branch '5.6-ps-bug801989' into 5.7-ps-bug801989
percona/percona-server pull request #1232
Opened 2016-12-09 02:21 UTC by ihanick

https://bugs.launchpad.net/percona-server/+bug/801989

#1231 5.6 PR
#1230 5.5 PR

Changed ibool type of os_file_set_nocache too bool.
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/541/

2016-12-09 10:39 UTC, laurynas-biveinis requested changes

2016-12-09 10:39 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +		/* Do fsync() on log files when setting O_DIRECT fails.
"on log and parallel doublewrite files" - see buf_parallel_dblwr_file_create, which sets O_DIRECT on the parallel doublewrite buffer, and buf_dblwr_flush_buffered_writes, which also skips flushing on SRV_UNIX_ALL_O_DIRECT. The code is correct, only the comment needs clarifying.

2016-12-11 12:43 UTC, ihanick commented
- added comment for doublewrite buffer
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/544/

2016-12-12 07:11 UTC, laurynas-biveinis approved these changes

2016-12-13 08:16 UTC, merged