Fix lp:1647530 "InnoDB: Failing assertion: success | InnoDB: page_zip_apply_log: 97>>1 > 1 | InnoDB: unable to decompress space 6 page 3".
percona/percona-server pull request #1248
Opened 2016-12-15 15:24 UTC by percona-ysorokin

Fixed problem with 'page_zip_fields_encode()' not taking into account additional 2 bytes header for columns with 'COLUMN_FORMAT COMPRESSED' attributes.

'innodb.xtradb_compressed_columns' MTR test case extended with checks for selecting data from a table with 'ROW_FORMAT=COMPRESSED' and 'COLUMNS_FORMAT COMPRESSED' after executing "SET GLOBAL innodb_buffer_pool_evict = 'uncompressed'".

'innodb.xtradb_compressed_columns_consistency_barracuda_compressed' MTR test case now also performs InnoDB buffer pool eviction and another identical 'SELECT' just after the original 'SELECT'.

2016-12-15 15:25 UTC, percona-ysorokin commented
Jenkins build link (--big-test)
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1529/

2016-12-16 05:27 UTC, laurynas-biveinis requested changes

2016-12-16 05:27 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/xtradb_compressed_columns.test
> +if($debug_build)
Better start a new testcase, xtradb_compressed_columns_debug.test

2016-12-21 16:12 UTC, percona-ysorokin commented
Updated Jenkins build
http://jenkins.percona.com/job/percona-server-5.6-param/1555/

2016-12-22 09:29 UTC, laurynas-biveinis approved these changes

2016-12-22 14:01 UTC, merged