Cherry pick MTR test cases from the 5.6 fix for lp:1647530 "InnoDB:Failing assertion: success | InnoDB: page_zip_apply_log: 97>>1 > 1 | InnoDB: unable to decompress space 6 page 3".
percona/percona-server pull request #1249
Opened 2016-12-15 15:26 UTC by percona-ysorokin

2016-12-15 20:09 UTC, percona-ysorokin commented
Jenkins build link (--big-test)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/548/

2016-12-16 05:42 UTC, laurynas-biveinis requested changes
Same comment as for 5.6

2016-12-21 16:11 UTC, percona-ysorokin commented
Updated Jenkins build
http://jenkins.percona.com/job/percona-server-5.6-param/1555/

2016-12-22 09:30 UTC, laurynas-biveinis approved these changes

2016-12-22 14:02 UTC, merged