Disable tokudb backup on --innodb-use-native-aio=on
percona/percona-server pull request #1270
Opened 2016-12-30 11:15 UTC by vlad-lesin

See https://tokutek.atlassian.net/browse/BACKUP-121.
http://jenkins.percona.com/job/percona-server-5.6-param/1573/

2017-01-02 07:31 UTC, laurynas-biveinis requested changes

2017-01-02 07:31 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb.backup/t/tokudb_backup_disable_if_innodb_use_native_aio_enabled.test
> +--source include/have_tokudb_backup.inc
--source include/have_innodb.inc

2017-01-02 07:31 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb.backup/t/tokudb_backup_disable_if_innodb_use_native_aio_enabled.test
> +--let $restart_parameters= restart:--innodb-use-native-aio=off
Maybe not required? This is basic backup functionality, other tests in this suite already exercise it

2017-01-02 07:31 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb.backup/t/tokudb_backup_disable_if_innodb_use_native_aio_enabled.test
> +# Check if tokudb hot backup is prevented if innodb_use_native_aio enabled
Very long test name - IMHO "innodb_native_aio.test" would be as descriptive

2017-01-26 15:40 UTC, vlad-lesin commented on mysql-test/suite/tokudb.backup/t/tokudb_backup_disable_if_innodb_use_native_aio_enabled.test
> +# Check if tokudb hot backup is prevented if innodb_use_native_aio enabled
done

2017-01-26 15:41 UTC, vlad-lesin commented on mysql-test/suite/tokudb.backup/t/tokudb_backup_disable_if_innodb_use_native_aio_enabled.test
> +--source include/have_tokudb_backup.inc
done

2017-01-26 15:41 UTC, vlad-lesin commented on mysql-test/suite/tokudb.backup/t/tokudb_backup_disable_if_innodb_use_native_aio_enabled.test
> +--let $restart_parameters= restart:--innodb-use-native-aio=off
done

2017-01-26 15:41 UTC, vlad-lesin commented
Laurynas, could you review it once more please?

2017-01-26 15:42 UTC, vlad-lesin commented
And 5.7 branch too.

2017-01-27 04:41 UTC, laurynas-biveinis approved these changes

2017-01-27 08:46 UTC, merged