Fixed LP bug #1595263 for server variables
percona/percona-server pull request #1296
Opened 2017-01-18 16:34 UTC by hrvojem

moved unique_checks description to known issues as it shoud gain better
visibility there

2017-01-18 17:34 UTC, george-lorch requested changes

2017-01-18 17:34 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_variables.rst
> +checkpoint. It uses old algorithm to set pool size to 4 / num_cpu_threads.
This variable defines the number of threads for the cachetable worker thread pool. This pool is used to perform node prefetches, and to serialize, compress, and write nodes during cachetable eviction.
The default value of 0 calculates the pool size to be num_cpu_threads * 2.

2017-01-18 17:34 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_variables.rst
> +session disabling checkpointing disables it globally. Special purpose only, do
If a session sets this lock and disconnects or terminates for any reason, the lock will not be released.

2017-01-18 17:34 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_variables.rst
> +This variable controls the Fractal Tree fanout.
The fanout defines the number of 'pivot' keys or child nodes for each internal tree node.

Changing the value of :variable:`tokudb_fanout` only affects subsequently created tables and indexes. The value of this variable cannot be changed for an existing table/index without a dump and reload.

2017-01-19 09:28 UTC, hrvojem commented
Fixed/pushed version which addresses the comments

2017-02-20 16:41 UTC, george-lorch approved these changes
TokuDB stuff looks good

*edit : Oops, no, wait...*

2017-02-20 16:45 UTC, george-lorch requested changes

2017-02-20 16:45 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_variables.rst
> +Uses old algorithm to set pool size to ``num_cpu_threads/4``.
"Default of 0 uses old algo..."

2017-02-20 16:45 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_variables.rst
> +algorithm to set pool size to 1 * num_cpu_threads.
Default value of 0 uses old ...

2017-02-21 20:37 UTC, george-lorch approved these changes

2017-02-21 20:39 UTC, merged