Bug#1592694 Query plan temp flag set is missed in create_duplicate_we…
percona/percona-server pull request #1299
Opened 2017-01-19 10:06 UTC by robgolebiowski

2017-01-20 04:08 UTC, laurynas-biveinis commented
Please always update the bug status once you are working on it (assignment, 5.5/5.6/5.7 series, In Progress, Fix Committed, Fix Released, Invalid, Won't Fix etc.). For this bug 5.5 and 5.6 were New, that is, the bug was found on 5.7, and the earlier versions have not been checked yet - that needs to be checked and the earliest fix version determined

2017-01-20 04:11 UTC, laurynas-biveinis commented
The commit message should describe the fix

2017-01-20 04:11 UTC, laurynas-biveinis commented
Needs a Jenkins run

2017-01-20 04:11 UTC, laurynas-biveinis requested changes

2017-01-20 04:11 UTC, laurynas-biveinis commented on mysql-test/include/subquery_sj.inc
> +
This should go to one of percona slow query log testcases

2017-01-20 04:11 UTC, laurynas-biveinis commented on sql/sql_class.cc
> +  query_plan_flags|= QPLAN_TMP_TABLE;
After the fix, this same statement in create_tmp_table becomes redundant and should be removed

2017-01-26 10:38 UTC, robgolebiowski commented on sql/sql_class.cc
> +  query_plan_flags|= QPLAN_TMP_TABLE;
Thanks a lot. I was going to removed it, but in the end as it turned out I had not.

2017-01-26 16:28 UTC, robgolebiowski commented
Jenkin's run: http://jenkins.percona.com/job/mysql-5.7-param/615/

2017-01-26 16:29 UTC, robgolebiowski commented
Still needs to check if this problem occurs on 5.5 and 5.6

2017-01-27 04:00 UTC, laurynas-biveinis commented
Looks good - please check lower versions and re-submit this patch as a merge

2017-01-27 14:20 UTC, robgolebiowski commented
This is merged from https://github.com/percona/percona-server/pull/1332. Self-approving.

2017-01-27 16:04 UTC, merged

2017-01-30 03:37 UTC, laurynas-biveinis commented
@robgolebiowski, please update the Launchpad bug