Bug #995624: RBR events are not reflected in userstat's Rows_updated
percona/percona-server pull request #1303
Opened 2017-01-20 08:26 UTC by robgolebiowski

After each batch of rows get replicated on a slave server the
rows_update gets incremented by the number of rows successfuly updated,
i.e. inserted/updated/deleted on the slave server.

I had to create another pull request, as I had to rebase my branch to exclude merge from 5.5 (we do port this bug fix to 5.5)

2017-01-23 03:43 UTC, laurynas-biveinis requested changes
Needs a Jenkins run link

2017-01-23 03:43 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +--source include/master-slave.inc
Should go above the echo block (this is not specific to this particular bug, but is global to the test file)

2017-01-23 03:43 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +select ROWS_UPDATED from information_schema.client_statistics;
Continuing discussion on the closed 5.6 PR, I'd replace the starting / ending situation records with include/assert.inc check. Let's discuss on Slack if needed

2017-01-23 03:43 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_percona_bug995624.test
> +source include/master-slave.inc;
This testcase largely duplicated the other one? Pushed by mistake perhaps?

2017-01-23 13:44 UTC, percona-ysorokin requested changes

2017-01-23 13:44 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +
--source include/not_embedded.inc

2017-01-23 13:44 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +
--source include/have_binlog_format_mixed_or_row.inc

2017-01-23 13:44 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +create table t1 (m int);
Although not required, making SQL keywords uppercase makes the code more readable.
For instance, I would write the following
```sql
CREATE TABLE t1 (m INT);
--echo 3 "updates" to rows
INSERT INTO t1 VALUES(15), (16), (17); 
--echo 1 "update" to rows (4 in total)
UPDATE t1 SET m = 20 WHERE m = 16;
--echo 1 "update" to rows (5 in total)
DELETE FROM t1 WHERE m = 17;
```

2017-01-25 14:38 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +
Done.

2017-01-25 14:40 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +
As discussed on Slack. We want the same output for mix, row and statement. This would limit the output just to mixed and row.

2017-01-25 15:19 UTC, robgolebiowski commented
Jenkins run : http://jenkins.percona.com/job/percona-server-5.6-param/1605/ There are few tests failing due to "Can't start server: Bind on TCP/IP port: Address already in use". I have re-run those tests locally and they pass fine.

2017-01-26 04:13 UTC, laurynas-biveinis requested changes
OK with two minor changes

2017-01-26 04:13 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +--source include/not_embedded.inc
not_embedded.inc should go to the top, specifically above master-slave.inc

2017-01-26 04:13 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +SET global userstat=ON;
s/global/GLOBAL/g to match the case of neighboring keywords (SET)

2017-01-26 14:56 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +--source include/not_embedded.inc
Done.

2017-01-26 14:56 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/rpl_percona_userstat.test
> +SET global userstat=ON;
Done.

2017-01-26 15:03 UTC, laurynas-biveinis approved these changes

2017-01-27 12:22 UTC, percona-ysorokin approved these changes
LGTM

2017-01-27 13:57 UTC, merged