Fix bug 1660239 (Test sys_vars.thread_cache_size_func is unstable)
percona/percona-server pull request #1337
Opened 2017-01-30 06:33 UTC by laurynas-biveinis

The testcase disconnects some threads, and waits for them to disappear
from INFORMATION_SCHEMA.PROCESSLIST before checking the Threads_cached
status variable. This introduces a race condition, as a thread will be
removed from PROCESSLIST before caching it.

Fix by waiting for the Threads_cached status variable to become equal
to its intended value instead.

http://jenkins.percona.com/job/percona-server-5.6-param/1627/

2017-02-01 09:28 UTC, robgolebiowski requested changes

2017-02-01 09:28 UTC, robgolebiowski commented on mysql-test/suite/sys_vars/t/thread_cache_size_func.test
After the Threads_cached variable becomes 3 - it could be useful to check if SELECT COUNT(*)= 1 FROM INFORMATION_SCHEMA.PROCESSLIST;

2017-02-06 09:44 UTC, laurynas-biveinis commented
http://jenkins.percona.com/job/percona-server-5.6-param/1661/

2017-02-24 12:32 UTC, robgolebiowski approved these changes
LGTM

2017-02-24 13:25 UTC, merged