Release notes for Percona Server 5.7.17-11
percona/percona-server pull request #1358
Opened 2017-02-02 17:56 UTC by hrvojem

2017-02-02 18:07 UTC, george-lorch reviewed
TokuDB parts LGTM

2017-02-03 03:49 UTC, laurynas-biveinis requested changes

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/management/innodb_kill_idle_trx.rst
> +This feature limits the age of idle |XtraDB| transactions. If a transaction is
Not just XtraDB. Currently XtraDB and TokuDB. (and MyRocks too in near future).

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/management/innodb_kill_idle_trx.rst
> +prevents users from blocking purge by mistake.
InnoDB purge

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/management/innodb_kill_idle_trx.rst
> +setting a different socket read timeout value instead of periodically scanning
s/different socket/connection socket/

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/management/innodb_kill_idle_trx.rst
> +        Feature re-implemented
Feature re-implemented using socket timeouts

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/management/innodb_kill_idle_trx.rst
> +   To enable this feature, set this variable to the desired seconds wait until
If non-zero, any idle transaction will be killed after being idle for this many seconds.

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + different socket read timeout value instead of periodically scanning the low
connection

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + |InnoDB| transaction list level. This re-implementation is also addressing
Insert "This makes the feature applicable to any transactional storage engine, such as TokuDB, and, in future, MyRocks".

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + Repeated execution of ``SET STATEMENT ... FOR`` could lead to a server crash.
"SELECT FROM <view>" part in the bug title is important here

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + ``CREATE TEMPORARY TABLE`` would create a transaction in binary log on read
a read only server.

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + ``CREATE TEMPORARY TABLE`` would create a transaction in binary log on read
Upstream bug ref

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + If a bitmap write I/O errors happened in the background log tracking thread
A server could crash if a bitmap write I/O error happens in the background log tracking thread while a FLUSH CPB is executing concurrently.

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + |InnoDB| index dives did not detect concurrent tree changes, which couldi
couldi

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + |InnoDB| index dives did not detect concurrent tree changes, which couldi
some of the concurrent tree changes

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + potentially incomplete bitmap data past the query range. Bug fixed
past the needed LSN range

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + |Percona Server| ``cmake`` compiler would always check *RocksDB* even if
"check" is vague. attempt to build?

2017-02-03 03:49 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + fixed :bug:`1660265`.
Thanks to Dawid Golunski (https://legalhackers.com)

This notice is required in 5.5/5.6 too

2017-02-03 08:17 UTC, laurynas-biveinis requested changes

2017-02-03 08:17 UTC, laurynas-biveinis commented on doc/source/management/innodb_kill_idle_trx.rst
> +This feature limits the age of idle transactions. If a transaction is idle for
"of idle transactions, for all transactional storage engines." (to avoid confusion, as specifically InnoDB purge is mentioned below)

2017-02-03 08:17 UTC, laurynas-biveinis commented on doc/source/management/innodb_kill_idle_trx.rst
> +   it will be removed in future major release.
a future

2017-02-03 08:17 UTC, laurynas-biveinis commented on doc/source/management/innodb_kill_idle_trx.rst
> +the low |InnoDB| transaction list level.
the internal InnoDB transaction list.

2017-02-03 08:17 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + |InnoDB| transaction list level. This makes the feature applicable to any
the internal InnoDB transaction list.

2017-02-03 08:17 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-11.rst
> + :bug:`1179136`, :bug:`907719`, and :bug:`1369373`.
some existing bugs, including server crashes:

2017-02-03 11:39 UTC, laurynas-biveinis approved these changes

2017-02-03 17:11 UTC, merged