Ps 5.6 myr merge november2016
percona/percona-server pull request #1367
Opened 2017-02-03 17:32 UTC by georgelorchpercona

Merge upstream November 2016 commits from 35ad59416fee5d840ab2e9144cfc30e70306f64e through 0151b45ae15087e4339ee8214cd52ed1b545d5ac

2017-02-03 19:13 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb.sys_vars/t/rocksdb_tmpdir_basic.test
> +--source include/have_rocksdb.inc
Test only needs MyRocks, nut as default.

2017-02-03 19:14 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/autoinc_vars_thread.test
> +--source include/have_rocksdb.inc
Test only needs MyRocks, not as default, properly uses ENGINE=ROCKSDB where necessary.

2017-02-03 19:16 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/autoinc_vars_thread_2.test
> +--source include/have_rocksdb.inc
Test only needs MyRocks, not as default, properly uses ENGINE=ROCKSDB where necessary.

2017-02-03 19:17 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/commit_in_the_middle_ddl.test
> +--source include/have_rocksdb.inc
Test only needs MyRocks, not as default, properly uses ENGINE=ROCKSDB where necessary.

2017-02-03 19:18 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/i_s_trx.test
> +--source include/have_rocksdb_as_default.inc
Test was renamed on merge in, this should not have been changed to _as_default.inc as the test properly uses ENGINE=ROCKSDB.

2017-02-03 19:19 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/i_s_trx_rpl.test
> +--source include/master-slave.inc
Test was renamed on merge in.
missing --source include/have_rocksdb.inc

2017-02-03 19:20 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/rocksdb.test
> +                 DEFAULT CHARSET=latin1;
missing ENGINE=ROCKSDB

2017-02-03 19:20 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/rocksdb.test
> +                 DEFAULT CHARSET=latin1;
missing ENGINE=ROCKSDB;

2017-02-03 19:21 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/tmpdir.test
> +--source include/have_rocksdb.inc
have_rocksdb is ok

2017-02-03 19:22 UTC, georgelorchpercona commented on storage/rocksdb/ha_rocksdb.cc
> +  nullptr, nullptr, 512*1024*1024L,
Magic number

2017-02-03 19:23 UTC, georgelorchpercona commented on storage/rocksdb/ha_rocksdb.cc
> +};
Best to put new class in a new header file?

2017-02-03 19:26 UTC, georgelorchpercona commented on storage/rocksdb/rdb_i_s.cc
>    DBUG_RETURN(ret);
Unnecessary addition of empty line?

2017-02-06 03:47 UTC, laurynas-biveinis requested changes

2017-02-06 03:47 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/autoinc_vars_thread.test
> +connect (con1, localhost, root,,);
--source include/count_sessions.inc

2017-02-06 03:47 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/autoinc_vars_thread.test
> +
--source include/wait_until_count_sessions.inc

2017-02-06 03:47 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/collation.test
> +--exec grep "Invalid pattern" $MYSQLTEST_VARDIR/log/mysqld.1.err | cut -d] -f2
Grepping the master error log file is flaky as its contents are arbitrary due to preceding testcases. The canonical MTR way would be to restart the server with a dedicated testcase error log file (and use one of the mysql-test/include files for the grep, i.e. search_pattern_in_file.inc)

2017-02-06 03:47 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/collation.test
> +--exec grep "Invalid pattern" $MYSQLTEST_VARDIR/log/mysqld.1.err | cut -d] -f2
Likewise

2017-02-06 03:47 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/i_s_trx_rpl.test
> +while ($stop != 1) {
I suspect this is going to be unstable without some sort of sync - what happens if slave fully syncs before this loop?

Also this burns CPU while waiting for the condition to become true, I'd add some --sleep 0.1 (and reduce $it limit accordingly)

2017-02-06 03:47 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/tmpdir.test
> +--echo # Connection con1
--source include/count_sessions.inc

2017-02-06 03:47 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/tmpdir.test
> +
--source include/wait_until_count_sessions.inc

2017-02-06 22:39 UTC, georgelorchpercona commented
Thanks again for the review Laurynas, everything recorded and will be sent upstream.

2017-02-06 22:39 UTC, merged