Bug 1650322: Valgrind error on main.audit_log_threadpool
percona/percona-server pull request #1387
Opened 2017-02-08 15:07 UTC by gl-sergei

When connection created in thread-per-connection handle there is a
thd_prepare_connection which starts as following:

    bool rc;
    lex_start(thd);
    rc= login_connection(thd);
    MYSQL_AUDIT_NOTIFY_CONNECTION_CONNECT(thd);

In case of pool-of-threads handler, connection goes to
threadpool_add_connection which is missing the lex_start call.

    bool rc= login_connection(thd);
    MYSQL_AUDIT_NOTIFY_CONNECTION_CONNECT(thd);

The fix is to simply add missing lex_start invocation.

2017-02-08 15:07 UTC, gl-sergei commented
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1677/

2017-02-08 16:18 UTC, laurynas-biveinis requested changes

2017-02-08 16:18 UTC, laurynas-biveinis commented on sql/threadpool_common.cc
> +    bool rc;
lext_start(thd);

bool rc= login_connection(thd);

2017-02-09 03:23 UTC, gl-sergei commented on sql/threadpool_common.cc
> +    bool rc;
Does it conform MySQL coding style?

2017-02-09 04:37 UTC, laurynas-biveinis commented on sql/threadpool_common.cc
> +    bool rc;
I have not found anything in https://dev.mysql.com/doc/internals/en/general-development-guidelines.html. Given the typical function length in the core server code declaring variables at first use helps to keep sanity

2017-02-09 08:16 UTC, gl-sergei commented
Maybe it is not there, but upstream code follows C practice for variable declarations. It is really a matter of personal taste. For me, declaring all variables all at once makes my program easier to understand. However, I'm not in mood to argue.

2017-02-13 13:10 UTC, gl-sergei commented
@laurynas-biveinis anything else needed for this PR?

2017-02-13 13:11 UTC, laurynas-biveinis approved these changes
Sorry, didn't know it was ready for review.

2017-02-13 13:33 UTC, merged