Ps 5.6 myr merge january2017
percona/percona-server pull request #1389
Opened 2017-02-08 21:32 UTC by georgelorchpercona

2017-02-08 21:32 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1678/

2017-02-08 22:24 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/add_unique_index_inplace.test
> +--source include/have_rocksdb.inc
Safe

2017-02-08 22:24 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/persistent_cache.test
> +--source include/have_rocksdb.inc
Safe

2017-02-09 04:32 UTC, laurynas-biveinis requested changes

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb.sys_vars/r/all_vars.result
> +ROCKSDB_ENABLE_2PC
"There should be *no* variables listed below", and yet are...

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb.sys_vars/r/rocksdb_disable_2pc_basic.result
>  CREATE TABLE invalid_values (value varchar(255)) ENGINE=myisam;
...because the testcase file has not been renamed together with variable rename?

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb.sys_vars/t/rocksdb_disable_2pc_basic.test
>  INSERT INTO invalid_values VALUES('\'aaa\'');
Rename file

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/add_index_inplace_crash.test
> +--error 1105
Use ER_FOO code

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/add_unique_index_inplace.test
> +--source include/have_debug.inc
The testcase should work on the release build too

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/add_unique_index_inplace.test
> +--disable_warnings
Remove

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/add_unique_index_inplace.test
> +--error 1062
ER_FOO

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/add_unique_index_inplace.test
> +--error 1062
ER_FOO

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/add_unique_index_inplace.test
> +--error 1105
ER_FOO

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/persistent_cache.test
> +--let $_server_id= `SELECT @@server_id`
--source include/restart_mysqld.inc with restart args

2017-02-09 04:32 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/persistent_cache.test
> +# restart server to re-read cache
Likewise

2017-02-09 04:32 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +const ulong TABLE_HASH_SIZE = 32;
What is the official MyRocks code style? MySQL, Google, or something else?

2017-02-09 04:32 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_index_merge.cc
> +  m_rec_buf_unsorted =
std::make_shared while at that?

2017-02-09 04:32 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +int ha_rocksdb::check_duplicate_sk(const TABLE *table_arg,
return type bool?

2017-02-10 17:57 UTC, merged