Ps 5.7 myr merge january2017
percona/percona-server pull request #1390
Opened 2017-02-08 21:33 UTC by georgelorchpercona

2017-02-08 21:33 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/665/

2017-02-09 04:33 UTC, laurynas-biveinis requested changes
5.6 comments + couple of specific 5.7 comments, which we should merge as there is no 5.7 upstream

2017-02-09 04:33 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb.sys_vars/t/rocksdb_max_background_compactions_basic.test
>  --source include/have_rocksdb_as_default.inc
--source include/have_myisam.inc

2017-02-09 04:33 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb.sys_vars/t/rocksdb_persistent_cache_path_basic.test
> +--source include/have_rocksdb_as_default.inc
--source include/have_myisam.inc

2017-02-10 17:57 UTC, merged