Fix lp:1652912 "Test main.bug80134 fails under AddressSanitizer default options"
percona/percona-server pull request #1391
Opened 2017-02-09 01:06 UTC by percona-ysorokin

Under address sanitizer (both 'gcc' and 'clang') unsuccessful attempts to
allocate very large memory blocks result in printing the following warning
to stderr:
'==<PID>== WARNING: AddressSanitizer failed to allocate <NNN> bytes'.
As the result this message is added to Percona Server error log, which in
turn makes MTR test cases fail.

Unfortunately, there is no way to suppress specific ASan warnings and the
only way to resolve this issue is to add a suppression on the MTR level.
Instead of calling 'call mtr.add_suppression("...")' in individual tests,
this commit adds a new record to 'mtr.global_suppressions' table as testing
for OOM is pretty common case among existing MTR tests.

Please also notice that when compiled with 'clang', default ASan behavior
for unsuccessful allocations is process termination. To avoid this problem
and make allocation functions return NULL as expected, please specify the
following ASan option via environment variable:
'ASAN_OPTIONS=allocator_may_return_null=1 ./mysql-test/mtr ...'.

2017-02-09 01:07 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-asan-param/116/

2017-02-09 03:16 UTC, laurynas-biveinis requested changes
The MTR suppression LGTM, but the bug report is about adding __asan_default_options to the source code so that ASAN_OPTIONS=allocator_may_return_null=1 is not required

2017-02-09 21:39 UTC, percona-ysorokin commented
Updated Jenkins build links:
http://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-asan-param/117 (ASan)
http://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-param/1525 (5.5-param with MTR_ARGS=main.bug80134)

2017-02-10 03:09 UTC, laurynas-biveinis approved these changes
LGTM, please merge to 5.6/5.7

2017-02-10 15:48 UTC, merged