Bug #84415 slave don't report Seconds_Behind_Master when running s lave_parallel_workers > 0
percona/percona-server pull request #1440
Opened 2017-02-21 13:28 UTC by robgolebiowski

The fix: When a task from GAQ finishes executing, last_master_timestamp gets assigned timestamp from next task in GAQ. In case GAQ is empty last_master_timestamp gets reset to 0. Because last_master_timestamp is only re-assigned when task leaves GAQ it must be also assigned when first event (from parallel execution) arrives.

jenkins run => http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/684/ - failing tests checked. Not failing locally or not failing due to the bug fix

2017-02-21 15:11 UTC, percona-ysorokin reviewed
The same comments as in 5.6

2017-02-21 15:11 UTC, percona-ysorokin commented on sql/rpl_rli_pdb.h
> +  Element_type* head_queue()
Was there an old implementation in the `.cc` file? If so, it must be removed.

2017-02-22 04:06 UTC, laurynas-biveinis requested changes

2017-02-22 04:06 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/bug84415_logical_clock.test
> +# 1st scenario. On slave - two statements are applied in parralel on one database.
"parallel" everywhere

2017-02-28 15:45 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/bug84415_logical_clock.test
> +# 1st scenario. On slave - two statements are applied in parralel on one database.
Done.

2017-02-28 15:45 UTC, robgolebiowski commented on sql/rpl_rli_pdb.h
> +  Element_type* head_queue()
No, there was only declaration and no implementation.

2017-03-10 08:06 UTC, robgolebiowski commented
Jenkins run => http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/717/

2017-03-13 03:42 UTC, laurynas-biveinis requested changes
Same minor comments as for 5.6 + one typo

2017-03-13 03:42 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/bug84415_logical_clock.test
> +# Must be statement as we relay on PROCESSLIST's Info column
s/relay/rely

2017-03-14 13:47 UTC, percona-ysorokin requested changes
Just minor comments

2017-03-14 13:47 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/bug84415_logical_clock.test
> +--source include/have_binlog_format_statement.inc
`have_*` includes before `master-slave`

2017-03-14 13:47 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/bug84415_logical_clock.test
> +#DROP USER test;
please remove

2017-03-14 13:47 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/bug84415-slave.opt
> +--slave-transaction-retries=0
is there a way to set `slave-transaction-retries` dynamically to get rid of `.opt` file?

2017-03-15 08:08 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/bug84415_logical_clock.test
> +--source include/have_binlog_format_statement.inc
Done.

2017-03-15 08:08 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/bug84415_logical_clock.test
> +#DROP USER test;
Done

2017-03-15 15:01 UTC, robgolebiowski commented
Jenkins run => http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/725/

2017-03-16 03:54 UTC, laurynas-biveinis approved these changes

2017-03-16 12:43 UTC, percona-ysorokin approved these changes
LGTM

2017-03-16 12:45 UTC, merged