Bugs 1654682 / 1652852 (FLUSH LOGS disabled by read_only and super_re…
percona/percona-server pull request #1456
Opened 2017-03-01 15:30 UTC by laurynas-biveinis

…ad_only)

As 5.6 is not affected by the bugs because it does not have
mysql.gtid_executed table and thus FLUSH LOGS does not attempt to
write to it on binlog rotation, only add the testcases.

http://jenkins.percona.com/job/percona-server-5.6-param/1727/

2017-03-01 19:31 UTC, percona-ysorokin requested changes

2017-03-01 19:31 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_gtid_read_only_flush_logs.test
> +SET GLOBAL read_only= @saved_read_only;
`SET GLOBAL read_only= ON` ?

2017-03-02 07:47 UTC, laurynas-biveinis commented
Fixed the typo of the week
http://jenkins.percona.com/job/percona-server-5.6-param/1732/

2017-03-02 08:17 UTC, robgolebiowski approved these changes
LGTM

2017-03-02 12:09 UTC, percona-ysorokin approved these changes
LGTM

2017-03-02 13:23 UTC, merged