Bug1654682 5.7
percona/percona-server pull request #1457
Opened 2017-03-01 15:31 UTC by laurynas-biveinis

http://jenkins.percona.com/job/mysql-5.7-param/697/

2017-03-01 19:50 UTC, percona-ysorokin requested changes

2017-03-01 19:50 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_gtid_read_only_flush_logs.test
> +SET GLOBAL read_only= @saved_read_only;
The same as in 5.6
`SET GLOBAL read_only= ON` ?

2017-03-02 07:47 UTC, laurynas-biveinis commented
Fixed http://jenkins.percona.com/job/mysql-5.7-param/700/

2017-03-02 08:16 UTC, robgolebiowski approved these changes
LGTM

2017-03-02 12:11 UTC, percona-ysorokin approved these changes
LGTM

2017-03-02 13:23 UTC, merged