Add tools to edit TokuDB directory file.
percona/percona-server pull request #1458
Opened 2017-03-02 01:21 UTC by vlad-lesin

The new system variables are involved:

===tokudb_dir_cmd===

This variable is used to send commands to edit directory file. The format of
the command line is the following:

command arg1 arg2 .. argn

I.e, if we want to execute some command the following statement can be used:

SET tokudb_dir_cmd = "command arg1 ... argn"

Currently the following commands are availabe:

attach dname iname - attach iname to dname, if dname exists - override
                     the previous value, add new record otherwise
detach dname       - remove record with corresponding dname,
                     the corresponding iname file stays untouched
move old_dname new_dname - rename (only) dname from old_dname to new_dname

If table and database names can be parsed from dname then MDL X lock is
acquired and the table is removed from mysql table dictionary cache. When some
table is removed from TDC it's TABLE_SHARE instance is released. TABLE_SHARE
contains refereces counter, when it equal to zero, the table is closed.
At the other hand tokudb cachetable contains a list of active cachefiles and a
list of stalled cachefiles. Each cachefile contains ft_handle which in turn
has refference counter too. When TABLE_SHARE is closed it decrements
the refference counter of corresponding ft_handles (there are usually several
ft_handles associated with one TABLE_SHARE instance as one table consists of
the several ft-files like main, status and keys). When the refference counter
of some ft_handle becomes zero it's cachefile is moved from active to stalled
list in cachetable. Cachefiles from stalled list are the first candidates for
eviction.

So it's enought just to remove table from TDC and it's cachefiles will be moved
to stalled list sooner or later. Sooner or later because there can be some
other objects which use the table's TABLE_SHARE instance, for example, tokudb
storage engine gathers some statistics in background and it can hold
TABLE_SHARE instances for this purpose.

As it was said when cachefiles are placed into stalled list they will be
evicted sooner or latter unless they are reopened before eviction. When new
ft-file is opened it's file_id is obtained. file_id consists of device id and
inode number. The cachefile is searched in stalled list by this file_id. If
it's not found then new cachefiles is created.

So if some iname was changed/deleted for some dname with the commands described
above the corresponding cachefile will be moved to stalled list and evicted
eventually unless the same iname is not used for opening ft-file with some
other dname before the eviction.

===tokudb_dir_cmd_last_error===

Contains error number of the last executed command

===tokudb_dir_cmd_last_error_string===

Contains error string of the last executed command

Testing: http://jenkins.percona.com/job/percona-server-5.6-param/1730/
tokudb.backup.tokudb_backup_exclude fails because the test uses tokubackup master which has updated api while the PS GCA branch still uses the old API.

See also: https://github.com/percona/PerconaFT/pull/367

2017-03-07 01:50 UTC, georgelorchpercona commented
I haven't reviewed fully yet, now that the FT 367 has been approved, please ensure that you move the PS submodule commit pointers once 367 is merged.

Since this is a new feature, it will need QA and documentation, so please create proper JIRA issues for RQA and DOC.

2017-03-08 02:21 UTC, george-lorch requested changes

2017-03-08 02:21 UTC, georgelorchpercona commented on storage/tokudb/tokudb_sysvars.cc
> +        THDVAR(thd, dir_cmd_last_error_string) =
We have had some serious memory issues with plugin setting string variables to use as error indicators. Please test with valgrind on both 5.6 and 5.7 where a regular MySQL cli sets these values, then the plugin sets them, then the client sets them again.

Also try SET STATEMENT on the value, guaranteed to cause issue.

2017-03-15 11:25 UTC, vlad-lesin commented on storage/tokudb/tokudb_sysvars.cc
> +        THDVAR(thd, dir_cmd_last_error_string) =
Sure, I will recheck this moment. But it looks like the issue is the same as described here https://bugs.launchpad.net/percona-server/+bug/1671082/comments/1 for TokuDB Hotbackup.

2017-03-16 04:02 UTC, georgelorchpercona commented on storage/tokudb/tokudb_sysvars.cc
> +        THDVAR(thd, dir_cmd_last_error_string) =
Yes, it is the same, and I was warning against introducing another like it. Unfortunately, this use is a very nice way to report session status/error back without having to change SQL layer error/warning messages.

2017-03-17 21:37 UTC, george-lorch approved these changes

2017-03-23 00:28 UTC, georgelorchpercona commented
Please be sure to create JIRA RQA and DOC issues for this and cross link them to the TokuDB issue when merging.

2017-03-23 11:07 UTC, vlad-lesin commented
George, you are right, I have changed the work with session variable to set error string by analogy with https://github.com/percona/percona-server/pull/1531. The new testing looks clean: https://github.com/percona/percona-server/pull/1531.

2017-03-23 12:03 UTC, merged

2017-03-23 14:32 UTC, vlad-lesin commented
https://jira.percona.com/browse/RQA-81,
https://jira.percona.com/browse/DOC-413

2017-03-24 12:53 UTC, laurynas-biveinis commented
This likely caused https://bugs.launchpad.net/percona-server/+bug/1675763