MYR-94 : 5.7 mtr - incorrect thd::query string access causes assertion
percona/percona-server pull request #1470
Opened 2017-03-06 23:39 UTC by georgelorchpercona

percona-server/include/thr_mutex.h:153: void safe_mutex_assert_not_owner(
  const my_mutex_t*): Assertion `!mp->count || !my_thread_equal(
  my_thread_self(), mp->thread)' failed.
- Fixed issue in Rdb_trx_info_aggregator to use thd_query_safe since this
  will be reading from thd->query across thread boundaries.

2017-03-06 23:40 UTC, georgelorchpercona commented
This passes local mtr and clears the issue from tests noted in the MYR issue. Depends on MYR-66 landing in PR 1469 to fully pass tests.

2017-03-07 03:22 UTC, laurynas-biveinis requested changes

2017-03-07 03:22 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +          thd, const_cast<char *>(query_str.c_str()), trx_query_max_len);
const_casting const away and writing to the result of std::string::c_str is undefined behaviour - replace it with &query_str[0]? Shorter, no need for const_cast, no UB

2017-03-07 06:24 UTC, georgelorchpercona commented
Changes made, quite minor, passed local testing with no issue. Also rebased to recent 5.7 changes.

2017-03-07 07:11 UTC, laurynas-biveinis approved these changes

2017-03-07 15:47 UTC, merged