Fixed lp:1631954 "It is possible to create COMPRESSED columns in MyISAM tables via specifying partition engines" and lp:1671492 "Unable to add compression columns to a partitioned table via 'ALTER TABLE'" (5.7)
percona/percona-server pull request #1512
Opened 2017-03-16 01:06 UTC by percona-ysorokin

2017-03-16 01:09 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/727/

2017-03-16 03:32 UTC, laurynas-biveinis requested changes
Same comments as for 5.6 and a 5.7-specific one

2017-03-16 03:32 UTC, laurynas-biveinis commented on sql/sql_table.cc
> +#ifdef WITH_PARTITION_STORAGE_ENGINE
IIRC 5.7 removed WITH_PARTITION_STORAGE_ENGINE #ifdefs in the code

2017-03-16 14:57 UTC, percona-ysorokin commented on sql/sql_table.cc
> +#ifdef WITH_PARTITION_STORAGE_ENGINE
good spot

2017-03-16 17:01 UTC, robgolebiowski approved these changes
LGTM

2017-03-16 21:10 UTC, percona-ysorokin commented
Updated Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/730/

2017-03-17 03:46 UTC, laurynas-biveinis approved these changes

2017-03-17 13:29 UTC, merged