Fix lp:1659992 "Function over userstat tables cause mysql to crash" (5.5)
percona/percona-server pull request #1540
Opened 2017-03-22 14:55 UTC by percona-ysorokin

Some 'SELECT' statements over 'table_statistics' IS table used to call
'check_grant()' from 'fill_schema_table_stats()' with 'table_list' parameter
which did not include any element that would have 'next_global' pointing to
'thd->lex->query_tables_own_last'. This was a violation of 'check_grant()'
pre-conditions.

Fixed by backporting part of the 5.7
"wl#6960: Refactoring auth code: milestone 1, new physical file structure"
(commit 0ed74a1) which added additional 'NULL' check to 'TABLE_LIST'
iteration in 'check_grant()'.

Added 'main.percona_bug1659992' MTR test case.

2017-03-22 14:55 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-param/1532/

2017-03-23 04:15 UTC, laurynas-biveinis requested changes

2017-03-23 04:15 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug1659992.test
> +#
No need for a new separate testcase - please merge with main.percona_userstat, replacing header comment with "--echo #" one

2017-03-23 04:15 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug1659992.test
> +    SELECT v.variable_value FROM information_schema.global_variables v WHERE v.variable_name = in_name INTO var_value;
IIRC INFORMATION_SCHEMA object names are in uppercase (PFS lowercase)

2017-03-23 04:15 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug1659992.test
> +  FROM information_schema.table_statistics s
Likewise

2017-03-23 15:11 UTC, percona-ysorokin commented
Updated Jenkins build link (as no code changes since the previous commit, just single test run)
http://jenkins.percona.com/view/PS%205.5/job/percona-server-5.5-param/1533/

2017-03-24 03:28 UTC, laurynas-biveinis approved these changes

2017-03-24 12:21 UTC, robgolebiowski approved these changes
LGTM

2017-03-24 12:47 UTC, merged