Release notes for Percona Server 5.7.17-12 (5.7)
percona/percona-server pull request #1552
Opened 2017-03-23 17:25 UTC by hrvojem

2017-03-23 17:28 UTC, george-lorch approved these changes
MyRocks and TokuDB LGTM

2017-03-24 03:25 UTC, laurynas-biveinis requested changes

2017-03-24 03:25 UTC, laurynas-biveinis commented on doc/source/flexibility/extended_mysqldump.rst
> +:variable:`rocksdb_skip_fill_cache` and set it to ``1`` if exists.
s/set/setting
s/if exists/if it exists

2017-03-24 03:25 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-12.rst
> + the |MySQL| configuration file, server couldn't be gracefully shut down. Bug
shut down by a SIGTERM signal

2017-03-24 03:25 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-12.rst
> + Running the query that uses range scan with primary key could lead to a server
A query using range scan with a complex range condition could lead ...

2017-03-24 03:25 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-12.rst
> + disconnects. Bug fixed  :bug:`1646100`.
Move up next to 1657128

2017-03-24 03:25 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.17-12.rst
> + ``FLUSH LOGS`` was disabled with :variable:`read_only` and
Move up next to 1652852

2017-03-24 08:43 UTC, laurynas-biveinis approved these changes

2017-03-24 08:43 UTC, merged