Fix lp:1669928 (Write/fsync amplification w/ duplicate GTIDs)
percona/percona-server pull request #1617
Opened 2017-04-04 16:34 UTC by percona-ysorokin

In some multi-source replications setups
'Xid_apply_log_event::do_apply_event()' method used to always update relay
log position regardless of whether the transaction being commited has already
been executed or not. In case of 'relay-log-info-repository=TABLE' this could
have had additional performance impact as updating 'slave_relay_log_info'
requires extra fsyncs. Moreover, depending on the number of channels receiving
duplicate (already executed) transactions, the situation could have become
proportionally worse.

Fixed by checking if the 'GTID_NEXT' was already logged and if so, omiting
relay log position update.

Added 'rpl.rpl_bug85141' MTR test case.

2017-04-04 16:37 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/784/

2017-04-05 03:43 UTC, laurynas-biveinis requested changes
Is 5.6 affected?
Is relay-log-info-repository=FILE affected?

2017-04-05 03:43 UTC, laurynas-biveinis commented on sql/rpl_gtid.h
> +bool is_already_logged_transaction(const THD *thd);
const method

2017-04-05 03:43 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_bug85141.test
> +--source include/not_group_replication_plugin.inc
Add --source include/have_perfschema.inc

2017-04-05 03:43 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_bug85141.test
> +STOP SLAVE;
Async always looks suspicious in MTR - use include/stop_slave.inc include/start_slave.inc here and everywhere?

2017-04-05 03:43 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_bug85141.test
> +--source include/assert.inc
Consider include/rpl_diff.inc instead

2017-04-05 03:43 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_bug85141.test
> +#SELECT Channel_name, Relay_log_pos, Master_log_pos FROM mysql.slave_relay_log_info;
Leftovers?

2017-04-06 12:28 UTC, percona-ysorokin commented
5.6 is not affected as  Multi Source Replication was introduced in 5.7.2.

2017-04-06 12:31 UTC, percona-ysorokin commented
Relay log position is updated via abstract interface with 2 implementations (file repository and table repository). So, with 'relay-log-info-repository=FILE' we will also eliminate some unnecessary disk writes. I am just not sure how to measure number of relay log file updates in this case.

2017-04-06 12:35 UTC, percona-ysorokin commented on sql/rpl_gtid.h
> +bool is_already_logged_transaction(const THD *thd);
It was a static function outside of any class which I just made extern.

2017-04-07 07:40 UTC, robgolebiowski approved these changes
LGTM

2017-04-10 02:42 UTC, laurynas-biveinis approved these changes

2017-04-10 21:16 UTC, percona-ysorokin commented
Addressed review comments: MTR test case now uses "include/rpl_diff.inc" to check data integrity on different servers.
Rebased on top of the most recent 5.7 to include fixed "include/rpl_diff.inc".
Updated Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/809/

2017-04-11 02:19 UTC, laurynas-biveinis approved these changes

2017-04-11 11:42 UTC, merged