MYR-74 : rocksdb.rpl_row_not_found fails
percona/percona-server pull request #1642
Opened 2017-04-08 22:54 UTC by georgelorchpercona

- When running with full debug build and --debug-server, extra suppressions are
  needed for log file.

2017-04-08 22:54 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/808/ shows the issue fixed

2017-04-10 02:52 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/include/rpl_row_not_found.inc
>  call mtr.add_suppression("Slave SQL: Worker.*failed executing transaction");
Is this one still needed? The one added below looks too similar, is it as 5.6 vs 5.7 difference?

2017-04-10 03:00 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/include/rpl_row_not_found.inc
>  call mtr.add_suppression("Slave SQL: Worker.*failed executing transaction");
I think that is all it is, a 5.6 to 5.7 diff with 5.7 bringing in the "for channel" but can't say offhand for sure as I have not gone back and looked at the actual 5.6 error being logged.

2017-04-10 03:17 UTC, laurynas-biveinis requested changes
Replace the suppression instead of adding a new one

2017-04-10 03:21 UTC, georgelorchpercona commented
Yup, will do, it just didn't occur to me that the current was 5.6 specific.

2017-04-10 23:11 UTC, georgelorchpercona commented
OK, re-pushed with the deprecated suppression removed and test re-recorded. jenkins here http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/811/ and we can see the test passing.

I'm going to go ahead and merge it at this point, nothing more really to do.

2017-04-10 23:12 UTC, merged