MYR-109: Fail to compile on jenkins yakkety
percona/percona-server pull request #1649
Opened 2017-04-11 15:10 UTC by gl-sergei

Removed redundant assert:

    DBUG_ASSERT_IMP(m_maybe_unpack_info, pk_unpack_info)

because `pk_unpack_info` cannot be NULL according to the function
declaration.

This commit addresses issue facebook/mysql-5.6#605

2017-04-11 18:29 UTC, laurynas-biveinis requested changes
I believe it is the assert which should be kept and attribute removed. It is useless and dangerous as it does not protect against NULL passed but it will optimize away any NULL checks in the implementation.

2017-04-11 18:58 UTC, georgelorchpercona commented
Gotta love useless syntactical sugar...either way, a coming merge from upstream changes the assertion so that it does not involve the passed argument. The current, and coming change is not an ASSERT != NULL, it is an assert that  `if (a==true) then b must also be true, if (!a) then b doesn't matter` where a is a class member and b happens to be the pointer argument.

The fact that it was operating on pointers is what invoked the NULL check error. In the end, both the attribute and the assertion are effectively useless, so being pedantic about which to remove is sort of a time sink.

2017-04-11 19:14 UTC, laurynas-biveinis commented
OK, if it's temporary, it does not matter.

2017-04-14 15:12 UTC, georgelorchpercona commented
+1 - I'll merge now, upstream merge to replace/overwrite should be coming in a short time.

2017-04-14 15:12 UTC, merged