MYR-19 : Fix tests disabled by MYR-15
percona/percona-server pull request #1653
Opened 2017-04-14 02:57 UTC by georgelorchpercona

MYR-58 : 5.7 mtr - re-record tests for Warning 1287 - deprecated partition
         handler
MYR-59 : 5.7 mtr - fix and re-record tests for deprecated EXPLAIN EXTENDED,
         new EXPLAIN result format, and format=json
MYR-61 : 5.7 mtr - fix and re-record tests using deprecated
         i_s.global_status
MYR-79 : 5.7 mtr - re-record tests that use restart_mysqld.inc due to new
         comment in output
MYR-81 : 5.7 mtr - re-record tests for new warning on INSERT IGNORE when
         duplicate exists
MYR-99 : Convert tests to not require have_rocksdb_as_default
- Many tests were disabled by MYR-15 due to new gap lock detection and SQL
  error. Tests needed some work to use either different queries or to
  temporarily switch ISO level to READ-COMMITTED
- While fixing tests, a few new issues appeared and were reported:
  - MYR-122 : split up rocksdb.rocksdb test into individual tests that
    actually test something specific
  - MYR-123 : PS 5.7 rocksdb_max_open_files differs from default
- Other issues listed above were addressed/re-recorded as impacted tests
  were enabled.
- A couple of the tests required some more significant work in order to
  test original intention and variant results based on ISO mode and
  intersection with gap lock error in RR ISO mode.
  - rocksdb.transaction reimplemented to some extent to run the full test
    once under each supported MyRocks ISO mode (READ COMMITTED and
    REPEATABLE READ)
  - rocksdb.unique_sec reimplemented to run the full test once under each
    supported MyRocks ISO mode (READ COMMITTED and REPEATABLE READ)
  - rocksdb.unique_sec_rev_cf reimplemented to run the full test once under
    each supported MyRocks ISO mode (READ COMMITTED and REPEATABLE READ)
- The rocksdb.rocksdb test is a special case as noted by the new issue
  above and just needs to be cratered and started over.

2017-04-14 02:57 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/825/

2017-04-14 04:43 UTC, laurynas-biveinis requested changes

2017-04-14 04:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/include/locking_issues_case1_1.inc
> +CREATE TABLE t0(id1 INT, id2 INT, value INT, PRIMARY KEY(id1, id2)) engine=rocksdb;
Here and everywhere inconsistent SQL syntax case "CREATE" but "engine". I don't know the official RocksDB capitalisation for the plugin SE name, likely it's "RocksDB"

2017-04-14 04:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/delete.test
> +set @orig_tx_iso=@@session.tx_isolation;
Here and everywhere, no need to save/restore the session variable, when it's restored at the very end of a testcase

2017-04-14 04:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/rocksdb.test
> +# this is bad and will result in unstable tests
Add some TODO marker?

2017-04-14 04:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/rocksdb.test
> +# this is bad and will result in unstable tests
Likewise here and everywhere

2017-04-14 04:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/select_for_update.test
> +set @orig_tx_iso=@@session.tx_isolation;
Saving the session variable is twice as much not required, when you just opened a session :)

2017-04-14 04:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/transaction.test
> +# in RC mode to illistrate passing functionality
s/illistrate/illiustrate/g

2017-04-14 05:02 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/include/locking_issues_case1_1.inc
> +CREATE TABLE t0(id1 INT, id2 INT, value INT, PRIMARY KEY(id1, id2)) engine=rocksdb;
Yeah, case consistency is non existent in this suite. In general, I should have been consistent with the case of the statement.

2017-04-14 05:06 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/delete.test
> +set @orig_tx_iso=@@session.tx_isolation;
True, end of tests really don't necessarily need to reset sessions, but, IIRC, I have been requested to track and reset sessions in reviews before. Perhaps it was not a realization that a set/reset was session only or that maybe future expectation is that even session sight span test cases. I'll remove them and yell at the next reviewer that asks that I reset a session var to its original value.

2017-04-14 05:07 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/rocksdb.test
> +# this is bad and will result in unstable tests
I thought this in itself was a marker, along with new MYR issue that this test needs to be destroyed and started over.

2017-04-14 05:08 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/transaction.test
> +# in RC mode to illistrate passing functionality
Stupid sausage fingers

2017-04-14 07:00 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/rocksdb.test
> +# this is bad and will result in unstable tests
OK then

2017-04-14 20:07 UTC, georgelorchpercona commented
Changes made and re-jenkinsed http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/833/

2017-04-18 03:17 UTC, laurynas-biveinis approved these changes

2017-04-18 03:43 UTC, merged