Fix bug 1684601 / 86016 (Make MTR show core dump stacktraces from uni…
percona/percona-server pull request #1674
Opened 2017-04-20 14:22 UTC by laurynas-biveinis

…t tests too)

Implement MTR showing the stacktraces of crashed unit tests by the
following:
- at the end of test run, if --unit-tests was set, search for core
  dumps in the build directory subtree and invoke My::CoreDump->show
  on them;
- removing _verify_binpath call in My::CoreDump::_gdb as it does not
  seem to be required on our supported platforms and if present, it
  assigns all the unit test core dumps to mysqltest executable.
- stop expected-crash tests from producing core dumps by introducing
  MY_EXPECT_DEATH and MY_EXPECT_DEATH_IF_SUPPORTED macros, which
  disable core dumping around the expected-crash calls. The macros and
  support functions are piggybacked on existing thread_utils.h and
  thread_utils.cpp, which is not a fully correct place for them, but
  IMHO acceptable enough.

http://jenkins.percona.com/job/percona-server-5.6-param/1849/

2017-04-21 12:11 UTC, percona-ysorokin requested changes
A few suggestions on enabling/disabling core dumps.

2017-04-21 12:11 UTC, percona-ysorokin commented on unittest/gunit/thread_utils.cc
> +MY_ATTRIBUTE((constructor))
Why compiler specific attribute, instead of `static struct rlimit initial_core_rlimit = init_initial_core_limit()`?

2017-04-21 12:11 UTC, percona-ysorokin commented on unittest/gunit/thread_utils.cc
> +  ASSERT_EQ(ret, 0);
Similarly to 'restore_core_dump_rlimit()'
```c++
if (ret != 0)
{
  perror("setrlimit(RLIMIT_CORE) failed (disable)");
  ASSERT_EQ(ret, 0);
}
```

2017-04-21 12:11 UTC, percona-ysorokin commented on unittest/gunit/thread_utils.cc
> +  if (ret == -1)
`if (ret != 0)` is more reliable

2017-04-21 12:11 UTC, percona-ysorokin commented on unittest/gunit/thread_utils.cc
> +static struct rlimit disabled_core_rlimit;
do we need this 'disabled_core_rlimit' at all? Looks like pre-caching a struct of 2 integers.

2017-04-21 12:11 UTC, percona-ysorokin commented on unittest/gunit/thread_utils.h
> +    disable_core_dumps();                               \
May be a RAII capsule which would store old and set new value in the constructor and restore in the destructor?
Something like the following with proper error checking. No static initialization at all here.
```c++
class disable_core_dumps_capsule
{
  public:
    disable_core_dumps_capsule(): captured_core_rlimit_()
    {
      ... =getrlimit(RLIMIT_CORE, &captured_core_rlimit_);
      struct rlimit disabled_core_rlimit= captured_core_rlimit_;
      disabled_core_rlimit.rlim_cur= 0;
      ...= setrlimit(RLIMIT_CORE, &disabled_core_rlimit);
    }
    ~disable_core_dumps_capsule()
    {
      ...= setrlimit(RLIMIT_CORE, &captured_core_rlimit_);
    }
  private:
    disable_core_dumps_capsule(const disable_core_dumps_capsule&);
    disable_core_dumps_capsule& operator = (const disable_core_dumps_capsule&);

    struct rlimit captured_core_rlimit_;
};
```

2017-04-21 15:37 UTC, robgolebiowski commented on unittest/gunit/thread_utils.cc
> +MY_ATTRIBUTE((constructor))
+1

2017-05-30 07:44 UTC, laurynas-biveinis commented on unittest/gunit/thread_utils.h
> +    disable_core_dumps();                               \
Implemented. No ASSERT_EQ in set/getrlimit failure handling, as these macros then make the constructor/destructor to return a value

2017-05-30 11:33 UTC, percona-ysorokin approved these changes
LGTM

2017-05-30 13:46 UTC, laurynas-biveinis commented
http://jenkins.percona.com/job/percona-server-5.6-param/1924/

2017-06-02 14:44 UTC, robgolebiowski approved these changes
LGTM

2017-06-08 03:31 UTC, merged