Bug 1650294: Test main.audit_log_filter_users is unstable
percona/percona-server pull request #1681
Opened 2017-04-24 22:46 UTC by gl-sergei

The source of instability is the fact that event of creating new
connection and closing previous one are not synchronized. It makes
"Quit" record to appear after "Connect" one.

It cannot be easily resolved even with using debug_sync. Simplest fix is
to grep "Quit" events away.

2017-04-24 22:46 UTC, gl-sergei commented
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1858/

2017-04-24 22:50 UTC, gl-sergei commented
Likely fixes 1626559 as well

2017-04-28 12:50 UTC, laurynas-biveinis requested changes
I think this can be fixed by replacing include/wait_until_disconnected.inc (which waits for its own connection to be closed and then server carries on, async, on the remaining disconnect business) with include/wait_until_count_sessions.inc (which waits for a specific Threads_connected value in the server, which is updated close to the very end of disconnect)

2017-05-01 23:54 UTC, gl-sergei commented
It looks like a good idea. I changed tests to use wait_until_count_sessions.
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1864/

2017-05-02 02:20 UTC, laurynas-biveinis approved these changes

2017-05-02 02:22 UTC, laurynas-biveinis commented
If you believe this fixes 1626559 too, please set that one to Fix Released or duplicate or Incomplete

2017-05-04 08:15 UTC, gl-sergei commented
Now 1626559 doesn't look like duplicate... or maybe there are two different issues there. Some comments report that sometimes SHOW WARNINGS record appears in audit log. It needs further investigation.

2017-05-04 08:16 UTC, merged