Bug #1686934: Test rpl_semi_sync_ack_thread is failing on 5.7
percona/percona-server pull request #1684
Opened 2017-05-01 08:36 UTC by robgolebiowski

Test sets up a debug sync point "before_get_MASTER_UUID". This sync
point emits signal in_get_master_version_and_clock and waits for
singal get_master_uuid. The fix is to consume signal
in_get_master_version_and_clock as we care only about "wait for" part
in this test.

2017-05-01 08:49 UTC, robgolebiowski commented
Jenkins run: http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/863/

2017-05-02 03:02 UTC, laurynas-biveinis requested changes

2017-05-02 03:02 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_semi_sync_ack_thread.test
> +SET DEBUG_SYNC= 'now WAIT_FOR in_get_master_version_and_clock';
Can this be merged with two lines below: SET debug_sync= 'now WAIT_FOR this SIGNAL that' ?

2017-05-10 02:13 UTC, laurynas-biveinis approved these changes

2017-05-10 02:13 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_semi_sync_ack_thread.test
> +SET DEBUG_SYNC= 'now WAIT_FOR in_get_master_version_and_clock';
OK, as you wrote on Slack, the merged debug_sync signals first, before waiting. LGTM with two separate SETs

2017-05-10 07:27 UTC, merged