MYR-123 : PS 5.7 rocksdb_max_open_files differs from default
percona/percona-server pull request #1689
Opened 2017-05-03 18:17 UTC by georgelorchpercona

- For plugin variables that are signed numbers, doing a SHOW VARIABLES will
  always show an unsigned number. Fix this by adding more types to the
  SHOW_* enums and then based on that, calling the *10_to_str functions
  appropriately.
- This commit is a port of upstream Facebook MySQL patch from
  https://github.com/facebook/mysql-5.6/commit/97acbd60eccf96962cdce9b01b2bc67f4291bcce

2017-05-03 18:18 UTC, georgelorchpercona commented
Previous jenkins run with same code but different commit message http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/857/

2017-05-04 12:37 UTC, laurynas-biveinis requested changes

2017-05-04 12:37 UTC, laurynas-biveinis commented on include/mysql/plugin.h
> +  SHOW_SIGNED_LONG,
Duplicate with the one in sql_plugin_enum.h. Probably that one has to be removed.

2017-05-04 18:09 UTC, georgelorchpercona commented on include/mysql/plugin.h
> +  SHOW_SIGNED_LONG,
I think you are misreading the diff, SHOW_SIGNED_LONG was removed from sql_plugin_enum.h and added to the enum_mysql_show_type along with the new SHOW_SIGNED_INT.

2017-05-05 02:45 UTC, laurynas-biveinis commented on include/mysql/plugin.h
> +  SHOW_SIGNED_LONG,
Sorry, you are right

2017-05-05 02:45 UTC, laurynas-biveinis approved these changes

2017-05-05 14:07 UTC, merged