MYR-124 : START TRANSACTION WITH CONSISTENT SNAPSHOT behaves different
percona/percona-server pull request #1690
Opened 2017-05-03 22:16 UTC by georgelorchpercona

- MYR-16 : myrocks/webscale uses different method to implement START
           TRANSACTION WITH CONSISTENT SNAPSHOT
  - This is where we diverged from upstream Facebook MySQL to make STWCS
    behave more like upstream Oracle MySQL in that is just returns SQL warning
    but not an error. Tests were unstable then so were never corrected.
- Corrected SQL warning to indicate the source of the warning is RocksDB.
- Enabled, fixed, and re-recorded snapshot tests to capture current, correct
  behavior in results.

2017-05-03 22:16 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/896/
Two instabilities apeared and have been logged as MYR-126 and MYR-127, unrelated to this change.

2017-05-04 12:30 UTC, laurynas-biveinis requested changes

2017-05-04 12:30 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/disabled.def
> +#cons_snapshot_read_committed : MYR-124 - Percona Server with MyRocks has different behavior of STWCS
Why comment out instead of removing?

2017-05-04 14:48 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/disabled.def
> +#cons_snapshot_read_committed : MYR-124 - Percona Server with MyRocks has different behavior of STWCS
Good catch, those were supposed to be removed. The comment was temporary during testing so I could remember exactly which tests needed work. I'll fix and re-push before merging.

2017-05-04 18:12 UTC, merged