Add diagnostics for bug 1689489 (SHOW SLAVE STATUS truncates Relay_Ma…
percona/percona-server pull request #1707
Opened 2017-05-09 13:18 UTC by laurynas-biveinis

…ster_Log_File intermittently)

SHOW SLAVE STATUS returned
Master_Log_File	master-bin.000004
Relay_Master_Log_File	master-bin.00000

I.e. Relay_Master_Log_File is truncated by one character. Add an
assert to catch this condition.

http://jenkins.percona.com/job/percona-server-5.6-param/1871/

2017-05-10 12:11 UTC, percona-ysorokin requested changes

2017-05-10 12:11 UTC, percona-ysorokin commented on sql/rpl_slave.cc
> +    DBUG_ASSERT((relay_master_log_file_len == strlen(master_log_file))
(relay_master_log_file_len == master_log_file_len)?

2017-05-10 15:02 UTC, robgolebiowski approved these changes
LGTM

2017-05-11 07:11 UTC, laurynas-biveinis commented
http://jenkins.percona.com/job/percona-server-5.6-param/1878/

2017-05-12 12:32 UTC, percona-ysorokin approved these changes
LGTM

2017-05-25 08:33 UTC, merged