Percona Server 5.6.36-82.0 release notes (5.6)
percona/percona-server pull request #1715
Opened 2017-05-10 14:34 UTC by hrvojem

2017-05-10 16:27 UTC, george-lorch approved these changes
Toku +1

2017-05-11 03:09 UTC, laurynas-biveinis requested changes

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/performance/prefix_index_queries_optimization.rst
> +Facebook.
Facebook patch for MySQL

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> +Based on `MySQL 5.6.34
Based on MySQL 5.6.36

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + |Percona Server| would hang during OLTP prepare with several buffer pool
What is "OLTP prepare"?

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + |Percona Server| would hang during OLTP prepare with several buffer pool
with several small buffer pool instances

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + :ref:`compressed_columns` could not be added to a partitioned table by using
How does the output text look here?

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + Fixed a memory leak which happened that happened in case of failure to create
which happened that happened

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + Combination of using the :ref:`audit_log_plugin` with MB collation connection
Not audit_log_plugin but any audit API-using plugin (audit_log, QRT, ...)

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + performance regression. Bug fixed :bug:`1631309`.
regression due to suboptimal LRU manager thread flushing heuristics

2017-05-11 03:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + Slave did not report a ``Seconds_Behind_Master`` with multiple number of slave
Replication slave did not report SBM correctly when running in multi-threaded slave mode

2017-05-11 03:10 UTC, laurynas-biveinis commented
Please also amend the commit message for the correct version number

2017-05-11 05:55 UTC, laurynas-biveinis requested changes

2017-05-11 05:55 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + Deadlock could occur when server was using several small buffer pool instances
Deadlock could occur in I/O-bound workloads when ...

2017-05-11 05:55 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + :ref:`compressed_columns` could not be added to a partitioned table by using
OK as discussed on Slack

2017-05-11 05:55 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + Combination of using any audit API-using plugin (audit_log, QRT, ...) with MB
As discussed on Slack

2017-05-11 06:08 UTC, laurynas-biveinis requested changes

2017-05-11 06:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.0.rst
> + small buffer pool instances in combination with
several buffer pool instances in combination with small redo log files and variable ...

2017-05-11 09:14 UTC, laurynas-biveinis approved these changes

2017-05-11 12:36 UTC, merged