Bug#1690531: Test rpl.rpl_killed_ddl is failing on 5.7
percona/percona-server pull request #1736
Opened 2017-05-15 08:37 UTC by robgolebiowski

Event created by this test was to be executed on a date based on
CURRENT_TIMESTAMP. Later creation of this event was executed on slave
and a diff of statements between master and slave was done. This diff
resulted in failure for statement based replication, as
CURRENT_TIMESTAMP on slave was different than the CURRENT_TIMESTAMP on
master. Fixed by replacing CURRENT_TIMESTAMP with fixed timestamp.

2017-05-15 08:37 UTC, robgolebiowski commented
jenkins run: http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/925/

2017-05-15 15:44 UTC, percona-ysorokin requested changes

2017-05-15 15:44 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_killed_ddl.test
> +  ON SCHEDULE AT '2020-01-01 00:00:00' + INTERVAL 1 DAY
2020 is just 3 years from now - it does not look unrealistic.
Funny thing is that Oracle fixed similar problem in its latest minor releases
https://github.com/percona/percona-server/commit/e7a3ccf6b1b1b41e0fa191d26e9e775517c6deee

May be, we can still use `CURRENT_TIMESTAMP` but eliminate the problem on MTR level. Something like
```sql
--let $timestamp= `SELECT CURRENT_TIMESTAMP()`
send_eval CREATE EVENT e2
  ON SCHEDULE AT '$timestamp' + INTERVAL 1 DAY
```

2017-05-15 18:17 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/rpl_killed_ddl.test
> +  ON SCHEDULE AT '2020-01-01 00:00:00' + INTERVAL 1 DAY
It does not have to look unrealistic - it can be any date.

2017-05-15 21:14 UTC, percona-ysorokin commented on mysql-test/suite/rpl/t/rpl_killed_ddl.test
> +  ON SCHEDULE AT '2020-01-01 00:00:00' + INTERVAL 1 DAY
As far as I remember, events cannot be created in the past. So, my concern is that in 3 years this test  will be failing.

2017-05-16 06:00 UTC, robgolebiowski commented on mysql-test/suite/rpl/t/rpl_killed_ddl.test
> +  ON SCHEDULE AT '2020-01-01 00:00:00' + INTERVAL 1 DAY
Oh, good to know, will change this, thanks

2022-03-24 13:41 UTC, closed without merging