Fixed DOC-466 by renaming the feature to dictionary (5.7)
percona/percona-server pull request #1737
Opened 2017-05-15 18:25 UTC by hrvojem

Release notes updates to mention where the contribution for prefix index queries optimisation is coming from.
Mentioned that the gap locks detection is intended for storage engines like MyRocks.

2017-05-15 18:59 UTC, george-lorch requested changes

2017-05-15 18:59 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_file_management.rst
> +has been implemented that can be used to edit the |TokuDB| dictionary.
Going to be a bit pedantic: In Tokutek nomenclature, a dictionary is an index or a single FT key/value FT file. The directory dictionary is what maps internal dictionary names to physical dictionary files on disk. See https://www.percona.com/blog/2016/09/27/tokudb-and-perconaft-database-file-management-part-1-of-2/ that explains the files. This new feature allows a user to manipulate the contents of the TokuDB/PerconaFT directory map.

So, if we want to be completely clear and accurate, we can reword this as "In |Percona Server| :rn:`5.7.18-14` new :variable:`tokudb_dir_cmd` variable has been implemented that can be used to edit the |TokuDB| directory mapping." and even perhaps link back to this blog post or some other doc content that has the same info.

2017-05-15 18:59 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_file_management.rst
> +Editing |TokuDB| dictionary with :variable:`tokudb_dir_cmd`
Same dictionary/directory clarification.

2017-05-15 18:59 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_file_management.rst
> +has been implemented that can be used to edit the |TokuDB| dictionary.
Same...

2017-05-15 18:59 UTC, georgelorchpercona commented on doc/source/tokudb/tokudb_file_management.rst
> +This variable is used to send commands to edit |TokuDB| dictionary.
Same...

2017-05-16 07:41 UTC, hrvojem commented
Changed term to  directory map as requested

2017-05-16 15:20 UTC, george-lorch approved these changes

2017-05-16 15:35 UTC, merged