[TDB-6] src/ydb.cc:2917 can_acquire_table_lock: Assertion `r == 0'
percona/percona-server pull request #1754
Opened 2017-05-23 18:31 UTC by Jun-Yuan

failed (errno=36) (r=36)

2017-05-24 23:31 UTC, george-lorch requested changes
OK, this move of the commit pointer is incorrect. It can onl have been done after the merge of the FT change to FT master as the actual merge commit is not picked up and other changes have been made to FT master that are also not picked up by the way this was done.

You need to checkout this PS branch, then:
cd storage/tokudb/PerconaFT
git checkout master
cd -
git add PerconaFT
git commit --amend
git push https://github.com/Jun-Yuan/percona-server ps-5.7-TDB-6 --force

Then you must run a Percona Server 5.6 jenkins job on your branch, posting the link here in the pull request and in the TDB issue along with a link to the pull request (see some of my closed TDB issues for example how I like to see things recorded in the issues).

Ping me privately if you have any questions.

2017-05-26 13:27 UTC, Jun-Yuan commented
Can you review again? Thanks

2017-05-29 19:13 UTC, georgelorchpercona commented
Much better! Merging...

2017-05-29 19:13 UTC, george-lorch approved these changes

2017-05-29 19:15 UTC, merged