Bug 1626559: Test `main.audit_log_default_db' is unstable
percona/percona-server pull request #1761
Opened 2017-05-25 22:39 UTC by gl-sergei

Sometimes "SHOW WARNINGS" appears in the audit log around UNINSTALL
PLUGIN / INSTALL PLUGIN. This is the warning which MySQL issue about
plugin being in use.

Normally warning should not make it to audit log because test case
truncates log after UNINSTALL PLUGIN. But sometimes mysql-test picks
this warning up after plugin has been reinstalled and it gets logged
into audit log.

This patch makes sure that test execution continues only when plugin
disappeared from the `mysql.plgins', which happens after `deinit' is
called and all plugin is fully shut down.

2017-05-25 22:39 UTC, gl-sergei commented
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1916/

2018-01-09 12:25 UTC, laurynas-biveinis requested changes
Sorry for missing this PR for over half year

2018-01-09 12:25 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_default_db.test
> +SHOW STATUS LIKE 'Threads_connected';
Debugging output?

2018-01-09 12:25 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_default_db.test
> +SHOW STATUS LIKE 'Threads_connected';
Likewise

2018-01-09 12:25 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_echo.inc
>        # part of wait_until_count_sessions.inc script
"part of wait_until_count_sessions.inc and wait_condition.inc scripts" ?

2018-01-09 12:25 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_default_db.test
> +SELECT * FROM INFORMATION_SCHEMA.PLUGINS WHERE PLUGIN_NAME LIKE 'audit_log';
Debugging output?

2018-01-09 12:25 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_default_db.test
> +--source include/count_sessions.inc      # count_sessions = 2
If this count_sessions is moved above connect(test, ...), then ...

2018-01-09 12:25 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_default_db.test
> +dec $count_sessions;                     # count_sessions = 1
... this hack disappears?

2018-01-09 12:25 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_default_db.test
> +connect (test,localhost,user1,111,db2,); # 2 connections: test, default
No need for connection-enumerating comments anymore?

2018-02-05 10:59 UTC, gl-sergei commented
@laurynas-biveinis can you please take a look before I port it to 5.7 https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2078/

2018-02-06 07:07 UTC, laurynas-biveinis approved these changes
Please port to 5.7

2018-02-09 08:44 UTC, merged