Fix for bug 1626559 in 5.7
percona/percona-server pull request #1762
Opened 2017-05-25 22:40 UTC by gl-sergei

2017-05-25 22:40 UTC, gl-sergei commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/966/

2018-01-09 12:25 UTC, laurynas-biveinis requested changes
Same comments as for the 5.6 version

2018-02-08 09:56 UTC, gl-sergei commented
re-merged 5.6 fix: https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1596/

2018-02-09 08:35 UTC, laurynas-biveinis approved these changes

2018-02-09 08:44 UTC, merged