Fix lp:1673656 "SSL Certificate Subject ALT Names with IPs or DNS: not respected with --ssl-verify-server-cert" (5.6)
percona/percona-server pull request #1780
Opened 2017-06-02 22:11 UTC by percona-ysorokin

2017-06-02 22:13 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1931 (OpenSSL)
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1932 (YaSSL)

2017-06-14 21:54 UTC, george-lorch approved these changes

2017-06-16 07:41 UTC, robgolebiowski requested changes
The same comments as for 5.5

2017-07-18 15:49 UTC, percona-ysorokin commented
Updated Jenkins build links (`--do-test=ssl`)
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1954 (OpenSSL)
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1955 (YaSSL)

2017-07-18 20:28 UTC, merged