Fix lp:1673656 "SSL Certificate Subject ALT Names with IPs or DNS: not respected with --ssl-verify-server-cert" (5.7)
percona/percona-server pull request #1781
Opened 2017-06-02 22:15 UTC by percona-ysorokin

2017-06-02 22:16 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/991 (OpenSSL)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/992 (YaSSL)

2017-06-14 21:58 UTC, george-lorch approved these changes

2017-06-16 07:42 UTC, robgolebiowski requested changes
The same comments as for 5.5

2017-07-18 20:30 UTC, percona-ysorokin commented
Updated Jenkins build links (`--do-test=ssl`)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1070 (OpenSSL)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1071 (YaSSL)

2017-07-18 20:33 UTC, merged