Fixed LP Bug #1662059 by mentioning that JSON data type is supported …
percona/percona-server pull request #1800
Opened 2017-06-21 16:44 UTC by borys-belinsky

…for compressed columns and informing that generated columns can also be compressed by using a syntax extension;

Fixed small grammar and style issues

2017-06-22 01:55 UTC, laurynas-biveinis commented
The style changes would be relevant for 5.6 too?

2017-06-22 11:10 UTC, percona-ysorokin requested changes

2017-06-22 11:10 UTC, percona-ysorokin commented on doc/source/flexibility/compressed_columns.rst
> +virtual and stored. Use this syntax extension as follows:
is applicable to generated STORED columns only (it does not make sense for generated VIRTUAL columns as their values are calculated on the fly)

2017-06-22 11:10 UTC, percona-ysorokin commented on doc/source/flexibility/compressed_columns.rst
> +* ``TEXT`` (including ``LONGTEXT``)
(including TINYTEXT, MEDUUMTEXT, LONGTEXT)

2017-06-23 13:05 UTC, percona-ysorokin approved these changes
LGTM

2017-06-26 16:18 UTC, borys-belinsky commented
There is no style change. It is only correction of grammar and style which does not introduce new or different meaning. For this reason, I would suggest that other version be not changed.

2017-06-27 14:13 UTC, merged