Ps 5.7 tdb 65
percona/percona-server pull request #1813
Opened 2017-07-05 23:35 UTC by georgelorchpercona

2017-07-05 23:35 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1031/

2017-07-07 02:33 UTC, laurynas-biveinis requested changes

2017-07-07 02:33 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb.rpl/t/rpl_tokudb_row_crash_safe.test
> +# for 5.7 --source include/not_group_replication_plugin.inc
This is 5.7

2017-07-13 23:36 UTC, georgelorchpercona commented
new jenkins with changes from 5.6 and 5.7 changes http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1058/

2017-07-14 02:11 UTC, laurynas-biveinis approved these changes

2017-07-14 17:13 UTC, merged