Fix lp:1702903 (Cannot build Percona Server on Debian Stretch) (5.7)
percona/percona-server pull request #1823
Opened 2017-07-12 15:26 UTC by percona-ysorokin

2017-07-12 18:41 UTC, percona-ysorokin commented
Jenkins build links:
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1049 (OpenSSL)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1050 (YaSSL)

2017-07-13 02:29 UTC, laurynas-biveinis requested changes
+ same question re. EC ciphers in the testsuite as in 5.6

2017-07-13 02:29 UTC, laurynas-biveinis commented on mysql-test/t/ssl_bug75311.test
>  # The first error string is returned by YaSSL, the second one by OpenSSL
Three replacements now but the comment explains only the two of them (this comment applies to lower versions too)

2017-07-13 17:05 UTC, george-lorch approved these changes
Same thing as 5.6, you might want to reload the failed jenkins platforms just to be sure.

2017-07-17 11:43 UTC, percona-ysorokin commented on mysql-test/t/ssl_bug75311.test
>  # The first error string is returned by YaSSL, the second one by OpenSSL
Fixed both in 5.6 and 5.7

2017-07-17 16:35 UTC, percona-ysorokin commented
EC- cipher testsuite changes were indeed not necessary. They were added just for symmetry reasons. Reverted.

2017-07-18 12:12 UTC, percona-ysorokin commented
Updated Jenkins build links
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1065 (OpenSSL)
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1066 (YaSSL)

2017-07-18 12:31 UTC, percona-ysorokin commented
@laurynas-biveinis @georgelorch  As there were no code changes (only EC-ciphers fixes and comment corrections in the MTR test cases) since the last review and Jenkins builds are much more stable now, I am going to merge this PR.

2017-07-18 12:33 UTC, laurynas-biveinis approved these changes

2017-07-18 14:25 UTC, merged