Ps 5.7 myr 145
percona/percona-server pull request #1839
Opened 2017-07-21 01:34 UTC by georgelorchpercona

2017-07-21 01:35 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1081/

Some unstable test regressions introduced and logged in MYR and upstream for tracking.

2017-07-21 02:43 UTC, laurynas-biveinis requested changes
Minor changes only, not all of them actionable in this PR

2017-07-21 02:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb.sys_vars/t/rocksdb_compact_cf_basic.test
> +call mtr.add_suppression(" Column family '[a-z]*' not found.");
Should go after the have_foo checks (not necessarily actionable in the current PR)

2017-07-21 02:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/include/bloomfilter.inc
> +--exec sed s/##CF##/" COMMENT 'rev:cf_short_prefix'"/g $tmpl_ddl > $ddl
SQL string statement manipulation or perl would be more canonical for portability, but I guess it's not something to lose sleep over

2017-07-21 02:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/partition.test
> +--error 1517
ER_SAME_NAME_PARTITION

2017-07-21 02:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/partition.test
> +--error 1493
ER_RANGE_NOT_INCREASING_ERROR and then the comment above becomes redundant

2017-07-21 02:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/partition.test
> +--error 1064
ER_PARSE_ERROR

2017-07-21 02:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/partition.test
> +--error 1493
Same as above

2017-07-21 02:43 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/partition.test
> +--error 1508
ER_DROP_LAST_PARTITION and then the comment above disappears

2017-07-21 02:43 UTC, laurynas-biveinis commented on storage/rocksdb/README
> +  --default-storage-engine=rocksdb
This is not correct for us, is it?

2017-07-21 02:43 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.h
> +const char RDB_PER_PARTITION_QUALIFIER_NAME_SEP = '_';
constexpr? Not necessarily actionable in this PR

2017-07-21 02:43 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.h
> +#define DEFAULT_SST_MGR_RATE_BYTES_PER_SEC (64 * 1024 * 1024)
Likewise

2017-07-21 02:43 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_sst_info.h
> +    inline int compare(rocksdb::Slice key1, rocksdb::Slice key2) {
const method?

2017-07-21 02:43 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_sst_info.h
> +    size_t size() { return m_stack.size(); }
const method

2017-07-21 20:30 UTC, georgelorchpercona commented
Addressed most of the comments, jenkins re-spin here with another instability that I am thinking may be specific to jenkins slowness http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1085/

2017-07-24 02:34 UTC, laurynas-biveinis approved these changes
LGTM - @georgelorchpercona , do you want me to merge this while you are away?

2017-07-31 17:51 UTC, merged