Release notes for Percona Server 5.6.36-82.1 updated to fix errors fo…
percona/percona-server pull request #1854
Opened 2017-07-28 14:18 UTC by borys-belinsky

…und during the review

2017-07-28 16:08 UTC, percona-ysorokin approved these changes
LGTM

2017-07-28 16:18 UTC, laurynas-biveinis requested changes

2017-07-28 16:18 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.1.rst
> + When a client application connecting to the Aurora cluster end point using SSL
Previous suggestion not implemented? (no need to mention Aurora; Yura's OpenSSL version comment not added)

2017-07-28 16:18 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.36-82.1.rst
> +Compatibility Matrix
If we do this, this has to go to some section in the main docs in addition to RNs (nobody will find it there after this release)

2017-07-28 16:18 UTC, laurynas-biveinis commented on doc/source/upstream-bug-fixes.rst
> +|:Upstream fix: 5.6                                                                                           |
5.6.38

2017-07-28 16:18 UTC, laurynas-biveinis commented on doc/source/upstream-bug-fixes.rst
>  |:Upstream fix: N/A                                                                                           |
5.6.38

2017-07-28 16:18 UTC, laurynas-biveinis commented on doc/source/upstream-bug-fixes.rst
> +|:Upstream state: Verified (checked on 2017-28-07)                                                            |
YYYY-MM-DD

2017-07-31 19:37 UTC, laurynas-biveinis commented
https://github.com/percona/percona-server/pull/1854/commits/364d507dd6a28d2eaee8e2b0c674fb245eb5fffb and https://github.com/percona/percona-server/pull/1854/commits/7e67de9efb8a89d568cabe1ae4b224c677fbd796 LGTM

2017-08-01 09:45 UTC, borys-belinsky commented on doc/source/release-notes/Percona-Server-5.6.36-82.1.rst
> +Compatibility Matrix
I have created a ticket to update the documentation: https://jira.percona.com/browse/DOC-572

2017-08-01 09:50 UTC, laurynas-biveinis approved these changes

2017-08-01 09:52 UTC, merged