Ps 5.7 myr 154
percona/percona-server pull request #1867
Opened 2017-08-04 16:44 UTC by georgelorchpercona

Cherry-picked the following : 
https://github.com/facebook/mysql-5.6/commit/001ca1fd52157a802656ca6d3b362c56aa8cfc02
https://github.com/facebook/mysql-5.6/commit/6f99962f8d2d2411d7a68c27037dc96801c4b487
https://github.com/facebook/mysql-5.6/commit/d344ec1b59508b5e4956b398eef632563529ca98
https://github.com/facebook/mysql-5.6/commit/a44d6c287111c63d35fde0222adfebeb54d601c7
https://github.com/facebook/mysql-5.6/commit/5159416ed973bd9cbbb090d98ec6307054a11493

These alter the server errmsg file sql/share/errmsg-utf8.txt to add MyRocks engine specific error codes to the 12000+ range.

2017-08-04 16:44 UTC, georgelorchpercona commented
Jenkins http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1105/

2017-08-07 05:37 UTC, laurynas-biveinis requested changes

2017-08-07 05:37 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--exec echo "wait" > $MYSQLTEST_VARDIR/tmp/mysqld.1.expect
--source include/expect_crash.inc

2017-08-07 05:37 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--exec grep "RocksDB: Error 197 finalizing last SST file while setting bulk loading variable" $MYSQLTEST_VARDIR/log/mysqld.1.err | cut -d] -f2
This does not work if some previous test on the same MTR worker also happened to have the same bulk load error (the fix is the same as for the next comment)

2017-08-07 05:37 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--exec echo "" >$MYSQLTEST_VARDIR/log/mysqld.1.err
This ruins troubleshooting, and CURRENT_TEST markers in the log which MTR uses. Please restart the server with custom error log location at the start of the testcase, restart with default at the end, and remove the custom error log.

2017-08-07 05:37 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +# restart the crashed server
--source include/start_mysqld.inc

2017-08-07 05:37 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--source include/have_rocksdb.inc
Add --source include/not_crashrep.inc

2017-08-07 05:37 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +      int rc __attribute__((__unused__));
MY_ATTRIBUTE

2017-08-07 20:23 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--exec echo "" >$MYSQLTEST_VARDIR/log/mysqld.1.err
Ahh crap, yeah, I missed this when importing the commits, should use the $restart_parameters=restart:--log-error=$some_file idiom

2017-08-07 23:21 UTC, georgelorchpercona commented
OK, fixed this stuff and pushed, new jenkins http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1108/ release builds reporting failed but really didn't fail due to https://jira.percona.com/browse/JEN-676

2017-08-08 01:54 UTC, laurynas-biveinis requested changes

2017-08-08 01:54 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--replace_result $SEARCH_FILE LOG_FILE
A nit which does not require fixing, but something to consider in the future: I'd prefer replacing $MYSQLTEST_VARDIR with MYSQLTEST_VARDIR only, there is no need to hide the constant file path part

2017-08-08 01:54 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--enable_reconnect
These two lines are consumed by start_mysqld.inc

2017-08-08 01:54 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--let SEARCH_PATTERN=
Nit: no need to reset those if you don't search_pattern_in_file again (and SEARCH_FILE is required by one of the later comments, see below)

2017-08-08 01:54 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +DROP TABLE t1;
--remove_file $SEARCH_FILE or MTR --repeat is broken

2017-08-08 02:12 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +--enable_reconnect
Ahh, cool, I did not know this, good tip.

2017-08-08 02:17 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +DROP TABLE t1;
Doh, yup, you're right, and I should have caught this. I usually do --repeat=3 before pushing but obviously forgot this time. This specific sequence (use alternate .err log file) seems frequent enough that I wonder if there is some relatively easy way to automate this via some --source and validate proper cleanup. Maybe even going a little higher level and add some facility to mtr like 'get_tmp_filename' that gives a properly pathed tmp file name and validates that the test has cleaned up (or auto cleanup?) on exit.

2017-08-08 02:19 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/bulk_load_errors.test
> +DROP TABLE t1;
I'm thinking of listing tmp and log dirs before and after the testcase run and adding its diff to the testcase state checker.

A funny thing here is that --repeat breaks here by false negative, so it appears to run fine

2017-08-08 23:05 UTC, georgelorchpercona commented
OK, new one http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1109/

2017-08-09 02:18 UTC, laurynas-biveinis approved these changes

2017-08-09 15:50 UTC, merged