Merge upstream 5.6.37 into Percona Server
percona/percona-server pull request #1872
Opened 2017-08-08 22:02 UTC by percona-ysorokin

2017-08-08 22:05 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/job/percona-server-5.6-param/1967/
(all release nodes are marked red for some reason although MTR runs succeeded)

2017-08-09 02:16 UTC, laurynas-biveinis requested changes
Automatic LGTM with scripts/mysqldumpslow.sh converted to @PERL_PATH@. No need for full test cycle: cmake + inspection of @PERL_PATH@ replacement in the script is enough

2017-08-09 02:16 UTC, laurynas-biveinis commented on scripts/CMakeLists.txt
> +  SET (PERL_PATH "/usr/local/bin/perl")
Our scripts/mysqldumpslow.sh also falls under the the s/#!/usr/bin/perl/@PERL_PATH@ /g replacement (I have no idea why upstream only changed scripts dir when there are Perl scripts everywhere)

2017-08-09 11:42 UTC, percona-ysorokin commented on scripts/CMakeLists.txt
> +  SET (PERL_PATH "/usr/local/bin/perl")
fixed

2017-08-09 11:46 UTC, merged