Release notes for PS 5.5.57-38.9
percona/percona-server pull request #1886
Opened 2017-08-11 09:38 UTC by azhebel

2017-08-11 11:07 UTC, laurynas-biveinis requested changes

2017-08-11 11:07 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.57-38.9.rst
> +* Added support and packages for Debian 9 (stretch).
Please consult https://github.com/percona/percona-server/pull/1851/files and https://github.com/percona/percona-server/pull/1854/files for feature and bug bug descriptions

2017-08-11 11:07 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.57-38.9.rst
> +* Minor fixes: :bug:`1160986`, :bug:`1622985`, :bug:`1684601`, :bug:`1689998`,
1622985 should be documented

2017-08-11 11:07 UTC, laurynas-biveinis commented on doc/source/upstream-bug-fixes.rst
> +|:Upstream state: Won't fix                                                                                   |
Spurious change?

2017-08-11 11:07 UTC, laurynas-biveinis commented on doc/source/upstream-bug-fixes.rst
>  =============================================================
Upstream bug 83264 state should have changed with this releae

2017-08-11 12:08 UTC, azhebel commented on doc/source/release-notes/Percona-Server-5.5.57-38.9.rst
> +* Added support and packages for Debian 9 (stretch).
@laurynas-biveinis the first link has no features. Everything from the second one is reflected. What didn't I cover relevant to 5.5? It should be mentioned here https://launchpad.net/percona-server/+milestone/5.5.57-38.9

2017-08-11 12:09 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.57-38.9.rst
> +* Added support and packages for Debian 9 (stretch).
@azhebel, re. features not much, just that Debian 9 packages are only available for amd64

2017-08-11 12:24 UTC, azhebel commented on doc/source/upstream-bug-fixes.rst
>  =============================================================
It is not listed here https://www.percona.com/doc/percona-server/5.5/upstream-bug-fixes.html
What is the corresponding LP bug?

2017-08-11 12:25 UTC, azhebel commented on doc/source/upstream-bug-fixes.rst
> +|:Upstream state: Won't fix                                                                                   |
It was a conflict with earlier change

2017-08-11 12:25 UTC, laurynas-biveinis commented on doc/source/upstream-bug-fixes.rst
>  =============================================================
https://bugs.launchpad.net/percona-server/+bug/1628417

2017-08-11 12:25 UTC, azhebel commented on doc/source/release-notes/Percona-Server-5.5.57-38.9.rst
> +* Minor fixes: :bug:`1160986`, :bug:`1622985`, :bug:`1684601`, :bug:`1689998`,
👍

2017-08-11 12:53 UTC, azhebel commented on doc/source/release-notes/Percona-Server-5.5.57-38.9.rst
> +* Added support and packages for Debian 9 (stretch).
Added

2017-08-11 12:53 UTC, azhebel commented on doc/source/upstream-bug-fixes.rst
>  =============================================================
Added

2017-08-23 13:57 UTC, laurynas-biveinis approved these changes

2017-08-23 16:13 UTC, merged