TDB-72 : Can not rename table in database with non alphanum character…
percona/percona-server pull request #1889
Opened 2017-08-13 02:27 UTC by georgelorchpercona

…s in its name.

- Fixed check for db dir existence to not use MySQL call that transforms again
  the directory name that has already been transformed.
- Added new test to validate the issue is addressed.

2017-08-13 02:27 UTC, georgelorchpercona commented
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1968/

2017-08-13 14:38 UTC, georgelorchpercona commented
Just re-pushed to remove --source include/have_innodb.inc as it was leftover/unneeded. No new jenkins for that.

2017-08-14 04:36 UTC, laurynas-biveinis requested changes
Minor comments, up to you to decide whether to address them

2017-08-14 04:36 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb/t/dir_per_db_rename_with_non_alnum_chars.test
> +ALTER TABLE `a::a@@`.`t1` rename `!@#$%^&*()`.`t1`;
uppercase RENAME

2017-08-14 04:36 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb/t/dir_per_db_rename_with_non_alnum_chars.test
> +--source include/have_tokudb.inc
I'd avoid starting a new testcase and just add an
--echo #
--echo # TDB-72: blah blah
--echo #

block to the existing dir_per_db testcase

2017-08-14 22:20 UTC, georgelorchpercona commented on mysql-test/suite/tokudb/t/dir_per_db_rename_with_non_alnum_chars.test
> +--source include/have_tokudb.inc
Hmm, sounds reasonable enough, particularly since the size and scope of this test is pretty small.

2017-08-14 23:37 UTC, merged