Ps 5.7 myr 148
percona/percona-server pull request #1901
Opened 2017-08-23 22:37 UTC by georgelorchpercona

Merge May 2017 changes

2017-08-23 22:38 UTC, georgelorchpercona commented
jenkins http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1164/

rocksdb.ttl_* and rocksdb.parts tests still going to be unstable as they only changed from sleep to real_sleep in mtr tests. Coming merges add code and debug variables for better synchronization and test stability.

2017-08-24 02:25 UTC, laurynas-biveinis requested changes

2017-08-24 02:25 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/index_merge_rocksdb-master.opt
> +--loose-rocksdb_strict_collation_check=off --binlog_format=row --log-bin
Why the last two?

2017-08-24 02:25 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/index_merge_rocksdb2-master.opt
> +--loose-rocksdb_strict_collation_check=off --binlog_format=row --log-bin --transaction-isolation='READ-COMMITTED'
Dynamic variables better set in the testcase directly

2017-08-24 02:25 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_sst_info.cc
> +#pragma GCC diagnostic push
This is a .cc file and thus benign, but I'd prefer to have a matching pop in order for this to survive any future refactoring better

2017-08-24 03:43 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/index_merge_rocksdb-master.opt
> +--loose-rocksdb_strict_collation_check=off --binlog_format=row --log-bin
Dunno, came from upstream and I didn't really notice. Good question as binlog/rpl shouldn't have anything to do with this test.

2017-08-24 03:44 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/index_merge_rocksdb2-master.opt
> +--loose-rocksdb_strict_collation_check=off --binlog_format=row --log-bin --transaction-isolation='READ-COMMITTED'
true, binlog options again are probably not needed here, but, trx iso I think is as IIRC the test includes files that use multiple connections...I'll have to look to be sure.

2017-08-24 03:45 UTC, georgelorchpercona commented on storage/rocksdb/rdb_sst_info.cc
> +#pragma GCC diagnostic push
yeah, and as I understand this is supposed to be temporary. I'll look ahead in merge history to see if there is another change coming, if not, I'll add a pop.

2017-08-24 15:00 UTC, georgelorchpercona commented on mysql-test/suite/rocksdb/t/index_merge_rocksdb2-master.opt
> +--loose-rocksdb_strict_collation_check=off --binlog_format=row --log-bin --transaction-isolation='READ-COMMITTED'
Actually, I see the problem, index_merge1.inc and possibly others restart mysqld, which wipes/resets any dynamic setting back to default. Thus iso needs to be set here in the .opt file to ensure it survives restarts.

2017-08-25 14:05 UTC, georgelorchpercona commented
Forgot the new jenkins link http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1166/

2017-08-28 16:33 UTC, georgelorchpercona commented
Going ahead and merging since everything was addressed and jenkins runs are clean.
Reported MYR-169 : rocksdb.sys_vars.rocksdb_pause_background_work_basic is unstable

2017-08-28 16:33 UTC, merged