Implemented Step 1 of bp:logical-read-ahead (Merge aio page read requests) (5.7)
percona/percona-server pull request #1922
Opened 2017-09-11 15:01 UTC by percona-ysorokin

2017-09-11 15:05 UTC, laurynas-biveinis requested changes

2017-09-11 15:05 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +		ut_malloc_nokey(m_slots.size() * sizeof(struct iocb*)));
ut_zalloc_nokey ?

2017-09-11 15:30 UTC, percona-ysorokin commented on storage/innobase/os/os0file.cc
> +		ut_malloc_nokey(m_slots.size() * sizeof(struct iocb*)));
fixed

2017-09-11 20:57 UTC, percona-ysorokin commented
Jenkins build link
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1201

2017-09-12 01:39 UTC, laurynas-biveinis approved these changes

2017-09-12 08:16 UTC, merged

2017-09-13 03:57 UTC, laurynas-biveinis commented
@percona-ysorokin, this needs a separate 5.7 blueprint on Launchpad

2017-09-13 09:51 UTC, percona-ysorokin commented
bp:merge-aio-page-read-requests-5.7 registered
https://blueprints.launchpad.net/percona-server/+spec/merge-aio-page-read-requests-5.7