lp-1657737: Print locking transaction which cause "Lock wait timeout"…
percona/percona-server pull request #1982
Opened 2017-11-21 11:14 UTC by vlad-lesin

… errors into log file

Post push fixes.

See https://github.com/percona/percona-server/pull/1970 for details.

Testing: http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2015/

2017-11-22 12:34 UTC, laurynas-biveinis requested changes

2017-11-22 12:34 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_print_lock_wait_timeout_trx.test
> +--exec echo "restart: --log-error=$log_error_path" > $MYSQLTEST_VARDIR/tmp/mysqld.1.expect
Please use restart_mysqld.inc

2017-11-29 22:37 UTC, vlad-lesin commented on mysql-test/suite/innodb/t/percona_print_lock_wait_timeout_trx.test
> +--exec echo "restart: --log-error=$log_error_path" > $MYSQLTEST_VARDIR/tmp/mysqld.1.expect
fixed

2017-11-29 22:37 UTC, vlad-lesin commented
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2023/

2017-11-30 04:20 UTC, laurynas-biveinis approved these changes

2017-11-30 08:55 UTC, merged