Fixed DOC-654 by documenting innodb_ft_ignore_stopwords (5.7)
percona/percona-server pull request #2014
Opened 2017-12-11 11:00 UTC by hrvojem

fixed dep8 issues in older RNs and a build warning

2017-12-11 11:42 UTC, percona-ysorokin commented on doc/source/flexibility/innodb_fts_improvements.rst
> +searched is ``east``, this one will find no matches because ``ea`` is on the
Although this is exactly what is stated in the blueprint document `ea` is not a default stopword.
I would suggest to change this to just `a`.

2017-12-11 11:42 UTC, percona-ysorokin commented on doc/source/flexibility/innodb_fts_improvements.rst
> +When enabled, this variable will instruct |InnoDB| Full Text Search n-gram
Remove `n-gram`. This is true for other parsers as well.

2017-12-11 12:33 UTC, hrvojem commented
Fixed

2017-12-11 14:26 UTC, laurynas-biveinis requested changes

2017-12-11 14:26 UTC, laurynas-biveinis commented on doc/source/flexibility/innodb_fts_improvements.rst
> +By default n-gram indexes check the `stopwords list
Make a new subsection for stopword ignoring

2017-12-11 14:26 UTC, laurynas-biveinis commented on doc/source/flexibility/innodb_fts_improvements.rst
> +By default n-gram indexes check the `stopwords list
All FTS indexes

2017-12-11 14:26 UTC, laurynas-biveinis commented on doc/source/flexibility/innodb_fts_improvements.rst
> +   Although this variable is introduced to resolve n-gram issues, it affects
BP description is usually not suitable for copy-pasting into docs directly. This note should be merged to the description above

2017-12-11 15:31 UTC, hrvojem commented
Fixed

2017-12-13 04:06 UTC, laurynas-biveinis approved these changes

2017-12-13 06:41 UTC, merged