lp1708073: Fix client help showing a 5.6 link
percona/percona-server pull request #2021
Opened 2017-12-14 11:25 UTC by inikep

2017-12-15 04:49 UTC, laurynas-biveinis commented
This is https://github.com/percona/percona-server/pull/2017 continued

2017-12-15 12:03 UTC, percona-ysorokin requested changes

2017-12-15 12:03 UTC, percona-ysorokin commented on client/mysql.cc
> +  my_snprintf((char*) glob_buffer.ptr(), glob_buffer.alloced_length(),
Use c++-style casts (`xxx_cast<char*>()`) for the new code. I believe `const_cast` is enough here.

2017-12-15 12:03 UTC, percona-ysorokin commented on client/mysql.cc
> +  put_info((char*) glob_buffer.ptr(), INFO_INFO);
Unnecessary cast  - `glob_buffer.ptr()` is already `const char*`

2017-12-18 10:01 UTC, inikep commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1392/

2017-12-18 13:42 UTC, percona-ysorokin approved these changes
Looks good to me (LGTM)

2017-12-20 15:27 UTC, merged