lp1739734: Fixed federated SE regression introduced in the gcc7 fixes.
percona/percona-server pull request #2033
Opened 2017-12-22 15:35 UTC by dutow

Also added a related test.

2017-12-27 04:56 UTC, laurynas-biveinis requested changes

2017-12-27 04:56 UTC, laurynas-biveinis commented on mysql-test/suite/federated/federated_bug_lp1739734.test
> +--echo #
Please check the Confluence page on the testcase naming, it should be named percona_bug1739734

2017-12-27 04:56 UTC, laurynas-biveinis commented on mysql-test/suite/federated/federated_bug_lp1739734.test
> +--echo #
No .result file

2017-12-27 04:56 UTC, laurynas-biveinis commented on mysql-test/suite/federated/federated_bug_lp1739734.test
> +DROP SERVER IF EXISTS local_server;
No need for DROP IF EXISTS in the testcases

2017-12-28 14:48 UTC, dutow commented
https://jenkins.percona.com/job/percona-server-5.5-param/1611/

2018-01-02 04:28 UTC, laurynas-biveinis approved these changes

2018-01-02 11:22 UTC, percona-ysorokin approved these changes
LGTM

2018-01-03 09:04 UTC, merged