Added .travis.yml for Travis CI (PS-5.6)
percona/percona-server pull request #2051
Opened 2018-01-04 16:10 UTC by inikep

2018-01-04 17:30 UTC, percona-ysorokin requested changes

2018-01-04 17:30 UTC, percona-ysorokin commented on .travis.yml
> +    -DWITHOUT_TOKUDB=ON
Both RocksDB and TokuDB must be enabled.

2018-01-04 17:30 UTC, percona-ysorokin commented on .travis.yml
> +    -DWITHOUT_TOKUDB=ON
Both RocksDB and TokuDB must be enabled.

2018-01-05 07:55 UTC, laurynas-biveinis commented on .travis.yml
> +    -DWITH_ZLIB=system
-DWITH_LIBEVENT=system ?

2018-01-05 07:55 UTC, laurynas-biveinis commented on .travis.yml
> +    -DWITH_ZLIB=system
Likewise

2018-01-08 15:09 UTC, inikep commented
I added tests with and without `-DWITH_READLINE=system` and `-DWITH_PAM=1`. I also added `-DWITH_LIBEVENT=bundled` and `-DWITH_LIBEVENT=system`.

2018-01-12 15:28 UTC, percona-ysorokin approved these changes
LGTM

2018-01-12 15:31 UTC, merged