Added .travis.yml for Travis CI (PS-5.7)
percona/percona-server pull request #2052
Opened 2018-01-04 16:12 UTC by inikep

2018-01-04 17:32 UTC, percona-ysorokin requested changes

2018-01-04 17:32 UTC, percona-ysorokin commented on .travis.yml
> +    -DWITHOUT_TOKUDB=ON
The same as in 5.6 (both TokuDB and RocksDB must be enabled).

2018-01-04 17:32 UTC, percona-ysorokin commented on .travis.yml
> +    -DWITHOUT_TOKUDB=ON
The same as in 5.6 (both TokuDB and RocksDB must be enabled).

2018-01-04 23:29 UTC, RoelVdP commented
@percona-ysorokin maybe I am misreading something here, but the comment says "both TokuDB and RocksDB must be enabled" whereas the RocksDB build option (-DWITH_ROCKSDB) is not included and TokuDB seems to be the reverse (-DWITHOUT_TOKUDB=ON instead of nothing)?

2018-01-05 07:57 UTC, laurynas-biveinis commented on .travis.yml
> +    -DWITH_ZLIB=system
-DWITH_CURL=system -DWITH_LZ4=system -DWITH_MECAB=system -DWITH_PROTOBUF=system ?

2018-01-05 07:57 UTC, laurynas-biveinis commented on .travis.yml
> +    -DWITH_ZLIB=system
Likewise

2018-01-05 14:35 UTC, percona-ysorokin commented
@RoelVdP You are absolutely right. The fix is on its way.

2018-01-12 15:29 UTC, percona-ysorokin approved these changes
LGTM

2018-01-12 15:32 UTC, merged

2018-01-12 21:01 UTC, RoelVdP commented
@percona-ysorokin hmm so maybe I am not following something here, but the merge includes;

```
+    -DWITHOUT_TOKUDB=ON
+    -DWITHOUT_ROCKSDB=ON
```

i.e. both are disabled?

2018-01-15 10:57 UTC, percona-ysorokin commented
@RoelVdP Unfortunately, we encountered a limitation with free Travis-CI accounts. Any job cannot last longer than 50 min. And we were far beyond that limit when compiling full source tree. So, we had to TEMPORARILY disable both toku and rocks engines for 5.7.
We are not giving up and still investigating how we can improve compilation speed. So, just be patient. this is gonna be an iterative process.

2018-01-16 00:16 UTC, RoelVdP commented
Got it, thanks