PS-298: keyring_vault's timeout should be configurable
percona/percona-server pull request #2068
Opened 2018-01-11 15:09 UTC by robgolebiowski

This patch adds keyring_vault_timeout variable. With use of this
variable user can control the timeout of keyring_vault - Vault server
connection [expressed in seconds]. The default value is 15s, the minimal
is 1s and maximal is 86400s (24 hours). The timeout can be disabled
by setting keyring_vault_timeout to 0.

2018-01-11 16:51 UTC, robgolebiowski commented
JR => https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1453/

2018-01-12 12:04 UTC, laurynas-biveinis requested changes

2018-01-12 12:04 UTC, laurynas-biveinis commented on plugin/keyring_vault/tests/mtr/keyring_vault_timeout.test
> +let $upper_bound= `SELECT @@GLOBAL.keyring_vault_timeout + 5`;
I'd test the lower bound only, since the Jenkins delays are boundless.

2018-01-12 12:04 UTC, laurynas-biveinis commented on plugin/keyring_vault/vault_curl.h
> +  uint *timeout;
Why it's a pointer?

2018-01-12 15:07 UTC, percona-ysorokin commented on plugin/keyring_vault/vault_curl.h
> +  uint *timeout;
The same question

2018-01-17 07:55 UTC, robgolebiowski commented
JR => https://jenkins.percona.com/job/mysql-5.7-param/1459/ (There is test failure : keyring_vault.keyring_vault_thd_wait due to bug in threadpool, I have filled a bug: PS-311)

2018-01-19 13:25 UTC, percona-ysorokin approved these changes
LGTM with minor comments

2018-01-19 13:25 UTC, percona-ysorokin commented on unittest/gunit/keyring_vault/vault_io-t.cc
> +    uint zero_timeout;
never used?

2018-01-19 13:25 UTC, percona-ysorokin commented on unittest/gunit/keyring_vault/vault_keys_container-t.cc
> +    uint zero_timeout;
Likewise, never used?

2018-01-22 07:48 UTC, laurynas-biveinis approved these changes
Extremely minor comment

2018-01-22 07:48 UTC, laurynas-biveinis commented on plugin/keyring_vault/tests/mtr/timeout_basic.test
> +--echo # Set keyring_vault's timeout and set it to maximum value, i.e. 86400s(24 hours)
Space after 86400s

2018-01-22 08:44 UTC, merged