Merge upstream 5.7.21 into Percona Server
percona/percona-server pull request #2137
Opened 2018-02-07 15:45 UTC by percona-ysorokin

2018-02-07 15:46 UTC, percona-ysorokin commented
Jenkins build link:
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1588/

2018-02-07 15:52 UTC, percona-ysorokin commented
@robgolebiowski 
Please, take a look at the `keyring_vault` part. These changes were necessary because of the extensions in the `keyring` API
WL #9769 "Keyring migration tool and new commercial keyring_encrypted_file plugin."
(commit mysql/mysql-server@4b4dd7a).
(see commit message for more details)

2018-02-08 10:53 UTC, laurynas-biveinis requested changes

2018-02-08 10:53 UTC, laurynas-biveinis commented on client/dump/sql_formatter.cc
> +          *((ulong*)&m_options->m_gtid_purged) == ((ulong)GTID_PURGED_AUTO))
Shouldn't this excellent code be replaced with a straightforward comparison as above due to https://bugs.mysql.com/bug.php?id=89422 / https://github.com/percona/percona-server/commit/f105be761ccfe313c7c7526171dc716ab33122e7 ?

2018-02-08 10:54 UTC, laurynas-biveinis commented
Please include TDB-94 in the commit message. My review comment change should require only --suite=main --do-test=mysqlpump testing

2018-02-08 12:35 UTC, percona-ysorokin commented on client/dump/sql_formatter.cc
> +          *((ulong*)&m_options->m_gtid_purged) == ((ulong)GTID_PURGED_AUTO))
Fixed

2018-02-08 14:43 UTC, percona-ysorokin commented
New Jenkins run (--suite=main --do-test=mysqlpump --big-test)
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1600/parameters/
Some nodes are marked red there despite the fact that all the tests passed successfully (could be another problem with parsing Jenkins results).

2018-02-08 14:49 UTC, laurynas-biveinis approved these changes

2018-02-08 15:08 UTC, merged