Releae notes for PS 5.6.39-83.1
percona/percona-server pull request #2145
Opened 2018-02-11 23:51 UTC by fiowro

2018-02-12 02:53 UTC, laurynas-biveinis requested changes
Can you also confirm (cc @hrvojem) that this is complete release content - given that development happened on the LP to JIRA transition, with bugs assigned to an LP milestone and 5.6.NEXT and 5.6.exact-version in JIRA?

2018-02-12 02:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +|Percona Server| now uses *TraviCI* for additional tests. Bug fixed
Travis CI

2018-02-12 02:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +There was an incompatibility of tokudb.backup suite with AddressSanitizer
Not a code change in the release; remove, not even a part of "other bugs"

2018-02-12 02:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +A memory leak was fixed in the PerconaFT library. Bug fixed :jirabug:`TDB-98`.
Needs more details - a server user will be concerned whether the leak affects him?

2018-02-12 02:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +Fixed vulnerability caused by the uninitialized variable being used in a key
"Vulnerability" is a strong word, does that bug have a security angle?

2018-02-12 02:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +(bug :jirabug:`TDB-78`).
TDB-78 to "other bugs" unless @georgelorchpercona thinks otherwise

2018-02-12 02:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +The |InnoDB| fulltext search returned case insensitive matches, regardless of
We did not fix this bug but took the fix as a part of upstream merge

2018-02-12 06:24 UTC, fiowro commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +Fixed vulnerability caused by the uninitialized variable being used in a key
"Potential vulnerability"?

2018-02-12 06:58 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +Fixed vulnerability caused by the uninitialized variable being used in a key
What I don't understand, why is this even a "potential" vulnerability?

2018-02-12 08:50 UTC, fiowro commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +Fixed vulnerability caused by the uninitialized variable being used in a key
Well, just general considerations, an uninitialized local variable allocated in stack... Taken into account stack randomization and other protection techniques, risk is much lower on modern systems, but such things are still supposed to bring some potential risk :) But from the other side, it is just a test... I'll change this to "Fixed uninitialized variable"

2018-02-12 12:28 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +
extra newline?

2018-02-12 12:28 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +Percona is glad to announce the release of |Percona Server| 5.6.39-83.1 on February 12, 2018. Downloads are available `here
line longer than 80, does the document pass doc8?

2018-02-12 12:50 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +Fixed vulnerability caused by the uninitialized variable being used in a key
I see, we usually don't label such bugs vulnerabilities unless we have other info. Perhaps @georgelorchpercona will have an opinion.

2018-02-12 13:11 UTC, percona-ysorokin commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +CVE-2018-2622, CVE-2018-2640, CVE-2018-2665, CVE-2018-2668.
This list is longer for 5.6
According to http://www.oracle.com/technetwork/security-advisory/cpujan2018-3236628.html#AppendixMSQL
```
CVE-2018-2562	Server: Partition	5.5.58 and prior, 5.6.38 and prior, 5.7.19 and prior
CVE-2018-2622	Server: DDL	5.5.58 and prior, 5.6.38 and prior, 5.7.20 and prior
CVE-2018-2640	Server: Optimizer	5.5.58 and prior, 5.6.38 and prior, 5.7.20 and prior
CVE-2018-2665	Server: Optimizer	5.5.58 and prior, 5.6.38 and prior, 5.7.20 and prior
CVE-2018-2668	Server: Optimizer	5.5.58 and prior, 5.6.38 and prior, 5.7.20 and prior

CVE-2018-2696	Server: Security: Privileges	5.6.38 and prior, 5.7.20 and prior
CVE-2018-2583	Stored Procedure	5.6.38 and prior, 5.7.20 and prior
CVE-2018-2612	InnoDB	5.6.38 and prior, 5.7.20 and prior
CVE-2018-2703	Server: Security : Privileges	5.6.38 and prior, 5.7.20 and prior
CVE-2018-2573	Server: GIS	5.6.38 and prior, 5.7.20 and prior
CVE-2017-3737	Server: Packaging (OpenSSL)	5.6.38 and prior, 5.7.20 and prior
CVE-2018-2647	Server: Replication	5.6.38 and prior, 5.7.20 and prior
CVE-2018-2591	Server: Partition	5.6.38 and prior, 5.7.19 and prior
CVE-2018-2590	Server: Performance Schema	5.6.38 and prior, 5.7.20 and prior
CVE-2018-2645	Server: Performance Schema	5.6.38 and prior, 5.7.20 and prior	 

CVE-2018-2576	Server: DML	5.7.20 and prior
CVE-2018-2586	Server: DML	5.7.20 and prior
CVE-2018-2646	Server: DML	5.7.20 and prior
CVE-2018-2565	Server: InnoDB	5.7.20 and prior
CVE-2018-2600	Server: Optimizer	5.7.20 and prior
CVE-2018-2667	Server: Optimizer	5.7.20 and prior
```

2018-02-12 15:20 UTC, percona-ysorokin commented
@hrvojem Please, also double check if `dynamic version` functionality

2018-02-12 15:36 UTC, hrvojem commented
@percona-ysorokin https://github.com/percona/percona-server/pull/2103 is not part of this 5.6 release

2018-02-12 15:46 UTC, percona-ysorokin commented
@hrvojem Great.
Just to let you know that @inikep created 2 new doc tasks for this: one for `5.7.21-20` and another one for `5.6.40-next`
https://jira.percona.com/browse/DOC-703
https://jira.percona.com/browse/DOC-704

2018-02-12 15:58 UTC, georgelorchpercona commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +Fixed vulnerability caused by the uninitialized variable being used in a key
Agreed, this is in a test, which is not shipped with our binaries, so no issue exists within the engine at all. I wouldn't even mention it at all.

2018-02-12 15:59 UTC, george-lorch approved these changes
TDB stuff looks good.

2018-02-13 03:59 UTC, laurynas-biveinis requested changes
There is also a typo in the commit message "Releae"

2018-02-13 03:59 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +February 12, 2018. Downloads are available `here
Bump the date as necessary

2018-02-13 03:59 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +was incompatible with InnoDB table definitions, thus adding new indexes would
... with InnoDB keys longer than 1000 bytes, thus ...

2018-02-13 03:59 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +A build error on FreeBSD was fixed (:psbug:`2284`).
caused by psbug ...

2018-02-13 03:59 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +Inserting special characters into a table caused the audit_log plugin to
More along the lines of "Server queries that contained JSON special characters and were logged by audit_log (link?) plugin in JSON format caused invalid output due to lack of escaping"

2018-02-13 03:59 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +A GCC 7 warning fix introduced regression in |Percona Server|
Original bug link?

2018-02-13 03:59 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +key objects on shutdown. Bug fixed :jirabug:`TDB-98`.
destroying

2018-02-13 15:12 UTC, laurynas-biveinis requested changes

2018-02-13 15:12 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.6.39-83.1.rst
> +A build error on FreeBSD caused by :psbug:`2284` was fixed.
It looks like you have replaced the fixed bug id with the bug id whose change introduced the regression, but both have to be present

2018-02-13 16:00 UTC, percona-ysorokin approved these changes
LGTM

2018-02-13 19:25 UTC, merged