Ps 5.7 myr 47
percona/percona-server pull request #2162
Opened 2018-02-13 21:45 UTC by georgelorchpercona

2018-02-13 21:45 UTC, georgelorchpercona commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1613/

2018-02-15 12:58 UTC, laurynas-biveinis requested changes
Is there a TokuDB angle to this?

2018-02-15 12:58 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/i_s_trx_rpl.test
> +--disable_warnings
There is a rpl_skip_start_slave (sic?) arg for master-slave.inc instead

2018-02-15 12:58 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/i_s_trx_rpl.test
> +--let $it=0
Replace with wait_for_condition.inc, among other things this loop is spinning without any pause between iterations

2018-02-15 12:58 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +  if (rpl_skip_tx_api_var == TRUE && super_read_only == FALSE) {
return !rpl_skip_tx_api_var || super_read_only

2018-02-15 22:02 UTC, georgelorchpercona commented
No TokuDB, PerconaFT does't have quite the same concept implemented, although it might be worth investigating if there is a way to use FT w/o transactions.

2018-02-15 23:14 UTC, georgelorchpercona commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1633/

2018-02-16 18:35 UTC, georgelorchpercona commented
OK, changes made, jenkins looks good (except for the known instabilities)

2018-02-19 04:19 UTC, laurynas-biveinis requested changes

2018-02-19 04:19 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +  if (rpl_skip_tx_api_var && !super_read_only) {
if (foo) return false; return true; -> return !foo;

2018-02-19 19:46 UTC, georgelorchpercona commented
trivial logic fix, new jenkins https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1649/

2018-02-20 14:28 UTC, laurynas-biveinis approved these changes

2018-02-20 17:19 UTC, merged