Release notes for PS 5.7.21-20.ease-notes/release-notes_index.rst
percona/percona-server pull request #2171
Opened 2018-02-14 23:29 UTC by fiowro

Also includes minimal fixes for DOC-695 (documenting server restart
on detected data corruption) and DOC-704 (version_suffix variable)

2018-02-15 03:58 UTC, george-lorch approved these changes
TDB and MYR are accurate, but I think I need to do a better job of exposing fixes and improvements to MYR that comes as part of upstream merges so they can be reflected in our release notes.

2018-02-15 07:24 UTC, hrvojem requested changes
Please add the PS changes as mentioned on Slack

2018-02-15 15:03 UTC, percona-ysorokin requested changes

2018-02-15 15:03 UTC, percona-ysorokin commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +
`version_comment` is no longer read-only. This should be mentioned here as well

2018-02-15 15:03 UTC, percona-ysorokin commented on doc/source/ps-variables.rst
Most probably `version_comment` should be mentioned here as well as its behavior is not the same as in upstream - it's no longer read-only.

2018-02-15 20:19 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +* It was possible to enable ``encrypt_binlog`` with no binary logging. Bug
:variable:`encrypt_binlog` ?

2018-02-15 20:20 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +  ``audit_log`` plugin in JSON format caused invalid output due to lack of
:ref:`audit_log_plugin`

2018-02-15 20:20 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +Other bugs fixed: :psbug:`257`, :psbug:`1090` (upstream :mysqlbug:`78048`), :psbug:`1109`, :psbug:`1127`, :psbug:`2415`,
doc8

2018-02-15 20:21 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +  :psbug:`255`) and on MacOS (caused by fixing the bug :psbug:`264`).
in |Percona Server| :rn:`$verision` so users know which versions are affected

2018-02-15 20:27 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +
only 21 entry, while milestone contains 34, some bugs (like ps-1075 and ps-3781) are missing from the list.

2018-02-16 09:41 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +
Missing https://jira.percona.com/browse/PS-298 description.

2018-02-16 14:54 UTC, robgolebiowski commented on doc/source/management/data_at_rest_encryption.rst
> +  ``keyring_vault`` this token also allows to remove keys from the Vault, as
this token also -> this token needs to allow removing . Something like this removing is an attribute of a token

2018-02-16 17:20 UTC, hrvojem commented on doc/source/management/data_at_rest_encryption.rst
> +Range: 0 - 86400
this should be part of the table, move to line 243 :range: 0 - 86400

2018-02-19 04:23 UTC, laurynas-biveinis requested changes

2018-02-19 04:23 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +  GCC 7. Bugs fixed :psbug:`3780` (upstream :mysqlbug:`89420`,
warning fixes (not errors, thus it was possible to compile under GCC 7 already, if needed with warnings-as-errors relaxed)

2018-02-19 04:23 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +* It was possible to enable :variable:`encrypt_binlog` with no binary logging.
with no binary or relay logging enabled

2018-02-19 04:23 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +* Long buffer wait times where occuring on busy servers in case of several
IMPORT TABLESPACE, what workers?

2018-02-19 04:24 UTC, laurynas-biveinis commented
syle -> style in the commit message

2018-02-19 10:46 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +
Please add the list of CVEs that are being fixed with this release.

2018-02-19 12:41 UTC, hrvojem approved these changes

2018-02-19 13:39 UTC, laurynas-biveinis requested changes
No further reviews from me are needed after addressing the comments

2018-02-19 13:39 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +on February 16, 2018. Downloads are available `here
Date

2018-02-19 13:39 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.21-20.rst
> +* A GCC 7 warning fix introduced regression in |Percona Server| that lead to
s/lead/led

2018-02-19 15:08 UTC, merged