PS-3834: Implement innodb log scrubbing
percona/percona-server pull request #2176
Opened 2018-02-16 12:23 UTC by dutow

Based on the same feature in MariaDB

2018-02-19 14:26 UTC, laurynas-biveinis requested changes
This is not mergeable PR until redo log itself is encrypted in the first place. No point in addressing review comments until then neither (as bulk of them are about tests, which will need it)

Please add feature tests (enable that option, and issue write workload, both at full speed and throttled).
Add a small testcase that innodb_read_only is handled correctly

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/log0log.h
> +log_ensure_scrubbing_thread(void);
extern "C" ?

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +DECLARE_THREAD(log_scrub_thread)(void*);
Redundant declaration

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
>  				<< ". Pending log flush writes: " << n_flush;
Diagnose scrubber running too

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +void
Header comment

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/log0log.h
> +void
Header comment

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/srv0srv.h
> +	int64_t innodb_scrub_log;
Comment (it's genuinely not clear, what's counted here?)

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +/******************************************************//**
New InnoDB doxygen style comment

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +consistent archived log files and scrubbing redo log. */
There is no "consistent archived log files" in 5.7 innodb

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +	/* We retrieve lsn only because otherwise gcc crashed on HP-UX */
Let's not

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +	ut_ad(!recv_no_log_write);
Assert not read only mode too

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +/*****************************************************************//*
New InnoDB doxygen style comments

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +/*****************************************************************//**
Likewise

2018-02-19 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +	ut_ad(!srv_read_only_mode);
This thread is invisible for performance schema

2018-02-19 14:29 UTC, laurynas-biveinis commented
Once it can be actually tested, run the whole testsuite with scrubbing enabled, collect any meaningful failures to new regression testcases

2018-10-24 12:12 UTC, dutow commented
Closing this PR, as it's now part of the "everything related to scrubbing" PR:
https://github.com/robgolebiowski/percona-server/pull/3/files

2018-10-24 12:12 UTC, closed without merging