PS-1095: Fix integer overflow in threadpool
percona/percona-server pull request #2190
Opened 2018-02-21 11:24 UTC by dutow

2018-02-21 12:57 UTC, laurynas-biveinis requested changes
Consider adding testcase to 5.5/5.6 too

2018-02-21 12:57 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps1095.test
> +# The server should be disconnected by the timer thread
Don't assume that in our Jenkins the timer thread will be scheduled to be run at least once, but synchronize: replace --error/drop table with wait_until_disconnected.inc

2018-02-21 12:57 UTC, laurynas-biveinis commented on sql/threadpool_unix.cc
> +    set_timespec_nsec(&ts, timer->tick_interval*1000000ULL);
Spaces around * since you are touching it

2018-02-22 12:42 UTC, dutow commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1664/

2018-02-22 12:56 UTC, laurynas-biveinis approved these changes

2018-02-22 15:15 UTC, merged