PS-290: Crash in the unsafe query warning checks with views
percona/percona-server pull request #2197
Opened 2018-02-26 12:23 UTC by dutow

In 5.7, the table pointer is null on updatable views, tables are
listed in the view_tables list.

2018-02-27 04:42 UTC, laurynas-biveinis requested changes
I am not sure re. its status in the lower versions: LP said "New", i.e. not checked there yet, and JIRA says "Not 5.5, Not 5.6", i.e. checked and found to not apply there. Is this correct?

In any case, please add the testcase to the lower versions too

2018-02-27 04:42 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps290.test
> +# PS-290: Unsafe query warning improvements caused a crash
The test should go to binlog suite, and SET binlog_format replaced with have_binlog_format_statement.inc

2018-02-27 04:42 UTC, laurynas-biveinis commented on sql/sql_base.cc
> +  } else {
}
else
{

2018-02-27 08:54 UTC, dutow commented
Yes, I checked it, and it's 5.7 only.

2018-02-27 09:50 UTC, dutow commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1677/

2018-02-28 03:22 UTC, laurynas-biveinis reviewed
Same as with 5.5 re. testcase, code part looks good

2018-03-01 08:38 UTC, merged