PS-1125: Move all CONSTRAINT/FOREIGN KEY declarations to ALTER TABLE
percona/percona-server pull request #2198
Opened 2018-02-26 15:25 UTC by inikep

This commit also fixes PS-3863.
It removes fixes for PS-605 which are not needed now.

2018-02-26 16:58 UTC, percona-ysorokin requested changes

2018-02-26 16:58 UTC, percona-ysorokin commented on client/mysqldump.c
> +    if (c == '\n' && !has_autoinc &&
Why moving `has_autoinc` before checking `type`?

2018-02-26 16:58 UTC, percona-ysorokin commented on client/mysqldump.c
> +	alter_constraints_list= list_reverse(alter_constraints_list);
Indentation

2018-02-26 16:58 UTC, percona-ysorokin commented on client/mysqldump.c
> +    for (keys= list_length(skipped_keys_list); keys > 0; keys--)
Why do we generate separate `ALTER TABLE` statement for each constraint? Can we combine them into a single statement? E. g.
```
ALTER TABLE t1
  ADD CONSTRAINT t1_ibfk_1 FOREIGN KEY (a) REFERENCES t1 (id),
  ADD CONSTRAINT t1_ibfk_2 FOREIGN KEY (b) REFERENCES t1 (id);
```

2018-02-26 16:58 UTC, percona-ysorokin commented on client/mysqldump.c
> +    for (keys= list_length(skipped_keys_list); keys > 0; keys--)
Moreover, why separate `CONSTRAINT`s from `KEY`s / `UNIQUE_KEY`s / `PRIMARY KEY`s? I believe MySQL grammar allows mixing them:
```
ALTER TABLE t1
  ADD KEY `a_index` (`a`),
  ADD CONSTRAINT `t1_const` FOREIGN KEY (`a`) REFERENCES `t1` (`id`);
```

2018-02-26 16:58 UTC, percona-ysorokin commented on mysql-test/t/percona_mysqldump_innodb_optimize_keys.test
> +#              implicitly named FK constraints
`explicitly`?

2018-02-26 18:45 UTC, percona-ysorokin commented
Jenkins build link
https://jenkins.percona.com/job/percona-server-5.6-param/2086/

2018-02-27 04:37 UTC, laurynas-biveinis requested changes

2018-02-27 04:37 UTC, laurynas-biveinis commented on client/mysqldump.c
> +LIST *alter_constraints_list;
static

2018-02-27 04:37 UTC, laurynas-biveinis commented on mysql-test/t/percona_mysqldump_innodb_optimize_keys.test
> +#     PS-605    explicitly named FK constraints
Why inserting a new bug number in the middle of another line-wrapped bug title?

2018-02-27 09:38 UTC, inikep commented on client/mysqldump.c
> +    if (c == '\n' && !has_autoinc &&
I think it makes code more readable.

2018-02-27 12:55 UTC, percona-ysorokin approved these changes
LGTM

2018-02-27 16:16 UTC, inikep commented
https://jenkins.percona.com/job/percona-server-5.5-param/1634/

2018-02-28 03:06 UTC, laurynas-biveinis approved these changes

2018-03-01 09:27 UTC, merged