TDB-137 : TokuDB 5.6 missing MRR tests
percona/percona-server pull request #2228
Opened 2018-03-13 18:26 UTC by georgelorchpercona

- TokuDB 5.6 supports the Multi-Range Read optimization but has no tests to
  verify it. This adds the basic MRR test taken from mysql-test/t/inodb_mrr.test
  with some minor modifications.

2018-03-13 18:26 UTC, georgelorchpercona commented
https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2108/

2018-03-14 03:30 UTC, laurynas-biveinis requested changes
How did you choose which of the MRR tests to adopt? These look like InnoDB-specific MRR tests, while there is include/mrr_tests.inc, which can be reused without copy-pasting. Please review `t/innodb_mrr.test`, `t/innodb_mrr_all.test`, `t/innodb_mrr_*.test`, `t/myisam_mrr*.test`, perhaps same should be adopted here.

2018-03-14 03:58 UTC, georgelorchpercona commented
This does include mrr_all, plus it copy-paste from innodb specific to tokudb specific test that tests two very specific cases. All include the same basic test of mysql-test/include/mrr_tests.inc. Innodb only adds two specific coded tests that are changed from innodb to tokudb. I only did not add the mrr_cost test, which is not a bad idea but seems very redundant as it is more intentioned to test the optimizer behavior and not how engines react/respond as engine participation is identical. I can add it but IMHO it is a useless addition for this purpose and only extends runtime.

2018-03-14 18:05 UTC, georgelorchpercona commented
As discussed on standup call, test is OK but one of the InnoDB specific additions is not necessary. I removed that but left the modified gap lock test in place as it does apply to TokuDB even though the gap lock behavior is slightly different. No new jenkins as this is just a removal of some test code and re-record. Verified it passes locally. Merging now as these changes are nneded/blocking the completion of 5.7/pre-8.0 work.

2018-03-14 18:05 UTC, merged