InnoDB: Transparent Data Encryption for Undo Tablespaces and Redo Log
percona/percona-server pull request #2241
Opened 2018-03-16 14:05 UTC by sysprg

Based on Oracle's WL#8548, WL#9289 and WL#9290, we provide
encryption support for redo log and undo tablespaces.

For encrypting redo/undo log, as same as we did in WL#8548,
we will en/decrypt the redo log blocks/undo log pages in the
I/O layer. Which means, the en/decryption only happens when
the redo/undo log read or write from/to disk.

For redo log, encryption metadata will be stored in the
header of first log file. Same as WL#8548, there're 2 key
levels here, master key and tablespace key. Master key is
stored in keyring plugin, and it's used to en/decrypt
tablespace key and iv. Tablespace key is for en/decrypt
redo log blocks, and it will be stored into the 3rd block
of first redo log file(ib_logfile0).

For undo log, Same as regular tablespace, the encryption
metadata will be stored in the first page of data file.

We also added 2 new global variables innodb_redo_log_encrypt=ON/OFF,
innodb_undo_log_encrypt=ON/OFF for en/disable redo/undo log encryption.

2018-03-22 14:26 UTC, laurynas-biveinis requested changes
- Please split commits to undo and redo encryption, PR them separately
- Please reference upstream commit hashes backported
- Has the upstream code and tests (which was originally introduces in 8.0.1) been changed in later 8.0 releases?
- Please outline the changes made in the backport from the original version
- How this was tested? The added testcases use "force-rmdir" MTR command, which is a 8.0 MTR command, and I don't see its backport
- Please see other comments inline. The ones marked with "TODO 8.0 backport" do not need immediate addressing, but rather for discussion with @percona-ysorokin, @robgolebiowski and others how we want to proceed with them

2018-03-22 14:26 UTC, laurynas-biveinis commented on include/my_compiler.h
> +#include "my_config.h"
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/include/restart_mysqld.inc
> -
Remove whitespace-only changes

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/include/restart_mysqld_no_echo.inc
> +
TODO 8.0 backport
Regular restart_mysqld.inc has restart_hide_args (sic?) parameter, please use that one instead

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/include/start_mysqld.inc
> -
Remove whitespace-only changes

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/include/start_mysqld_no_echo.inc
> +if (!$restart_parameters)
TODO 8.0 backport
Regular start_mysqld.inc has restart_hide_args (sic?) parameter, please use that one instead

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_2.test
> +--sleep 2
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_2.test
> +# Restart the server with keyring loaded
Use include file (in this instance it does not matter if it's a straightforward backport)

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_2.test
> +DROP TABLE IF EXISTS t1;
TODO 8.0 backport

Obsolete idiom

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_2.test
> +# Restart to confirm the encryption info can be retrieved properly.
Use include file (in this instance it does not matter if it's a straightforward backport)

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_2.test
> +--source include/kill_mysqld.inc
kill_and_restart_mysqld.inc

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_2.test
> +DROP DATABASE IF EXISTS tde_db;
TODO 8.0 backport

Obsolete idiom

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_3.test
> +--disable_warnings
TODO 8.0 backport

Obsolete idiom

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_3.test
> +--disable_warnings
TODO 8.0 backport

Obsolete idiom

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_3.test
> +--sleep 3
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_3.test
> +--let $_server_id= `SELECT @@server_id`
Please use include file

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_3.test
> +--sleep 3
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_3.test
> +--let $_server_id= `SELECT @@server_id`
Please use include file

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_4.test
> +--force-rmdir $MYSQL_TMP_DIR/log_encrypt_dir1
Is force-rmdir command supported in 5.7?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_5.test
> +--disable_warnings
TODO 8.0 backport
Obsolete idiom

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_5.test
> +# Enable following after bug fix
Ugh, is there anything know about what "bug fix"?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_6.test
> +--disable_warnings
TODO 8.0 backport

Obsolete idiom

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_6.test
> +--let $_server_id= `SELECT @@server_id`
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +
Add source include/not_embedded.inc

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +--disable_warnings
TODO 8.0 backport

Obsolete idiom

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +begin
TODO 8.0 backport

Inconsistent SQL keyword case

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +--sleep 3
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +--shutdown_server 0
Use include files

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +--sleep 20
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +--shutdown_server 0
Please use include file

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +--sleep 2
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/undo_encrypt_basic.test
> +--sleep 1
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/undo_encrypt_basic.test
> +--sleep 1
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/undo_encrypt_basic.test
> +--exec echo "restart:--early-plugin-load="keyring_file=$KEYRING_PLUGIN" --loose-keyring_file_data=$MYSQL_TMP_DIR/mysecret_keyring_log1 $KEYRING_PLUGIN_OPT --keyring_file_data=$MYSQL_TMP_DIR/my_key_un
Use include file

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/undo_encrypt_bootstrap.test
> +#--echo # Start the DB server with undo log encryption disabled, and no keyring plugin. It should fail.
TODO 8.0 backport

No commented out code please

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/undo_encrypt_bootstrap.test
> +#--replace_regex /\.dll/.so/
TODO 8.0 backport

No commented out code please

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/undo_encrypt_bootstrap.test
> +--sleep 2
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/undo_encrypt_bootstrap.test
> +--sleep 2
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on rapid/plugin/x/tests/mtr/t/log_encrypt_xplugin-master.opt
> +--plugin_dir=$MYSQLXPLUGIN_DIR
Should not be required because suite.opt with the same contents exists

2018-03-22 14:26 UTC, laurynas-biveinis commented on rapid/plugin/x/tests/mtr/t/log_encrypt_xplugin.test
> +--sleep 3
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on rapid/plugin/x/tests/mtr/t/log_encrypt_xplugin.test
> +#------------------------------------------------------------------------------
What is the purpose of this test? It does not appear to do anything X-specific

2018-03-22 14:26 UTC, laurynas-biveinis commented on sql/my_decimal.h
> -#if defined(MYSQL_SERVER) || defined(EMBEDDED_LIBRARY)
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/buf/buf0checksum.cc
> +
Please remove spurious whitespace changes

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/fil/fil0fil.cc
> +	if (fsp_is_system_or_temp_tablespace(space_id)) {
Is this actually compatible with the temp tablespace encryption we are developing?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/fil/fil0fil.cc
> -	ut_ad(algorithm != Encryption::NONE);
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/fil/fil0fil.cc
> +		if (fsp_is_system_or_temp_tablespace(space->id)
Is this actually compatible with the temp tablespace encryption we are developing?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/fsp/fsp0file.cc
> +			ib::info()
Looks like this logging is superfluous and spammy in case of large number of tablespaces?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/fsp/fsp0fsp.cc
> +	return srv_is_undo_tablespace(space_id);
Remove commented out code

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +	if (ret) {
Duplicates the existing code below

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +  "Enable or disable Encrypt of UNDO tablespace.",
"Enable or disable encryption of undo tablespace"

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +  "Enable or disable Encryption of REDO tablespace.",
"Enable or disable encryption of redo log"

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/api0api.h
> +#include "config.h"
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/btr0btr.h
> +#include "my_compiler.h"
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/btr0btr.h
> -#include "univ.i"
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/dict0dict.h
> +	static const ulint		s_space_id = 0xFFFFFFFE;
DD tablespace does not exist in 5.7. Might be a good idea to check against it in asserts, but the comment needs clarifying

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/dict0mem.h
> +#endif /* !UNIV_INNOCHECKSUM */
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/dict0mem.ic
> -#include "dict0mem.h"
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/fsp0file.h
> +typedef enum device_t {
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/fsp0fsp.h
> +	const page_size_t&	page_size);
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/fsp0fsp.h
> +fsp_header_write_encryption(
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/fsp0fsp.h
> +fsp_is_undo_tablespace(space_id_t space_id);
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/fsp0fsp.h
> +fsp_is_system_or_temp_tablespace(space_id_t space_id)
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/log0log.h
> +bool
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/log0log.h
> +log_write_encryption(
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/log0log.h
> +bool
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/log0log.h
> +UNIV_INLINE
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/log0log.h
> +	ibool	val);
s/ibool/bool

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/os0file.h
> +	static bool fill_encryption_info(byte*	key,
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/os0file.h
> +	static bool decode_encryption_info(byte*	key,
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/os0file.h
> +	bool encrypt_log_block(
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/os0file.h
> +	byte* encrypt_log(
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/os0file.h
> +	dberr_t decrypt_log_block(
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/os0file.h
> +	dberr_t decrypt_log(
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/sync0rw.h
> +#include "my_compiler.h"
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	inline bool is_reserved(space_id_t space_id)
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	inline space_id_t num2id(space_id_t space_num)
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	inline space_id_t id2num(space_id_t space_id)
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		char* make_space_name(space_id_t space_id);
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		char* make_file_name(space_id_t space_id);
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		char* make_log_file_name(space_id_t space_id);
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		space_id_t id()
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		space_id_t num()
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		TrxUndoRsegs* rsegs()
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +			// for (Tablespace* undo_space : m_spaces) {
No commented out code

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		ulint size() {
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		bool empty() {
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		Tablespace* at(size_t pos) {
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		bool contains(space_id_t id) {
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +			/* The sort method above puts this vector in order by
There is no sort method above?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +			//for (Tablespace* undo_space : m_spaces) {
Remove commented out code

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +			for (Tablespaces_Vector::iterator undo_space_ptr =
const_iterator

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/log0log.ic
> +	if (LOG_BLOCK_ENCRYPT_BIT_MASK
if (x) return true; return false; -> return x;

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	dberr_t start_logging(space_id_t space_id);
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	bool is_active_truncate_log_present(space_id_t space_id);
"DDL LOG" is WL#9536, and nothing concerning it should be backported

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		space_id_t num()
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		ulint size() {
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		bool empty() {
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		bool contains(space_id_t id) {
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		Tablespace* find(space_id_t id) {
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +		Tablespace* find(space_id_t id) {
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	bool is_under_construction(space_id_t space_id);
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	bool is_under_construction(space_id_t space_id);
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	bool is_active(space_id_t space_id);
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	bool is_active(space_id_t space_id);
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	inline bool is_inactive(space_id_t space_id) {
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0purge.h
> +	inline bool is_inactive(space_id_t space_id) {
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0sys.h
> +	bool contains(space_id_t id) {
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0sys.h
> +	bool contains(space_id_t id) {
const method

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0sys.h
> +		if (size() == 0) {
Redundant check, std::find will handle it

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/trx0sys.h
> +	iterator find(space_id_t id) {
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/include/univ.i
>  #ifdef _WIN32
Why? (for all patches in this file)

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +#include <mysqld.h>
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +@param[in]	start_lsn	log file data starts at this lsn */
Formatting-only change

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +
Whitespace-only change

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +				ib::info() << "Read redo log encryption"
Message is missing verb

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +	if (srv_shutdown_state != SRV_SHUTDOWN_NONE) {
First thing in the function

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +			ib::error() << "Can't set redo log tablespace to be"
Please add a testcase that attempts to start the server in InnoDB read only mode with redo log encryption

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +Block*
Annotate with MY_NODISCARD, defined in my_compiler.h

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +			/* Skip encrypt log file header */
"Skip encrypting ... " or "Do not encrypt ... "

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +			/* Skip encrypt log file header */
"Skip encrypting ... " or "Do not encrypt ... "

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +
Why? (this whole chunk)

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +		ib::error() << "Encryption can't find master key"
These three chunks: formatting-only change

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +		if (!recv_recovery_is_on()) {
if (!x) return false; else return true; -> return x;

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +				ib::error()
This is behavior change for all the existing encryption support, I think it's a good one, but we are past GA, @robgolebiowski , @percona-ysorokin , are we OK with this?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +	ut_print_buf(stderr, m_key, 32);
Formatting

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0srv.cc
> +#include <mysqld.h>
Why?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0srv.cc
> -
Whitespace-only change

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0srv.cc
> +			ib::error() << cant_set_undo_tablespace << "s"
I know this is a backport, and we are probably going to leave it as-is, but here we have the worst i18n ever.

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0srv.cc
> +	const char*	cant_set_undo_tablespace = "Can't set undo tablespace";
This crosses the line for me of what's acceptable to backport without fixing. It should be static at least

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0srv.cc
> +				<< ", since innodb_undo_tablespaces=0.";
Can you please show where this is tested? In MTR I see that this error is being suppressed in one of the testcases, but I was unable to find an attempt to execute this path.

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0srv.cc
> +			srv_undo_log_encrypt = false;
Please add a testcase

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0srv.cc
> +		for (undo::Tablespaces_Vector::iterator undo_space_ptr =
const_iterator

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0srv.cc
> +	for (undo::Tablespaces_Vector::iterator undo_space_ptr =
const_iterator

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0start.cc
> +	if (Encryption::check_keyring() == false) {
if (x == false) -> if (!x)

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0start.cc
> +#if 0
No commented out code

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0start.cc
> +		(void) success;
?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0start.cc
> +		    if (!log_read_encryption()) {
Add a testcase for innodb_force_recovery >= SRV_FORCE_NO_LOG_REDO

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/trx/trx0purge.cc
> +		/* 8.0 undo tablespace names have an extra '_' */
We should not be concerned with 8.0 names here

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/trx/trx0purge.cc
> +		/* 8.0 undo tablespace names have an extra '_' */
We should not be concerned with 8.0 names here

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/trx/trx0purge.cc
> +	/** Populate log file name based on space_id
Clarify which log

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/trx/trx0purge.cc
> +	/** Create the truncate log file.
What is the "truncate log" here?

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/trx/trx0purge.cc
> +		for (Space_Ids::iterator it = s_under_construction.begin();
const_iterator

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/trx/trx0purge.cc
> +		//return(undo_space->rsegs()->is_active());
Remote commented out code

2018-03-22 14:26 UTC, laurynas-biveinis commented on storage/innobase/os/os0file.cc
> +	bool	encrypted = encrypted_log != buf;
I can't fully follow how an error from encrypt_log above would be handled here and in callers

2018-03-22 14:30 UTC, laurynas-biveinis requested changes
- Please split commits to undo and redo encryption, PR them separately
- Please reference upstream commit hashes backported
- Has the upstream code and tests (which was originally introduces in 8.0.1) been changed in later 8.0 releases?
- Please outline the changes made in the backport from the original version
- How this was tested? The added testcases use "force-rmdir" MTR command, which is a 8.0 MTR command, and I don't see its backport
- Please see other comments inline. The ones marked with "TODO 8.0 backport" do not need immediate addressing, but rather for discussion with @percona-ysorokin, @robgolebiowski and others how we want to proceed with them

2018-03-26 08:51 UTC, robgolebiowski commented on storage/innobase/srv/srv0srv.cc
> +				space->flags | FSP_FLAGS_MASK_ENCRYPTION;
I see you are setting FSP_FLAGS_MASK_ENCRYPTION here, but you are not saving it in undo tablespace header (you would need to update data dictionary for that too)  - which makes this flag temporary. What happens when we restart or crash - how the server will know that this tablespace is encrypted ?

2018-03-26 12:09 UTC, robgolebiowski requested changes
The encryption information is read very early - different than what is MariaDB doing and could be that moving it to be read later can make the diff smaller. I will investigate can coordinate via Slack.

2018-03-26 12:09 UTC, robgolebiowski commented on storage/innobase/srv/srv0srv.cc
> +				space->flags | FSP_FLAGS_MASK_ENCRYPTION;
I do not think we can relay on MAGIC - as this can be correct by accident.

2018-03-26 12:29 UTC, robgolebiowski commented
MariaDB reads encryption information in file_node_open_file for undo. We can do the same - add verification if the key was read there. This should make the diff smaller as the code for reading encryption info will not need to be duplicated.

2018-04-30 11:17 UTC, laurynas-biveinis commented
Is this ready for the next review?

2018-06-29 06:27 UTC, closed without merging