PS-3901: Fix -DWITHOUT_xxx_STORAGE_ENGINE=ON for some plugins
percona/percona-server pull request #2250
Opened 2018-03-20 12:50 UTC by inikep

2018-03-20 12:51 UTC, inikep commented
https://jenkins.percona.com/job/percona-server-5.5-param/

2018-03-21 08:24 UTC, laurynas-biveinis requested changes
The commit message should describe the issues being fixed and the fix

2018-03-21 10:11 UTC, inikep commented
The commit message is updated.

2018-03-22 14:55 UTC, laurynas-biveinis approved these changes

2018-03-22 16:32 UTC, merged