PS-3887: TokuDB does not compile with -DWITH_PERFSCHEMA_STORAGE_ENGINE=OFF
percona/percona-server pull request #2253
Opened 2018-03-21 14:53 UTC by inikep

Add `-DWITHOUT_PERFSCHEMA_STORAGE_ENGINE=ON` to inverted config in Travis config file

Fix TokuDB usage of the following functions to match `psi/mysql_thread.h` definitions:
1. inline_mysql_mutex_lock to `if defined(SAFE_MUTEX) || defined (HAVE_PSI_MUTEX_INTERFACE)`
2. inline_mysql_mutex_unlock to `#ifdef SAFE_MUTEX`

2018-03-21 16:02 UTC, inikep commented
https://jenkins.percona.com/job/percona-server-5.6-param/2129/

2018-03-22 16:55 UTC, inikep commented
https://jenkins.percona.com/job/percona-server-5.6-param/2131/

2018-03-26 10:44 UTC, percona-ysorokin requested changes

2018-03-26 10:44 UTC, percona-ysorokin commented on storage/innobase/log/log0online.cc
> +		ut_snprintf(bitmap_file->name, sizeof(bitmap_file->name), "%s%c%s",
This is a legitimate fix, but it should be applied to 5.5 branch as well. So, please file a new bug and fix this part in all 3 branches.

2018-03-27 11:43 UTC, percona-ysorokin approved these changes
LGTM

2018-03-27 15:45 UTC, george-lorch approved these changes
OK as is or you can touch up the mentioned #if defined if you wish and merge without further review.

2018-03-27 15:45 UTC, georgelorchpercona commented on storage/tokudb/tokudb_thread.h
> +#ifdef SAFE_MUTEX
Why not #if defined(SAFE_MUTEX) like others instead of #ifdef ?

2018-03-28 11:37 UTC, merged

2020-01-29 13:25 UTC, peterschwaller commented
touch