PS-3773 : LP #1744430: "Incorrect key file for table" frequently for …
percona/percona-server pull request #2273
Opened 2018-03-28 18:06 UTC by georgelorchpercona

…tokudb

- Added new logging when an index inconsistency is discovered between any SK
  and the PK, specifically when a key in an SK can not find the corresponding
  record in the PK.
- Added DBUG_EXECUTE_IF point to fake return a HA_ERR_CRASHED/ER_NOT_KEYFILE from
  various index lookup calls and implemented basic test to ensure new logging
  actualy occurs.

2018-03-28 18:07 UTC, georgelorchpercona commented
Jenkins https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2134/
Two test failures were due to me not placing the most obvious have_tokudb.inc in the test which I later added and pushed.

2018-03-29 08:34 UTC, laurynas-biveinis requested changes

2018-03-29 08:34 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb.bugs/t/PS-3773.test
> +--remove_file $SEARCH_FILE
Better to avoid removing in-use file - remove after restart instead

2018-03-29 18:13 UTC, george-lorch commented
Done...

2018-03-30 06:26 UTC, laurynas-biveinis approved these changes

2018-04-03 14:56 UTC, merged