PS-235: query_response_time_session_stats variable
percona/percona-server pull request #2286
Opened 2018-04-03 09:32 UTC by dutow

2018-04-03 13:40 UTC, laurynas-biveinis approved these changes

2018-04-03 15:13 UTC, percona-ysorokin requested changes
Requested changes in MTR test case only.
Jenkins re-run with single test case is OK.

2018-04-03 15:13 UTC, percona-ysorokin commented on plugin/query_response_time/tests/mtr/session_toggle.test
> +SELECT SUM(COUNT) FROM INFORMATION_SCHEMA.QUERY_RESPONSE_TIME;
Here and everywhere, please replace direct `SELECT SUM(COUNT) FROM INFORMATION_SCHEMA.QUERY_RESPONSE_TIME` with
```
--let $assert_text= ...
--let $assert_cond="[SELECT SUM(COUNT) FROM INFORMATION_SCHEMA.QUERY_RESPONSE_TIME]" = XXX
--source include/assert.inc
```
specifying expected value XXX explicitly.

2018-04-04 06:18 UTC, dutow commented on plugin/query_response_time/tests/mtr/session_toggle.test
> +SELECT SUM(COUNT) FROM INFORMATION_SCHEMA.QUERY_RESPONSE_TIME;
I tried this, but looks like that the assert include itself executes a large, variable number of queries. With that, instead of simple comments and easy to follow numbers we'll get rapidly increasing counts, which are quite impossible to follow.

In the current version, I can see why the numbers start as 0/2/3. With the asserts, it would be 0/8/36, based on the  implementation of the include files, which could possibly change with unrelated commits.

2018-04-04 11:56 UTC, percona-ysorokin commented on plugin/query_response_time/tests/mtr/session_toggle.test
> +SELECT SUM(COUNT) FROM INFORMATION_SCHEMA.QUERY_RESPONSE_TIME;
Oh, did not think about that. Changing to approved.

2018-04-04 11:56 UTC, percona-ysorokin approved these changes
LGTM

2018-04-04 18:43 UTC, dutow commented
Jenkins: https://jenkins.percona.com/job/percona-server-5.6-param/2141/

2018-04-04 18:44 UTC, merged