PS-235: query_response_time_session_stats variable (5.7)
percona/percona-server pull request #2287
Opened 2018-04-03 13:38 UTC by dutow

2018-04-03 13:42 UTC, laurynas-biveinis approved these changes

2018-04-03 15:14 UTC, percona-ysorokin requested changes
The same comments as in 5.6

2018-04-04 11:57 UTC, percona-ysorokin approved these changes
LGTM

2018-04-04 18:42 UTC, dutow commented
Jenkins: https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1759/

2018-04-04 18:44 UTC, merged