TDB-191 : Implement better compression algo testing
percona/percona-server pull request #2322
Opened 2018-04-17 01:48 UTC by georgelorchpercona

- Implement new test that performs about as full of an end-to-end validation
  that the requested compression algo at the SQL layer is actually applied to
  the FT data files. The only practical way to check this is to use tokuftdump
  and look at the data files header value for compression_method.

2018-04-17 01:48 UTC, georgelorchpercona commented
https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2158/

2018-04-17 08:22 UTC, laurynas-biveinis requested changes

2018-04-17 08:22 UTC, laurynas-biveinis commented on mysql-test/mysql-test-run.pl
> +  # ----------------------------------------------------
I vaguely recall but am unable to confirm in the source code that it's possible to have MTR suite-specific Perl files for setup (suite.pm (?) but grep finds nothing). Would that be a better place for this?

2018-04-17 08:22 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb/t/compressions.test
> +--let $datadir = query_get_value(SELECT @@global.datadir AS datadir, datadir, 1)
```--let $datadir = `SELECT @@datadir` ```
likewise for TOKUDB_FILE_MAP queries

2018-04-17 14:44 UTC, georgelorchpercona commented on mysql-test/mysql-test-run.pl
> +  # ----------------------------------------------------
Possibly, but we kind of already set this precedent by also taking in sst_dump for my rocks. It is worth a try though to see if it works, and if so, remove the sst_dump as well from the primary runner.

2018-04-17 14:48 UTC, georgelorchpercona commented on mysql-test/suite/tokudb/t/compressions.test
> +--let $datadir = query_get_value(SELECT @@global.datadir AS datadir, datadir, 1)
Likewise what? I do not understand how this has anything to do with test setups. This seems to me to be a pretty normal and straightforward way to compile a path to a specific data file and is based on copying ideas from some tests from other suites.

2018-04-17 14:51 UTC, laurynas-biveinis commented on mysql-test/suite/tokudb/t/compressions.test
> +--let $datadir = query_get_value(SELECT @@global.datadir AS datadir, datadir, 1)
I am only suggesting to use backticks instead of query_get_value with three args for the same

2018-04-17 14:55 UTC, laurynas-biveinis commented on mysql-test/mysql-test-run.pl
> +  # ----------------------------------------------------
Yeah, this could have been done for Rocks too

2018-04-17 15:25 UTC, georgelorchpercona commented on mysql-test/suite/tokudb/t/compressions.test
> +--let $datadir = query_get_value(SELECT @@global.datadir AS datadir, datadir, 1)
Ahh, OK, formatting in browser was weird so the example was not clear/visible, I see the comment in the diff, I get it now...

2018-04-17 15:58 UTC, georgelorchpercona commented on mysql-test/mysql-test-run.pl
> +  # ----------------------------------------------------
So I blindly tried a few combinations of suite .pm .pl, etc to no avail. I then rooted through the mysql-test0run.pl and lib/my_*.pm and found no evidence of any kind of suite specific perl setup modules. I am no perl expert by any stretch but from what I can tell, there is no such construct for this. It does seem like a nice idea. That said, I did find suite specific plugin.defs but IIRC we visited this once and there was something about these not being used/recognized during the initial bootstrap and test qualification and caused tests that required a plugin to run to be skipped.

2018-04-17 18:03 UTC, georgelorchpercona commented
Converted the query_get_value to `blah`
Jenkins re-spin https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2159/

2018-04-18 05:32 UTC, laurynas-biveinis approved these changes

2018-04-18 17:04 UTC, merged