Ps 5.7 tdb 191
percona/percona-server pull request #2323
Opened 2018-04-17 01:49 UTC by georgelorchpercona

2018-04-17 01:49 UTC, georgelorchpercona commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1777/

2018-04-17 08:23 UTC, laurynas-biveinis requested changes
Same comments as for 5.6

2018-04-17 18:03 UTC, georgelorchpercona commented
jenkins re-spin https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1778/

2018-04-18 05:32 UTC, laurynas-biveinis approved these changes

2018-04-18 17:05 UTC, merged