PS-3950: gcc-8 compilation warnings
percona/percona-server pull request #2325
Opened 2018-04-17 09:09 UTC by inikep

1. Add gcc-8 to Travis config file
2. Fix the following gcc-8 warnings:
- cast between incompatible function types [-Werror=cast-function-type]
- clearing an object with no trivial copy-assignment [-Werror=class-memaccess]
- directive output may be truncated [-Werror=format-truncation=]

(the commit will be cherry-picked forward to 5.7)

2018-04-17 11:50 UTC, percona-ysorokin requested changes

2018-04-17 11:50 UTC, percona-ysorokin commented on sql/sql_optimizer.cc
> +                   reinterpret_cast<uchar*>(&idx));
Why?

2018-04-17 11:50 UTC, percona-ysorokin commented on sql/field.h
> +  void reset_fields() { memset(static_cast<void*>(&value), 0, sizeof(value)); }
more than 78 chars

2018-04-17 11:50 UTC, percona-ysorokin commented on sql/partition_info.cc
> +      memcpy(static_cast<void*>(subpart_clone), subpart, sizeof(partition_element));
more than 78 chars

2018-04-17 11:50 UTC, percona-ysorokin commented on sql/sql_planner.cc
> +MY_DISABLE_WARN_MAYBE_UNINITIALIZED
Shouldn't this be put inside Loose_scan_opt's constructor?

2018-04-17 11:50 UTC, percona-ysorokin commented on storage/innobase/fts/fts0pars.cc
> +		fts0b_scan_bytes((char*) query, query_len, fts_lexer->yyscanner);
c-style cast, removed const

2018-04-17 11:50 UTC, percona-ysorokin commented on storage/innobase/fts/fts0pars.cc
> +		fts0t_scan_bytes((char*) query, query_len, fts_lexer->yyscanner);
Likewise

2018-04-17 13:25 UTC, inikep commented on sql/sql_optimizer.cc
> +                   reinterpret_cast<uchar*>(&idx));
```
error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
```

2018-04-17 14:07 UTC, percona-ysorokin approved these changes
LGTM

2018-04-18 05:46 UTC, laurynas-biveinis reviewed
What was the answer to Yura's question on sql_planner.cc?

2018-04-18 10:19 UTC, inikep commented on sql/sql_planner.cc
> +MY_DISABLE_WARN_MAYBE_UNINITIALIZED
The following code does not fix the warning:
```
MY_DISABLE_WARN_MAYBE_UNINITIALIZED
Loose_scan_opt() :
    try_loosescan(FALSE),
    quick_uses_applicable_index(FALSE)
  {
     ...
  }
MY_RESTORE_WARN_MAYBE_UNINITIALIZED
```

2018-04-18 10:35 UTC, laurynas-biveinis approved these changes

2018-04-20 09:57 UTC, merged