PS-3325: Prevent changes with gtid_deployment_step set
percona/percona-server pull request #2336
Opened 2018-04-19 20:53 UTC by dutow

Changes executed after gtid_deployment_step was set resulted in binlog damage, or assertions/crashes of the server.

This commit ensures that checks are based on the correct, lock protected variable, and also enforces super_read_only while gtid_deployment_step is set.

It incorporates PR#1554 by keyurdg, which implements the first part of the above changes.

2018-06-19 14:18 UTC, dutow commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1848/

2018-07-03 12:32 UTC, laurynas-biveinis requested changes
gtid_deployment_step variables now can be made static to sys_vars.cc?

2018-07-03 12:32 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps3325-slave.opt
> +--log_slave_updates
Nit: inconsistent with -master.opt

2018-07-03 12:32 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps3325.test
> +sync_slave_with_master;
--source include/sync_slave_sql_with_master.inc here and everywhere

2018-07-03 12:32 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps3325.test
> +set global super_read_only=1;
Inconsistent SQL case

2018-07-03 12:32 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps3325.test
> +--source include/log_cleanup.inc
Why?

2018-07-03 12:32 UTC, laurynas-biveinis commented on sql/sys_vars.cc
> +  if(opt_gtid_deployment_step)
Space after if

2018-07-09 08:43 UTC, dutow commented
Updated.
Jenkins: https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/6/

2018-07-11 10:18 UTC, laurynas-biveinis reviewed
What about making gtid_deployment_step variable static to sys_vars.cc?

2018-07-11 10:22 UTC, dutow commented
That's doable too, I kept it this way because now both variables are initialized in `sql/mysqld.cc` at the same location, and that seems logical. Making it static would mean that at least one of them should be initialized in a different file.

2018-07-11 10:24 UTC, laurynas-biveinis approved these changes
Please prepare a null-merge to 5.7 and push both

2018-07-11 11:08 UTC, merged