PS-3958: handle_fatal_signal (sig=11) in subselect_hash_sj_engine::cl…
percona/percona-server pull request #2347
Opened 2018-04-23 16:37 UTC by gl-sergei

…eanup

subselect_hash_sj_engine::cleanup crashed when temporary table was not
created.

Fix is to avoid crash.

Changes in MTR required to allow it to start server with "Encryption
can't find master key" error.

2018-04-23 16:37 UTC, gl-sergei commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1789/

2018-04-30 11:27 UTC, laurynas-biveinis requested changes
LGTM with fprintf removed, no need for another review.

2018-04-30 11:27 UTC, laurynas-biveinis commented on sql/item_subselect.cc
> +  fprintf(stderr, "tab = %p\n", tab);
Remove

2018-04-30 11:29 UTC, laurynas-biveinis commented on mysql-test/t/ps-3958.test
> +#
On a second thought, should this be added to the main --innodb-temp-tablespace-encrypt testcase?

2018-05-01 12:41 UTC, gl-sergei commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1798/

Test case merged into temp_table_encrypt.inc

2018-05-14 11:59 UTC, laurynas-biveinis approved these changes

2018-05-15 11:24 UTC, merged