PS-3967: Re-added the Twitter NUMA patch
percona/percona-server pull request #2350
Opened 2018-04-24 10:48 UTC by dutow

Compared to the NUMA implementation in MySQL, this version forces allocation using MAP_POPULATE.

(cherry picked from commit 1170aef6fa012e44398e8dfa3096b440a3a77fda)

2018-04-26 12:33 UTC, percona-ysorokin requested changes

2018-04-26 12:33 UTC, percona-ysorokin commented on storage/innobase/buf/buf0buf.cc
> +	ibool		populate)	/*!< in: virtual page preallocation */
The same `ibool`->`bool` comments as in 5.6

2018-04-26 12:33 UTC, percona-ysorokin commented on storage/innobase/os/os0proc.cc
> +	__attribute__((unused)))
MY_ATTRIBUTE((unused))

2018-04-26 12:33 UTC, percona-ysorokin commented on storage/innobase/os/os0proc.cc
> +		fprintf(stderr, "InnoDB: Warning: mmap(MAP_POPULATE) "
new Logging mechanism in 5.7
`ib::fatal() << ` / `ib::error() << ` / `ib::warn() << `

2018-04-26 12:33 UTC, percona-ysorokin commented on storage/innobase/srv/srv0srv.cc
> +my_bool	srv_buf_pool_populate	= FALSE;
not needed any more

2018-04-26 12:33 UTC, percona-ysorokin commented on storage/innobase/include/ut0new.h
> +		bool           populate)
formatting

2018-04-26 14:01 UTC, percona-ysorokin requested changes

2018-04-26 14:01 UTC, percona-ysorokin commented on storage/innobase/buf/buf0buf.cc
> +				                    (bool) srv_numa_interleave)) {
static_cast<bool>(srv_numa_interleave)

2018-04-26 14:01 UTC, percona-ysorokin commented on storage/innobase/srv/srv0srv.cc
> +my_bool	srv_buf_pool_populate	= false;
Not removed

2018-04-26 16:04 UTC, percona-ysorokin approved these changes
LGTM

2018-04-26 20:58 UTC, percona-ysorokin commented
Jenkins build link for custom Percona Server 5.7.21-21 with NUMA patches
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1797/

2018-04-30 07:03 UTC, laurynas-biveinis requested changes
s/MAP_PREPOPULATE/MAP_POPULATE in the commit message

2018-05-14 08:18 UTC, laurynas-biveinis approved these changes

2018-05-15 14:32 UTC, dutow commented
Jenkins: https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1806/

2018-05-15 14:33 UTC, merged