Release notes for PS 5.5.60-38.12
percona/percona-server pull request #2383
Opened 2018-05-17 19:44 UTC by fiowro

2018-05-17 19:52 UTC, tduzan commented
These look okay to me.  @laurynas-biveinis probably should review before merge as well.

2018-05-18 06:53 UTC, laurynas-biveinis requested changes

2018-05-18 06:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.60-38.12.rst
> +  working with foreign keys on the same table, producing invalid SQL
foreign keys pointing to the same table

2018-05-18 06:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.60-38.12.rst
> +  Bug fixed :psbug:`3903`.
The bug description does not match PS-3903, either wrong description or the ref

2018-05-18 06:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.60-38.12.rst
> +* A code clean-up was done to fix compilation warnings and errors specific with
"with for"

2018-05-18 06:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.60-38.12.rst
> +* The possibility of a truncated bitmap file name was fixed in |InnoDB| logging
Other bugs

2018-05-18 06:53 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.60-38.12.rst
> +Other bugs fixed: :psbug:`3767`, :psbug:`3778`, :psbug:`3794`, and
For other bugs, please copy-paste their titles next to them as requested by @svetasmirnova

2018-05-18 06:53 UTC, laurynas-biveinis commented on doc/source/upstream-bug-fixes.rst
>  |:Upstream bug: :mysqlbug:`83264` - uint3korr should stop reading four instead of three bytes on x86          |
The statuses of other bugs should be updated

2018-05-18 07:24 UTC, fiowro commented on doc/source/upstream-bug-fixes.rst
>  |:Upstream bug: :mysqlbug:`83264` - uint3korr should stop reading four instead of three bytes on x86          |
There is a ready fix for a separate DOC-734 ticket (changing launchpad links to jira ones), with updated upstream-bug-fixes.rst, and It would be convenient to bind status checks to it also.

2018-05-18 15:13 UTC, percona-ysorokin commented on doc/source/conf.py
> +release = '-5.5.60-38.12'
Should this start with the dash?

2018-05-18 15:13 UTC, percona-ysorokin commented on doc/source/release-notes/Percona-Server-5.5.60-38.12.rst
> +* Temporary file I/O was not instrumented for Performance Schema. Bug fixed
`Some IO_CACHE file operations were not instrumented for Performance Schema causing inaccurate statistics generated.`

2018-05-18 15:52 UTC, percona-ysorokin approved these changes

2018-05-18 17:25 UTC, merged

2018-05-21 06:15 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.5.60-38.12.rst
> +  working with foreign keys pointing on the same table, producing invalid SQL
s/on/to