Fix for DOC-734 changing launchpad links to JIRA, 5.6 version
percona/percona-server pull request #2385
Opened 2018-05-18 13:38 UTC by fiowro

2018-05-21 09:17 UTC, laurynas-biveinis requested changes
Same comments as for the 5.5 version, and the last check date is not updated at all

2018-05-25 08:51 UTC, laurynas-biveinis requested changes
Same trailing whitespace comments as for the 5.5 version

2018-05-25 08:58 UTC, fiowro commented
Highlighted trailing whitespaces are just visual representation of the github diff. Raw file format shows the whole table is filled with spaces

2018-05-25 09:06 UTC, laurynas-biveinis approved these changes

2018-05-25 16:14 UTC, merged