Fix for DOC-734 changing launchpad links to JIRA, 5.7 version
percona/percona-server pull request #2386
Opened 2018-05-18 13:38 UTC by fiowro

2018-05-21 09:18 UTC, laurynas-biveinis requested changes
Same comments as for the 5.6 version

2018-05-25 08:52 UTC, laurynas-biveinis requested changes
Same trailing whitespace comments as for 5.5 and 5.6

2018-05-25 09:00 UTC, fiowro commented
Same answer on highlighted trailing whitespaces (just a diff visual highlighting; the whole table is filled with spaces)

2018-05-25 09:08 UTC, laurynas-biveinis approved these changes

2018-05-25 19:13 UTC, merged