Null-merge branch 5.6 (commit f5c4f8d) into 5.7
percona/percona-server pull request #2407
Opened 2018-05-30 14:38 UTC by inikep

This is a null merge after merging upstream 5.6.40 and 5.7.22.

Port the following changes:
1. https://github.com/percona/percona-server/commit/8f1473543d5abdefcb76ef28afc39fe1892fb3b1
Remove "register" keywords from
- storage/innobase/fts/fts0blex.cc
- storage/innobase/fts/fts0tlex.cc
- storage/innobase/pars/lexyy.cc
- storage/innobase/page/page0page.cc
- storage/myisam/mi_close.c

2. https://github.com/percona/percona-server/commit/c47a6984c36e859939e0c17c36e706cf6343a6f7
- Add "break" to storage/innobase/row/row0sel.cc
- Add brackets to libmysqld/lib_sql.cc
- Change "uint" to "ulong" in sql/log_event.cc
- Change "sprintf" to "snprintf" in sql/sp_head.cc

2018-05-30 14:41 UTC, laurynas-biveinis requested changes
It is slightly suspicious that the warning fixes, which motivated the changes being ported, need re-doing in 5.7?

2018-05-30 14:41 UTC, laurynas-biveinis commented on sql/sp_head.cc
> +      const char format[]= "Instruction at position %u has m_ip=%u";
If this is touched, might as well be made static

2018-05-30 15:44 UTC, inikep commented
5.5 and 5.6 had a valid warning because it was defined: 
```
const char *format = ...
char tmp[sizeof(format) + 2 * sizeof(uint) + 1];
```

5.7 had no warning because of:
```
const char *format = ...
char tmp[64 + 2 * MY_INT32_NUM_DECIMAL_DIGITS];
```

2018-05-30 16:17 UTC, laurynas-biveinis commented
So then it should be a null merge - cleanup patches without a clear objective (e.g. a warning fix) is not something we should maintain

2018-05-31 13:32 UTC, inikep commented
Changes within `sp_head.cc` were removed.

2018-05-31 13:34 UTC, laurynas-biveinis commented
The question still stands for the remaining changes

2018-05-31 13:48 UTC, dutow commented
As I see, the warning fixes are mostly about the register keyword.

* In 5.6, I included the commit which removed them (180b7e4). That commit is also part of the current 5.7 branch.
* However, in 5.7 commits after 180b7e4 again added the register keyword to some locations - so its not a merge issue, they are simply newer than the commit which removes them.

This shouldn't result in any warnings/errors in 5.7 (that's why I didn't notice them when I fixed the 5.7 warnings), as we always build 5.7 in C++03/11 mode (compared to 5.5/5.6, where we use the default language level of the compiler) to avoid some other deprecation warnings in the standard library.

2018-05-31 14:35 UTC, inikep commented
After removing changes without any visible payoff the null-merge is empty.

2018-05-31 15:07 UTC, percona-ysorokin approved these changes
LGTM

2018-06-01 09:11 UTC, merged