PS-3840: With FIPS enabled and performance_schema=off, instance crash…
percona/percona-server pull request #2418
Opened 2018-06-11 13:08 UTC by satya-bodapati

…es on CREATE VIEW

Description:
-----------
MySQL binaried compiled with OpenSSL (not YaSSL) and running the
binaries under FIPS enabled environment, crashes the server.

This is because MD5 algorithm is not FIPS compliant.

Fix:
----
1. Disable FIPS mode for MySQL which allows mysqld to be run under
   FIPS environment.
2. Create binary to detect FIPS enabled environment
3. changes to MTR framework to detect FIPS

2018-06-12 06:25 UTC, laurynas-biveinis requested changes

2018-06-12 06:25 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +    sql_print_warning("MySQL cannot operate under OpenSSL FIPS mode."
While the statement is true for MySQL too in general, the product here is Percona Server

2018-06-12 06:25 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +  unsigned int fips_mode = FIPS_mode();
OpenSSL docs suggest plain "int" as FIPS_mode return type

2018-06-12 06:25 UTC, laurynas-biveinis commented on extra/fipstest.cc
> +  /* Other SSLs, we dont care */
don't

2018-06-12 06:25 UTC, laurynas-biveinis commented on mysql-test/include/have_fips.inc
> +--let FILE= $MYSQLTEST_VARDIR/tmp/fips.out
While the utility app works everywhere, I wonder if a shell-based test would be enough for all of our practical testing use cases - i.e. on CentOS, `cat /proc/sys/crypto/fips_enabled`. We probably won't be testing FIPS on Debian/Ubuntu anyway for time being

2018-06-12 06:25 UTC, laurynas-biveinis commented on mysql-test/t/fips.test
> +let SEARCH_FILE= $MYSQLTEST_VARDIR/log/mysqld.1.err;
grep mysqld.1.err is an antipattern. It breaks --repeat (the 2nd invocation will just hit the 1st one's output), it will break if any of the previous tests on the same worker got the same warning. Deleting the log file to fix the above is not good neither. The best solution I know so far is to restart the server with custom error log path, grep, restart with default, delete the custom error log.

2018-06-12 06:25 UTC, laurynas-biveinis commented on extra/fipstest.cc
> +    fprintf(stdout, "FIPS enabled\n");
Just printf I guess

2018-06-12 06:25 UTC, laurynas-biveinis commented on extra/fipstest.cc
> +#include <stdio.h>
(see the have_fips.inc review comments first)

2018-06-12 06:25 UTC, laurynas-biveinis commented on extra/fipstest.cc
> +  fprintf(stdout, "FIPS not enabled\n");
printf

2018-06-12 12:38 UTC, satya-bodapati commented on sql/mysqld.cc
> +    sql_print_warning("MySQL cannot operate under OpenSSL FIPS mode."
Done! changed to Percona Server

2018-06-12 12:38 UTC, satya-bodapati commented on extra/fipstest.cc
> +  /* Other SSLs, we dont care */
removed this file

2018-06-12 12:39 UTC, satya-bodapati commented on mysql-test/include/have_fips.inc
> +--let FILE= $MYSQLTEST_VARDIR/tmp/fips.out
Ok, my approach was more generic. I have implemented the suggestion. The change looks smaller now :)

2018-06-12 12:40 UTC, satya-bodapati commented on mysql-test/t/fips.test
> +let SEARCH_FILE= $MYSQLTEST_VARDIR/log/mysqld.1.err;
Fixed. the test is now named as percona_fips.test

2018-06-12 13:03 UTC, laurynas-biveinis requested changes
The diff itself looks good, other comments:
- please squash commits
- please provide Jenkins run link (in fact I prefer requesting PRs for my work when Jenkins completes and I review it, others have other styles)

2018-06-13 12:42 UTC, satya-bodapati commented
Jenkins: https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1842/

2018-06-13 13:00 UTC, laurynas-biveinis commented
Jenkins checks out OK. Before merging:
- please squash your commits
- please do not merge from trunk

2018-06-13 14:34 UTC, merged