Ps 5.7 4196
percona/percona-server pull request #2434
Opened 2018-06-25 23:29 UTC by georgelorchpercona

Prepare MyRocks for 8.0

2018-06-25 23:29 UTC, georgelorchpercona commented
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1860/

2018-06-26 05:02 UTC, laurynas-biveinis requested changes
The majority of comments ask to convert auto iterator ... to const auto & iterator ... - to avoid copying the iterator

2018-06-26 05:02 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +  auto it = m_hash.find(s_table_name);
const auto & it

2018-06-26 05:02 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +    const size_t ret MY_ATTRIBUTE((__unused__)) =
No need to change from auto to size_t

2018-06-26 05:02 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +  for (auto it = m_hash.begin(); it != m_hash.end(); it++) {
const auto & it : m_hash

2018-06-26 05:02 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.cc
> +  auto it = m_ddl_hash.find(table_name);
const auto & it

2018-06-26 05:02 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.cc
> +  auto it = m_ddl_hash.find(dbname_tablename);
const auto & it

2018-06-26 05:02 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.cc
> +  auto it = m_ddl_hash.find(dbname_tablename);
const auto & it

2018-06-26 05:02 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.cc
> +  for (auto it = m_ddl_hash.cbegin(); it != m_ddl_hash.cend(); it++)
const auto & it, also consider switching to range-based loop const auto & it : m_ddl_hash

2018-06-26 05:02 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.cc
> +  for (auto it = m_ddl_hash.cbegin(); it != m_ddl_hash.cend(); it++) {
const auto & it, also consider switching to range-based loop

2018-06-26 18:07 UTC, georgelorchpercona commented
All good points and addressed, new jenkins here https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1861/

2018-06-27 04:50 UTC, laurynas-biveinis approved these changes

2018-06-27 18:48 UTC, georgelorchpercona commented
The previous Travis run identified a few minor formatting issues that I fixed, tested, pushed, jenkins https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1864/ but not all are corrected as I disagree with the suggested reformat. Merging now.

2018-06-27 18:48 UTC, merged