PS-4545: protobuf compilation issue with Travis CI
percona/percona-server pull request #2436
Opened 2018-06-26 13:28 UTC by inikep

Use an explicit version of the protobuf library.

2018-06-26 15:09 UTC, percona-ysorokin approved these changes
LGTM

2018-06-27 04:52 UTC, laurynas-biveinis requested changes
Please add a comment why - it's impossible to tell that e.g. for 8.0 we can switch to the latest version again just by looking at Travis config

2018-06-27 10:30 UTC, inikep commented
I added a comment.

2018-06-27 10:35 UTC, laurynas-biveinis approved these changes

2018-06-27 11:16 UTC, merged