PS-4524: innodb-optimize-keys fails when variable name is a prefix
percona/percona-server pull request #2440
Opened 2018-06-29 12:16 UTC by inikep

Fixed by checking lengths of compared strings (column names).

https://ps.cd.percona.com/view/5.5/job/percona-server-5.5-param/18/

2018-06-29 12:37 UTC, laurynas-biveinis requested changes

2018-06-29 12:37 UTC, laurynas-biveinis commented on mysql-test/t/percona_mysqldump_innodb_optimize_keys.test
> +--cat_file $file
I am not sure we need the dump itself in the output - I'd test after loading the dump SHOW CREATE TABLE instead

2018-06-29 12:37 UTC, laurynas-biveinis commented on client/mysqldump.c
> +                                       intptr_t autoinc_column_len,
size_t

2018-06-29 14:12 UTC, inikep commented
`ssize_t` used instead of `intptr_t`.

https://ps.cd.percona.com/view/5.5/job/percona-server-5.5-param/19/

2018-07-02 03:24 UTC, laurynas-biveinis approved these changes

2018-07-03 09:16 UTC, merged