DOC-572 fix with SSL improvements and compatibility matrix
percona/percona-server pull request #2472
Opened 2018-07-29 23:02 UTC by fiowro

2018-07-30 07:15 UTC, laurynas-biveinis requested changes

2018-07-30 07:15 UTC, laurynas-biveinis commented on doc/source/management/ssl_compatibility.rst
> +from the original MySQL commuinty edition.
commuinty

2018-07-30 07:15 UTC, laurynas-biveinis commented on doc/source/management/ssl_compatibility.rst
> +enable encrypted connections based on the OpenSSL API. All binary packages of
should be discussing network protocols, not APIs: encrypted connections based on Transport Layer Security / Secure Sockets Layer

2018-07-30 07:15 UTC, laurynas-biveinis commented on doc/source/management/ssl_compatibility.rst
> +Due to using OpenSSL version not older than 1.1, *Percona Server for MySQL*
Drop the "Due ... " clause

2018-07-30 07:15 UTC, laurynas-biveinis commented on doc/source/management/ssl_compatibility.rst
> +Due to using OpenSSL version not older than 1.1, *Percona Server for MySQL*
OpenSSL 1.1 support is an item by itself

2018-07-30 07:15 UTC, laurynas-biveinis commented on doc/source/management/ssl_compatibility.rst
> +Subject Alternative Names and binlog SSL options support
binlog SSL options support not in this section

2018-07-30 07:15 UTC, laurynas-biveinis commented on doc/source/management/ssl_compatibility.rst
> +SSL options. All encryption-aware client tools beside mysqlbinlog in MySQL are
What are they?

2018-08-01 13:30 UTC, fiowro commented
Fixed all current comments :)

2018-08-02 07:01 UTC, laurynas-biveinis requested changes
OpenSSL 1.1 support nowhere mentioned as a separate item

2018-08-02 07:01 UTC, laurynas-biveinis commented on doc/source/management/ssl_compatibility.rst
> +SSL options. Other encryption-aware client tools (``mysql``, ``mysqlcheck``,
No, the comment was not to list the other command line tools, but the added SSL options

2018-08-02 07:01 UTC, laurynas-biveinis commented on doc/source/management/ssl_compatibility.rst
> +in `<https://dev.mysql.com/doc/refman/5.6/en/openssl-versus-yassl.html>`_.
5.5 link please

2020-04-15 20:32 UTC, closed without merging

2020-04-15 20:33 UTC, patrickbirch commented
Closing old PR for 5.5.