PS-4729 : 8.0 eliminates TRUE and FALSE for bool values, only true an…
percona/percona-server pull request #2482
Opened 2018-08-10 19:12 UTC by georgelorchpercona

…d false are valid.

- s/TRUE/true   s/FALSE/false

2018-08-10 19:12 UTC, georgelorchpercona commented
https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2201/

2018-08-13 12:48 UTC, laurynas-biveinis requested changes

2018-08-13 12:48 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_hton.cc
> +    db_env_set_direct_io(tokudb::sysvars::directio == true);
cond == true -> cond, but see the comment below

2018-08-13 12:48 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_hton.cc
> +        tokudb::sysvars::compress_buffers_before_eviction == true);
cond == true -> cond, but see the comment below

2018-08-13 12:48 UTC, laurynas-biveinis commented on storage/tokudb/tokudb_sysvars.cc
> +my_bool     checkpoint_on_flush_logs = false;
false/true are not values of my_bool type, which is char in 5.6. IMHO FALSE/TRUE should be kept for my_bool

2018-08-13 18:33 UTC, georgelorchpercona commented
Made changes to revert the changes to my_bool types, but fixed/kept minor conditional changes. New jenkins https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2205/.

Since changes here are trivial and jenkins indicates no issue, merging ahead of further approval.

2018-08-13 18:33 UTC, merged