PS-4386 : Fix various places where macros are redefined or used when …
percona/percona-server pull request #2490
Opened 2018-08-14 15:23 UTC by georgelorchpercona

…undefined

- Fix various places where macros are redefined or used when undefined-

2018-08-14 15:24 UTC, george-lorch commented
https://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/2206/

2018-08-14 21:31 UTC, georgelorchpercona commented
new jenkins https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/10/

2018-08-16 14:49 UTC, laurynas-biveinis requested changes

2018-08-16 14:49 UTC, laurynas-biveinis commented on storage/tokudb/tokudb_sysvars.h
> +#if defined(TOKUDB_DEBUG) && TOKUDB_DEBUG
Now there are two forms of this check: above defined(FOO) and here defined(FOO) && FOO. Should be a single form (IMHO the former one) only

2018-08-16 20:20 UTC, george-lorch commented on storage/tokudb/tokudb_sysvars.h
> +#if defined(TOKUDB_DEBUG) && TOKUDB_DEBUG
Ahh, yeah, good point.

2018-08-16 23:01 UTC, georgelorchpercona commented
Fixed and new jenkins https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/12/

2018-08-17 11:39 UTC, laurynas-biveinis approved these changes

2018-08-17 16:04 UTC, merged