PS-4790: Improve user statistics accuracy (8.0)
percona/percona-server pull request #2522
Opened 2018-08-29 11:16 UTC by inikep

Measure times for `dispatch_command` instead of mysql_parse, mysqld_stmt_reset, mysqld_stmt_fetch, mysqld_stmt_prepare, mysqld_stmt_execute.

2018-08-30 08:43 UTC, laurynas-biveinis requested changes
Nice cleanup. Minor comments

2018-08-30 08:43 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +  double start_usecs = 0;
0.0

2018-08-30 08:43 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +  double end_usecs = 0;
0.0

2018-08-30 08:43 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +  double start_cpu_nsecs = 0;
0.0

2018-08-30 08:43 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +    if (!(start_time_error = gettimeofday(&start_time, NULL))) {
nullptr

2018-08-30 08:43 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +  if (unlikely(opt_userstat)) {
There is a race condition in that opt_userstat can change its value between the two sections. So in the second section I'd only check for start_* timestamp initialization

2018-08-30 08:43 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +    if (!(end_time_error = gettimeofday(&end_time, NULL))) {
nullptr

2018-08-30 08:43 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +      if (thd->busy_time > 2629743) {
unlikely

2018-08-30 08:43 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +      if (thd->cpu_time > 2629743) {
unlikely

2018-08-30 15:18 UTC, inikep commented
Added `userstat.cc` and `userstat.h` with the following functions:
```
void userstat_start_timer(double &start_busy_usecs, double &start_cpu_nsecs);
void userstat_finish_timer(double &start_busy_usecs, double &start_cpu_nsecs,
                           double &busy_sec, double &cpu_sec);
```

2018-08-30 16:33 UTC, inikep commented
use pointer for output arg:
```
void userstat_start_timer(double *start_busy_usecs, double *start_cpu_nsecs);
void userstat_finish_timer(double &start_busy_usecs, double &start_cpu_nsecs,
                           double *busy_sec, double *cpu_sec);
```

2018-08-31 07:17 UTC, laurynas-biveinis requested changes
Minor comments

2018-08-31 07:17 UTC, laurynas-biveinis commented on sql/sql_parse.cc
> +    update_global_user_stats(thd, true, time(NULL));
nullptr

2018-08-31 07:17 UTC, laurynas-biveinis commented on sql/userstat.cc
> +void userstat_finish_timer(double &start_busy_usecs, double &start_cpu_nsecs,
Pass by value start args

2018-08-31 07:17 UTC, laurynas-biveinis commented on sql/userstat.cc
> +  struct timeval start_time;
Declare at use

2018-08-31 07:17 UTC, laurynas-biveinis commented on sql/userstat.cc
> +  double end_cpu_nsecs = 0.0;
Declare at use

2018-08-31 07:17 UTC, laurynas-biveinis commented on sql/userstat.h
> +void userstat_start_timer(double *start_busy_usecs, double *start_cpu_nsecs);
both are noexcept

2018-08-31 08:27 UTC, laurynas-biveinis approved these changes

2018-08-31 08:28 UTC, merged