Release notes for 5.7.23-23 (57)
percona/percona-server pull request #2523
Opened 2018-08-29 12:37 UTC by borys-belinsky

2018-08-30 06:54 UTC, hrvojem requested changes

2018-08-30 06:54 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +
5.7.23-23

2018-08-30 08:08 UTC, laurynas-biveinis requested changes
Upstream bugs list needs updating too

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* In the InnoDB system tablespace all data are encrypted including the parallel
It is not clear whether system tablespace encryption is an existing feature we changed somehow or a new feature (it's the latter)
The parallel doublewrite buffer is not a part of the system tablespace. The legacy doublewrite buffer is.

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* Changing ``rocksdb_update_cf_options`` shows warnings and errors in the
What was the previous behavior? (cc @georgelorchpercona)
Add JIRA ref

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* The :variable:`max_binlog_files` variable is deprecated and replaced
Add JIRA link

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* In the InnoDB system tablespace all data are encrypted including the parallel
Add JIRA link

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* InnoDB statistics could incorrectly report zeros in the slow query log. Bug
InnoDB extensions for the slow query log, consider linking to the feature doc page

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* :psbug:`3702` "ALTER TABLE is slow in 5.7 when the number of dirty pages is high"
To main bugs fixed

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* :psbug:`4546` "Can\'t run mysql on Ubuntu systems with long recovery time"
To main bugs fixed

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* :psbug:`3988` "Unclear message in the LOG for fast CRC32"
To main bugs fixed

2018-08-30 08:08 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* :psbug:`3796` "Cannot configure flush_caches on PS 5.7 using systemd"
To main bugs fixed ?

2018-08-31 17:07 UTC, hrvojem requested changes

2018-08-31 17:07 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +  variables are ``OFF`` by default. For more information, see :psbug:`3822`.
This should be added to https://www.percona.com/doc/percona-server/5.7/management/data_at_rest_encryption.html where rest of the feature is described. This is also missing BETA/GA information.

2018-08-31 17:07 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +  semantics. For more information, see :psbug:`275`.
this info should be in the feature documentation as well, for users that get redirected to `max_binlog_files`

2018-08-31 17:07 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +  5.7.21-20. Bug fixed :psbug:`4479`.
s/5.7.21-20/:rn:`5.7.21-20` this will create the link to that PS version release notes.

2018-09-03 07:17 UTC, laurynas-biveinis requested changes
In addition to @hrvojem comments.
Upstream bug list needs updating too.

2018-09-03 07:17 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +  client. For more information, see :psbug:`4258`.
returns any warnings and errors to the client instead of printing them to the server error log

2018-09-05 15:05 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +  variables are ``OFF`` by default. For more information, see :psbug:`3822`.
This still doesn't mention the feature Beta/GA status

2018-09-05 16:16 UTC, hrvojem requested changes
Documentation/Descriptions for: PS-4764, PS-4774, PS-4776, PS-4777, PS-4778, PS-4779, and PS-4780 are still missing from the release notes.

2018-09-05 22:23 UTC, borys-belinsky commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +  variables are ``OFF`` by default. For more information, see :psbug:`3822`.
Is my understanding correct that informing that the feature is in beta would conflict with the proposed (and implemented) solution for https://jira.percona.com/browse/PS-4752?

2018-09-06 06:04 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +  variables are ``OFF`` by default. For more information, see :psbug:`3822`.
No, please check https://jira.percona.com/browse/PS-4754

2018-09-10 20:51 UTC, breisig commented
Any update?

2018-09-11 05:50 UTC, hrvojem requested changes

2018-09-11 05:50 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* When ``innodb_temp_tablespace_encrypt`` was set to ``ON`` the ``CREATE TABLE``
use :variable:`innodb_temp_tablespace_encrypt` so it's automatically linked to variable description.

2018-09-12 08:03 UTC, fiowro commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* When ``innodb_temp_tablespace_encrypt`` was set to ``ON`` the ``CREATE TABLE``
fixed

2018-09-12 11:28 UTC, hrvojem approved these changes
LGTM

2018-09-12 11:59 UTC, laurynas-biveinis requested changes

2018-09-12 11:59 UTC, laurynas-biveinis commented on doc/source/ext/psdom.py
> +        for refname, (docname, type) in self.data['objects'].items():
?

2018-09-12 11:59 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.22-22.rst
> +* :psbug:`4451` \"Implement better compression algo testing\"
Why escape the quotes? What's the difference in the output?

2018-09-12 11:59 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* Starting with |release|, all data are encrypted in the InnoDB system
maybe "it is possible to encrypt all data in..." as this an optional feature

2018-09-12 12:42 UTC, laurynas-biveinis approved these changes

2018-09-12 13:02 UTC, merged