PS-281: Convert LP 1354988 fix to new "SHOW EFFECTIVE GRANTS"
percona/percona-server pull request #2537
Opened 2018-09-04 13:56 UTC by inikep

2018-09-05 12:05 UTC, laurynas-biveinis requested changes

2018-09-05 12:05 UTC, laurynas-biveinis commented on sql/sql_yacc.yy
> +%token<keyword> EFFECTIVE_SYM
Add a header comment "Tokens from Percona Server 8.0" for this one

2018-09-05 12:05 UTC, laurynas-biveinis commented on sql/auth/sql_authorization.cc
> +        ((!effective_grants &&
The condition (!effective_grants && !my_strcasecmp()) || (effective_grants && compare_hostname()) is repeated several times - please extract (and remove one of the "effective_grants" in effective_grants || !effective_grants)

2018-09-06 09:12 UTC, laurynas-biveinis commented on sql/auth/sql_authorization.cc
> +static bool hosts_match_for_grants(ACL_HOST_AND_IP &acl_db_host,
Can this arg be const ref?

2018-09-06 09:23 UTC, laurynas-biveinis approved these changes

2018-09-06 09:29 UTC, inikep commented on sql/auth/sql_authorization.cc
> +static bool hosts_match_for_grants(ACL_HOST_AND_IP &acl_db_host,
no

2018-09-06 09:29 UTC, merged