Fix PS-4723 (PURGE CHANGED_PAGE_BITMAPS doesn't work when innodb_data_home_dir used)
percona/percona-server pull request #2538
Opened 2018-09-05 15:12 UTC by percona-ysorokin

https://jira.percona.com/browse/PS-4723

'PURGE CHANGED_PAGE_BITMAPS' InnoDB handler
('log_online_purge_changed_page_bitmaps()') used to call
'os_file_delete_if_exists()' for deleting old '.xdb' files using relative
paths. Therefore, when '--innodb-data-home-dir' was different from
'--datadir'(which is by default the current working directory), it tried to
delete these file from the wrong location.

Fixed by prepending '.xdb' file name with 'log_bmp_sys->bmp_file_home'.

Added 'innidb.percona_bug_ps4723' MTR test case which simulates the reported
scenario.

2018-09-06 08:15 UTC, laurynas-biveinis requested changes

2018-09-06 08:15 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_bug_ps4723.test
> +--echo #
There must be a matching main feature testcase to add to instead - please check

2018-09-06 08:15 UTC, laurynas-biveinis commented on storage/innobase/log/log0online.c
> +	char	full_bmp_file_name[2 * FN_REFLEN + 1];
Declare in the scope where it's used

2018-09-07 16:22 UTC, percona-ysorokin commented
Added support for the case when redo log tracking is disabled. Test scenario moved to 'innodb.percona_changed_page_bmp_requests' MTR test case.

Jenkins build link
https://ps.cd.percona.com/view/5.5/job/percona-server-5.5-param/27/

2018-09-10 08:43 UTC, laurynas-biveinis approved these changes

2018-09-10 08:43 UTC, laurynas-biveinis commented on storage/innobase/log/log0online.c
> +			size_t	srv_data_home_len = strlen(srv_data_home);
nit: const

2018-09-11 20:48 UTC, percona-ysorokin commented on storage/innobase/log/log0online.c
> +			size_t	srv_data_home_len = strlen(srv_data_home);
Fixed

2018-09-11 20:50 UTC, percona-ysorokin commented
Had to move test scenario to `innodb.percona_changed_page_bmp_requests_debug` to be able to use
`innodb_log_checkpoint_now` / `innodb_track_redo_log_now`.

Updated Jenkins build link
https://ps.cd.percona.com/view/5.5/job/percona-server-5.5-param/28/

2018-09-12 05:20 UTC, laurynas-biveinis approved these changes

2018-09-14 11:35 UTC, percona-ysorokin commented
Removed `--innodb-file-per-table=0` option along with assertion from the second (non-tracking) restart.
Jenkins build link
https://ps.cd.percona.com/view/5.5/job/percona-server-5.5-param/30/ (single test run `innodb.percona_changed_page_bmp_requests_debug --repeat=2`)

2018-09-14 12:19 UTC, laurynas-biveinis approved these changes

2018-09-14 13:32 UTC, merged