PS-269: Fix main.log_options_cmdline --sanitize
percona/percona-server pull request #2565
Opened 2018-09-24 16:09 UTC by inikep

For 64-bit server compilation with ASan we have `ASAN_OPTIONS=disable_coredump=1` as default.
It causes the following warning to be detected by main.log_options_cmdline:
`[Warning] [MY-010108] [Server] setrlimit could not change the size of core files to 'infinity';  We may not be able to generate a core file on signals`

We can fix it by:
1. Use `ASAN_OPTIONS=disable_coredump=0` to enable coredump
2. Disable the warning when `HAVE_ASAN` is defined

This patch implements option 2.

2018-09-24 16:14 UTC, laurynas-biveinis approved these changes
Please file upstream

2018-09-26 10:21 UTC, inikep commented
Pushed a completely rewritten solution that changes `log_error_verbosity` to `sys_var::PARSE_EARLY`.

2018-09-26 10:59 UTC, laurynas-biveinis approved these changes

2018-09-26 16:34 UTC, inikep commented
Fixed issue with printing warnings with `mysqld --help`.

2018-09-27 09:17 UTC, laurynas-biveinis requested changes

2018-09-27 09:17 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +   * option_error_reporter() */
nit: why 2nd line started with *

2018-09-27 09:17 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +  for (my_option *opt = my_long_early_options; opt->name != NULL; opt++) {
nullptr

2018-09-27 09:17 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +    if (!strcmp("help", opt->name) || !strcmp("initialize", opt->name) ||
Maybe add some static std::vector<string> foo = {"help", ... }; std::find(foo.cbegin(), foo.cend(), opt->name);

2018-09-27 09:17 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +  char **copy_argv = new char *[copy_argc + 1];
std::vector<char **>? handle_options should be able to take &copy_argv[0]

2018-09-27 16:09 UTC, inikep commented
The commit is updated to address the comments.

2018-09-28 06:03 UTC, laurynas-biveinis approved these changes

2018-09-28 08:15 UTC, merged