Fixed PS-1107 (LP #1703346: Binlog corruption when tmpdir gets full) (5.6)
percona/percona-server pull request #2569
Opened 2018-09-25 21:42 UTC by percona-ysorokin

https://jira.percona.com/browse/PS-1107

Cherry-picked from ps-5.5-bugps1107-tmpdir_full branch
(commit c39bd882e6a).

Changes in 'rpl.rpl_bug72457' MTR test case:
* '--source include/rpl_sync.inc' changed to
  '--source include/sync_slave_sql_with_master.inc'.
* 'simulate_disk_full_at_flush_pending' DEBUG directive changed to
  'simulate_tmpdir_partition_full'.
* Hardcoded error code 1590 changed to
  'convert_error(ER_SLAVE_INCIDENT)'.

2018-09-25 21:47 UTC, percona-ysorokin commented
Not following GCA here as proper 'out of disk space' simulation requires 'simulate_disk_full_at_flush_pending' DBUG directive from
```
Bug #27399620: BINLOG AND ENGINE BECOME INCONSISTENT WHEN BINLOG CACHE FILE GETS OUT OF SPACE
```
(commit a50fcc1)
which is available in MySQL 5.6.41 only.

Jenkins build link
https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/26/

2018-09-26 07:09 UTC, laurynas-biveinis requested changes
Same comments as for the 5.5 version

2018-09-26 19:58 UTC, percona-ysorokin commented
Updated Jenkins build link
https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/27/

2018-09-27 06:40 UTC, laurynas-biveinis approved these changes

2018-09-27 12:28 UTC, merged