Fixed PS-1107 (LP #1703346: Binlog corruption when tmpdir gets full) (5.7)
percona/percona-server pull request #2570
Opened 2018-09-25 21:42 UTC by percona-ysorokin

https://jira.percona.com/browse/PS-1107

Cherry-picked from ps-5.6-bugps1107-tmpdir_full branch
(commit c7b6226).

Fixed problem with wrapping 'reinit_io_cache()' inside
'MYSQL_BIN_LOG::do_write_cache()' with 'simulate_file_write_error' DBUG
directive. 'DBUG_SET("-d,simulate_file_write_error")' should be called
not only when 'reinit_io_cache()' fails but when it succeeds as welll.
Whithout this patch, any subsequent call to 'my_write()' ends up with
an infinite loop.

Reorganized 'rpl.rpl_bug72457' MTR test case. Instead, we now have two
'rpl.rpl_bug72457_myisam' and 'rpl.rpl_bug72457_innodb' which test the
same (original) scenario with different values of
'--internal-tmp-disk-storage-engine' and '--default-tmp-storage-engine'
variables set to 'MyISAM' and 'InnoDB' correspondingly.

2018-09-25 21:52 UTC, percona-ysorokin commented
Not following GCA here as proper 'out of disk space' simulation requires 'simulate_disk_full_at_flush_pending' DBUG directive from

Bug #27399620: BINLOG AND ENGINE BECOME INCONSISTENT WHEN BINLOG CACHE FILE GETS OUT OF SPACE
(commit 9395f0a)
which is available in MySQL 5.7.23 only.

Jenkins build link
https://ps.cd.percona.com/job/percona-server-5.7-param/72/

2018-09-26 07:12 UTC, laurynas-biveinis requested changes
Same comments as for the 5.5 and 5.6
Please also prepare an 8.0 version if needed
Please also upstream

2018-09-26 19:58 UTC, percona-ysorokin commented
Updated Jenkins build link
https://ps.cd.percona.com/job/percona-server-5.7-param/73/

2018-09-27 06:41 UTC, laurynas-biveinis approved these changes

2018-09-27 12:28 UTC, merged