PS-269: Fix x.connection_tls_version
percona/percona-server pull request #2577
Opened 2018-09-28 12:40 UTC by inikep

Fix regexps to match SSL errors from 8.0.

2018-09-28 12:40 UTC, inikep commented
Tested at https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/57/

2018-09-28 13:38 UTC, laurynas-biveinis requested changes
As discussed on Slack, please remove replacements that are not actually seen on 8.0 platforms

2018-09-28 16:30 UTC, inikep commented
PR is updated and tested:
https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/59/

2018-10-01 07:59 UTC, laurynas-biveinis approved these changes

2018-10-01 09:10 UTC, merged