PS-269: Fix MTR tests (8.0)
percona/percona-server pull request #2595
Opened 2018-10-16 15:18 UTC by inikep

1. Fix `main.subselect_debug` by reverting `item_subselect.cc` to upstream
2. Fix SEGFAULT in `main.percona_bug1193264` by detection of `dd_table == nullptr` in `Ha_innopart_share::open_table_parts`.
3. Fix `main.heap_btree` by resoring missing `memcpy` in `heap_rlast()`

2018-10-17 08:16 UTC, laurynas-biveinis requested changes
All these changes are not related to each other - please PR separately

2018-10-17 08:53 UTC, inikep commented
PR was divided into 3 separate PRs.

2018-10-17 11:10 UTC, laurynas-biveinis requested changes
Please elaborate in the commit message - why is this a correct change? Why is it legal for dd_table to be nullptr here? Is it because it's a cloned handler for for I_S.GLOBAL_TEMP_TABLES query?
Please also change the commit message header accordingly: it's PS-269, but not merely fixing one test, more like "fix a crash on querying GLOBAL_TEMP_TABLES in the presence of partitioned InnoDB tables"

2018-10-17 15:02 UTC, inikep commented
The commit message was updated.

2018-10-18 08:55 UTC, laurynas-biveinis approved these changes

2018-10-18 09:00 UTC, merged