Ps 8.0 4960 4962
percona/percona-server pull request #2621
Opened 2018-10-26 22:26 UTC by georgelorchpercona

2018-10-26 22:26 UTC, george-lorch commented
https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/86/

2018-10-29 09:07 UTC, laurynas-biveinis requested changes

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +uint32_t KEY_AND_COL_INFO::get_max_secondary_key_pack_desc_size() const {
Mark inline, and move to header, it seems it should compile to "return a constant plus a bit". Might as well mark as noexcept.

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +uint32_t KEY_AND_COL_INFO::get_max_desc_size(TABLE *form) const {
Mark inline, and move to header, it seems it should compile to "return a constant plus a bit". Might as well mark as noexcept.

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +uint32_t KEY_AND_COL_INFO::get_len_of_offsets(TABLE_SHARE *table_share,
consider const ref for table_share

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +  cp_info[keynr] = NULL;
nullptr

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +      cp_info[i] = NULL;  // 3144
s/NULL/nullptr/g

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +    field_types = NULL;
s/NULL/nullptr/g

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +  assert_always(cp_info[keynr] == NULL);
nullptr

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +int32_t KEY_AND_COL_INFO::initialize_col_pack_info(TABLE_SHARE *table_share,
consider const ref for table_share

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +int32_t KEY_AND_COL_INFO::initialize(TABLE_SHARE *table_share, TABLE *table,
Consider const ref for table_share and table

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +  if (multi_ptr == NULL) {
nullptr

2018-10-29 09:07 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.cc
> +int32_t KEY_AND_COL_INFO::allocate(TABLE_SHARE *table_share) {
Consider const ref for table_share

2018-10-30 01:14 UTC, georgelorchpercona commented
Made suggested changes, also wen a little deeper down the rabbit hole in refactoring and const ref changes.  New jenkins https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/88/

2018-10-30 08:03 UTC, laurynas-biveinis requested changes

2018-10-30 08:03 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.h
> +  // bitmaps for each key..ey_filters[i] is associated with the i'th
Oops :)

2018-10-30 13:36 UTC, georgelorchpercona commented on storage/tokudb/hatoku_cmp.h
> +  // bitmaps for each key..ey_filters[i] is associated with the i'th
what the heck did I do there :-\

2018-10-30 13:55 UTC, laurynas-biveinis commented on storage/tokudb/hatoku_cmp.h
> +  // bitmaps for each key..ey_filters[i] is associated with the i'th
Probably tried to quit vi :)

2018-10-30 14:14 UTC, georgelorchpercona commented on storage/tokudb/hatoku_cmp.h
> +  // bitmaps for each key..ey_filters[i] is associated with the i'th
ZING!

2018-10-30 15:08 UTC, georgelorchpercona commented
Fixed typo, also fixed format issue pointed out by Travis clang-format-diff.

2018-10-31 09:54 UTC, laurynas-biveinis approved these changes

2018-10-31 16:06 UTC, merged

2020-01-30 01:01 UTC, peterschwaller commented
Dummy comment to trigger sync to Jira.  Please ignore.