PS-4988: Fix uninitailized btr stat mutex
percona/percona-server pull request #2643
Opened 2018-11-01 08:15 UTC by dutow

2018-11-01 09:46 UTC, robgolebiowski approved these changes

2018-11-07 09:41 UTC, laurynas-biveinis requested changes

2018-11-07 09:41 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps4988.test
> +# PS-4988: Uninitailized btr stat mutex caused assertion failure
"Uninitialized"

2018-11-07 09:41 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps4988.test
> +# PS-4988: Uninitailized btr stat mutex caused assertion failure
Consider naming the test "percona_sync_debug", so that it can receive further similar tests in the future

2018-11-20 06:52 UTC, dutow commented
https://ps.cd.percona.com/job/percona-server-5.7-param/15/

2018-12-05 10:01 UTC, merged