PS-4989: Fixing innodb_track_changed_pages debug validation
percona/percona-server pull request #2644
Opened 2018-11-01 09:38 UTC by dutow

In debug builds, this setting is allowed to be turned off temporarily after it was
turned on during startup. Howewer memory garbage also caused it to be accidentally
turned on when it was disabled at startup.

2018-11-07 09:45 UTC, laurynas-biveinis requested changes
Are lower versions affected?

2018-11-07 09:45 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_changed_page_bmp_1368530.test
The testcase no longer is "1368530", I'd rename to percona_changed_page_bmp_debug_tracking_off ?

2018-11-07 09:45 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +
Spurious

2018-11-26 05:43 UTC, dutow commented
Testcase renamed, submitted 5.5 and 5.6 PRs

2018-11-26 09:48 UTC, laurynas-biveinis requested changes
Same comment as for the 5.5 version

2018-11-26 09:49 UTC, laurynas-biveinis commented
@dutow, please submit an 8.0 version too

2018-12-11 14:16 UTC, merged