PS-4971 : Setting utf8mb4 as a key in MyRocks table could lead to a s…
percona/percona-server pull request #2662
Opened 2018-11-06 20:24 UTC by georgelorchpercona

…erver crash

- 8.0 changes the behavior of the character set strnxfrm methods in a way that
  alters what was a once 'defined' behavior in 5.7 to a now 'undefined'
  behavior.  Quoted right from m_ctype.h "@param num_codepoints Treat the string
  as if it were of type CHAR(num_codepoints)." ... "If the string has more than
  "num_codepoints" codepoints, behavior is undefined; may truncate, may crash,
  or do something else entirely."  The 5.7 behavior was to truncate the result
  to the num_codepoints length and is what the MyRocks packing code expected.
  This patch alters MyRocks to now tell strnxfrm what the srclen is based on the
  lesser of Field_varstring codepoint size or trimmed value length rather than
  always passing it the trimmed value length of the incoming value.

2018-11-06 20:24 UTC, george-lorch commented
https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/95/

2018-11-07 08:16 UTC, laurynas-biveinis requested changes

2018-11-07 08:16 UTC, laurynas-biveinis commented on mysql-test/suite/rocksdb/t/type_varchar.test
> +eval create table t1 (
Redundant eval

2018-11-07 08:16 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.cc
> +  const uchar *src =
It looks like src is used as const uchar * in one location, and as const char * in four, probably, makes sense to swap?

2018-11-07 19:17 UTC, george-lorch commented on mysql-test/suite/rocksdb/t/type_varchar.test
> +eval create table t1 (
Oops, yup, cut-n-paste fat finger

2018-11-07 22:32 UTC, georgelorchpercona commented
Changes made and locally tested OK, not firing jenkins yet because it still may be shaky, but really probably isn't totally necessary based on the changes.

2018-11-09 13:24 UTC, laurynas-biveinis approved these changes

2018-11-09 16:42 UTC, merged