PS-5006: Port storage engine enforcement to 8.0
percona/percona-server pull request #2688
Opened 2018-11-16 10:38 UTC by inikep

1. The patch is based on https://github.com/percona/percona-server/commit/7ad12e4df3880ac11fbf7656a14bf9b8043d25e1 with improvements at https://github.com/percona/percona-server/commit/868dbf4ba27ac4974b98f11c835ae367bdeb0022 and https://github.com/percona/percona-server/commit/1b93144cd839fcb804e6c0fbe8bb4a30de27dce5
2. Added exceptions for transactional data dictionary (DD) tables (enforcement is forbidden)
3. `percona_enforce_se_create_table_like` was changed as `mysql.proc` was removed in 8.0

2018-11-16 11:18 UTC, laurynas-biveinis requested changes
Minor comments only

2018-11-16 11:18 UTC, laurynas-biveinis commented on mysql-test/include/percona_enforce_storage_engine_alter_table.inc
> +# This statement will use "ALGORITHM=INPLACE" in both 5.6 and 5.7
Does "AlGORITHM=INPLACE" hold in 8.0 too? Please edit comment

2018-11-16 11:18 UTC, laurynas-biveinis commented on mysql-test/include/percona_enforce_storage_engine_alter_table.inc
> +# This statement will use "ALGORITHM=COPY" in both 5.6 and 5.7
Does "AlGORITHM=COPY" hold in 8.0 too? Please edit comment

2018-11-16 11:18 UTC, laurynas-biveinis commented on mysql-test/t/percona_enforce_storage_engine.test
> +--disable_warnings
Drop obsolete idiom

2018-11-16 11:18 UTC, laurynas-biveinis commented on sql/handler.h
> +      int error MY_ATTRIBUTE((unused))) {
?

2018-11-16 11:18 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +    if ((plugin = ha_resolve_by_name(0, &name, false))) {
s/0/nullptr

2018-11-16 11:18 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +      if ((defplugin = ha_resolve_by_name(0, &defname, false))) {
s/0/nullptr

2018-11-16 11:18 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +      plugin_unlock(0, defplugin);
s/0/nullptr

2018-11-16 11:18 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +      plugin_unlock(0, plugin);
s/0/nullptr

2018-11-16 15:02 UTC, inikep commented
All comments were addressed.
Moreover I added tests for `ALTER TABLE` with `ALGORITHM=INSTANT,INPLACE,COPY` in `percona_enforce_storage_engine_alter_table.inc`.

2018-11-19 06:43 UTC, laurynas-biveinis requested changes
OK to push with the comment addressed

2018-11-19 06:43 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +  if ((plugin = ha_resolve_by_name(nullptr, &name, false)))
Please do not cleanup otherwise untouched code

2018-11-19 12:43 UTC, merged