PS-4950: Invalid audit log file size when audit_log_rotations is chan…
percona/percona-server pull request #2717
Opened 2018-11-24 22:06 UTC by gl-sergei

…ged during runtime

audit_log_rotations and audit_log_rotate_on_size were messed up when set
at runtime.

2018-11-24 22:06 UTC, gl-sergei commented
https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/4/

2018-11-26 10:02 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_rotate.test
>  --echo success
This "echo success" is reporting the state of the 1st test above, should be moved there?

2018-11-26 10:04 UTC, laurynas-biveinis requested changes
OK with comments addressed, no need for further reviews

2018-11-26 10:04 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_rotate.test
>  --remove_files_wildcard $MYSQLD_DATADIR test_audit.log*
How about --remove_files_wildcard before this snippet too, so that it's not dependant on the previous snippet?

2018-11-26 10:04 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_rotate.test
>  --echo success
This "echo success" is reporting the state of the 1st test above, should be moved there?

2018-11-26 10:04 UTC, laurynas-biveinis commented on mysql-test/t/audit_log_rotate.test
> +# PS-4950: Invalid audit log file size when audit_log_rotations is changed during runtime
Please use
```
--echo #
--echo # PS-4950 ...
--echo #
```
so that .result file has it too

2018-11-27 10:40 UTC, gl-sergei commented
https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/8/

2018-11-27 10:41 UTC, merged