PS-5076: Redo log scrubbing ported to 8.0
percona/percona-server pull request #2727
Opened 2018-11-27 13:54 UTC by dutow

2018-11-28 15:51 UTC, laurynas-biveinis requested changes
OK to merge and address comments later

2018-11-28 15:51 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +     0, 0, 0);
some of those 0 must be nullptr and some false

2018-11-28 15:51 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +     NULL, NULL,
```suggestion
     nullptr, nullptr,
```

2018-11-28 15:51 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +static ulint next_lbn_to_pad = 0;
Is "lbn" a term used in 8.0 InnoDB?

2018-11-28 15:51 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +/*===========================*/
Please remove

2018-11-28 15:51 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +  ulint pad_length;
Declare at first use with const or const auto as applicable

2018-11-28 15:51 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +/*=========*/
Remove

2018-11-28 15:51 UTC, laurynas-biveinis commented on storage/innobase/log/log0log.cc
> +  ulint cur_lbn = log_block_convert_lsn_to_no(log_sys->current_file_lsn);
const local vars which don't change

2018-11-28 15:51 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0start.cc
> +/* @} */
Is there an opening {@ ?

2018-12-05 10:03 UTC, dutow commented
https://ps.cd.percona.com/job/percona-server-8.0-param/38

2018-12-05 10:03 UTC, merged