PS-4985: Fixing innodb_log_encrypt tests
percona/percona-server pull request #2800
Opened 2018-12-14 07:07 UTC by dutow

8.0 also missed redo log encryption changes which were part of PS-4556 (243e2d8cc2dacbbef84806f96ba2ae50312bd5b0). These changes were also ported in this commit, with the already improved tests.

2018-12-14 07:28 UTC, laurynas-biveinis requested changes
Some changes can be addressed later, but please keep track

2018-12-14 07:28 UTC, laurynas-biveinis commented on mysql-test/include/log_encrypt_1.inc
> +# eNable redo log encryption, should report error in server log, since keyring is not loaded.
"Enable"

2018-12-14 07:28 UTC, laurynas-biveinis commented on mysql-test/include/log_encrypt_4.inc
> +--sleep 5
Redundant: the bootstrap is synchronous

2018-12-14 07:28 UTC, laurynas-biveinis commented on mysql-test/include/log_encrypt_4.inc
> +--source include/start_mysqld_no_echo.inc
One of replace_result/replace_regex and _no_echo.inc looks redundant?

2018-12-14 07:28 UTC, laurynas-biveinis commented on mysql-test/include/log_encrypt_4.inc
> +--sleep 10
I don't understand why bootstraps are followed by sleep

2018-12-14 07:28 UTC, laurynas-biveinis commented on mysql-test/include/log_encrypt_5.inc
> +call mtr.add_suppression("\\[Error\\] InnoDB: Encryption can't find master key, please check the keyring plugin is loaded.");
Why this change? The old string would have matched, but the new one will not, now messages look like
[Error] [InnoDB] [MY-123] Blah blah

2018-12-14 07:28 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/log_encrypt_kill.test
> +--source include/not_embedded.inc
I suspect this PR was not tested?

2018-12-14 07:28 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +static TYPELIB redo_log_encrypt_typelib = {
const too?

2018-12-14 07:28 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +  NULL
nullptr

2018-12-14 07:28 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +			 "Possible values: OFF, ON, MASTER_KEY, KEYRING_KEY.",
clang-format

2018-12-14 07:28 UTC, laurynas-biveinis commented on storage/innobase/log/log0write.cc
> +      ib::error() << "Redo log was encrypted,"
ib::fatal() ? What happens up in the callstack if error is returned here?

2018-12-14 07:28 UTC, laurynas-biveinis commented on storage/innobase/log/log0write.cc
> +    char *key_type = NULL;
s/NULL/nullptr/g

2018-12-14 09:05 UTC, dutow commented on storage/innobase/handler/ha_innodb.cc
> +static TYPELIB redo_log_encrypt_typelib = {
Results in a compilation error :(

2018-12-17 07:21 UTC, dutow commented
Latest innodb suite run: https://ps.cd.percona.com/job/percona-server-8.0-param/101/
Since then, I've fixed the issues with encrypt_kill (needed rerecording) and log_encrypt_6 (left an echo there)

Everything passes on ubuntu, but _rk tests fail for some reasons on other distros + eatmydata.

2018-12-17 07:29 UTC, dutow commented on storage/innobase/log/log0write.cc
> +      ib::error() << "Redo log was encrypted,"
I left ib::error there. The server shuts down correctly after the error (because of the return), and fatal would result  in a different behavior (error status) compared to upstrem / what the tests currently expect.

2018-12-17 08:39 UTC, laurynas-biveinis approved these changes
OK to push. Previous comments still stand, and it still needs another review once RK is finalized

2018-12-17 15:08 UTC, merged