PS-5025: Setting compression flags for fields on DD load
percona/percona-server pull request #2803
Opened 2018-12-14 12:53 UTC by dutow

2018-12-14 13:04 UTC, laurynas-biveinis requested changes
Please use GCA starting at 5.6 to add the testcase to there and to 5.7 (please address the testcase merging comment too)

2018-12-14 13:04 UTC, laurynas-biveinis commented on mysql-test/t/percona_bug_ps5025.test
> +# PS-5025: field flag's weren't correctly set for compressed columns, causing a crash on an insert after the column was altered
Please merge with one of the existing compressed column testcases

2018-12-14 13:04 UTC, laurynas-biveinis commented on storage/innobase/dict/dict0dd.cc
> +    ulint is_compressed =
const

2018-12-17 12:15 UTC, dutow commented
Updated.

2018-12-17 13:00 UTC, laurynas-biveinis approved these changes

2018-12-17 15:06 UTC, merged