PS-5105: Fix 8.0.13 binlog encryption
percona/percona-server pull request #2848
Opened 2018-12-18 20:17 UTC by robgolebiowski

Removed basic::ostream position() function, which was also added to all
inheriting classes. Binlog encryption/decryption works only on binlog
files. All binlog files interfaces already contain position function.
Thus the addition to basic::ostream was not needed.

2018-12-18 20:22 UTC, robgolebiowski commented
JR => https://ps.cd.percona.com/job/percona-server-8.0-pipeline/1141 quite a number of failures due to Sergei's push. I can re-run if needed.

2018-12-19 05:02 UTC, laurynas-biveinis requested changes
Please remove GR Transaction_message::position too

2018-12-19 15:00 UTC, robgolebiowski commented
https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/121/

2018-12-20 07:51 UTC, laurynas-biveinis approved these changes

2018-12-20 10:00 UTC, merged