Fixed PS-1827 (LP #1736921: Inconsistent and unsafe FLUSH behavior in terms of replication)
percona/percona-server pull request #2890
Opened 2018-12-28 21:12 UTC by percona-ysorokin

https://jira.percona.com/browse/PS-1827

Introduced new global boolean system variable 'binlog_skip_flush_commands'.
When set to 'ON', all 'FLUSH <XXX>' statements are not written to the binary
log.

Added 'binlog.bug88720' MTR test case which checks if various 'FLUSH <XXX>'
statements change 'gtid_executed' when 'binlog_skip_flush_commands' is set
to 'ON'.

Added 'sys_vars.binlog_skip_flush_commands_basic' MTR test case which checks
basic global boolean system variable functionality.

Re-recorded 'main.mysqld--help-notwin' MTR test case because of the new
variable added.

2018-12-29 17:31 UTC, percona-ysorokin commented
Jenkins build link (--big-test)
https://ps.cd.percona.com/view/5.6/job/percona-server-5.6-param/27/

2019-01-02 11:43 UTC, laurynas-biveinis reviewed
This works, but I don't like that we are introducing new variable: documentation burden and most users will find it after an incident - in the best case.

Have you investigated stopping binlogging those commands unconditionally?

2019-01-03 13:08 UTC, percona-ysorokin commented
Sent an email to Experts asking their opinion.

2019-01-16 15:15 UTC, percona-ysorokin commented
@laurynas-biveinis Changed behavior of 'read_only' / 'super_read_only' modes as per new spec. Extended MTR test case. Ready for another round of review.

2019-01-23 12:24 UTC, laurynas-biveinis requested changes

2019-01-23 12:24 UTC, laurynas-biveinis commented on mysql-test/r/mysqld--help-notwin.result
> + --binlog-skip-flush-commands
Is perfschema suite clean? show_sanity, show_sanity56

2019-01-23 12:24 UTC, laurynas-biveinis commented on mysql-test/suite/binlog/t/percona_binlog_skip_flush_commands-master.opt
> +--gtid_mode=ON --enforce-gtid-consistency --log-slave-updates
Move to binlog_gtid while upmerging

2019-01-23 12:24 UTC, laurynas-biveinis commented on mysql-test/suite/binlog/t/percona_binlog_skip_flush_commands.test
> +--echo # Bug #88720 "Inconsistent and unsafe FLUSH behavior in terms of replication"
Add link to JIRA too

2019-01-23 12:24 UTC, laurynas-biveinis commented on mysql-test/suite/binlog/t/percona_binlog_skip_flush_commands.test
> +FLUSH PRIVILEGES;
Should not be needed

2019-01-23 12:24 UTC, laurynas-biveinis commented on mysql-test/suite/binlog/t/percona_binlog_skip_flush_commands.test
> +FLUSH PRIVILEGES;
Redundant

2019-02-01 14:39 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/percona_binlog_skip_flush_commands.test
> +FLUSH PRIVILEGES;
Done

2019-02-01 14:39 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/percona_binlog_skip_flush_commands.test
> +FLUSH PRIVILEGES;
Done

2019-02-01 14:44 UTC, percona-ysorokin commented on mysql-test/r/mysqld--help-notwin.result
> + --binlog-skip-flush-commands
`show_sanity` and `show_sanity56` are 5.7-only

2019-02-01 14:44 UTC, percona-ysorokin commented on mysql-test/suite/binlog/t/percona_binlog_skip_flush_commands.test
> +--echo # Bug #88720 "Inconsistent and unsafe FLUSH behavior in terms of replication"
Done

2019-02-04 13:20 UTC, percona-ysorokin commented
Updated Jenkins build link
https://ps2.cd.percona.com/view/5.6/job/percona-server-5.6-param/5/

2019-02-04 13:20 UTC, percona-ysorokin commented
@laurynas-biveinis This is ready for the second round of review before upmerging to 5.7 and 8.0

2019-02-04 13:29 UTC, laurynas-biveinis approved these changes

2019-02-06 11:13 UTC, merged