PS-5263: no tmpdir space can lead to assert in THD::send_statement_status (8.0)
percona/percona-server pull request #2892
Opened 2019-01-02 15:37 UTC by inikep

1. Update `handle_binlog_flush_or_sync_error()` to set `my_ok(thd)` after `thd->clear_error()`.
2. Update `rpl_bug72457.inc` to support errorless statements that disable binary logging.
3. Re-record `rpl_bug72457_innodb` and `rpl_bug72457_myisam`.

2019-01-02 15:41 UTC, inikep commented
Tests started at https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/137/

2019-01-02 15:58 UTC, laurynas-biveinis requested changes

2019-01-02 15:58 UTC, laurynas-biveinis commented on mysql-test/suite/rpl/t/rpl_bug72457_innodb-master.opt
> +--log-error=$MYSQLTEST_VARDIR/tmp/rpl_bug72457.err
This is still not good enough in the case of MTR --repeat: the testcase should restart the server in the .test file itself with the custom path, then restart in the end with default, remove the custom error log

2019-01-21 20:33 UTC, inikep commented
Tested at https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/181/

2019-01-22 12:12 UTC, laurynas-biveinis approved these changes

2019-01-23 14:24 UTC, inikep commented
Tested at https://ps.cd.percona.com/view/8.0/job/percona-server-8.0-param/190/

2019-01-23 14:29 UTC, merged