PS-4996, PS-3956: Fixing user statistics bugs (5.6)
percona/percona-server pull request #2894
Opened 2019-01-03 09:58 UTC by dutow

2019-01-04 14:16 UTC, laurynas-biveinis requested changes
If this is a backport cherrypick, use -x option to include original commit hash, and copy its commit message.
If this is not a cherrypick, please expand the commit message what and how is being fixed

2019-01-08 06:15 UTC, dutow commented
Commit message edited. In 5.6, I've added tests to every variable which was mentioned in the tickets, but only 2 weren't working. In 5.7 / 8.0, a few more fixes had to be added - I'll open those pull requests based on this after this is approved.

2019-01-08 08:59 UTC, laurynas-biveinis requested changes
Typo in the commit message: "statisctics".

OK with both comments fixed

2019-01-08 08:59 UTC, laurynas-biveinis commented on sql/handler.cc
> +  if(!error)
Space after if

2019-01-30 07:36 UTC, dutow commented
https://ps.cd.percona.com/job/percona-server-5.6-param/44/

2019-01-30 07:46 UTC, laurynas-biveinis approved these changes

2019-01-30 07:50 UTC, merged