PS-4949: Bad select+order by+limit performance in 5.7
percona/percona-server pull request #2904
Opened 2019-01-04 05:43 UTC by gl-sergei

Optimizer choosing ref-access when range access is more optimal. This is
related to upstream bug #26727773 (commit ddd9d614a32). This bug was
fixed differently in 5.7 and 8.0. 5.7 fix doesn't work for this query
and 8.0 looks more robust. It is choosing range access over ref access
if ref access using more keyparts.

Fixed by taking fix and test cases from 8.0.

Take 8.0 version of fix for #26727773

fix/re-record some test cases

2019-01-04 05:44 UTC, gl-sergei commented
https://ps.cd.percona.com/view/5.7/job/percona-server-5.7-param/67/ it seems no optimizer-related failures left.
8.0 version will be null-merge, I'll create PR if we agree on approach.

2019-01-04 13:49 UTC, laurynas-biveinis requested changes
The approach LGTM.

Digging git history suggests to backport 5c93ff30c3af40eced199cbbe3653621c1c9a0ed too, please check

2019-01-08 10:19 UTC, gl-sergei commented
Indeed, I missed that bit. Fixed and pushed

2019-01-08 10:20 UTC, gl-sergei commented
https://ps.cd.percona.com/view/5.7/job/percona-server-5.7-param/75/

2019-01-09 07:39 UTC, laurynas-biveinis approved these changes

2019-01-09 08:17 UTC, merged