PS-4996, PS-3956: Fixing user statistics bugs (8.0)
percona/percona-server pull request #2936
Opened 2019-01-14 10:13 UTC by dutow

* Added tests to ensure that some untested columns of user/thread statisctics work correctly, as they were mentioned in PS-4996.
  Some counters are only bugged in later versions, but work in 5.6.
* Fixed commit counter: committed transactions weren't counted
* Fixed access denied counter: most access denied paths weren't counted
* Fixed denied connections counter: authentication failures weren't counted

This is a cherry-pick of 6ee45b95be7c931fc83290d83f0c592a065b9deb, as GCA merge in a merge conflict to the 5.7 trunk.

(cherry picked from commit cee57554e8fafc10802773b399af6b392e38c054)

2019-01-14 10:19 UTC, laurynas-biveinis requested changes

2019-01-14 10:19 UTC, laurynas-biveinis commented on sql/auth/sql_authentication.cc
> +  update_global_user_stats(thd, false, time(NULL), mpvio->auth_info.user_name,
nullptr

2019-01-14 10:19 UTC, laurynas-biveinis commented on sql/auth/sql_authentication.cc
> +#ifndef EMBEDDED_LIBRARY
No EMBEDED_LIBRARY in 8.0

2019-01-14 10:55 UTC, dutow commented
updated.

2019-01-14 11:53 UTC, laurynas-biveinis approved these changes

2019-01-30 07:35 UTC, dutow commented
Same fix as for 5.7, jenkins looks good now: https://ps.cd.percona.com/job/percona-server-8.0-param/197/

2019-01-30 07:48 UTC, laurynas-biveinis approved these changes

2019-01-30 07:50 UTC, merged