PS-5331 : Fix instances of 'const char* const name = "foo"' to be 'st…
percona/percona-server pull request #2944
Opened 2019-01-18 17:16 UTC by georgelorchpercona

…atic const constexpr char name[]= "foo"'

- Subject says it all, modernize 'const' to 'constexpr'

2019-01-18 17:16 UTC, georgelorchpercona commented
https://ps.cd.percona.com/view/5.7/job/percona-server-5.7-param/87/

2019-01-21 08:17 UTC, laurynas-biveinis requested changes

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr uint RDB_INVALID_KEY_LEN = uint(-1);
```suggestion
const constexpr uint RDB_INVALID_KEY_LEN = uint(-1);
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr size_t RDB_CHECKSUM_SIZE = sizeof(uint32_t);
```suggestion
const constexpr size_t RDB_CHECKSUM_SIZE = sizeof(uint32_t);
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr size_t RDB_CHECKSUM_CHUNK_SIZE = 2 * RDB_CHECKSUM_SIZE + 1;
```suggestion
const constexpr size_t RDB_CHECKSUM_CHUNK_SIZE = 2 * RDB_CHECKSUM_SIZE + 1;
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr char RDB_CHECKSUM_DATA_TAG = 0x01;
```suggestion
const constexpr char RDB_CHECKSUM_DATA_TAG = 0x01;
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr char RDB_UNPACK_DATA_TAG = 0x02;
```suggestion
const constexpr char RDB_UNPACK_DATA_TAG = 0x02;
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr size_t RDB_UNPACK_DATA_LEN_SIZE = sizeof(uint16_t);
```suggestion
const constexpr size_t RDB_UNPACK_DATA_LEN_SIZE = sizeof(uint16_t);
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr size_t RDB_UNPACK_HEADER_SIZE =
```suggestion
const constexpr size_t RDB_UNPACK_HEADER_SIZE =
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr char RDB_UNPACK_COVERED_DATA_TAG = 0x03;
```suggestion
const constexpr char RDB_UNPACK_COVERED_DATA_TAG = 0x03;
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr size_t RDB_UNPACK_COVERED_DATA_LEN_SIZE = sizeof(uint16_t);
```suggestion
const constexpr size_t RDB_UNPACK_COVERED_DATA_LEN_SIZE = sizeof(uint16_t);
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr size_t RDB_COVERED_BITMAP_SIZE = sizeof(uint16_t);
```suggestion
const constexpr size_t RDB_COVERED_BITMAP_SIZE = sizeof(uint16_t);
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_datadic.h
> +constexpr size_t RDB_UNPACK_COVERED_HEADER_SIZE =
```suggestion
const constexpr size_t RDB_UNPACK_COVERED_HEADER_SIZE =
```

2019-01-21 08:17 UTC, laurynas-biveinis commented on storage/rocksdb/rdb_utils.h
> +constexpr size_t RDB_MAX_HEXDUMP_LEN = 1000;
```suggestion
const constexpr size_t RDB_MAX_HEXDUMP_LEN = 1000;
```

2019-01-21 21:47 UTC, georgelorchpercona commented
done, new jenkins https://ps.cd.percona.com/view/5.7/job/percona-server-5.7-param/93/

2019-01-22 12:09 UTC, laurynas-biveinis approved these changes

2019-01-22 16:49 UTC, merged