Implementation of PS-3969 - 5.7
percona/percona-server pull request #2955
Opened 2019-01-23 19:51 UTC by altmannmarcelo

This commit adds a variable to track when an audit log entry was either
 dropped or written directly to the file due to its size being bigger
than audit_log_buffer_size

2019-01-24 09:50 UTC, laurynas-biveinis requested changes
Same comments as for 5.6

2019-02-12 16:00 UTC, altmannmarcelo commented
Ready for the next review - https://ps.cd.percona.com/job/percona-server-5.6-param/51/

2019-02-13 06:42 UTC, laurynas-biveinis requested changes
Same comments as for 5.6 + 1 5.7-specific comment

2019-02-13 06:42 UTC, laurynas-biveinis commented on plugin/audit_log/audit_log.c
> +   SHOW_INT, SHOW_SCOPE_GLOBAL},
It was SHOW_LONG in 5.6 version

2019-02-28 01:31 UTC, altmannmarcelo commented
Ready for next review - https://ps.cd.percona.com/job/percona-server-5.7-param/121/ (some Jenkins build failed, seems to be something with the pipeline itself)

2019-02-28 12:54 UTC, laurynas-biveinis requested changes

2019-02-28 12:54 UTC, laurynas-biveinis commented on plugin/audit_log/buffer.c
> +    my_atomic_add64(&audit_log_buffer_size_overflow,1);
space after comma:
```suggestion
    my_atomic_add64(&audit_log_buffer_size_overflow, 1);
```

2019-02-28 15:47 UTC, altmannmarcelo commented
Ready for next review

2019-03-01 07:22 UTC, laurynas-biveinis approved these changes

2019-03-08 11:21 UTC, altmannmarcelo commented
replaced by #3056

2019-03-08 11:21 UTC, closed without merging