PS-5221 : Page Cleaner will sleep for long time if clock changes
percona/percona-server pull request #2959
Opened 2019-01-28 17:53 UTC by georgelorchpercona

- Added monotonic clock source for transient comparisons.

- Changed InnoDB page flusher, lru, and bp load throttle to use new monotonic
  clock source.

2019-01-28 17:53 UTC, georgelorchpercona commented
https://ps.cd.percona.com/view/5.7/job/percona-server-5.7-param/97/

2019-01-29 08:28 UTC, laurynas-biveinis commented
One thing that I missed in the original discussion is that we should fix 5.6 too, right?

2019-01-29 08:33 UTC, laurynas-biveinis requested changes

2019-01-29 08:33 UTC, laurynas-biveinis commented on storage/innobase/buf/buf0dump.cc
> +	ut_monotonic_time	elapsed_time;
elapsed_time staying as ulint would result in a smaller diff?

2019-01-29 08:33 UTC, laurynas-biveinis commented on storage/innobase/buf/buf0flu.cc
> +			ut_monotonic_time tm = ut_monotonic_time_ms();
```suggestion
			const ut_monotonic_time tm = ut_monotonic_time_ms();
```

2019-01-29 08:33 UTC, laurynas-biveinis commented on storage/innobase/buf/buf0flu.cc
> +			ut_monotonic_time tm = ut_monotonic_time_ms();
```suggestion
			const ut_monotonic_time tm = ut_monotonic_time_ms();
```

2019-01-29 08:33 UTC, laurynas-biveinis commented on storage/innobase/include/ut0ut.h
> +/*============*/
```suggestion
```

2019-01-29 13:41 UTC, georgelorchpercona commented
Hmm 5.6?  That is entirely your call to make @laurynas-biveinis  I can't imagine it being difficult to back port this onto a GCA point.

2019-01-29 16:47 UTC, george-lorch commented on storage/innobase/buf/buf0dump.cc
> +	ut_monotonic_time	elapsed_time;
True, it doesn't look like it currently would be a threat from an upstream change that needs triggering on a merge.

2019-02-04 22:39 UTC, georgelorchpercona commented
Re-pushed due to 5.6 and GCA merge forward.  New jenkins with jobs that appear to have been aborted due to spot instance demand https://ps.cd.percona.com/view/5.7/job/percona-server-5.7-param/111/.  Going to go ahead and merge as requested changes have been made.

2019-02-04 22:49 UTC, merged