PS-5254: version_suffix, version_comment - add definition
percona/percona-server pull request #2962
Opened 2019-01-29 12:07 UTC by borys-belinsky

2019-01-29 12:08 UTC, laurynas-biveinis requested changes

2019-01-29 12:08 UTC, laurynas-biveinis commented on doc/source/glossary.rst
> +       variable and thereby it is now cutomizable.
```suggestion
       variable and thereby it is now customizable.
```

2019-01-29 15:03 UTC, borys-belinsky commented on doc/source/glossary.rst
> +       variable and thereby it is now cutomizable.
Ready for review

2019-01-29 15:26 UTC, laurynas-biveinis approved these changes

2019-01-29 15:37 UTC, merged

2020-01-30 01:01 UTC, peterschwaller commented
Dummy comment to trigger sync to Jira.  Please ignore.