PS-4688: SSL improvement: discribe for PS 5.7
percona/percona-server pull request #2978
Opened 2019-01-31 12:04 UTC by borys-belinsky

2019-01-31 12:15 UTC, laurynas-biveinis requested changes

2019-01-31 12:15 UTC, laurynas-biveinis commented on doc/source/management/ssl-improvement.rst
> +.. Remove:
Remove the remove comment now that it's implemented

2019-01-31 12:15 UTC, laurynas-biveinis commented on doc/source/management/ssl-improvement.rst
> +      https://dev.mysql.com/doc/refman/5.6/en/openssl-versus-yassl.html
5.7

2019-02-05 23:06 UTC, borys-belinsky commented on doc/source/management/ssl-improvement.rst
> +      https://dev.mysql.com/doc/refman/5.6/en/openssl-versus-yassl.html
Ready for review

2019-02-06 06:43 UTC, laurynas-biveinis approved these changes

2019-02-06 17:26 UTC, merged