Fix PS-1827 (LP #1736921: Inconsistent and unsafe FLUSH behavior in terms of replication) (5.7)
percona/percona-server pull request #2984
Opened 2019-02-04 18:50 UTC by percona-ysorokin

2019-02-05 06:29 UTC, laurynas-biveinis approved these changes

2019-02-05 13:28 UTC, percona-ysorokin commented
Jenkins build link
https://ps2.cd.percona.com/view/5.7/job/percona-server-5.7-param/19/
`MySQL.perfschema.show_sanity` fails are connected with an existing problem.

2019-02-05 17:29 UTC, percona-ysorokin commented
Updated Jenkins build link after re-push
https://ps2.cd.percona.com/view/5.7/job/percona-server-5.7-param/20/

2019-02-06 07:01 UTC, laurynas-biveinis requested changes

2019-02-06 07:01 UTC, laurynas-biveinis commented on sql/mysqld.cc
> +my_bool opt_binlog_skip_flush_commands= 0;
```suggestion
my_bool opt_binlog_skip_flush_commands= FALSE;
```

2019-02-06 11:13 UTC, merged