Ps 4688 ssl certificate compatibility matrix 8.0
percona/percona-server pull request #2995
Opened 2019-02-07 18:08 UTC by borys-belinsky

2019-02-08 06:09 UTC, laurynas-biveinis requested changes
Please read my last comment on https://jira.percona.com/browse/PS-4688

2019-02-08 09:01 UTC, borys-belinsky commented
Ready for review

2019-02-08 12:36 UTC, laurynas-biveinis requested changes

2019-02-08 12:36 UTC, laurynas-biveinis commented on doc/source/management/ssl-improvement.rst
> +|Percona Server| enables transmitting data in the encrypted form by
Remove paragraph

2019-02-14 16:46 UTC, borys-belinsky commented on doc/source/management/ssl-improvement.rst
> +|Percona Server| enables transmitting data in the encrypted form by
Ready for review

2019-02-15 07:21 UTC, laurynas-biveinis approved these changes

2019-02-15 13:17 UTC, merged