JEN-795 Failed connect to vault.public-ci.percona.com:8600
percona/percona-server pull request #3013
Opened 2019-02-19 14:59 UTC by robgolebiowski

vault.public-ci.percona was deemed to be unsecure and thus removed.
keyring_vault MTR test should use https://vault.percona.com, which is
maintained by IIT team. The tests were amended to use this new server.
The policy was changed to more strict one in comparision to
vault.public-ci.percona - the tests were also amended to cope with the
new policy.

Also new tests were added to test the separation of keyrings inside a
Vault server on directory level. For those tests only one new mount
point is created on the server and the separation is done by creating
separate directories inside the mount point - one directory per each
Percona server keyring_vault keyring.

The old tests are still checking the separation of keyrings with use of
separate mount points.

The not_repeat.inc was added to check whether the tests are not run with
--repeat > 1. This is because the tests are creating mount points at
the beginning of a run and delete when at the end of the run. When repeat is
used server will remember that it has already created master key and will
try to fetch the key. Unfortunately the key will be gone because the
mount point was deleted and re-created.

Changed the number of times the Master Key is rotated in
keyring_vault.table_encrypt_3.test and
keyring_vault.table_encrypt_3_directory to 100, so not to DoS the Vault Server.

Ported keyring_vault unittest to 8.0 - as they were not building,
enabled MERGE_UNITTESTS for keyring_vault as the linking of unittests
in 8.0 takes substantial amount of time.

Also clang-format-5.0 was applied.

(cherry picked from commit 78e4297ff14fa0f419fb29e8168399a24e9fca7c)

2019-02-19 15:03 UTC, robgolebiowski commented
https://ps2.cd.percona.com/view/8.0/job/percona-server-8.0-param/56/

2019-02-25 10:10 UTC, laurynas-biveinis requested changes
Minor comments only, looks great overall

2019-02-25 10:10 UTC, laurynas-biveinis commented on plugin/keyring_vault/vault_curl.cc
> -static const constexpr size_t max_response_size = 32000000;
Why?

2019-02-25 10:10 UTC, laurynas-biveinis commented on plugin/keyring_vault/vault_curl.cc
> -  if ((list = curl_slist_append(list, token_header.c_str())) == nullptr ||
Why?

2019-02-25 10:10 UTC, laurynas-biveinis commented on unittest/gunit/keyring_vault/CMakeLists.txt
> +    #TARGET_LINK_LIBRARIES(${test}-t gunit_large strings dbug regex)
Remove commented-out block

2019-02-25 10:10 UTC, laurynas-biveinis commented on unittest/gunit/keyring_vault/vault_io-t.cc
> +  // MOCK_METHOD1(set_timeout, void(uint timeout));
```suggestion
```

2019-02-25 10:10 UTC, laurynas-biveinis commented on unittest/gunit/keyring_vault/vault_keyring-api-t.cc
> +TEST_F(Keyring_vault_api_test, StorePBStoreSKFetchPBRemovePerconInnodb) {
```suggestion
TEST_F(Keyring_vault_api_test, StorePBStoreSKFetchPBRemovePerconaInnodb) {
```

2019-02-25 10:37 UTC, robgolebiowski commented on plugin/keyring_vault/vault_curl.cc
> -  if ((list = curl_slist_append(list, token_header.c_str())) == nullptr ||
A mistake - probably during merging while cherry-picking, reverted.

2019-02-25 10:42 UTC, robgolebiowski commented on plugin/keyring_vault/vault_curl.cc
> -static const constexpr size_t max_response_size = 32000000;
Because constexpr implies const.

2019-02-25 12:11 UTC, laurynas-biveinis approved these changes

2019-02-27 10:19 UTC, percona-ysorokin reviewed
The same comments/questions as in 5.7 + commented out code

2019-02-27 10:19 UTC, percona-ysorokin commented on plugin/keyring_vault/tests/mtr/innodb_row_log_encryption.test
> +#--replace_result $MYSQLTEST_VARDIR MYSQLTEST_VARDIR
Commented out code.

2019-02-27 10:19 UTC, percona-ysorokin commented on unittest/gunit/keyring_vault/uuid.cc
> +  std::string id = uuid + key_id;
```suggestion
```

2019-02-27 10:19 UTC, percona-ysorokin commented on unittest/gunit/keyring_vault/uuid.cc
> +  signature << id.length() << '_' << id << user.length() << '_' << user;
Just a suggestion to simplify this a bit
```suggestion
  signature << uuid.length() + key_id.length() << '_' << uuid << key_id << user.length() << '_' << user;
```

2019-02-27 10:22 UTC, percona-ysorokin commented
Another question is what's the reason of introducing `MERGE_UNITTESTS` define?

2019-03-07 05:52 UTC, laurynas-biveinis commented
As discussed on Slack, merging now for better Vault testing, Yura's review comments will be addressed once Robert returns

2019-03-07 05:52 UTC, merged