PS-4858: Update release notes for 5.7.23-23
percona/percona-server pull request #3036
Opened 2019-03-04 13:28 UTC by borys-belinsky

2019-03-05 12:33 UTC, laurynas-biveinis requested changes

2019-03-05 12:33 UTC, laurynas-biveinis commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* When more space was added to the data partition to the error that the disk
```suggestion
* When more space was added to the data partition after the error that the disk
```

2019-03-21 10:14 UTC, borys-belinsky commented on doc/source/release-notes/Percona-Server-5.7.23-23.rst
> +* When more space was added to the data partition to the error that the disk
Ready for review

2019-03-22 09:13 UTC, laurynas-biveinis approved these changes

2019-08-23 18:20 UTC, merged

2020-01-30 01:01 UTC, peterschwaller commented
Dummy comment to trigger sync to Jira.  Please ignore.