8.0 ps 3969
percona/percona-server pull request #3058
Opened 2019-03-08 11:15 UTC by altmannmarcelo

This commit adds a variable to track when an audit log entry was either
dropped or written directly to the file due to its size being bigger
than audit_log_buffer_size

https://ps.cd.percona.com/job/percona-server-8.0-param/256/

2019-03-12 13:22 UTC, laurynas-biveinis approved these changes

2019-03-12 13:23 UTC, laurynas-biveinis requested changes
Please reformat the source to fix the CircleCI failures (check the automated PR tests)

2019-03-12 21:29 UTC, altmannmarcelo commented
Ready for next review

2019-03-13 06:53 UTC, laurynas-biveinis approved these changes
Please push all three PRs now

2019-03-19 10:52 UTC, merged