PS-5492: bootstrap failure with innodb_encrypt_tables = 1
percona/percona-server pull request #3080
Opened 2019-03-15 12:10 UTC by satya-bodapati

Problem:
--------
Bootstrap fails (asserts in debug build) with innodb_encrypt_tables = 1

This happens because server requests to create temporary table before UUID
is ready. InnoDB allocates session temp tablespace and tries to set encryption
info. The assert detects that encryption is requested before UUID is ready.

We do have handlerton API innobase_fix_tablespaces_empty_uuid() to fix the
UUID issue. This API is called after init_server_components() (in this UUID is
created/loaded). The request for temp table comes before init_server_components()
and hence UUID is not yet ready and hence the assert.

Fix:
----
When UUID is not yet ready, we use un-encrypted session temp tablespace for create
temporary table request.

2019-03-18 03:35 UTC, satya-bodapati commented
Ready for review with new approach.

2019-03-18 07:01 UTC, laurynas-biveinis requested changes

2019-03-18 07:01 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +      ut_ad(0);
The debug build assert is in the innermost loop, so for release build this is a loop with no-op body. I'd surround the whole piece with #ifdef UNIV_DEBUG

2019-03-18 07:01 UTC, laurynas-biveinis commented on storage/innobase/include/srv0tmp.h
> +  void iterate_active_tbsp(F &&f) {
Hmm, that lambda is not actually moved into this, is it? Not moving it also should allow to declare it as const auto

2019-03-18 07:01 UTC, laurynas-biveinis commented on storage/innobase/include/srv0tmp.h
> +  bool is_encrypt() const { return (is_encrypt(m_purpose)); }
```suggestion
  bool is_encrypted() const { return (is_encrypt(m_purpose)); }
```

2019-03-18 07:01 UTC, laurynas-biveinis commented on storage/innobase/include/srv0tmp.h
> +  static bool is_encrypt(enum tbsp_purpose purpose) {
```suggestion
  static bool is_encrypted(enum tbsp_purpose purpose) {
```

2019-03-18 07:01 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0tmp.cc
> +  if (!is_encrypt()) {
```suggestion
  if (!is_encrypted()) {
```

2019-03-18 07:01 UTC, laurynas-biveinis commented on storage/innobase/srv/srv0tmp.cc
> +  if (Tablespace::is_encrypt(purpose)) {
```suggestion
  if (Tablespace::is_encrypted(purpose)) {
```

2019-03-18 09:20 UTC, satya-bodapati commented
addressed review comments ready for review @laurynas-biveinis

2019-03-18 09:21 UTC, satya-bodapati commented
run all innodb suites: https://ps80.cd.percona.com/job/percona-server-8.0-pipeline/367/

2019-03-19 06:50 UTC, laurynas-biveinis approved these changes

2019-03-19 06:50 UTC, laurynas-biveinis commented on storage/innobase/include/srv0tmp.h
> +  void iterate_active_tbsp(F &&f) {
What was the resolution here?

2019-03-19 06:54 UTC, satya-bodapati commented on storage/innobase/include/srv0tmp.h
> +  void iterate_active_tbsp(F &&f) {
Isn't this request to use const auto for the lamba function? 
I have used
const auto find_encrypted = [&]...

2019-03-19 07:05 UTC, laurynas-biveinis commented on storage/innobase/include/srv0tmp.h
> +  void iterate_active_tbsp(F &&f) {
That was half of it yes, the other half was - is it required to pass by rvalue ref?

2019-03-19 07:19 UTC, satya-bodapati commented on storage/innobase/include/srv0tmp.h
> +  void iterate_active_tbsp(F &&f) {
Hmm, probably not. Just used same as original implementation.

2019-03-19 10:33 UTC, merged