Fixed PS-5353 (Wrong binlog entry for BLOB on a blackhole intermediary master) (8.0)
percona/percona-server pull request #3146
Opened 2019-04-16 15:56 UTC by percona-ysorokin

2019-04-17 07:59 UTC, percona-ysorokin commented
Jenkins build link:
https://ps80.cd.percona.com/job/percona-server-8.0-param/84/

2019-04-17 11:02 UTC, laurynas-biveinis requested changes

2019-04-17 11:02 UTC, laurynas-biveinis commented on storage/blackhole/ha_blackhole.cc
> +      for (Field **field_ptr = table->field; *field_ptr != NULL; ++field_ptr) {
C++11'ize

2019-04-22 18:28 UTC, percona-ysorokin commented on storage/blackhole/ha_blackhole.cc
> +      for (Field **field_ptr = table->field; *field_ptr != NULL; ++field_ptr) {
fixed

2019-04-22 19:13 UTC, percona-ysorokin commented
Updated Jenkins build link
https://ps80.cd.percona.com/job/percona-server-8.0-param/91/ (rpl.bug93917 rpl.bug93917 --repeat=2)

2019-04-23 05:44 UTC, laurynas-biveinis approved these changes

2019-04-23 10:45 UTC, merged