PS-5659-RHEL-requires-mysql-mod-disabled-for-packages-installation ad…
percona/percona-server pull request #3214
Opened 2019-06-05 14:01 UTC by patrickbirch

…ded RHEL to the supported releases and added a note in the installing PS using downloaded rpm packages - section 2 before the installation step.

2019-06-05 16:22 UTC, hrvojem commented on doc/source/installation/yum_repo.rst
> +	 percona-server-devel-80-8.0.13-3.el7.x86_64.rpm6
where did the `6` came from :)

2019-06-06 10:05 UTC, laurynas-biveinis commented
Make sure to squash commits on merge

2019-06-06 10:09 UTC, laurynas-biveinis requested changes
The fix branches must be GCA-based

2019-07-15 18:48 UTC, patrickbirch commented
Updated branch to GCA

2019-07-16 05:46 UTC, laurynas-biveinis commented
This cannot possibly be GCA-based: there are three commits, none of them is a merge from a lower version

2019-07-16 13:54 UTC, patrickbirch commented
Thank you. Yes, this is the one for version 8. I am waiting for approval of the 5.7 version before fixing this version and updating it. 
When I created this PR I was unaware that I needed the merges from the lower version. Hrvoje and George have explained that I should do the lowest version first, have that one approved, before working on the next version.

2019-07-17 06:25 UTC, laurynas-biveinis approved these changes

2019-08-06 12:20 UTC, merged

2019-08-12 06:47 UTC, laurynas-biveinis commented
@patrickbirch this is still not GCA. Was it merged by mistake or did you think it was actually GCA?

2019-08-12 14:05 UTC, patrickbirch commented
My mistake. Will fix.