PS-5659-RHEL8-package-install-requires-mysql-mod-disabled - added RHE…
percona/percona-server pull request #3215
Opened 2019-06-05 14:22 UTC by patrickbirch

…L 8 to supported releases and added a note to installing PS using rpm packages - step 2.

2019-06-06 10:09 UTC, laurynas-biveinis requested changes
The fix branches must be GCA-based

2019-06-06 10:25 UTC, laurynas-biveinis requested changes
The fix branches must be GCA-based

2019-07-15 18:47 UTC, patrickbirch commented
Fixed branch to GCA

2019-07-18 16:14 UTC, george-lorch approved these changes

2019-07-18 16:38 UTC, merged