PS-5656-doc-incorrect-encryption-5.7
percona/percona-server pull request #3218
Opened 2019-06-05 21:04 UTC by patrickbirch

corrected notes and added specific version features that PXB does not support.

2019-06-06 08:20 UTC, laurynas-biveinis reviewed
Need reply from @gl-sergei to finish the review

2019-06-06 08:20 UTC, laurynas-biveinis commented on doc/source/management/data_at_rest_encryption.rst
> +      * Parallel doublewrite buffer encryption
@gl-sergei does XB care about the parallel doublewrite buffer at all?

2019-07-15 15:36 UTC, patrickbirch commented
Added Sergei - please see Laurynas comment.

2019-08-02 16:02 UTC, patrickbirch commented
Sergei said:
Parallel doublewrite buffer encryption does not affect xtrabackup in any way. System tablespace encryption is not supported in 2.4, but will be supported in 8.0 with the next release.

2019-08-02 20:21 UTC, patrickbirch commented
updated the doc based on Sergei's comments.

2019-09-04 06:43 UTC, dutow requested changes

2019-09-04 06:43 UTC, dutow commented on doc/source/management/data_at_rest_encryption.rst
> +>>>>>>> Stashed changes
You left a merge marker here

2019-09-04 06:43 UTC, dutow commented on doc/source/management/data_at_rest_encryption.rst
> +<<<<<<< Updated upstream
You left a merge marker here

2019-09-04 12:27 UTC, patrickbirch commented on doc/source/management/data_at_rest_encryption.rst
> +>>>>>>> Stashed changes
removed.

2019-09-04 12:28 UTC, patrickbirch commented on doc/source/management/data_at_rest_encryption.rst
> +<<<<<<< Updated upstream
removed

2019-09-04 12:55 UTC, dutow commented
@patrickbirch now the PR contains changes for many files it shouldn't?

2019-09-04 13:03 UTC, patrickbirch commented
Odd. OK. I'll redo this.

2019-09-04 13:05 UTC, dutow commented
You can do

`git reset HEAD~
git add doc/source/management/data_at_rest_encryption.rst
git commit ...`

to recreate the commit with just that single file.

2019-09-04 13:05 UTC, patrickbirch commented
Thanks. I'll do that.

2019-09-12 08:20 UTC, dutow approved these changes
One small comment, otherwise looks good

2019-09-12 08:20 UTC, dutow commented on doc/source/management/data_at_rest_encryption.rst
> +    |Percona XtraBackup| version 2.4 does not support the following:
This paragraph is now indented differently than the rest of the file? Existing indentation is also inconsistent, but I don't see any other paragraphs with 4 space indents.

2019-09-12 08:21 UTC, dutow commented
Please also change the commit message as I mentioned in #3424

2019-11-12 14:26 UTC, patrickbirch commented
replaced by 6075 - no longer needed.

2019-11-12 14:26 UTC, closed without merging