PS-5656-doc-incorrect-encryption-8.0
percona/percona-server pull request #3219
Opened 2019-06-05 22:08 UTC by patrickbirch

added text to note line 225 and fixed note header line 641

2019-06-06 08:57 UTC, laurynas-biveinis reviewed
Same comment as for the 5.7 version

2019-08-29 16:15 UTC, george-lorch requested changes

2019-08-29 16:15 UTC, george-lorch commented on doc/source/management/data_at_rest_encryption.rst
> +    |Percona XtraBackup| version 2.4 and version 8.0 support the backup of encrypted general
Only PXB 8.0 works on PS 8.0, 2.4 does not support PS/MySQL 8.0.  Should remove all references to 2.4 in 8.0 docs other than maybe to state the fact that only PXB 8.0 supports PS/MySQL 8.0.

2019-11-11 20:08 UTC, patrickbirch commented
No longer needed. Encryption docs have been updated.

2019-11-11 20:08 UTC, closed without merging