Ps 8.0 5651
percona/percona-server pull request #3225
Opened 2019-06-10 06:19 UTC by mohitj1988

Description:

Added new sub-tests to test sys tablespace encryption functionality
when innodb_file_per_table is disabled
Move table from encrypted sys tablespace to un-encrypted tablespace
Move table from un-encrypted sys tablespace to encrypted tablespace
Move table from encrypted sys tablespace to another encrypted tablespace
Move table from un-encrypted sys tablespace to another un-encrypted tablespace
Testcase name: percona_sys_tablespace_encrypt.test

2019-06-10 07:28 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_sys_tablespace_encrypt.test
> +DROP TABLE t8,t9;
```suggestion
DROP TABLE t8, t9;
```

2019-06-10 07:30 UTC, laurynas-biveinis reviewed
Please show CI results (running only this testcase is enough)

2019-06-12 12:19 UTC, mohitj1988 commented
Test Results: https://ps57.cd.percona.com/job/percona-server-5.7-param/46/

2019-06-12 12:40 UTC, satya-bodapati approved these changes
Please the close the 8.0 PR you have created for the same patch (before GCA process)

2019-06-12 12:41 UTC, satya-bodapati commented
> Test Results: https://ps57.cd.percona.com/job/percona-server-5.7-param/46/

This is wrong link for 8.0 PR request

2019-06-13 06:18 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_sys_tablespace_encrypt.test
> +DROP TABLE t8,t9;
Comment not addressed

2019-06-13 06:18 UTC, laurynas-biveinis requested changes
Previous review comment needs addressing

2019-06-13 06:20 UTC, mohitj1988 commented
Updated Test results for 8.0: https://ps80.cd.percona.com/job/percona-server-8.0-param/160/

2019-06-13 06:37 UTC, mohitj1988 commented on mysql-test/suite/innodb/t/percona_sys_tablespace_encrypt.test
> +DROP TABLE t8,t9;
Fixed

2019-06-13 06:53 UTC, mohitj1988 reviewed
Approved by Laurynas over Slack

2019-06-13 06:54 UTC, merged