PS-5658: improve innodb_redo_log_encrypt vali/dation and formatting (8.0).
percona/percona-server pull request #3239
Opened 2019-06-13 12:20 UTC by dutow

* Variable no longer accepts 2 and 3 as valid values
* Value is dispayed in upcase as with other variables

(cherry picked from commit 5524aa3c84ced75558a10379fd90c7b74cc1be63)

2019-06-14 09:26 UTC, laurynas-biveinis requested changes
Same comments as for the 5.7 version

2019-06-17 09:09 UTC, laurynas-biveinis requested changes
OK with the minor change, no need for further reviews

2019-06-17 09:09 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +  ut_a(save != NULL);
```suggestion
  ut_a(save != nullptr);
```

2019-06-17 09:09 UTC, laurynas-biveinis commented on storage/innobase/handler/ha_innodb.cc
> +  ut_a(value != NULL);
```suggestion
  ut_a(value != nullptr);
```

2019-07-04 06:07 UTC, dutow commented
Rebased on 8.0 after ps-5565 merge, no other change. 

https://ps80.cd.percona.com/job/percona-server-8.0-param/216/

2019-07-05 04:49 UTC, dutow commented
Rerecorded log_encrypt_2 and reran jenkins: https://ps80.cd.percona.com/job/percona-server-8.0-param/224

Failures seems to be jenkins timeouts around 99% mtr, previous run completed all.

2019-07-05 04:50 UTC, merged