WIP PS-5102: MyRocks errors after 8.0.16 merge
percona/percona-server pull request #3269
Opened 2019-06-28 12:44 UTC by dutow

* Regular expressions are now based on std::regex
*
* Added include my_systime.h to get declaration of my_sleep
* Fix initialization of PSI_stage_info_v1 structs that are now C++14-ized
* Fix use of Item::print as it now needs a const THD* passed in.
* Added include of mysql/psi/mysql_rwlock.h to re-gain rwlock types/definitions.
* Added include of sql/sql_table.h to re-gain declaration of ST_FIELD_INFO
* Fix initialization of PSI thread, mutex, rwlock, cond, and memory structs that all had new members added.
* Rerecorded many testcases where warnings now refer to different rows, but are still correct.
* Rerecorded 2 tests (collation_exceptions_lctn_0, collation_exceptions_lctn_1) where additional warnings are reported now
* Rerecorded rocksdb.rocksdb, where an explain changed (impossible where) (?)
* Rerecorded rocksdb_cf_per_partition: information_schema.rocksdb_cfstats now has an upper case value
* Rerecorded type_decimal: warning formatting changed

Remaining MTR failures:

* rocksdb.create_table - missing encryption support
* rocksdb.unique_sec_rev_cf - Using Gap Lock without full unique key in multi-table or multi-statement transactions is not allowed.
* rocksdb.unique_sec - Using Gap Lock without full unique key in multi-table or multi-statement transactions is not allowed.
* rocksdb.select - syntax error in a query (?)
* rocksdb.bulk_load_sk - select count(*) with force index returns a different result
* upgrade_parts_from_prev_ver - mysql_upgrade deprecated

2019-07-01 09:01 UTC, laurynas-biveinis requested changes

2019-07-01 09:01 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +    std::smatch matches;
Move out of try block so that it contains only potentially throwing operations (initializing flags is OK)

2019-07-01 09:01 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> -  rdb_collation_exceptions = new Regex(key_rwlock_collation_exception_list);
Is this key ever used then?

2019-07-01 14:10 UTC, dutow commented on storage/rocksdb/ha_rocksdb.cc
> +    std::smatch matches;
Done.

2019-07-01 14:10 UTC, dutow commented on storage/rocksdb/ha_rocksdb.cc
> -  rdb_collation_exceptions = new Regex(key_rwlock_collation_exception_list);
No, I removed it.

2019-07-01 20:50 UTC, georgelorchpercona commented
With my_regex gone, we also need to remove the wrapper file for my_regexp at sql/sql_regex.h

2019-07-02 17:29 UTC, george-lorch approved these changes
The remaining failing mtr tests are known issues that need to be diagnosed and fixed separately from the 8.0.16 merge.  Everything looks good, please merge.

2019-07-03 06:31 UTC, laurynas-biveinis commented on storage/rocksdb/ha_rocksdb.cc
> +    std::smatch matches;
I don't see any difference from previous code?

2019-07-03 06:32 UTC, laurynas-biveinis commented
sql/sql_regex.h removal can happen in this PR or separately

2019-07-03 20:20 UTC, merged