PS-5581: Bloom_filter allocates too much memory (8.0)
percona/percona-server pull request #3309
Opened 2019-07-12 12:45 UTC by dutow

2019-07-15 07:45 UTC, laurynas-biveinis requested changes

2019-07-15 07:45 UTC, laurynas-biveinis commented on sql/sql_class.h
> -  ~Bloom_filter() {
~Bloom_filter() = default

2019-07-16 05:58 UTC, laurynas-biveinis approved these changes

2019-07-16 08:07 UTC, dutow commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/240/

2019-07-16 08:07 UTC, merged