Fix PS-5780 (The release build (5.6) does not work on Debian buster) (5.6)
percona/percona-server pull request #3317
Opened 2019-07-17 11:50 UTC by percona-ysorokin

https://jira.percona.com/browse/PS-5780

Partially cherry-picked 5.7 upstream fixes for gcc-8 - releated warnings.
"Bug#27558169 BACKPORT TO 5.7 BUG #26826272: REMOVE GCC 8 WARNINGS [noclose]"
(commit mysql/mysql-server@1ffd796)
(commit mysql/mysql-server@a091d6b)

2019-07-17 11:52 UTC, percona-ysorokin commented
Jenkins build links:
https://ps56.cd.percona.com/job/percona-server-5.6-param/27/
https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-pipeline/1276/ (Debian Buster Release)
https://ps3.cd.percona.com/view/5.6/job/percona-server-5.6-pipeline/1277/ (Debian Buster Debug)

2019-07-18 07:45 UTC, laurynas-biveinis requested changes

2019-07-18 07:45 UTC, laurynas-biveinis commented on mysys/my_gethwaddr.c
> +      memcpy(ifr.ifr_name, ifri->ifr_name, sizeof(ifr.ifr_name));
What was the warning fixed?
The only difference between strncpy and memcpy here should have been that strncpy might have stopped earlier on seeing NUL. Since the destination is memset to zero, the result should have been the same

2019-07-18 07:45 UTC, laurynas-biveinis commented on storage/innobase/log/log0online.cc
> +			memcpy(bitmap_files->files[array_pos].name,
What was the fixed warning?
Our code, not an upstream backport - the commit message should mention this.
This will need an upmerge, right?

2019-07-18 09:14 UTC, percona-ysorokin commented on mysys/my_gethwaddr.c
> +      memcpy(ifr.ifr_name, ifri->ifr_name, sizeof(ifr.ifr_name));
```
/home/yura/ws/percona-server/mysys/my_gethwaddr.c: In function ‘my_gethwaddr’:
/home/yura/ws/percona-server/mysys/my_gethwaddr.c:111:7: error: ‘strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]
       strncpy(ifr.ifr_name, ifri->ifr_name, sizeof(ifr.ifr_name));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
As far as I understood from https://en.cppreference.com/w/cpp/string/byte/strncpy the main reson fro this warning is
`If count is reached before the entire string src was copied, the resulting character array is not null-terminated.`

This fix is from the upstream https://github.com/mysql/mysql-server/commit/a091d6b#diff-8b61af0eaadf2d4f8128d3c5122fecf5, btw

2019-07-18 09:19 UTC, percona-ysorokin commented on storage/innobase/log/log0online.cc
> +			memcpy(bitmap_files->files[array_pos].name,
```
/home/yura/ws/percona-server/storage/innobase/log/log0online.cc: In function ‘ulint log_online_setup_bitmap_file_range(log_online_bitmap_file_range_t*, lsn_t, lsn_t)’:
/home/yura/ws/percona-server/storage/innobase/log/log0online.cc:1471:11: error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 512 bytes from a string of length 3999 [-Werror=stringop-truncation]
    strncpy(bitmap_files->files[array_pos].name,
    ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     bitmap_dir_file_info.name, FN_REFLEN);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Yes, this is our code. And this is the biggest mystery. For some reason, this fragment does not trigger any warnings in 5.7 code.

2019-07-18 09:25 UTC, laurynas-biveinis commented on storage/innobase/log/log0online.cc
> +			memcpy(bitmap_files->files[array_pos].name,
@percona-ysorokin check if the array lengths (most likely the destination one) did not change between 5.6 and 5.7

2019-07-18 12:52 UTC, percona-ysorokin commented on storage/innobase/log/log0online.cc
> +			memcpy(bitmap_files->files[array_pos].name,
@laurynas-biveinis 
Actually `log_online_bitmap_file_range_struct` definitions in both 5.6 and 5.7 are identical
https://github.com/percona/percona-server/blob/5.6/storage/innobase/include/log0online.h#L145
https://github.com/percona/percona-server/blob/5.7/storage/innobase/include/log0online.h#L144
`FN_REFLEN` in both branches is 512.

`os_file_stat_t` definitions are also identical
https://github.com/percona/percona-server/blob/5.6/storage/innobase/include/os0file.h#L567
https://github.com/percona/percona-server/blob/5.7/storage/innobase/include/os0file.h#L1286
`OS_FILE_MAX_PATH` in both cases is 4000.

I believe this is just a limitation of GCC to detect this warning (5.7 code could be more complicated from its point of view).
In any case, I believe the `bitmap_files->files[array_pos].name[FN_REFLEN - 1] = '\0';` at the next line makes both statements (`strncpy` and `memcpy`) safe here. So, if `memcpy` makes GCC 8.3 happier in 5.6, I would do this change only for 5.6 and leave 5.7 as is.

2019-07-18 13:41 UTC, laurynas-biveinis commented on storage/innobase/log/log0online.cc
> +			memcpy(bitmap_files->files[array_pos].name,
@percona-ysorokin I agree, please proceed

2019-07-18 14:21 UTC, percona-ysorokin commented
No new Jenkins build links as only commit message updated.

2019-07-18 14:26 UTC, merged