PS-5794: Crash when innodb-redo-log-encrypt=ON specified during boots…
percona/percona-server pull request #3325
Opened 2019-07-24 05:18 UTC by dutow

…trap

2019-07-24 05:50 UTC, laurynas-biveinis requested changes
5.7?

2019-07-24 05:50 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_bug_ps5794.test
> +# restart
Remove

2019-07-24 05:50 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_bug_ps5794.test
> +--sleep 5
Please sync properly

2019-07-24 08:56 UTC, satya-bodapati commented
This looks like wrong fix. Enum shouldn't allow optional arguments. Option value is must.

for
  static MYSQL_SYSVAR_ENUM(redo_log_encrypt, srv_redo_log_encrypt,

you should use PLUGIN_VAR_RQCMDARG instead of PLUGIN_VAR_OPCMDARG

2019-07-24 12:40 UTC, dutow commented
Upstream allows it to be empty - so we should allow it to be empty. Also, even if I disallow the empty version, the issue would be there with `=ON`, as that's basically the empty option.

2019-07-24 12:41 UTC, dutow commented
In 5.7,  we don't allow the "ON" option, it's not affected.

2019-07-29 12:30 UTC, satya-bodapati approved these changes
Please move this testcase to existing redo log encrypt testcase

2019-08-01 10:01 UTC, dutow commented
@satya-bodapati I kept the test where it is - other test either have a specific topic or have mk/rk variants both.

2019-08-02 09:54 UTC, laurynas-biveinis approved these changes

2019-08-05 05:42 UTC, dutow commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/274/

2019-08-05 05:42 UTC, merged