PS-5790: keyring_vault tests are failing on Jenkins
percona/percona-server pull request #3332
Opened 2019-07-30 09:07 UTC by robgolebiowski

There is a bug in curl on Debian and it seems to not support http v2.
Because of that we should fall back to HTTP 1.1 in keyring_vault.
We should check when new fixes come around on Debian and re-check the
problem. Re-enable HTTP v2 in keyring_vault when the problem goes away
on Debian. There should not be any negative consequences security-wise
as all communication happens over TLS.

2019-07-30 09:08 UTC, robgolebiowski commented
https://ps57.cd.percona.com/job/percona-server-5.7-param/119/

2019-07-31 06:30 UTC, laurynas-biveinis reviewed
Is there a Debian bug #?

2019-08-08 13:36 UTC, robgolebiowski commented
I do not see any bug reported against it. If you want me I can report it to Vault and ask them to investigate it?

2019-08-12 05:01 UTC, laurynas-biveinis commented
Please do - stuff like this needs some end game plan

2019-08-15 07:32 UTC, robgolebiowski commented
@laurynas-biveinis Created bug against Vault: https://github.com/hashicorp/vault/issues/7320

2019-08-16 06:20 UTC, laurynas-biveinis approved these changes

2019-08-16 06:21 UTC, laurynas-biveinis requested changes

2019-08-16 06:21 UTC, laurynas-biveinis commented on plugin/keyring_vault/vault_curl.cc
> +          CURLE_OK ||
Please reference the bug report at least there, and maybe in the MTR patch too

2019-08-16 07:08 UTC, merged