Follow up to PS-5772 : 8.0.16 encryption reconciliation
percona/percona-server pull request #3337
Opened 2019-07-31 07:03 UTC by satya-bodapati

Fixes innodb.percona_force_encryption test with new variable
default_table_encryption and privilege changes

2019-07-31 07:10 UTC, laurynas-biveinis requested changes

2019-07-31 07:10 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_force_encryption.test
> +set default_table_encryption='ON';
Consistent SQL keyword case please
```suggestion
SET default_table_encryption='ON';
```

2019-07-31 07:10 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_force_encryption.test
> +--error  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON
```suggestion
--error ER_ALTER_OPERATION_NOT_SUPPORTED_REASON
```

2019-07-31 07:10 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_force_encryption.test
> +eval set global default_table_encryption=$initial_encrypt_tables_value;
```suggestion
eval SET global default_table_encryption=$initial_encrypt_tables_value;
```

2019-07-31 07:10 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_force_encryption.test
> +let $initial_encrypt_tables_value = `select @@default_table_encryption`;
Nit: I'd rename to initial_default_table_encryption_value

2019-08-01 05:48 UTC, satya-bodapati commented
ready for review

2019-08-01 05:52 UTC, laurynas-biveinis approved these changes

2019-08-01 05:58 UTC, merged