PS-5581: Bloom_filter allocates too much memory (5.7)
percona/percona-server pull request #3341
Opened 2019-08-01 16:17 UTC by dutow

In the 5.7 port, the extended slow query log was changed: the
Bloom_filter uses a MEM_ROOT instead of new/malloc, reallocating
the filter on clearing. For complex statements, such as stored
procedures calling many statements, or updates calling user functions
for each row, this results in a huge amount of allocations, which
will only be freed at the end of the entire statemment.
(8c9fa78caf62)

This commit changes how clear works: instead of allocating a new
bitset on the next use, the current bitset is cleared.

In this 5.7 version, there's also an additional (no-op) merge, as I didn't force-push the PS-5581 5.7 branch after rebasing to the GCA point.

2019-08-01 16:19 UTC, dutow commented
Also: this restores the previous behavior before PS-5581, with the memory usage reduced, but I think this is only a workaround if we want accurate statistics.

2019-08-03 22:53 UTC, percona-ysorokin commented on sql/sql_class.h
> +      bit_set_copy= Bit_set_ptr(new Bit_set());
I believe there is also boost::make_shared
```suggestion
      bit_set_copy= boost::make_shared<Bit_set>();
```

2019-08-03 22:53 UTC, percona-ysorokin commented on sql/sql_class.h
> +      bit_set= bit_set_copy;
This call is not thread-safe. In c++11 I would use std::atomic_exchange here
https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic
I believe there must be something similar in boost

2019-08-03 22:53 UTC, percona-ysorokin commented on sql/sql_class.h
> +    bit_set_copy->set(pos);
`set()` method on an `std::bitset<N>` class is not atomic either - it still does
```
mov <register>, internal_array[index]
or <register>, <mask>
mov internal_array[index], <register>
```
internally.
Unless we can ignore some inaccuracies in the statistics, this needs to be reworked as well. I would implement a simple  helper class `atomic_bitset` or something. which would internally hold `std::array<std::atomic_ullong, N>`.

2019-08-04 07:38 UTC, dutow commented on sql/sql_class.h
> +      bit_set= bit_set_copy;
Before C++20, there is no atomic_shared_ptr in any of the standard libraries - using atomic_exchange basically means a mutex+lock. (and I'm not sure if now that C++20 requires it, modern compilers will or will not "backport" it to earlier standards)

So if we need thread safety here, we could also use a mysql lock like everywhere else. (but I'm not sure if we need. To me, it looks like two innodb workers can't call this function simultaneously, but I could be wrong here)

2019-08-04 07:41 UTC, dutow commented on sql/sql_class.h
> +    bit_set_copy->set(pos);
We have to ignore some inaccuracies - the entire issue is an inaccuracy: if test_and_set is called after clear, we are inaccurate - we miss some statistics for the current statement, and we assign some to the next executed statement... but it happens, as we report these stats from some background workers.

And again, I'm not sure if this method is called concurrently. But if we want to, I can change this, there's a boost::array for 5.7 too.

2019-08-05 06:27 UTC, dutow commented on sql/sql_class.h
> +      bit_set= bit_set_copy;
One possible multi-worker issue is that if workers are way too behind (at least 2 statements/commits). I'm not sure if that can happen in a real scenario, but theoretically should be possible. Will update with locking here.

2019-08-05 16:16 UTC, percona-ysorokin requested changes
All of this makes sense only if there cannot be concurrent calls between `test_and_set()` and `clear()`. Otherwise, I don't see any way to implement this other than just always protecting everything with a mutex.

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +  typedef boost::shared_ptr<Bit_set> Bit_set_ptr;
@dutow I have a strange feeling that using `shared_ptr` here will case us more race condition troubles despite the fact that it may potentially simplify the code.
Although I don't like this either, for 5.7 I would go with canonical volatile pointer approach.
```suggestion
  typedef Bit_set* Bit_set_ptr;
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +    mysql_mutex_destroy(&LOCK_bit_set);
```suggestion
    clear();
    mysql_mutex_destroy(&LOCK_bit_set);
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +  Bit_set_ptr bit_set;
```suggestion
  volatile Bit_set_ptr bit_set;
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +  Bloom_filter() {
```suggestion
  Bloom_filter() : bit_set(NULL) {
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +    Bit_set_ptr bit_set_copy= bit_set;
```suggestion
    Bit_set_ptr local_bit_set = my_atomic_loadptr(&bit_set);
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +    if (!bit_set_copy)
```suggestion
    if (local_bit_set != NULL)
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +      if (!bit_set_copy)
```suggestion
      local_bit_set = my_atomic_loadptr(&bit_set);
      if (local_bit_set != NULL)
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +        bit_set_copy= Bit_set_ptr(new Bit_set());
```suggestion
        local_bit_set_copy= new Bit_set;
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +        bit_set= bit_set_copy;
```suggestion
        my_atomic_storeptr(&bit_set, local_bit_set);
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +    if (bit_set_copy->test(pos))
```suggestion
    if (local_bit_set->test(pos))
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +    bit_set_copy->set(pos);
```suggestion
    local_bit_set->set(pos);
```

2019-08-05 16:16 UTC, percona-ysorokin commented on CMakeLists.txt
> +  ${CMAKE_SOURCE_DIR}/libbinlogevents/export
Not needed if shared_ptr is not used.
See below

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +#include <boost/shared_ptr.hpp>
```suggestion
```

2019-08-05 16:16 UTC, percona-ysorokin commented on sql/sql_class.h
> +    bit_set.reset();
Here, I would also protect this with a mutex.
```suggestion
    mysql_mutex_lock(&LOCK_bit_set);
    Bit_set_ptr local_bit_set = my_atomic_loadptr(&bit_set);
    delete local_bit_set;
    my_atomic_storeptr(&bit_set, NULL);
    mysql_mutex_unlock(&LOCK_bit_set);
```

2019-08-05 18:11 UTC, dutow commented on sql/sql_class.h
> +  typedef boost::shared_ptr<Bit_set> Bit_set_ptr;
And for 8.0, should I keep shared pointers?

2019-08-06 11:32 UTC, dutow commented
Updated.

2019-08-06 15:19 UTC, percona-ysorokin approved these changes
LGTM

2019-08-07 06:55 UTC, dutow commented
https://ps57.cd.percona.com/job/percona-server-5.7-param/128/

2019-08-07 11:15 UTC, merged

2019-08-08 13:32 UTC, percona-ysorokin commented
@dutow `perfschema.dml_setup_instruments` MTR test case should have been re-recorded as part of this commit because of the new `key_LOCK_bloom_filter` being instrumented.