PS-5325 Conditional jump or move depends on uninitialised value on in…
percona/percona-server pull request #3347
Opened 2019-08-06 20:58 UTC by altmannmarcelo

…nodb_zip.wl5522_zip and innodb.alter_missing_tablespace

Problem:
As part of DISCARD TABLESPACE, MySQL deinitialize table statistics.
Later if we need to access the table (MySQL allows DDL)
those variables won't have been initialized again.

Solution:
Call dict_stats_init even if the table has been discarded.
This will result in dict_stats_report_error been called, which as
part of the error handling will init empty table statistics.
As part of the fix, we need to suppress warnings that will be generated
by dict_stats_report_error on related tests.

2019-08-06 21:09 UTC, altmannmarcelo commented
https://ps57.cd.percona.com/job/percona-server-5.7-param/132/ - all normal tests

```
# With Path
bash-4.2$ ./mtr --debug-server --valgrind-mysqld --valgrind-option=--track-origins=yes wl5522_zip innodb.alter_missing_tablespace
Logging: ./mtr  --debug-server --valgrind-mysqld --valgrind-option=--track-origins=yes wl5522_zip innodb.alter_missing_tablespace
MySQL Version 5.7.25
Too long tmpdir path '/tmp/ps/bld/usr/local/Percona-Server-5.7.25-28-debug-valgrind-MINE-Linux.x86_64/mysql-test/var/tmp'  creating a shorter one...
 - using tmpdir: '/tmp/9Nw3HNhiFl'

Turning on valgrind for all executables
Running valgrind with options " --tool=memcheck --num-callers=16 --show-reachable=yes --track-origins=yes --suppressions=/tmp/ps/bld/usr/local/Percona-Server-5.7.25-28-debug-valgrind-MINE-Linux.x86_64/mysql-test/valgrind.supp "
Turning off --check-testcases to save time when valgrinding
Checking supported features...
 - SSL connections supported
 - binaries are debug compiled
Collecting tests...
Checking leftover processes...
Removing old var directory...
Creating var directory '/tmp/ps/bld/usr/local/Percona-Server-5.7.25-28-debug-valgrind-MINE-Linux.x86_64/mysql-test/var'...
Installing system database...
Using parallel: 1

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
[ 50%] innodb.alter_missing_tablespace          [ pass ]  64749
[100%] innodb_zip.wl5522_zip                    [ pass ]  157361
[150%] valgrind_report                          [ pass ]
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 222.110 of 323 seconds executing testcases

Completed: All 3 tests were successful.

bash-4.2$


#without patch
2019-08-06T21:03:03.025903Z 2 [ERROR] InnoDB: Could not find a valid tablespace file for `test/t`. Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-troubleshooting-datadict.html for how to resolve the issue.
Thread 25:
Conditional jump or move depends on uninitialised value(s)
   at 0x19D2916: ha_innobase::info_low(unsigned int, bool) (ha_innodb.cc:15559)
   by 0x19D333B: ha_innobase::info(unsigned int) (ha_innodb.cc:15884)
   by 0x19C2F24: ha_innobase::open(char const*, int, unsigned int) (ha_innodb.cc:7308)
   by 0xF73EF1: handler::ha_open(TABLE*, char const*, int, int) (handler.cc:2952)
   by 0x167F73E: open_table_from_share(THD*, TABLE_SHARE*, char const*, unsigned int, unsigned int, unsigned int, TABLE*, bool) (table.cc:3475)
   by 0x14FB95F: open_table(THD*, TABLE_LIST*, Open_table_context*) (sql_base.cc:3614)
   by 0x14FE504: open_and_process_table(THD*, LEX*, TABLE_LIST*, unsigned int*, unsigned int, Prelocking_strategy*, bool, Open_table_context*) (sql_base.cc:5231)
   by 0x14FF66D: open_tables(THD*, TABLE_LIST**, unsigned int*, unsigned int, Prelocking_strategy*) (sql_base.cc:5847)
   by 0x150080D: open_and_lock_tables(THD*, TABLE_LIST*, unsigned int, Prelocking_strategy*) (sql_base.cc:6569)
   by 0x161F1DF: mysql_discard_or_import_tablespace(THD*, TABLE_LIST*, bool) (sql_table.cc:6336)
   by 0x17A0444: Sql_cmd_discard_import_tablespace::execute(THD*) (sql_alter.cc:402)
   by 0x158D45C: mysql_execute_command(THD*, bool) (sql_parse.cc:5136)
   by 0x158F818: mysql_parse(THD*, Parser_state*, bool) (sql_parse.cc:5905)
   by 0x158408B: dispatch_command(THD*, COM_DATA const*, enum_server_command) (sql_parse.cc:1532)
   by 0x1582EA3: do_command(THD*) (sql_parse.cc:1053)
   by 0x16C9943: handle_connection (connection_handler_per_thread.cc:318)
 Uninitialised value was created by a client request
   at 0x1CE64F8: dict_stats_deinit(dict_table_t*) (dict0stats.ic:199)
   by 0x1CE72F5: dict_table_close(dict_table_t*, unsigned long, unsigned long) (dict0dict.cc:524)
   by 0x19C26A2: ha_innobase::open(char const*, int, unsigned int) (ha_innodb.cc:7099)
   by 0xF73EF1: handler::ha_open(TABLE*, char const*, int, int) (handler.cc:2952)
   by 0x167F73E: open_table_from_share(THD*, TABLE_SHARE*, char const*, unsigned int, unsigned int, unsigned int, TABLE*, bool) (table.cc:3475)
   by 0x14FB95F: open_table(THD*, TABLE_LIST*, Open_table_context*) (sql_base.cc:3614)
   by 0x14FE504: open_and_process_table(THD*, LEX*, TABLE_LIST*, unsigned int*, unsigned int, Prelocking_strategy*, bool, Open_table_context*) (sql_base.cc:5231)
   by 0x14FF66D: open_tables(THD*, TABLE_LIST**, unsigned int*, unsigned int, Prelocking_strategy*) (sql_base.cc:5847)
   by 0x1626568: mysql_alter_table(THD*, char const*, char const*, st_ha_create_information*, TABLE_LIST*, Alter_info*) (sql_table.cc:9656)
   by 0x17A0214: Sql_cmd_alter_table::execute(THD*) (sql_alter.cc:348)
   by 0x158D45C: mysql_execute_command(THD*, bool) (sql_parse.cc:5136)
   by 0x158F818: mysql_parse(THD*, Parser_state*, bool) (sql_parse.cc:5905)
   by 0x158408B: dispatch_command(THD*, COM_DATA const*, enum_server_command) (sql_parse.cc:1532)
   by 0x1582EA3: do_command(THD*) (sql_parse.cc:1053)
   by 0x16C9943: handle_connection (connection_handler_per_thread.cc:318)
   by 0x1909593: pfs_spawn_thread (pfs.cc:2190)
 . . . [many more]
```

2019-08-12 09:52 UTC, laurynas-biveinis reviewed
As discussed before: since this is present in Percona Server but not MySQL, have you identified which change of ours introduced this regression?

2019-08-13 11:02 UTC, altmannmarcelo commented
Yes. We diverted from upstream due to work related to encryption, more specifically the commit - https://github.com/percona/percona-server/commit/c7f44ee3974d .

2019-08-13 13:03 UTC, laurynas-biveinis commented
OK, this should be mentioned in the commit message ("regression introduced by PS-XXXX") and should be reviewed by @satya-bodapati or @robgolebiowski

2019-08-13 13:40 UTC, altmannmarcelo commented
@laurynas-biveinis commit message and PR description updated.

Requesting @satya-bodapati or @robgolebiowski to review it

2019-09-05 11:23 UTC, satya-bodapati requested changes

2019-09-05 11:23 UTC, satya-bodapati commented on storage/innobase/handler/ha_innodb.cc
> +	if (ib_table->is_readable() || dict_table_is_discarded(ib_table)) {
Thanks for finding the root cause commit. That commit still gives sleepless nights.. (many coding guide violations) and also caused other bugs.

It looks like upstream calls this dict_stats_init() unconditionally. Can you make it unconditional and run all tests (specially the encryption tests)?

2019-09-05 11:23 UTC, satya-bodapati commented on storage/innobase/handler/ha_innodb.cc
> +	if (ib_table->is_readable() || dict_table_is_discarded(ib_table)) {
As I see it if we can call stats init without IBD file, it should be fine with an unreadable file too?

2019-09-10 18:14 UTC, altmannmarcelo commented
@robgolebiowski @satya-bodapati stats initialization now matches upstream code. Manually run the requested tests with missing keyring file and with/out innodb_stats_persistent - all tests passed.

Ready for the next review.

2019-09-11 08:24 UTC, robgolebiowski commented
Hey @altmannmarcelo. There is one more scenario where this fix might be needed. It is when keyring has a key id that is needed to decrypt the table, but the key itself is different. For instance:
Keyring 1: key_id = 1 Key = 123456
Keyring 2: key_id = 1 Key = 789012
The table could be encrypted using keyring1  and then somebody tries to decrypt it using keyring2. This is what test encryption.innodb-bad-key-change4 - could you check if it pass with and without your fix ? Thanks.

2019-10-01 18:14 UTC, altmannmarcelo commented
@robgolebiowski both upstream and my patch passes the test:
```
bash-4.2$ ./mtr encryption.innodb-bad-key-change4 --valgrind-mysqld --valgrind-option=--track-origins=yes
Logging: /tmp/ps/mysql-test/mysql-test-run.pl  encryption.innodb-bad-key-change4 --valgrind-mysqld --valgrind-option=--track-origins=yes
MySQL Version 5.7.25
Turning on valgrind for all executables
Running valgrind with options " --tool=memcheck --num-callers=16 --show-reachable=yes --track-origins=yes --suppressions=/tmp/ps/mysql-test/valgrind.supp "
Turning off --check-testcases to save time when valgrinding
Checking supported features...
 - SSL connections supported
 - binaries are debug compiled
Collecting tests...
Checking leftover processes...
Removing old var directory...
Creating var directory '/tmp/ps/bld/mysql-test/var'...
Installing system database...
Using parallel: 1

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
[100%] encryption.innodb-bad-key-change4        [ pass ]  96185
[200%] valgrind_report                          [ pass ]
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 96.185 of 397 seconds executing testcases

Completed: All 2 tests were successful.
```

2019-10-11 07:45 UTC, robgolebiowski approved these changes

2019-12-17 15:23 UTC, merged