GPL UDF function to send emails from MySQL
percona/percona-server pull request #3357
Opened 2019-08-11 07:19 UTC by fmbiete

Simple curl based UDF function to send emails from MySQL. 
For example; I use this to notify of the results of MySQL scheduled events.

2019-08-21 13:09 UTC, dutow requested changes
Thanks!

The idea is great, sending e-mails directly from MySQL could have its uses.

I added some comments to specific codeparts, where I see some issues.

I also have a more generic concern: security. 

In this form, if this plugin is installed, it allows any user to send any number of messages, to any server, at any rate, without any logging.

* I don't think allowing anybody to send an email is a good idea - somehow this should be limited (list of allowed users, some role, ...)
* I don't think allowing the user of the function to specify any SMTP server is a good idea. The server, or a whilelist of possible servers should be specified as a global variable
* The same could be true for the sender/addressee too
* There should be an option to log sent emails - at least which user sent an email to who, when, so the server administrator could see this without owning the used SMTP server too

We will also need some tests with this, possibly with a dummy smtp server started as part of an MTR testcase. But as even that needs some environment setup, maybe we should implement that after merging.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +    char buffer[80];
Please use a static const variable instead of the magic constant (below too). Please also use a more specific variable name, e.g. `formatted_date`.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/plugin.cc
> +//#define mysql_declare_plugin_end   ,{0,0,0,0,0,0,0,0,0,0,0,0,0,0}} <- 14 v8.0
Please don't leave commented out code

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/CMakeLists.txt
> +  message(STATUS "Plugin Mail UDF won't be compiled: curl package is missing")
I would go with `FATAL_ERROR`, as this means we'll skip the plugin. A `WITH_EMAIL` or similar switch could be useful too, like in the LDAP plugin.

Also please use consistent case in CMake too (`MESSAGE`)

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +    struct curl_slist *recipients = nullptr;
These `struct` keywords aren't required, as this is a C++ source, please use C++ style.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +    msg.lines.push_back(std::string("From: ").append(from).append("\r\n"));
These user specified parameters should be validated before used, otherwise, it's possible for users to inject additional headers - and even to skip later headers specified in this file by injecting an additional line break.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +      curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
I don't think disabling these checks without any condition is a good idea - maybe behind an option?

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +    if (strncmp(smtp_uri, "smtps", 5) == 0) {
Please also check the other case - the user should specify an SMTP server, not something else.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +  std::string res = _mail_send(args->args[0], args->args[1], args->args[2],
Please use `const` where possible.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/CMakeLists.txt
> +INCLUDE(CheckLibraryExists)
Why is this needed?

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/README.md
> +### MySQL v5.7 or superior
The code as-is only works with MySQL 8.0, as it requires C++11. I would go with only documenting that version here.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/include/plugin.h
> +#endif  //_PLUGIN_MAIL_PLUGIN_H
Please use `/* ... */` for comments. (at other places too)

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/plugin.cc
> +  sql_print_information("Mail Plugin: Initializing Mail plugin structures");
This seems like debug information, and even then DBUG_ENTER will tell the same in a trace file. Some other similar prints too. Please consider removing them.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/plugin.cc
> +    sql_print_error("Mail Plugin: ERROR initilizing CURL");
Please use `LogPluginErr`

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +  std::vector<std::string> lines;
I have two issues with this class/how it is used:

(1) it's misleading, this vector doesn't store lines - for example, the entire message body is in one entry of this vector
(2) most of the time, it underuses the buffer in the payload functions, and in some cause it could cause an overflow

It looks like you copied this from the basic curl smtp example (which also has an author and a copyright message), with the simple difference that there lines were really short lines.

I don't think  `READFUNCTION` is needed for this plugin at all - you could simply build a stringstream, and then pass the data as `stream.str().c_str()` to curl, it should be able to handle it.

And at that point, this code won't be the same as the curl example anymore.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +#define UDF_MAIL_SEND_EOM "UDF_MAIL_SEND_EOM"
I don't see the need for this define. With the suggested stringstream change, it won't be needed at all - but even with the current code, you could check `lines_read` against the size of the vector.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +#define UDF_MAIL_SEND_OK "Mail sent"
Please change this to a static constant.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/include/udf_descriptor.h
> +struct udf_descriptor {
This (and later related parts) seems to be copy-pasted from some other (group replication?) plugin, and are present in the data masking pull request too. 

This is bad for multiple reasons:
* duplicating a few hundred lines of code isn't a good idea
* Oracle isn't mentioned as author in any of the plugins
* for this plugin, this complex infrastructure isn't needed at all: registering a single UDF function would only take a few lines, in one file

So in this case, I think writing a simple init functions which register the UDF function without these additional utilities will be easier.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +  if (initid->ptr) free(initid->ptr);
When is this pointer set?

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +static size_t _prepare_message(char *ptr, size_t size, size_t nitems,
This function isn't necessary. (see other comment about using a stringstream & copying an example with copyright)

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +    memcpy(ptr, data, len);
This is where currently a buffer overflow is possible: for a long email, `len > size * nitems` is possible.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +    if (strlen(cc) > 0) recipients = curl_slist_append(recipients, cc);
And if it's empty?

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +  initid->maybe_null = 1;
I don't see when this function returns a NULL?

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_mail_send.cc
> +  strcpy(result, res.c_str());
Please use `srtncpy`, there is a possible buffer overflow here.

2019-08-21 13:09 UTC, dutow commented on plugin/mail_udf/src/udf_registration.cc
> +/* Copyright (c) 2019 Francisco Miguel Biete Banon. All rights reserved.
This file looks mostly the same as the one in the GR plugin? If you do keep it, please don't include it under your own copyright and mention Oracle as an author. If you simplify the UDF initialization, it isn't needed.

2019-09-07 13:29 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +    char buffer[80];
Changed

2019-09-07 13:29 UTC, fmbiete commented on plugin/mail_udf/src/plugin.cc
> +//#define mysql_declare_plugin_end   ,{0,0,0,0,0,0,0,0,0,0,0,0,0,0}} <- 14 v8.0
Removed

2019-09-07 13:29 UTC, fmbiete commented on plugin/mail_udf/CMakeLists.txt
> +  message(STATUS "Plugin Mail UDF won't be compiled: curl package is missing")
Changed

2019-09-07 13:30 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +    struct curl_slist *recipients = nullptr;
Changed

2019-09-07 13:32 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +    if (strlen(cc) > 0) recipients = curl_slist_append(recipients, cc);
Fixed.

2019-09-07 13:35 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +  initid->maybe_null = 1;
Changed.

2019-09-07 13:35 UTC, fmbiete commented on plugin/mail_udf/src/udf_registration.cc
> +/* Copyright (c) 2019 Francisco Miguel Biete Banon. All rights reserved.
Added Oracle.

2019-09-07 13:37 UTC, fmbiete commented on plugin/mail_udf/CMakeLists.txt
> +INCLUDE(CheckLibraryExists)
Removed

2019-09-07 13:38 UTC, fmbiete commented on plugin/mail_udf/README.md
> +### MySQL v5.7 or superior
Changed

2019-09-07 13:45 UTC, fmbiete commented on plugin/mail_udf/src/plugin.cc
> +  sql_print_information("Mail Plugin: Initializing Mail plugin structures");
Removed

2019-09-07 13:46 UTC, fmbiete commented on plugin/mail_udf/src/plugin.cc
> +    sql_print_error("Mail Plugin: ERROR initilizing CURL");
Changed

2019-09-07 14:05 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +  std::vector<std::string> lines;
Changed to use stringstream.
But we need to use READFUNCTION. READDATA is a pointer to the argument passed to READFUNCTION (if it's used) or a FILE pointer (if READFUNCTION is not specified). We cannot put the message text as it is.

2019-09-07 14:09 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +#define UDF_MAIL_SEND_OK "Mail sent"
Changed

2019-09-07 14:09 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +#define UDF_MAIL_SEND_EOM "UDF_MAIL_SEND_EOM"
Removed

2019-09-07 14:13 UTC, fmbiete commented on plugin/mail_udf/include/udf_descriptor.h
> +struct udf_descriptor {
Added Oracle copyright

2019-09-07 14:15 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +  if (initid->ptr) free(initid->ptr);
Removed

2019-09-07 14:15 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +static size_t _prepare_message(char *ptr, size_t size, size_t nitems,
We need it

2019-09-07 16:02 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +      curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
Added a flag to disable/or not certificate verification.

2019-09-07 16:20 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +    if (strncmp(smtp_uri, "smtps", 5) == 0) {
Added validation for smtp uri

2019-09-07 16:21 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +  std::string res = _mail_send(args->args[0], args->args[1], args->args[2],
It's already using const

2019-09-07 16:29 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +    msg.lines.push_back(std::string("From: ").append(from).append("\r\n"));
Fixed; validating that header parameters don't contain line breaks. But they can contain anything else.

2019-09-07 16:30 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +    memcpy(ptr, data, len);
Fixed

2019-09-07 16:40 UTC, fmbiete commented on plugin/mail_udf/src/udf_mail_send.cc
> +  strcpy(result, res.c_str());
Fixed

2019-09-07 16:41 UTC, fmbiete commented on plugin/mail_udf/include/plugin.h
> +#endif  //_PLUGIN_MAIL_PLUGIN_H
// is also valid and used across MySQL code. In some parts the old C format makes sense, in other I don't think so.

2022-07-19 12:08 UTC, dutow commented
Hello!

We decided not to include these patches in Percona Server for MySQL because of security considerations.

2022-07-19 12:08 UTC, closed without merging