PS-5642 - page tracker thread won't exist if startup fails
percona/percona-server pull request #3379
Opened 2019-08-20 13:54 UTC by altmannmarcelo

If page tracker is enabled and innodb fail to start,
shutdown process won't signal page tracker thread to exit.

This fix ensure those threads will be proper signaled and exit.

2019-08-20 13:54 UTC, altmannmarcelo commented
https://ps56.cd.percona.com/job/percona-server-5.6-param/39/

2019-08-20 17:07 UTC, altmannmarcelo commented
https://ps56.cd.percona.com/job/percona-server-5.6-param/40/

2019-08-21 04:17 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_changed_page_bmp_shutdown_thread.test
> +--echo # Asserting that the server aborted.
Same comment as for the 8.0 PR

2019-08-27 13:29 UTC, altmannmarcelo commented
ready for next review

2019-09-04 06:34 UTC, dutow requested changes
For PRs with multiple (5.6, 5.7, ...) versions, please also include the version in the PR title.

2019-09-04 06:34 UTC, dutow commented on mysql-test/suite/innodb/t/percona_changed_page_bmp_shutdown_thread.test
> +--source include/have_debug.inc
Also `--source include/not_embedded.in`

2019-09-10 11:21 UTC, altmannmarcelo commented
@dutow Ready for next review

2019-09-11 10:36 UTC, dutow approved these changes

2019-10-01 13:34 UTC, altmannmarcelo commented
There was a small typo in ``` Also --source include/not_embedded.in``` it should be ```--source include/not_embedded.inc```

2019-11-05 17:15 UTC, merged