Ps 5.7 5642
percona/percona-server pull request #3381
Opened 2019-08-20 18:49 UTC by altmannmarcelo

If page tracker is enabled and innodb fail to start,
shutdown process won't signal page tracker thread to exit.

This fix ensure those threads will be proper signaled and exit.

2019-08-20 18:49 UTC, altmannmarcelo commented
https://ps57.cd.percona.com/job/percona-server-5.7-param/145/

2019-08-21 04:13 UTC, laurynas-biveinis commented on mysql-test/suite/innodb/t/percona_changed_page_bmp_shutdown_thread.test
> +--echo # Asserting that the server aborted.
Same comment as for the 8.0 PR

2019-08-27 13:29 UTC, altmannmarcelo commented
ready for next review

2019-09-05 06:37 UTC, dutow requested changes
Same comments as for the 5.6 version

2019-10-01 13:37 UTC, altmannmarcelo commented
@dutow ready for next review.

2019-10-01 16:21 UTC, altmannmarcelo commented
@dutow ready for next review

2019-10-10 08:00 UTC, dutow commented on storage/innobase/srv/srv0start.cc
> +			if (srv_redo_log_thread_started) {
Is 5.7 affected then? If yes, the jira ticket should also be updated.

2019-10-10 20:12 UTC, altmannmarcelo commented
@dutow fixed. Added 5.6 and 5.7 as affected.

2019-10-11 06:16 UTC, dutow approved these changes
5.6 isn't affected, you only ported the testcase there. Other than that looks good.

2019-11-05 17:17 UTC, merged