ps-8.0-5922
percona/percona-server pull request #3397
Opened 2019-08-27 17:12 UTC by patrickbirch

Added utility-user to index
Updated 5.7 utility-user doc with 8.0.17-8 version info.
Added limitation

2019-08-28 06:13 UTC, dutow requested changes
Please also fix these for earlier versions.

2019-08-28 06:13 UTC, dutow commented on doc/source/management/utility_user.rst
> +  * Utility user will increase the result in the `SHOW STATUS LIKE '%Connections'` statement.
It's either "results" or you could specify that it's about `Threads_connected` and `Threads_created`. And also the `Connections` counter.

2019-08-28 06:13 UTC, dutow commented on doc/source/management/utility_user.rst
> +  * Utility user will not appear in :table:`USER_STATISTICS`, :table:`CLIENT_STATISTICS` or :table:`THREAD_STATISTICS` tables.
Or in any performance_schema tables.

2019-08-28 06:13 UTC, dutow commented on doc/source/management/utility_user.rst
> + Example: :option:`--utility_user_schema_access` =schema1,schema2,schema3 ;
The ; is a typo?

2019-08-28 06:13 UTC, dutow commented on doc/source/management/utility_user.rst
> + Example: :option:`--utility-user-privileges` ="CREATE, DROP, LOCK TABLES"
Spaces aren't supported between arguments - this should be `CREATE_DROP,LOCK TABLES`

2019-08-28 06:13 UTC, dutow commented on doc/source/management/utility_user.rst
> +This variable can be used to specify a comma-separated list of extra access privileges to grant to the utility user. Supported values for the privileges list are: ``SELECT, INSERT, UPDATE, DELETE, CR
Missing space between PROCESS and FILE, and LOCK TABLES and EXECUTE

2019-08-28 06:15 UTC, dutow commented
"Updated 5.7 utility-user doc with 8.0.17-8 version info." - I don't see a PR for 5.7 (and 5.6)?

2019-08-28 13:05 UTC, patrickbirch commented on doc/source/management/utility_user.rst
> +  * Utility user will increase the result in the `SHOW STATUS LIKE '%Connections'` statement.
In the 5.6 version, rewrote the sentence.

2019-08-28 13:05 UTC, patrickbirch commented on doc/source/management/utility_user.rst
> +  * Utility user will not appear in :table:`USER_STATISTICS`, :table:`CLIENT_STATISTICS` or :table:`THREAD_STATISTICS` tables.
added in the 5.6 version.

2019-08-28 13:06 UTC, patrickbirch commented on doc/source/management/utility_user.rst
> + Example: :option:`--utility_user_schema_access` =schema1,schema2,schema3 ;
Should I remove the ";" or delete the space between schema3 ;?

2019-08-28 13:06 UTC, patrickbirch commented on doc/source/management/utility_user.rst
> + Example: :option:`--utility-user-privileges` ="CREATE, DROP, LOCK TABLES"
fixed in 5.6 version

2019-08-28 13:06 UTC, patrickbirch commented on doc/source/management/utility_user.rst
> +This variable can be used to specify a comma-separated list of extra access privileges to grant to the utility user. Supported values for the privileges list are: ``SELECT, INSERT, UPDATE, DELETE, CR
fixed in 5.6 version

2019-08-28 13:07 UTC, patrickbirch commented
Created https://github.com/percona/percona-server/pull/3398 for the 5.6 version.

2019-08-29 15:40 UTC, dutow commented on doc/source/management/utility_user.rst
> + Example: :option:`--utility_user_schema_access` =schema1,schema2,schema3 ;
Remove.

2019-08-30 06:52 UTC, dutow approved these changes

2019-08-30 11:44 UTC, merged