Ps 8.0 5427 document the correct distribution upgrade process for percona server
percona/percona-server pull request #3418
Opened 2019-09-06 21:49 UTC by patrickbirch

2019-09-11 10:46 UTC, dutow commented
The 8.0 docs needs no change? The jira ticket mentions that 8.0 is affected.

2019-09-11 14:09 UTC, patrickbirch commented
Updated with changes to 8.0. Thank you.

2019-09-12 08:14 UTC, dutow commented
This is a different change than the 5.6 and 5.7 PRs, and I don't see that part in the 8.0 docs. Is this really the same issue?

2019-09-12 09:18 UTC, hrvojem requested changes
This change doesn't look to be related to distribution upgrade docs

2019-09-12 09:18 UTC, hrvojem commented on doc/source/.res/replace.txt
> +.. |debian-tenth| replace:: Debian 10.0 (buster)
if we're already changing this should we change last -> ninth?

2019-09-12 13:05 UTC, patrickbirch commented on doc/source/.res/replace.txt
> +.. |debian-tenth| replace:: Debian 10.0 (buster)
Sure.

2019-09-12 14:17 UTC, patrickbirch commented
duplicate pull request - closing

2019-09-12 14:17 UTC, closed without merging