PS-3411: Prevent creation of xb_doublewrite file when innodb_doublewrite is disabled (5.7)
percona/percona-server pull request #3430
Opened 2019-09-16 20:02 UTC by kamil-holubicki

https://jira.percona.com/browse/PS-3411

Unnecessary xb_doublewrite file is no more created when innodb_doublewrite option is disabled.

2019-09-16 20:02 UTC, kamil-holubicki commented
https://ps57.cd.percona.com/job/percona-server-5.7-param/163/

2019-09-17 07:33 UTC, dutow requested changes

2019-09-17 07:33 UTC, dutow commented on mysql-test/suite/innodb/t/percona_doublewrite.test
> +DROP TABLE IF EXISTS t1;
Code like this is present in some old tests, but it's not used anymore: if it exists, drop it (without if exists, without disabling warnings), if it doesn't, delete this block.

2019-09-17 07:33 UTC, dutow commented on mysql-test/suite/innodb/t/percona_doublewrite.test
> +--real_sleep 3
Sleep (even real_sleep) can be unreliable on jenkins. It's better to use wait_condition / debug sync points, depending on what's the easiest to do for a given situation. For page flushes, you probably want somethning like

```
# wait until pages flushed
--let $wait_condition= SELECT variable_value = 0 FROM performance_schema.global_status WHERE LOWER(variable_name) = 'innodb_buffer_pool_pages_dirty'
--source include/wait_condition.inc
```

2019-09-17 07:34 UTC, dutow commented on mysql-test/suite/innodb/t/percona_doublewrite.test
> +SELECT * FROM t1 LIMIT 10;
Either remove this select (is it really part of the test?), or add an order by

2019-09-19 14:39 UTC, dutow approved these changes

2019-09-23 18:18 UTC, merged