PS-5921 - Detect memory leaks on stage of bootstrap if PS was built w…
percona/percona-server pull request #3456
Opened 2019-10-08 20:40 UTC by altmannmarcelo

…ith '-DWITH_ASAN'

Problem:
As part of boostrap process, DDSE_dict_init reads proprieties from
the first table in the data dictionary to decide whatever or not
the next tables will be created with encryption. The object that
stores the proprieties of the first table is never destroyed.

Solution:
Call delete on dd::Properties *p object.

2019-10-08 20:43 UTC, altmannmarcelo commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/355/ - Jenkins tests are failing with:

```
. . . 
Removing old var directory
Creating var directory '/tmp/results/PS/mysql-test/var'
Installing system database
Using parallel: 1

==============================================================================
                  TEST NAME                       RESULT  TIME (ms) COMMENT
------------------------------------------------------------------------------
worker[1] 191008 21:31:29 mysql-test-run: WARNING: Process [mysqld.1 - pid: 109, winpid: 109, exit: 10752] died after mysql-test-run waited 0.2 seconds for /tmp/results/PS/mysql-test/var/run/mysqld.1.pid to be created.
191008 18:31:29 [ 50%] main.thread_cache_size                    [ fail ]
        Test ended at 2019-10-08 18:31:29

Server log is:
ERROR: ld.so: object '/usr/lib64/libasan.so.5
/usr/lib64/libasan.so.5' from LD_PRELOAD cannot be preloaded: ignored.
==110==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
safe_process[109]: Child process: 110, exit: 42
``` 

Running manually on my machine works:
```
bash-4.2$ ./mysql-test/mtr --big-test --debug-server --sanitize main.thread_cache_size
Logging: /tmp/ps/mysql-test/mysql-test-run.pl  --big-test --debug-server --sanitize main.thread_cache_size
MySQL Version 8.0.16
Checking supported features
 - Binaries are debug compiled
Using 'all' suites
Collecting tests
Removing old var directory
Creating var directory '/tmp/ps/bld/mysql-test/var'
Installing system database
Using parallel: 1

==============================================================================
                  TEST NAME                       RESULT  TIME (ms) COMMENT
------------------------------------------------------------------------------
[ 50%] main.thread_cache_size                    [ pass ]    163
[100%] sanitize_report                           [ pass ]
------------------------------------------------------------------------------
The servers were restarted 0 times
The servers were reinitialized 0 times
Spent 0.163 of 29 seconds executing testcases

Completed: All 2 tests were successful.
```

2019-10-10 07:52 UTC, dutow requested changes

2019-10-10 07:52 UTC, dutow commented on sql/dd/impl/bootstrap/bootstrapper.cc
> +  delete p;
A better (safer) fix would be to change the type of p to `std::unique_ptr<dd::Properties>` - grep for other uses of parse_properties for examples.

2019-10-15 11:28 UTC, altmannmarcelo commented
Closing since 8.0.17 has @percona-ysorokin 's fix https://github.com/percona-ysorokin/percona-server/commit/9752e38f3089f819a35a616785a518227f397721

2019-10-15 11:28 UTC, closed without merging