PS-5181: Assertion when executing multi table DROP
percona/percona-server pull request #3466
Opened 2019-10-17 09:25 UTC by kamil-holubicki

https://jira.percona.com/browse/PS-5181

This is handling of corner case when:
1. gtid_next is set to GTID value
2. DROP statement with temporary and non-temporary tables is executed
3. row-based logging is enabled

Theoretically such transaction should not be logged by master. It would be split into 2 separate transactions (SBR) or drop of temporary table would be skipped from logging, resulting in single table DROP for non-temporary table (RBR)

However there are still at least 2 cases when it can happen:

1. Simulate replicated transaction by invoking DROP with 2 such tables directly on slave.
2. Create t1, t2 as non-temporary tables on master, then replicate to slave. Next drop t1, t2 from slave and create t1, t2 on slave only using stored procedure. This scenario is strange, however rpl_gtid_split_statements.test performs such scenario.

If slave uses RBL, dropping of temporary table will not be logged, so single table drop of non-temporary table will go to slave's binlog.
If slave uses SBL, case 1 above will issue the error (2 tables would be logged to binlog, but as separate transactions using the same GTID, which is not allowed).
If slave uses SBL, case 2 will still work, as temporary tables created by stored procedures are not logged even if SBL is used.

2019-10-17 09:26 UTC, kamil-holubicki commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/366/

2019-11-05 09:49 UTC, kamil-holubicki commented
Hi @percona-ysorokin , @dutow .
Could you please review?

2019-11-05 12:47 UTC, dutow requested changes
Only two minor test related comments.

2019-11-05 12:47 UTC, dutow commented on mysql-test/suite/rpl/t/rpl_split_statements_bug_ps5181-master.opt
> +--gtid_mode=ON --enforce_gtid_consistency=ON
Place the testcase in the rpl_gtid suite, these are defaults there.

2019-11-05 12:47 UTC, dutow commented on mysql-test/suite/rpl/t/rpl_split_statements_bug_ps5181.test
> +CREATE TABLE t1 (a int) engine = MyISAM;
8.0 doesn't always has myisam, include have_myisam.inc

2019-11-07 21:08 UTC, kamil-holubicki commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/412/

2019-11-08 09:16 UTC, merged