PS-6783 [Doc] Release Notes
percona/percona-server pull request #3619
Opened 2020-01-17 13:39 UTC by patrickbirch

fix to remove internal task only jira tickets from the release notes
added 5.6.47-87.0 
added 5.6.47-87.0 to index
 Changes to be committed:
	modified:   source/release-notes/Percona-Server-5.6.40-84.0.rst
	modified:   source/release-notes/Percona-Server-5.6.44-85.0.rst
	modified:   source/release-notes/Percona-Server-5.6.45-86.1.rst
	new file:   source/release-notes/Percona-Server-5.6.47-87.0.rst
	modified:   source/release-notes/release-notes_index.rst

2020-01-17 14:01 UTC, hrvojem requested changes

2020-01-17 14:01 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +all the bug fixes in it. Percona Server for MySQL 5.6.47-88 is now the current
version is `87.0`

2020-01-17 14:01 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +Find the release notes for Percona Server for MySQL 5.6.47-88 in
s/88/87.0/

2020-01-17 14:05 UTC, patrickbirch commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +all the bug fixes in it. Percona Server for MySQL 5.6.47-88 is now the current
Fixed.

2020-01-17 14:05 UTC, patrickbirch commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +Find the release notes for Percona Server for MySQL 5.6.47-88 in
fixed.

2020-01-20 14:48 UTC, kamil-holubicki approved these changes

2020-01-21 14:43 UTC, george-lorch approved these changes

2020-01-21 14:43 UTC, george-lorch commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +* :psbug:`4842`: Documentation -  innodb_corrupt_table_action does not list a default value
nit, extra space after '-'

2020-01-21 14:43 UTC, george-lorch commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +* :psbug:`1469`: The Memory storage engine detects an incorrect  "is full"  condition stuck when the space contained reusable memory chunks and the space could be reused.
nit, extra spaces around "is full"

2020-01-21 14:43 UTC, george-lorch commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +* :psbug:`5591`: mysql server crash after empty set sql query  (Upstream :mysqlbug:`95236`)
nit, extra space after "sql query"

2020-01-21 14:43 UTC, george-lorch commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +* :psbug:`5813`: Setting 'none' value for slow_query_log_use_global_control  throws error.
nit, extra space after "slow_query_log_use_global_control"

2020-01-21 15:27 UTC, patrickbirch commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +* :psbug:`1469`: The Memory storage engine detects an incorrect  "is full"  condition stuck when the space contained reusable memory chunks and the space could be reused.
Fixed.

2020-01-21 15:28 UTC, patrickbirch commented on doc/source/release-notes/Percona-Server-5.6.47-87.0.rst
> +* :psbug:`4842`: Documentation -  innodb_corrupt_table_action does not list a default value
fixed

2020-01-21 15:47 UTC, merged