PS-6885 Documented the new variable rocksdb_rollback_on_timeout which…
percona/percona-server pull request #3678
Opened 2020-02-28 21:35 UTC by patrickbirch

… allows the rollback of an entire transaction on timeout.

modified file: myrocks/variables
added rocksdb_rollback_on_timeout information and description

2020-03-02 09:51 UTC, inikep requested changes
`rocksdb_rollback_on_timeout` is dynamic

2020-03-05 12:37 UTC, patrickbirch commented
changed the dynamic to YES.

2020-03-05 12:43 UTC, inikep approved these changes

2020-03-05 12:44 UTC, inikep commented
LGTM

2020-03-06 12:46 UTC, merged