Documented the new variable blind_delete_primary_key
percona/percona-server pull request #3681
Opened 2020-03-05 16:33 UTC by patrickbirch

modified myrocks/variable
added myrocks_blind_delete_primary_key and description

2020-03-05 17:25 UTC, inikep requested changes
Scope is `Global, Session`

2020-03-05 18:10 UTC, patrickbirch commented
updated to Global, Session

2020-03-06 09:46 UTC, inikep requested changes

2020-03-06 09:46 UTC, inikep commented on doc/source/myrocks/variables.rst
> +     - Global
Global, Session

2020-03-06 12:22 UTC, patrickbirch commented on doc/source/myrocks/variables.rst
> +     - Global
Missed that. Fixed.

2020-03-06 12:28 UTC, inikep approved these changes

2020-03-06 12:28 UTC, inikep commented
LGTM

2020-03-10 12:49 UTC, merged