PS-5666: 100% CPU with innodb_encrypt_threads=1
percona/percona-server pull request #3852
Opened 2020-06-02 15:40 UTC by robgolebiowski

The issue was that when encryption threads did not find any space to
rotated they kept setting - in order to notify other threads that
there might be some work to do. That caused infinitive loop. The fix
is to not set when a thread did not find any space to rotated.

Apart from running test from ticket PS-5666 I have run encryption test
suite, with and without the fix and I have measured the times:

Without fix:
real    13m48,692s
user    34m39,848s
sys     2m30,826s

With fix:
real    13m57,575s
user    20m34,633s
sys     1m55,404s

2020-06-02 15:40 UTC, robgolebiowski commented
JR => https://ps80.cd.percona.com/job/percona-server-8.0-param/595 (the failure of test encryption.innodb_default_key is being addressed as PS-7101

2020-06-03 13:44 UTC, satya-bodapati requested changes
Can you change "kept setting" to a more meaningful word? May be "they keep signalling the crypt_threads_event, which in turn caused other threads to..."

review in progress...

@satya-bodapati done. I have also checked if there is increase in CPU usage when innodb-encryption-rotate-key-age > 0. There isn't.

2020-06-12 09:18 UTC, satya-bodapati approved these changes
LGTM! Merge after addressing align comment

2020-06-12 09:18 UTC, satya-bodapati commented on storage/innobase/fil/fil0crypt.cc
> +                                                might be some work to do. */
Please try to align

2020-07-20 07:21 UTC, merged