PS-4692 Add paragraph for how to manually install/uninstall MyRocks
percona/percona-server pull request #3868
Opened 2020-06-09 13:54 UTC by patrickbirch

modified install
added install plugin and uninstall plugin information

2020-06-09 15:41 UTC, george-lorch approved these changes

2020-06-10 10:58 UTC, kathy-williamson requested changes
Please correct spelling in  UNNSTALL PLUGIN ROCKSDB_GLOBAL_INFO; (missing an I)

2020-06-10 12:00 UTC, inikep approved these changes

2020-06-10 12:24 UTC, patrickbirch commented
Fixed.

2020-06-19 13:39 UTC, kathy-williamson approved these changes

2020-06-19 13:40 UTC, merged