PS-7090 Update documentation to reflect 8.0.20 parallel doublewrite c…
percona/percona-server pull request #3895
Opened 2020-06-24 19:23 UTC by patrickbirch

…hanges

Modified changed_in_version
Modified performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
Modified scalability/innodb_io.rst
Modified security/encrypting-doublewrite-buffers.rst

2020-06-24 20:02 UTC, kathy-williamson approved these changes

2020-06-25 17:28 UTC, george-lorch approved these changes

2020-07-06 17:06 UTC, percona-ysorokin requested changes

2020-07-06 17:06 UTC, percona-ysorokin commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +As of |Percona Server| 8.0.20-11, this variable is considered **deprecated** and is no longer configurable. You should use `innodb_doublewrite_dir <https://dev.mysql.com/doc/refman/8.0/en/innodb-para
```suggestion
As of |Percona Server| 8.0.20-11, this variable is considered **deprecated** and has no effect. You should use `innodb_doublewrite_dir <https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_doublewrite_dir>`_.

2020-07-06 17:06 UTC, percona-ysorokin commented on doc/source/scalability/innodb_io.rst
>         call to flush doublewrite files.
This table is no longer accurate and should be completely removed.

The statement above with `affects doublewrite buffers exactly the same as in |MySQL| 8.0.20` should suffice.

2020-07-07 12:22 UTC, patrickbirch commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +As of |Percona Server| 8.0.20-11, this variable is considered **deprecated** and is no longer configurable. You should use `innodb_doublewrite_dir <https://dev.mysql.com/doc/refman/8.0/en/innodb-para
Updated.

2020-07-07 12:23 UTC, patrickbirch commented on doc/source/scalability/innodb_io.rst
>         call to flush doublewrite files.
Removed table

2020-07-07 14:21 UTC, percona-ysorokin approved these changes
LGTM

2020-07-07 20:53 UTC, merged