PS-7226: Post-merge fixes for the LDAP plugin
percona/percona-server pull request #3990
Opened 2020-08-17 09:19 UTC by dutow

* Improved logging
* Added TLS testcase
* Modified MTR tests to use environment variables
* Removed some dead code
* authentication_ldap_simple_bind_root_pwd value no longer shown
* Code improvements to conform to the c++/mysql coding conventions

2020-09-07 11:50 UTC, dutow commented
Rebased to 8.0.21

2020-09-16 10:10 UTC, percona-ysorokin requested changes

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/src/plugin_simple.cc
> +  fprintf(stderr, "XXXXXXX: %s\n", value);
Is this intentional or just a debug print?

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/src/plugin_simple.cc
> +  //*(char *)var_ptr = *(char *)const_cast<void *>(value);
commented out code

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_simple.result
> +connect(localhost,zoidberg,zoidberg,test,13000,/home/dutow/workspace/topics/ldap-fixup/80-local/mysql-test/var/tmp/mysqld.1.sock);
Non-masked local paths in a MTR `.result` file.

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_simple.result
> +SET GLOBAL authentication_ldap_simple_server_host = '127.0.0.1';;
Probably `127.0.0.1` should be masked as well as it depends on `$MTR_LDAP_HOST` env variable.
Double semicolon;

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_simple.result
> +SET GLOBAL authentication_ldap_simple_server_port = 389;;
Probably `389` should be masked as well as it depends on `$MTR_LDAP_PORT` env variable.
Double semicolon.

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_simple.result
> +connect(localhost,zoidberg,zoidberg,test,13000,/home/dutow/workspace/topics/ldap-fixup/80-local/mysql-test/var/tmp/mysqld.1.sock);
Non-masked local paths in a MTR .result file.

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_simple.result
> +authentication_ldap_simple_server_host	127.0.0.1
Should be masked as well

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_simple.test
> +--eval SET GLOBAL authentication_ldap_simple_server_host = '$MTR_LDAP_HOST'
Add `--replace-result $MTR_LDAP_HOST <MTR_LDAP_HOST>`
and 
`--replace-result $MTR_LDAP_PORT <MTR_LDAP_PORT>`
here

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_simple.test
> +--eval SET GLOBAL authentication_ldap_simple_server_host = '$MTR_LDAP_HOST';
Likewise

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_simple.test
> +--eval SET GLOBAL authentication_ldap_simple_server_port = $MTR_LDAP_PORT;
Likewise

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_tls.test
> +--eval SET GLOBAL authentication_ldap_simple_server_host = '$MTR_LDAP_HOST'
Add `--replace-result` here

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_tls.test
> +--eval SET GLOBAL authentication_ldap_simple_server_port = $MTR_LDAP_PORT
Add `--replace-result` here

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_tls.test
> +--eval SET GLOBAL authentication_ldap_simple_server_host = '$MTR_LDAP_HOST';
Add `--replace-result` here

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_tls.test
> +--eval SET GLOBAL authentication_ldap_simple_server_port = $MTR_LDAP_PORT;
$MTR_LDAP_PORT

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_tls.test
> +
Add `count_session.inc` / `wait_until_count_session.inc`

2020-09-16 10:10 UTC, percona-ysorokin commented on plugin/auth_ldap/tests/mtr/auth_ldap_tls.test
> +SET GLOBAL authentication_ldap_simple_server_port = 388;
May be
```suggestion
--replace_result ...
SET GLOBAL authentication_ldap_simple_server_port = $MTR_LDAP_HOST + 1;
```

2020-09-16 15:15 UTC, percona-ysorokin approved these changes
LGTM

2020-09-16 18:59 UTC, dutow commented
@percona-ysorokin I've added an ActiveDirectory test case

2020-09-17 11:15 UTC, percona-ysorokin approved these changes
ActiveDirectory test looks fine

2020-09-17 12:12 UTC, merged