PS-7215 Release Notes for 5.7.31-34 (5.7)
percona/percona-server pull request #3996
Opened 2020-08-20 15:57 UTC by patrickbirch

modified:   source/conf.py
	new file:   source/release-notes/Percona-Server-5.7.31-34.rst
	modified:   source/release-notes/release-notes_index.rst

2020-08-20 16:05 UTC, kathy-williamson approved these changes

2020-08-20 16:59 UTC, hrvojem requested changes

2020-08-20 16:59 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +
use :variable: tags to link to variable descriptions

2020-08-20 16:59 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +* :jirabug:`PS-7132`: Make default value of rocksdb_wal_recovery_mode compatible with InnoDB
use :variable: tags to link to variable description

2020-08-20 16:59 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +* :jirabug:`PS-7114`: Enhance crash artifacts (core dumps and stack traces) to provide additional information to the operator
should this be "Implemented Coredumper funcionality", with link to feature documentation/description.

2020-08-20 16:59 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +* :jirabug:`PS-5263`: Update handle_binlog_flush_or_sync_error() to set my_ok(thd) after thd->clear_error() to correct assert in THD::send_statement_status (Upstream :mysqlbug:`93770`)
this should be more user friendly description.

2020-08-20 16:59 UTC, hrvojem commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +* :jirabug:`PS-7075`: Provide binary tarball with shared libs and glibc suffix
link to changed/updated docs with more details about the changes.

2020-08-21 18:25 UTC, george-lorch approved these changes
Approved pending Hrvojes requests and my comment on PS-7203

2020-08-21 18:25 UTC, george-lorch commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +* :jirabug:`PS-7203`: Modify open_tables to skip the test triggered if the thread originating it is a SQL thread or any replication thread (in the case of Multi thread replication)
This makes no sense and does not even mention the audit log plugin/functionality.  Please have @altmannmarcelo or @kathy-williamson re-write this to make sense.

2020-08-21 19:30 UTC, patrickbirch commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +* :jirabug:`PS-7114`: Enhance crash artifacts (core dumps and stack traces) to provide additional information to the operator
Changed to "Added".

2020-08-21 19:33 UTC, altmannmarcelo commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +* :jirabug:`PS-7203`: Modify open_tables to skip the test triggered if the thread originating it is a SQL thread or any replication thread (in the case of Multi thread replication)
@georgelorchpercona don't know where the above description came from. This is a leak on audit plugin with slave thread and those words should be mentioned. I changed it back to original title.

2020-08-24 11:40 UTC, patrickbirch commented on doc/source/release-notes/Percona-Server-5.7.31-34.rst
> +* :jirabug:`PS-7203`: Modify open_tables to skip the test triggered if the thread originating it is a SQL thread or any replication thread (in the case of Multi thread replication)
Updated

2020-08-24 16:59 UTC, hrvojem approved these changes
LGTM

2020-08-24 17:03 UTC, merged