PS-7256 [Doc] Update Binary Tarball Description
percona/percona-server pull request #3997
Opened 2020-08-20 18:17 UTC by patrickbirch

modified:   source/installation.rst

2020-08-20 18:55 UTC, kathy-williamson approved these changes

2020-08-20 20:38 UTC, EvgeniyPatlan requested changes

2020-08-20 20:38 UTC, EvgeniyPatlan commented on doc/source/installation.rst
> +In |Percona Server| before 8.0.20-11, multiple tarballs are provided based on the *OpenSSL* library available in the distribution:
based on glibc not on openssl version

2020-08-20 20:59 UTC, patrickbirch commented on doc/source/installation.rst
> +In |Percona Server| before 8.0.20-11, multiple tarballs are provided based on the *OpenSSL* library available in the distribution:
Fixed. Thanks.

2020-08-21 04:24 UTC, EvgeniyPatlan commented on doc/source/installation.rst
> +In |Percona Server| before 8.0.20-11, multiple tarballs are provided based on the glibc version available in the distribution:
Sorry I was wrong I missed key word ‘before 8.0.20’ yes before 8.0.20 we provided tars based on OpenSSL version. Please revert this change back

2020-08-21 10:38 UTC, patrickbirch commented on doc/source/installation.rst
> +In |Percona Server| before 8.0.20-11, multiple tarballs are provided based on the glibc version available in the distribution:
No problem. Fixed.

2020-08-21 10:50 UTC, EvgeniyPatlan approved these changes

2020-09-04 12:31 UTC, merged