PS-7270: extra_port should not accept proxied connections
percona/percona-server pull request #4007
Opened 2020-08-27 11:44 UTC by impimp

2020-08-27 12:59 UTC, altmannmarcelo commented
https://ps57.cd.percona.com/job/percona-server-5.7-param/334/

2020-08-31 12:57 UTC, percona-ysorokin requested changes

2020-08-31 12:57 UTC, percona-ysorokin commented on mysql-test/t/proxy_protocol_extra_port.test
> +SELECT @@proxy_protocol_networks;
Change this to `assert.inc`

2020-08-31 12:57 UTC, percona-ysorokin commented on mysql-test/t/proxy_protocol_extra_port.test
> +--disable_query_log
Either remove this completely or add corresponding `--enable_query_log`

2020-09-01 13:15 UTC, altmannmarcelo commented
@percona-ysorokin  https://ps57.cd.percona.com/job/percona-server-5.7-param/335/ 
`proxy_protocol_admin_port` test is passing on all platforms.

2020-09-01 13:54 UTC, percona-ysorokin approved these changes
LGTM

2020-09-01 14:31 UTC, merged