PS-7270: extra_port should not accept proxied connections - 8.0
percona/percona-server pull request #4008
Opened 2020-08-27 11:44 UTC by impimp

2020-08-27 12:59 UTC, altmannmarcelo commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/750/

2020-08-31 13:02 UTC, percona-ysorokin requested changes

2020-08-31 13:02 UTC, percona-ysorokin commented on mysql-test/t/proxy_protocol_admin_port.test
> +--disable_query_log
Either remove this or add corresponding `--disable_query_log` afterwards

2020-08-31 13:02 UTC, percona-ysorokin commented on mysql-test/t/proxy_protocol_admin_port.test
> +--source include/remove_extra_root_users.inc
move this after
```
--disconnect conn1
--connection default
```
to make sure we are on `default` connection

2020-09-01 13:55 UTC, percona-ysorokin approved these changes
LGTM

2020-09-01 14:31 UTC, altmannmarcelo commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/761/ - `proxy_protocol_admin_port` test is passing on all platforms.

2020-09-01 14:32 UTC, merged