PS-7289: Limit innodb_encryption_threads to 255
percona/percona-server pull request #4025
Opened 2020-09-14 08:09 UTC by oleksandr-kachan

Server crashes in case innodb_encryption_threads
is set to too big value. Limiting the max allowed
value to 255.

2020-09-14 18:46 UTC, oleksandr-kachan commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/776/

2020-09-15 08:16 UTC, satya-bodapati requested changes

2020-09-15 08:16 UTC, satya-bodapati commented on storage/innobase/handler/ha_innodb.cc
> +    innodb_encryption_threads_validate, innodb_encryption_threads_update, 0, 0,
why did you remove srv_n_fil_crypt_threads_requested?

2020-09-15 10:47 UTC, satya-bodapati commented on storage/innobase/handler/ha_innodb.cc
> +    innodb_encryption_threads_validate, innodb_encryption_threads_update, 0, 0,
Hmm, the variable is assigned to 0, so the default is 0. OK to use explicit value.

2020-09-15 10:56 UTC, satya-bodapati approved these changes

2020-09-15 12:52 UTC, merged