PS-7289: Fix min/max value check for innodb_encryption_threads
percona/percona-server pull request #4057
Opened 2020-09-28 13:26 UTC by oleksandr-kachan

The min and max variable value provided with variable definition
don't take effect in case there is a custom validator for a variable.
Added min and max allowed value check into custom validator
for innodb_encryption_threads variable.

(cherry picked from commit dc73cfb8f04825d539851c00cf850d06aa10c987)

2020-09-29 08:00 UTC, oleksandr-kachan commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/786/

2020-09-30 07:10 UTC, satya-bodapati requested changes
Why cherrypick? is it because 8.0.21 release branch not created? Is it possible to regular merge from 5.7 now?

2020-09-30 08:39 UTC, oleksandr-kachan commented
> Why cherrypick?
The change to 5.7 was done on top of the first commit done in scope of this task. So it is ahead of last GCA point now. Not sure if it is Ok to do merge to 8.0 in this case (at least there will be some additional conflicts).

2020-09-30 11:57 UTC, georgelorchpercona commented
> > Why cherrypick?
> 
> The change to 5.7 was done on top of the first commit done in scope of this task. So it is ahead of last GCA point now. Not sure if it is Ok to do merge to 8.0 in this case (at least there will be some additional conflicts). Should I still do a merge in this case?

Yes, as discussed, since the 5.7 commit for this change is based upon a previous 5.7 change that occurs _after_ the 5.7 GCA point, it is needed that this commit be based on the 5.7 HEAD and cherry-picked forward to 8.0

2020-10-01 06:17 UTC, satya-bodapati commented
> > > Why cherrypick?
> > 
> > 
> > The change to 5.7 was done on top of the first commit done in scope of this task. So it is ahead of last GCA point now. Not sure if it is Ok to do merge to 8.0 in this case (at least there will be some additional conflicts). Should I still do a merge in this case?
> 
> Yes, as discussed, since the 5.7 commit for this change is based upon a previous 5.7 change that occurs _after_ the 5.7 GCA point, it is needed that this commit be based on the 5.7 HEAD and cherry-picked forward to 8.0

Thanks for the explanation @georgelorchpercona

2020-10-01 06:18 UTC, satya-bodapati approved these changes

2020-10-01 08:41 UTC, merged