PS-7367 Update OpenSSL versions in Installation (5.6)
percona/percona-server pull request #4079
Opened 2020-10-09 17:10 UTC by patrickbirch

modified source/installation.rst

2020-10-30 10:03 UTC, hrvojem requested changes

2020-10-30 10:03 UTC, hrvojem commented on doc/source/installation.rst
> +     - For all *Debian/Ubuntu* versions except *Debian Squeeze* (``libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f2e389a5000)``);
these distributions aren't supported anymore

2020-10-30 10:03 UTC, hrvojem commented on doc/source/installation.rst
> +     - For *Debian* 9 and *Ubuntu* versions starting from 14.04 (``libssl.so.1.1 => /usr/lib/libssl.so.1.1``);
Ubuntu 14.04 isn't supported anymore

2020-11-16 15:41 UTC, patrickbirch commented on doc/source/installation.rst
> +     - For *Debian* 9 and *Ubuntu* versions starting from 14.04 (``libssl.so.1.1 => /usr/lib/libssl.so.1.1``);
Removed platforms which has reached EOL.

2020-11-17 10:00 UTC, hrvojem approved these changes
LGTM

2020-11-23 19:24 UTC, merged