PS-7441 Document RocksDB variable "rocksdb_max_compaction_history" an…
percona/percona-server pull request #4137
Opened 2020-11-30 13:07 UTC by patrickbirch

…d deprecate "strict_collation_check"

modified:   source/myrocks/variables.rst

2021-01-22 10:23 UTC, inikep requested changes

2021-01-22 10:23 UTC, inikep commented on doc/source/myrocks/variables.rst
> +This variable is considered **deprecated** in version 8.0.21-12.
It will be deprecated from 8.0.23

2021-01-22 10:23 UTC, inikep commented on doc/source/myrocks/variables.rst
> +This variable is considered **deprecated** in version 8.0.21-12.
It will be deprecated from 8.0.23

2021-01-22 12:48 UTC, patrickbirch commented on doc/source/myrocks/variables.rst
> +This variable is considered **deprecated** in version 8.0.21-12.
fixed.

2021-01-22 12:48 UTC, patrickbirch commented on doc/source/myrocks/variables.rst
> +This variable is considered **deprecated** in version 8.0.21-12.
fixed.

2021-01-26 21:59 UTC, inikep approved these changes
LGTM

2021-05-12 12:18 UTC, merged