PS-4894: Virtual column support for MyRocks
percona/percona-server pull request #4151
Opened 2020-12-14 07:20 UTC by dutow

This commit adds indexed virtual commis support to MyRocks, along with
tests adapted from the innodb suite. Parts of the tests which relied on
features not supported by MyRocks (inplace alter, fulltext, spatial)
were removed, and parts that failed because of gap lock issues were
modifed.

2020-12-16 13:34 UTC, inikep requested changes

2020-12-16 13:34 UTC, inikep commented on mysql-test/suite/rocksdb/t/virtual_basic.test
> +CREATE TABLE `t1` ( `a` INT(11) DEFAULT NULL,   `b` INT(11) DEFAULT NULL,   `c` INT(11) GENERATED ALWAYS AS (a+b) VIRTUAL,   `x` INT(11) NOT NULL,   `h` VARCHAR(10) DEFAULT NULL,   PRIMARY KEY (`x`),
For whole file `INT(11)` should be replaced with `INT` as `INT(11)` causes
```
Warning	1681	Integer display width is deprecated and will be removed in a future release.
```

2020-12-16 13:34 UTC, inikep commented on mysql-test/suite/rocksdb/t/virtual_index.test
> +     col1 int(11) NOT NULL,
For whole file `INT(11)` should be replaced with `INT`.

2020-12-16 13:34 UTC, inikep commented on mysql-test/suite/rocksdb/t/virtual_index.test
> +--source include/have_innodb_max_16k.inc
Missing `--source include/have_rocksdb.inc`

2020-12-16 13:34 UTC, inikep commented on mysql-test/suite/rocksdb/t/virtual_index.test
> +		) ENGINE=INNODB;
I would suggest to change it to `rocksdb` or remove whole `if (0)` fragment.

2020-12-16 13:34 UTC, inikep commented on mysql-test/suite/rocksdb/t/virtual_index.test
> +		) ENGINE=INNODB
I would suggest to change it to `rocksdb` or remove whole `if (0)` fragment.

2020-12-17 14:03 UTC, inikep approved these changes
LGTM

2021-01-21 06:42 UTC, dutow commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/878/

2021-01-21 06:42 UTC, merged