PS-7633 Document parallel_dblwr_encrypt becoming a dummy system varia…
percona/percona-server pull request #4241
Opened 2021-04-08 13:19 UTC by patrickbirch

…ble (8.0)

 Changes to be committed:
	modified:   source/security/encrypting-doublewrite-buffers.rst

2021-04-14 18:49 UTC, percona-ysorokin requested changes

2021-04-14 18:49 UTC, percona-ysorokin commented on doc/source/security/encrypting-doublewrite-buffers.rst
> +doublewrite buffer is replaced with the `MySQL implementation <https://dev.mysql.com/doc/refman/8.0/en/innodb-doublewrite-buffer.html>`_.
@patrickbirch I would put the full summary here:
1. **Percona Server from the very first 8.0 release `Percona-Server-8.0.12-1.alpha` till `Percona-Server-8.0.19-10` inclusive**
Percona had its own implementation of parallel doublewrite buffer (at that moment could be enabled by setting `innodb_parallel_doublewrite_path`).
In case it was enabled, `innodb_parallel_dblwr_encrypt` was used to control whether parallel doublewrite pages should be encrypted or not.
In case it was disabled, doublewrite buffer pages were located in the system tablespace (`ibdata1`). System tablespace itself could be encrypted by setting `innodb_sys_tablespace_encrypt` which in turn caused doublewrite buffer pages to be encrypted as well.
2. **Percona Server from `Percona-Server-8.0.20-11` till `Percona-Server-8.0.22-13` inclusive**
In MySQL Server 8.0.20 Oracle implemented its own parallel doublewrite buffer which is stored in external files (`#ib_16384_xxx.dblwr`) and never in the system tablespace and therefore Percona's implementation was reverted.
As the result, `innodb_parallel_doublewrite_path` became a no-op variable.
However, Oracle did not implement parallel doublewrite buffer encryption at that moment, so Percona had to re-implement parallel doublewrite buffer encryption on top of the new parallel doublewrite buffer implementation from Oracle. Percona preserved the meaning and functionality of the `innodb_parallel_dblwr_encrypt` variable.
3. **Percona Server from `Percona-Server-8.0.23-14`**
In MySQL 8.0.23 Oracle implemented its own version of Parallel doublewrite encryption (https://dev.mysql.com/doc/refman/8.0/en/innodb-data-encryption.html#innodb-doublewrite-file-encryption).
Pages that belong to encrypted tablespaces are also written into doublewrite buffer in encrypted form.
Therefore Percona's implementation was reverted and `innodb_parallel_dblwr_encrypt` became a no-op variable.

2021-04-15 15:47 UTC, patrickbirch commented on doc/source/security/encrypting-doublewrite-buffers.rst
> +doublewrite buffer is replaced with the `MySQL implementation <https://dev.mysql.com/doc/refman/8.0/en/innodb-doublewrite-buffer.html>`_.
Rewritten.

2021-04-21 20:16 UTC, percona-ysorokin requested changes

2021-04-21 20:16 UTC, percona-ysorokin commented on doc/source/security/encrypting-doublewrite-buffers.rst
> +       doublewrite pages were encrypted or not. The doublewrite buffer pages were located in the system tablespace (ibdata1). The system tablespace itself could be encrypted by setting :variable:`inn
```suggestion
       doublewrite pages were encrypted or not. In case parallel doublewrite buffer was disabled (:variable:`innodb_parallel_doublewrite_path` was set to empty string), the doublewrite buffer pages were located in the system tablespace (ibdata1). The system tablespace itself could be encrypted by setting :variable:`innodb_sys_tablespace_encrypt`, which also encrypted the  doublewrite buffer pages.
```

2021-04-21 20:16 UTC, percona-ysorokin commented on doc/source/security/encrypting-doublewrite-buffers.rst
> +doublewrite buffer.
```suggestion
This variable used to control whether parallel doublewrite buffer pages were encrypted or not.
The encryption used the key of the tablespace to which the page belong.
Starting from |Percona Server| 8.0.23-14, regardless of the value of this variable, pages from encrypted tablespaces are always written to the doublewrite buffer as encrypted, whereas pages from unencrypted tablespaces are always written unencrypted.
```

2021-04-22 10:55 UTC, patrickbirch commented on doc/source/security/encrypting-doublewrite-buffers.rst
> +       doublewrite pages were encrypted or not. The doublewrite buffer pages were located in the system tablespace (ibdata1). The system tablespace itself could be encrypted by setting :variable:`inn
Updated.

2021-04-22 10:55 UTC, patrickbirch commented on doc/source/security/encrypting-doublewrite-buffers.rst
> +doublewrite buffer.
Updated.

2021-04-22 11:10 UTC, percona-ysorokin approved these changes
LGTM

2021-05-12 12:27 UTC, merged