PS-7591 Document new variables global.net_buffer_shrink_interval and …
percona/percona-server pull request #4242
Opened 2021-04-08 14:41 UTC by patrickbirch

…net_buffer_length (8.0)

 Changes to be committed:
	modified:   source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst

2021-04-14 15:24 UTC, ldonoso commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +  * .. versionadded:: `8.0.12-1` Feature ported from |Percona Server| 5.7
It was ported from Facebook MySql 5.6

2021-04-14 15:35 UTC, patrickbirch commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +  * .. versionadded:: `8.0.12-1` Feature ported from |Percona Server| 5.7
Fixed.

2021-04-22 08:06 UTC, ldonoso requested changes

2021-04-22 08:06 UTC, ldonoso commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +Network buffers grows towards the `max_allowed_packet <https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet>`_ size and do not shrink until the connection is
A tiny typo, it should be "grow" or "The network buffer of a connection grow ..."

2021-04-22 08:06 UTC, ldonoso commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +The default value is 0, which disables the variable. The minimum value is 0 and the maximum value is 31536000.
I'd use "this functionality" instead of "the variable"

2021-04-22 08:06 UTC, ldonoso commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +The :variable:`net_buffer_shrink_interval` variable shrinks network buffers, according to the workload, during the specified interval. The thread's network buffer size is set to the maximum packet si
I'd rephrase this paragraph. Maybe:

>To solve this problem, the variable `net_buffer_shrink_interval` has been introduced. If it is different from 0, percona server records the maximum used size of the network buffer during the number of seconds set by net_buffer_shrink_interval. At the beginning of the next interval the network buffer will be set to this size. This allows to forget spikes in the buffer size

2021-04-22 08:06 UTC, ldonoso commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +You can achieve similar results by disconnecting and reconnecting the TCP connections, but this solution is a heavier process. Also, this process also disconnects and reconnects connections with smal
I haven't thought of this. This comment is really useful.

2021-04-22 08:06 UTC, ldonoso commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +.. variable:: net_buffer_shrink_interval
I would mention the unit of time is seconds. But sorry, I would know where this information should go.

2021-04-22 10:59 UTC, patrickbirch commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +Network buffers grows towards the `max_allowed_packet <https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet>`_ size and do not shrink until the connection is
Fixed.

2021-04-22 11:00 UTC, patrickbirch commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +The default value is 0, which disables the variable. The minimum value is 0 and the maximum value is 31536000.
updated.

2021-04-22 11:47 UTC, patrickbirch commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +The :variable:`net_buffer_shrink_interval` variable shrinks network buffers, according to the workload, during the specified interval. The thread's network buffer size is set to the maximum packet si
Rewritten.

2021-04-22 11:47 UTC, patrickbirch commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +You can achieve similar results by disconnecting and reconnecting the TCP connections, but this solution is a heavier process. Also, this process also disconnects and reconnects connections with smal
Thanks.

2021-04-22 11:48 UTC, patrickbirch commented on doc/source/performance/xtradb_performance_improvements_for_io-bound_highly-concurrent_workloads.rst
> +.. variable:: net_buffer_shrink_interval
Added.

2021-04-23 09:00 UTC, ldonoso approved these changes

2021-05-12 12:28 UTC, merged