PS 7746 [8.0] - Null merge from PS-7746 5.7
percona/percona-server pull request #4416
Opened 2021-07-19 13:07 UTC by ldonoso

<https://jira.percona.com/browse/PS-7746>
<https://ps80.cd.percona.com/job/percona-server-8.0-param/1016/>

2021-07-20 11:43 UTC, venkatesh-prasad-v commented on storage/innobase/handler/ha_innodb.cc
> +  *share = NULL;
Can we use `nullptr` here?

2021-07-20 13:16 UTC, ldonoso commented on storage/innobase/handler/ha_innodb.cc
> +  *share = NULL;
Good call, I will change it

2021-07-21 04:12 UTC, venkatesh-prasad-v approved these changes
Looks good to me. Approved!

2021-07-21 06:39 UTC, satya-bodapati requested changes
@ldonoso looks good. Please squash 5.7 and 8.0 as well.

2021-07-21 11:03 UTC, satya-bodapati approved these changes

2021-07-21 13:28 UTC, merged