Port of security or crash fixes from MySQL 5.7.33 to 5.7.34
percona/percona-server pull request #4422
Opened 2021-07-23 15:03 UTC by avbelov23

2021-08-03 14:19 UTC, kamil-holubicki requested changes
Hi, thanks for working on these backports. 
I have created release branch release-5.6.51-92.0. The PR should be against this branch, not the already released version. Shouldn't be a big deal to change, as there is no ongoing development on 5.6.

Please also see my other comments.

2021-08-03 14:19 UTC, kamil-holubicki commented on sql/sql_yacc.yy
> +#ifndef NDEBUG
I think we need to change it to DBUG_OFF, like in commit 6051df17b88a9151910bb2cf2e70ca8a359de8cb
?
m_sp member is under #ifndef DBUG_OFF in item.h

2021-08-03 14:19 UTC, kamil-holubicki commented on storage/innobase/handler/ha_innodb.cc
> +		free_share(share);
I'm not sure about the flow here.
We are calling free_share, then if we get into the next 'if (UNIV_UNLIKELY)' we will call free_share again...

I think the solution is in commit 9a507dc4add6c3676d7aa18bcf4dc9c1ed54b604 from PS

2021-08-03 14:19 UTC, kamil-holubicki commented on mysys/my_conio.c
> +  size_t nchars = my_mbstou16s(cs, (const uchar *) data, datalen, u16buf,
s/nchars =/nchars=

2021-08-06 12:58 UTC, avbelov23 commented on storage/innobase/handler/ha_innodb.cc
> +		free_share(share);
Condition is `if (UNIV_UNLIKELY(**ib_table** &&`, but `ib_table = NULL;` after `free_share(share);`

2021-08-06 19:54 UTC, kamil-holubicki commented on storage/innobase/handler/ha_innodb.cc
> +		free_share(share);
I agree in this case, indeed. But why we introduced 'free_share_and_nullify()' in the mentioned commit? Are we safe in 5.6 without doing this?
@ldonoso, could you advise, please?

2021-08-16 08:02 UTC, ldonoso commented on storage/innobase/handler/ha_innodb.cc
> +		free_share(share);
@avbelov23 , please, apply the changes on commit above. Some other functions of Percona Server expect `share` to be available if not null.

2021-08-18 14:04 UTC, kamil-holubicki commented
LGTM. I started Jenkins job to check if everything is OK
https://ps56.cd.percona.com/job/percona-server-5.6-param/151/

2021-08-19 08:40 UTC, kamil-holubicki commented
Hi @avbelov23 , unfortunately after applying the patch the following tests fail with segfault:
innodb.xtradb_rseg_bug_1260259
innodb.innodb-wl5980-linux
innodb.innodb_mysql
innodb.percona_changed_page_bmp_requests_debug
innodb.percona_bug_1433197
innodb.percona_changed_page_bmp
innodb.percona_changed_page_bmp_1364315

2021-08-19 09:34 UTC, kamil-holubicki commented
https://ps56.cd.percona.com/job/percona-server-5.6-param/153/

2021-08-19 14:00 UTC, kamil-holubicki approved these changes

2021-08-19 14:02 UTC, merged