PS-5168: Set stats.data_file_length in temptable SE
percona/percona-server pull request #4484
Opened 2021-10-05 09:43 UTC by oleksandr-kachan

https://jira.percona.com/browse/PS-5168

The stats.data_file_length isn't set in temptable storage
engine. As a result of this we always get "Tmp_table_sizes: 0"
in slow query log even in case temporary table was actually
used during query processing.

To fix the issue the Handler::info() for temptable was updated
to set stats.data_file_length. Needed info is fetched from the
allocator instance wich handles all memory allocations for
the temptable storage engine.
In addition invocation of Handler::info() added in Handler::close()
to properly update memory usage before table is closed.

The close_tmp_table() method which fetches memory usage stats from
a temporary table was updated to update stats right after temporary
table is actually closed. At this point storage engine is supposed to
provide up to date memory usage stats.

2021-10-06 11:18 UTC, oleksandr-kachan commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/1067/

2021-10-08 12:11 UTC, satya-bodapati requested changes

2021-10-08 12:11 UTC, satya-bodapati commented on sql/sql_tmp_table.cc
> +
why did we move this down? I don't see any info() call in between.

2021-10-08 13:00 UTC, oleksandr-kachan commented on sql/sql_tmp_table.cc
> +
info() call is done by temptable storage engine itself when closing a table

"In addition invocation of Handler::info() added in Handler::close()
to properly update memory usage before table is closed."

2021-10-08 13:53 UTC, satya-bodapati commented on sql/sql_tmp_table.cc
> +
ah, there is ha_close() in between. Got it!

2021-10-08 13:58 UTC, satya-bodapati commented on storage/temptable/src/handler.cc
> +  info(HA_STATUS_VARIABLE);
I dont see such info() in ha_innobase::close(). How does it work for InnoDB?

2021-10-13 14:47 UTC, oleksandr-kachan commented on storage/temptable/src/handler.cc
> +  info(HA_STATUS_VARIABLE);
Removed this one.

2021-10-19 06:06 UTC, satya-bodapati requested changes

2021-10-19 06:06 UTC, satya-bodapati commented on storage/temptable/include/temptable/allocator.h
> +  }
Is this per table? or shared across tables?

2021-10-21 11:22 UTC, oleksandr-kachan commented on storage/temptable/include/temptable/allocator.h
> +  }
This one was shared but we need per table stats here... I've reworked change a bit.

2021-10-21 11:58 UTC, satya-bodapati commented on storage/temptable/include/temptable/allocator.h
> +  m_state->allocated_mem_counter += n_bytes_requested;
is the free done only at close() of table object? I don't see any decrements. Not necessary? :thinking:

2021-10-21 12:05 UTC, oleksandr-kachan commented on storage/temptable/include/temptable/allocator.h
> +  m_state->allocated_mem_counter += n_bytes_requested;
In my understanding we want to know the max used memory by tmp table while processing some query. So I'm not sure we need tracking deallocations here. What do you think?

2021-11-11 06:31 UTC, satya-bodapati approved these changes

2021-11-11 12:03 UTC, merged