PS 7921 [8.0]: Merge percona-202104 and percona-202105
percona/percona-server pull request #4496
Opened 2021-10-17 15:20 UTC by ldonoso

https://jira.percona.com/browse/PS-7921
https://ps80.cd.percona.com/job/percona-server-8.0-param/1081/ (baseline)
https://ps80.cd.percona.com/job/percona-server-8.0-param/1092/
https://ps80.cd.percona.com/job/percona-server-8.0-pipeline/34157/ (ASAN)

---
https://github.com/facebook/mysql-5.6/tree/percona-202104
https://github.com/facebook/mysql-5.6/tree/percona-202105

## percona-202104

1. Update rocksdb submodule to bfb9496af09 Modify script which generates TARGETS (#8366) (v6.21.1)

2. Support SELECT FOR UPDATE SKIP LOCKED / NOWAIT

3. Cherry-pick the following commits from `percona-202104`:

    5b302cbdd16553f9f163c98fe44fa63e41dff341 Using RocksDB Env API to create / access the corruption marker file.
    a736771d4a7d1c90448c7bbfb352a10c684c16e4 Delete garbage temp sst files using RocksDB Env API
    15d69687142bdf5efa7b999504ef7a390fdf59e3 Support SELECT FOR UPDATE SKIP LOCKED / NOWAIT
    6a279bc3c6a05424e7a99660908849b3a0bbe8aa Add RENAME TABLE test for x-database RENAME and DROP DATABASE
    25fa8acf4c0e4076af16b500c6199876dbb87812 Update rocksdb submodule to 6.21.1
    b659d0f2524d22385ad36fda61bbe05a9a80b182 Reduce flakiness of rocksdb.optimize_table

4. Null cherry-picked RocksDB upstream commits:

    45a8f6b80b2913be190f561c8f3682c68ee2a415 add mrr partition support
    90fd80dbf5be6d16f84692bdabac557e0189a4d9 Use upstream method of forcing group by plan

4. Null cherry-picked upstream commits:

    24d89cf7e68ecbcbe260b7a206e17b4d8f10d2d6 Fix assertion during SHOW ENGINE
    16b2705d0aef0a17add0240798e22c69eff925b0 fix flaky raft testcase
    b0df78d143e1542c6d14b0de9dacea6dc05abe9c Fix heap overflow in group_relay_log_name handling
    a9f3a2f2a49dd049d172fc08dca36aa3efd513ea This is the 8.0 port of D28735624
    4c6fbb745832f95729cf36ce81528a7b7d6e58b6 Use DBUG_TRACE instead of DBUG_ENTER
    a1ad6e1bab2dc6c61d18c10da67488eb5c6380f3 Add bounds checks to response attributes
    337fcca18f89f09981fd8bb7e17b27a458a0d6ef Backport BUG#32113015 - WHEN THE INPUT OF NET_LENGTH_SIZE IS 251, THE RETURN SHOULD BE 3
    125380f940b85fe20758ae35e22df6d842f4adbd check for sql_bin_log = 0 with write throttling
    82efb8e044d5a52f8a739efa365a879560c33068 fix memory during MYSQL_BIN_LOG::open_existing_binlog
    241994a1d0686795e58dda832c10265866dfbb11 add more timeout for asandebug shutdown
    cb7ea1a95739f23006179df28a7c77dd4bfeb924 Port COMMIT wait event and admission_control_multiquery_filter to 8.0
    4f7e9fda91d4cfbfe4865e9256d8051950a491b3 Add valgrind suppression of 'scope array' in dlclose()
    b6242ec8a13a8dfc4697ac2bb0bfd8e3df90df49 Using locks in Dump_log methods only when raft is enabled
    abb9f51c8859e74bb05b513bf823f777ddd823c1 Port D27349016 Add low HLC boundary support for transactions to 8.0.20
    87f9846531658db7b6af633c6eb45b6102947bf7 Porting D28003281 "Upper HLC bound support" to 8.0.20.
    1a7a8ce21d7218c4b2145dde7c604d96c9fd8cc8 leader election to be a sync point in the new leader
    c9c2dbe61b33d45b957fd4f08c9694f243ee574a Track out of order hlc value during slave apply
    d456ee64dd77d0a8b11c9d8146ecbf0b0b9dd2b2 Add integer_digits.h to installed extra headers
    87019737e52aecb92609ebfdfe2b24681e01dca8 Add optimizer hint to force group by plans
    ae7527cdf97d1ca5c58bc91c29555c04dadeb349 add new test fault macros reset_hlc_for_tests
    6904d7eae9e5c0157ec13db4abc86ee196937d25 Error out SQL thread on out of order opids in raft logs
    9fbe1c1d29083d4a5bcf8284f8e1e94743fd7289 Consider limit when costing group-by plans
    d11fc6b336d0a76bdbb69eeb15f6dde9e47290b2 Support commit order deadlocks resolution in dependency replication
    f7192b6f70c282bffdd499c68bfc0c40c2361493 Fallback to TBL mode instead of syncing trxs when errors are encountered while parsing keys
    ed02e3f19647b1540344865cd3bd314f3e3bdc82 Fixing rpl_raft_out_of_order_raft_log test
    5473299b42b8a6aec2a1dcfd7d2b83a23880b8ed Limit memory allocated for FTS table sync messages
    1deffd7fac63e4e7aed0c18b35e4f34aca77303e SHOW SLAVE STATUS shows real error
    0d46cc9ae61a33529bb89276e0898255d7eee882 Fixing rpl_raft_out_of_order_raft_log test again
    ab824f9c2d90055bf45f7d6e63895ae142e199cf Add variable to disable events_wait_summary_by_thread_by_event_name to reduce 40M per instance
    46e095c15618aaad0f1896983d47dba24e208fc3 Backport Bug #31549724: MYSQL --BINARY-AS-HEX PRINTS NULL AS EMPTY STRING

## percona-202105

1. Update rocksdb submodule to c04a86a0e9a Update HISTORY.md and version.h 6.23 release (v6.23.fb)

2. New functionality:

    New MyRocks variables:
        `rocksdb-partial-index-sort-max-mem`
        `rocksdb-bulk-load-partial-index`
        `rocksdb_cancel_manual_compactions`
    Supporting cancelling manual compactions

3. Cherry-pick the following commits from `percona-202105`:

    8dfbf7987848f70c0c48b3e97e01c535f70b299c MyRocks crashes on pure virtual function when querying rocksdb_trx list
    f35c50e28dc68d831930ef2d49e5d98fc603d05a Use Get for secondary key point lookups
    045ead26e815218e8e135eb06ebecfe01a3c9ffa Implement iterator class
    e6bb5f208bd7d9383105c0c63517838c35f3fdb4 Support parsing index comments for partial indexes
    0249a96c31e8f23ac008d9cca29cfd296f011f35 Add partial index iterator
    d054548154184f51ce297fc033e68b61aed71f3e Prematerialize partial indexes during bulk loading
    7deb48465e0471073514f0490837170f2b731803 update rocksdb submodule to 6.22.fb
    b6af72667a11e7c184ee97a154e7d323006fe098 Fix error handling during iteration
    63ab55f35f9780ecef55dcba8b36475f5c4cb073 Fix locking in partial indexes
    3518e50dacfe641c7a672a61b5c61cd717cdc87e Supporting cancelling manual compactions
    4ff643f5e47bb873cd8f7e19bfbf01c9f06e2bc5 Updating RocksDB submodule to 6.23.fb

4. New commits:

    3a8fcccc599b306ed907db6bda107ac3488cf50c Fix incorrect setting of m_full_key_lookup
    [Fix rocksdb.non_blocking_manual_compaction]
    7d1be2321e2 Fix incorrect setting of m_full_key_lookup

5. Null cherry-picked RocksDB upstream commits:

    47b45a29558ad97a73d20cb2a0ffca7995379f5b Fix two bugs in bypass
    d7fe2e254e4b74b0e6d51b35499e794361ba132f Move myrocks settings to my.cnf

6. Null cherry-picked upstream commits:

    d719f01525c51b273250438a2beab64b0b7d83d8 Add bounds checks to all resp attr code
    354b67c308d41962eb6dedbb2f0576ad0aa1fff5 Add MTR tests for privacy plugin
    582f9c9995322ac9bf9a1cd6803d212934b07399 fix show engine trx stats
    09220b3e5e2b0898e8a7ebbb7dd03bdb79ab770c Port MTR tests for COMMIT wait event and admission_control_multiquery_filter
    1721ff60a7c3d82c915fe2b9c641d650e7e5155d Add privacy test suite into default suite list
    21fcf7bf1e2cc5f692639d4f47b0e5214d82c830 port dscp_on_socket to 8.0
    5f43db54443561f1167f2fdf36ccb7ec1b7b14be remove rpl_dscp_on_socket
    8ee08672fcfd882511831882548de961b4727801 Suppress valgrind issue with rocksdb CacheEntryStats
    0931a17ea678a1225f9f436b8a86e59f3b5e9733 always use lz4_pic.a for libmysqlclient
    d1f81022d095c7a76b8b0e3d9a810ab721db45df Fix sending server_cpu as part of query response attributes
    e21b92bec59a6a0515b48e145f581e89f86a1499 Generate code coverage using suite option
    54365ee2dbecb1af38d636ab4b7dbc98c1df0d10 Remove privacy test suite from default suites
    bcd67a2957f4dce6957dbe356ad2610f95bc9323 add GET_COMMITTED_GTIDS for raft
    bf8b7610b9d23406aec014b7552f0a7f4f79efe2 raft: skip mts_recovery_groups during start slave
    184e7296eaee1515a99f418cd2dfd84e24ab83b7 Revert SHARED_LIB_MAJOR_VERSION back
    cd90913f526a8166a9230442375bdaa862f133f3 Port mysql_change_user_nonblocking from 8.0.17 to 8.0.20
    9daef992840f07c623cfbcc1f43fada081731131 Fix table names in COLUMN_STATISTICS
    7e480400f321602e94731a9747b9037798df61c1 Fix valgrind suppression for thread pool
    95431ae7d2705860676c8e91cba5de95c651c812 Fix valgrind error on rpl.rpl_io_thd_wait_for_disk_space
    e2fdc597aedfdd9d20fd6fe3983108e09dd84c64 Fix invalid MDL wait timeout in replication threads
    d394360404aa792e9f9a7094 [...]

2021-10-18 09:31 UTC, inikep commented on mysql-test/suite/rocksdb/t/rename_table.test
> +# RENAME table across database test
All RocksDB MTR tests must have '--include "have_rocksdb.inc"'

2021-10-18 09:32 UTC, inikep commented on mysql-test/suite/rocksdb/t/rename_table.test
> +CREATE TABLE t1 (pk int primary key);
Add "Engine=RocksDB" for all "CREATE TABLE" occurrences. FB uses "--default-storage-engine=RocksDB" but we don't.

2021-10-18 09:32 UTC, inikep commented on mysql-test/suite/rocksdb/t/rename_table.test
> +CREATE TABLE t2 (pk int primary key);
"Engine=RocksDB"

2021-10-18 09:33 UTC, inikep commented on mysql-test/suite/rocksdb/t/rename_table.test
> +CREATE TABLE t3 (pk int primary key);
"Engine=RocksDB"

2021-10-18 09:34 UTC, inikep commented on mysql-test/suite/rocksdb/t/skip_locked_nowait.test
> +--let $engine=ROCKSDB
include "have_rocksdb.inc"

2021-10-28 13:30 UTC, inikep requested changes

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/cancel_mc-master.opt
> +--rocksdb_rate_limiter_bytes_per_sec=256k --rocksdb_default_cf_options=write_buffer_size=64k;target_file_size_base=64k;max_bytes_for_level_base=1m;compression_per_level=kNoCompression;max_compaction_
In any of the myrocks .opt files we need to prefix all myrocks options with --loose for the cases/platforms where myrocks isn't built but the default suites are run
(from https://confluence.percona.com/display/PS/MyRocks+Merges)

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/partial_index_link-master.opt
> +--rocksdb_default_cf_options=write_buffer_size=128m;target_file_size_base=32m;max_bytes_for_level_base=512m;level0_file_num_compaction_trigger=4;level0_slowdown_writes_trigger=20;level0_stop_writes_t
In any of the myrocks .opt files we need to prefix all myrocks options with --loose for the cases/platforms where myrocks isn't built but the default suites are run

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/partial_index_stress-master.opt
> +--rocksdb_default_cf_options=write_buffer_size=128m;target_file_size_base=32m;max_bytes_for_level_base=512m;level0_file_num_compaction_trigger=4;level0_slowdown_writes_trigger=20;level0_stop_writes_t
In any of the myrocks .opt files we need to prefix all myrocks options with --loose for the cases/platforms where myrocks isn't built but the default suites are run

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/cancel_mc.test
> +--enable_warnings
Can be changed to
`drop table t1;`
in 8.0.

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/partial_index.inc
> +INSERT INTO t values ("111111111", "2", "2", "1");
The .inc files should be introduced into "rocksdb/include" and not "rocksdb/t"

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/partial_index_bulk_load.inc
> +SET rocksdb_bulk_load_allow_sk=1;
The .inc files should be introduced into "rocksdb/include" and not "rocksdb/t"

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/partial_index_link.inc
> +--let $binary_id1=1
The .inc files should be introduced into "rocksdb/include" and not "rocksdb/t"

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/cancel_mc.test
> +--connect (con2,localhost,root,,)
Add `--source include/count_sessions.inc` and `--source include/wait_until_count_sessions.inc` to check if all connections were closed.

2021-10-28 13:30 UTC, inikep commented on mysql-test/suite/rocksdb/t/cancel_mc_timeout.test
> +--connect (con2,localhost,root,,)
Add `--source include/count_sessions.inc` and `--source include/wait_until_count_sessions.inc` to check if all connections were closed

2021-10-29 06:17 UTC, ldonoso commented on mysql-test/suite/rocksdb/t/cancel_mc.test
> +--enable_warnings
@inikep , please, mind if I do that I get the following error:

```
CURRENT_TEST: rocksdb.cancel_mc
mysqltest: At line 21: Query 'DROP TABLE t1' failed.
ERROR 1051 (42S02): Unknown table 'test.t1'
```

2021-10-29 09:01 UTC, inikep commented on mysql-test/suite/rocksdb/t/cancel_mc.test
> +--enable_warnings
Sorry, `drop table t1;` can be removed because `mysql-test/include/check-testcase.test` makes sure that there is no leftovers from previous tests. You may leave it here but please remove it next time.

2021-10-29 09:04 UTC, inikep commented on storage/rocksdb/ha_rocksdb.cc
> +// TODOLUIS >>>>>>> 045ead26e81... Implement iterator class
What is it?

2021-10-29 09:25 UTC, inikep approved these changes
LGTM

2021-10-29 09:26 UTC, inikep commented on storage/rocksdb/ha_rocksdb.cc
> +// TODOLUIS >>>>>>> 045ead26e81... Implement iterator class
I can see it in commit history, no big deal.

2021-11-01 13:21 UTC, ldonoso commented on storage/rocksdb/ha_rocksdb.cc
> +// TODOLUIS >>>>>>> 045ead26e81... Implement iterator class
I will remove it

2021-11-01 13:25 UTC, ldonoso commented on mysql-test/suite/rocksdb/t/cancel_mc.test
> +--enable_warnings
I will remove it

2021-11-02 17:14 UTC, merged