PS-7960 Document percona-202104 and percona-202105 new functionality(…
percona/percona-server pull request #4537
Opened 2021-11-18 20:10 UTC by patrickbirch

…8.0)

modified:   source/index.rst
	new file:   source/myrocks/added-features.rst
	modified:   source/myrocks/limitations.rst
	modified:   source/myrocks/variables.rst

2022-01-10 15:16 UTC, ldonoso requested changes

2022-01-10 15:16 UTC, ldonoso commented on doc/source/myrocks/added-features.rst
> +* **Percona Server for MySQL** 8.0.27-17 adds support for ``SELECT FOR UPDATE SKIP LOCKED/NOWAIT``. The transaction isolation level must be ``READ COMMITTED``.
Please @patrickbirch watch out that there is being an intermediate release 8.0.26-17 so the next one is 8.0.27-18.

I guess this changes are included starting at 8.0.26-17 but please, could you verify it asking @percona-ysorokin ?

2022-02-17 20:09 UTC, patrickbirch commented on doc/source/myrocks/added-features.rst
> +* **Percona Server for MySQL** 8.0.27-17 adds support for ``SELECT FOR UPDATE SKIP LOCKED/NOWAIT``. The transaction isolation level must be ``READ COMMITTED``.
Fixed to 27-18

2022-02-18 14:55 UTC, ldonoso approved these changes

2022-03-03 17:03 UTC, merged