Crash when auto incremented column updated in partitioned table
percona/percona-server pull request #4589
Opened 2022-01-11 09:10 UTC by voodam

https://jira.percona.com/browse/PS-7856

Change write_set to read_set to fix fail on ASSERT_COLUMN_MARKED_FOR_READ. Probably write_set is written by mistake, because there is no writing for autoincrement column here, only reading.

2022-01-19 09:14 UTC, kamil-holubicki requested changes

2022-01-19 09:14 UTC, kamil-holubicki commented on mysql-test/suite/innodb/t/partition_autoinc.test
> +#################################
`--source include/have_innodb.inc`

2022-01-20 13:28 UTC, voodam commented on mysql-test/suite/innodb/t/partition_autoinc.test
> +#################################
Done

2022-01-27 14:03 UTC, kamil-holubicki approved these changes
LGTM. Please squash commits before continuing with merge to 8.0 (GCA)

2022-01-31 11:40 UTC, merged