Crash when auto incremented column updated in partitioned table
percona/percona-server pull request #4590
Opened 2022-01-11 09:20 UTC by voodam

https://jira.percona.com/browse/PS-7856

Change write_set to read_set to fix fail on ASSERT_COLUMN_MARKED_FOR_READ. Probably write_set is written by mistake, because there is no writing for autoincrement column here, only reading.

This is new PR instead of https://github.com/percona/percona-server/pull/4567 to comply GCA process.

2022-01-11 10:33 UTC, satya-bodapati requested changes
1. please fix commit message and github description. I think the write_set part is not relevant anymore
2. This doesn't look a GCA commit. If this is fixed in 5.7, we should see two commits for 8.0 branch

2022-01-11 11:28 UTC, voodam commented
> 1. please fix commit message and github description. I think the write_set part is not relevant anymore

Done, my bad.

> 2. This doesn't look a GCA commit. If this is fixed in 5.7, we should see two commits for 8.0 branch

You mean second commit with resolving conflicts? Yes, but AFAIU I first need to merge PR for 5.7: https://github.com/percona/percona-server/pull/4589, otherwise this 5.7 PR will have wrong commit. Or this is wrong undestanding of GCA?

2022-01-19 09:16 UTC, kamil-holubicki commented on mysql-test/suite/innodb/t/partition_autoinc.test
> +#################################
`--source include/have_innodb.inc`

2022-01-20 13:28 UTC, voodam commented on mysql-test/suite/innodb/t/partition_autoinc.test
> +#################################
Done (for 5.7)

2022-01-20 14:21 UTC, voodam commented
I need to close PR again because of missunderstanding GCA, sorry for the mess. Now all should be OK.

2022-01-20 14:21 UTC, closed without merging