PS-7923 Sort metadata locks acquired during ALTER TABLESPACE
percona/percona-server pull request #4708
Opened 2022-04-03 00:53 UTC by i-rinat

https://jira.percona.com/browse/PS-7923

Problem:
Metadata locks upgraded during ALTER TABLESPACE are upgraded in
no particular order, which present deadlock possibility. Metadata deadlock
prevention mechanism kicks in and rolls back an attachable transaction
during data dictionary updates, which causes the server to terminate.

Fix:
Sort metadata lock requests before upgrade procedure.
Move metadata lock upgrading routine to MDL_context class to reuse the
sorting comparator.

2022-04-05 11:07 UTC, satya-bodapati requested changes
This fix looks much better than the previous one (which blocked connections).
Why didn't you bring the testcase from that commit?

2022-04-05 13:22 UTC, i-rinat commented
> Why didn't you bring the testcase from that commit?

That testcase will fail every time unless this pull request will also include setting of thread ID in `fsp_init_resume_alter_encrypt_tablespace()`. Unless I clump everything together into a combined pull request, the testcase will have to go to the third one. I haven't made the third one yet, because it strongly depends on the patch in this pull request. Without third patch the testcase will not fail every time, but instead will fail intermittently.

I've also just had an idea. It may be possible to make a specific testcase for the lock ordering issue if I place debug points in the right places. I'll try to explore that idea.

2022-04-12 13:11 UTC, i-rinat commented
> It may be possible to make a specific testcase for the lock ordering issue

Turned out to be not feasible. It's required to add debug point into cycles, and essentially single-step those cycles in a testcase. That testcase would then be highly-dependent on particular table names in "mysql" tablespace, and would silently stop checking anything useful if another table was introduced. Moreover, such test would not prevent accidental out of order lock acquiring in new code. So essentially that test would be a dead weight.

2022-04-19 11:33 UTC, satya-bodapati commented
> > Why didn't you bring the testcase from that commit?
> 
> That testcase will fail every time unless this pull request will also include setting of thread ID in `fsp_init_resume_alter_encrypt_tablespace()`. Unless I clump everything together into a combined pull request, the testcase will have to go to the third one. I haven't made the third one yet, because it strongly depends on the patch in this pull request. Without third patch the testcase will not fail every time, but instead will fail intermittently.
> 
> I've also just had an idea. It may be possible to make a specific testcase for the lock ordering issue if I place debug points in the right places. I'll try to explore that idea.

@i-rinat Just setting thread_id is fine. we can include this and bring the testcase. Does it need InnoDB fil_io() fix as well?

2022-04-21 18:27 UTC, i-rinat commented
> Just setting thread_id is fine. we can include this and bring the testcase. Does it need InnoDB fil_io() fix as well?

The test will trigger assertion in InnoDB, sometimes.

Without the test and setting thread_id, so as this pull request is right now, it doesn't not really depend on the InnoDB's fix.

2022-05-23 07:25 UTC, satya-bodapati approved these changes

2022-09-14 10:12 UTC, merged