PS-8143: Fix memory leak in File_query_log::set_rotated_name() (8.0)
percona/percona-server pull request #4723
Opened 2022-04-09 12:15 UTC by oleksandr-kachan

https://jira.percona.com/browse/PS-8143

The opt_slow_logname now uses allocated memory to keep file path.
Make sure previously allocated memory is freed when generating
rotated file name. Also add PREALLOCATED flag in variable declaration.

(cherry picked from commit 4b5212cbf7e9a23166bfb7f3dd752c155915c868)

2022-04-09 12:17 UTC, oleksandr-kachan commented
https://ps80.cd.percona.com/job/percona-server-8.0-param/1211/

2022-04-27 09:40 UTC, satya-bodapati requested changes
Please check if GCA is possible?

2022-04-27 12:53 UTC, oleksandr-kachan commented
> Please check if GCA is possible?

It is not possible unfortunately as 8.0.28 not yet done and GCA not updated after last 5.7 release.

2022-04-28 10:33 UTC, satya-bodapati approved these changes

2022-05-02 10:50 UTC, merged