Fixed PS-8018 (Parallel replication with blackhole table on replica throws error 1863)
percona/percona-server pull request #4804
Opened 2022-05-29 00:33 UTC by i-rinat

https://jira.percona.com/browse/PS-8018

Problem:

Applying DELETE commands on a replica causes an error that stops
the replication process if the involved table uses BLACKHOLE engine and
is subject to table scans for finding a particular row. In other words,
has no usable indexes.

When applying DELETEs, Partition_helper::ph_delete_row() checks that
the partition ID that was determined by partition info, is exactly the
partition ID from Partition_helper::m_last_part. Latter is set in
Partition_helper::ph_rnd_next() to an ID of the first partition that
reports having the requested row. Since BLACKHOLE engine stores nothing,
it searches nothing. On replicas it happily reports that it has any
requested row. Thus making Partition_helper::ph_rnd_next() believe that
partition 0 is the one that has the row. Partition_helper::m_last_part is
therefore always set to 0 when BLACKHOLE engine is in use. That's fine for
rows in the first partition, but causes HA_ERR_ROW_IN_WRONG_PARTITION for
other partitions.

Fix:

BLACKHOLE engine has no need to track specific rows, so the solution is
to disable the check in Partition_helper::ph_delete_row() by making
ha_blackhole::rpl_lookup_rows() always return false.

handler::rpl_lookup_rows() was introduced as a part of optimizations for
TokuDB and RocksDB, and with that introduced a warning that explicitly
mentions "TokuDB/RocksDB" in its text. Receiving such warning when
BLACKHOLE engine is used would be confusing. So the text of the message is
changed to be engine-agnostic.

2022-06-10 08:19 UTC, kamil-holubicki reviewed
Hi, The fix looks fine.
Would it be possible to extend the test with UPDATE? Looking at the code it seems that it should suffer the same problem
```
  int update_row(const uchar *old_data, uchar *new_data) override
  {
    return Partition_helper::ph_update_row(old_data, new_data,
                                           rpl_lookup_rows());
  }
```

2022-06-10 08:21 UTC, kamil-holubicki commented
https://ps57.cd.percona.com/job/percona-server-5.7-pipeline/27834/

2022-06-11 00:57 UTC, i-rinat commented
> Would it be possible to extend the test with UPDATE?

Sure. Added an UPDATE to the testcase.

> Looking at the code it seems that it should suffer the same problem

I've tried just to be sure. And UPDATEs do trigger the same issue. The patch helps as `Partition_helper::ph_update_row()` contains similar code that skips the error when `lookup_rows` is `false`.

2022-06-11 00:57 UTC, i-rinat commented
> Would it be possible to extend the test with UPDATE?

Sure. Added an UPDATE to the testcase.

> Looking at the code it seems that it should suffer the same problem

I've tried just to be sure. And UPDATEs do trigger the same issue. The patch helps as `Partition_helper::ph_update_row()` contains similar code that skips the error when `lookup_rows` is `false`.

2022-06-13 09:23 UTC, kamil-holubicki commented
https://ps57.cd.percona.com/job/percona-server-5.7-pipeline/27854/

2022-06-14 08:35 UTC, venkatesh-prasad-v requested changes

2022-06-14 08:35 UTC, venkatesh-prasad-v commented on mysql-test/suite/rpl/t/rpl_blackhole_partitioned.test
> +--connection master
Please use `--source include/rpl_connection_master.inc`

2022-06-14 08:35 UTC, venkatesh-prasad-v commented on mysql-test/suite/rpl/t/rpl_blackhole_partitioned.test
> +--sync_with_master 0
Please source `--source include/sync_slave_sql_with_master.inc` to sync the replica server with the source.

2022-06-14 08:35 UTC, venkatesh-prasad-v commented on mysql-test/suite/rpl/t/rpl_blackhole_partitioned.test
> +--sync_with_master 0
Likewise

2022-06-14 16:28 UTC, i-rinat commented on mysql-test/suite/rpl/t/rpl_blackhole_partitioned.test
> +--connection master
✅

2022-06-14 16:30 UTC, i-rinat commented on mysql-test/suite/rpl/t/rpl_blackhole_partitioned.test
> +--sync_with_master 0
Replaced with `source include/sync_slave_sql_with_master.inc`.

2022-06-14 16:31 UTC, i-rinat commented on mysql-test/suite/rpl/t/rpl_blackhole_partitioned.test
> +--sync_with_master 0
Replaced with `source include/sync_slave_sql_with_master.inc`.

2022-06-14 16:32 UTC, i-rinat commented
Made changes according to the suggestions from the review.

2022-06-15 07:49 UTC, kamil-holubicki approved these changes
lgtm

2022-07-25 06:58 UTC, venkatesh-prasad-v approved these changes

2022-09-14 10:34 UTC, merged