PS-8190 Assertion Failure buf0buf.cc:4318:page_size.equals_to(space_p…
percona/percona-server pull request #4809
Opened 2022-06-02 07:08 UTC by rahulmalik87

…age_size)

https://jira.percona.com/browse/PS-8190

Problem:
Crash in debug build when discard table followed by drop table.

Analysis:
As part of discard tablespace, server sets index root page to null but
does not remove AHI(Adaptive Hash Index) entries from buffer pool.It can
causes crash if there a drop after the discard tablespace. As drop
tablespace explicity remove AHI entries but these indexes root pages are
already set to null and it asserts different places in code

Fix:
drop AHI as part of discard tablespace

2022-06-02 13:37 UTC, satya-bodapati requested changes
Please also include the testcase from other duplicate bug

2022-06-02 13:39 UTC, satya-bodapati requested changes

2022-06-02 13:39 UTC, satya-bodapati commented on mysql-test/suite/innodb/t/discard_drop_tablespace.test
> +--echo # Bug PS#8190 ASSERT AFTER DISCARD TABLESPACE followed by Drop Table
```suggestion
--echo # PS-8190 : Assertion Failure buf0buf.cc:4318:page_size.equals_to(space_page_size)
```

2022-06-02 13:39 UTC, satya-bodapati commented on mysql-test/suite/innodb/t/discard_drop_tablespace.test
> +--echo # Bug PS#8190 ASSERT AFTER DISCARD TABLESPACE followed by Drop Table
or edit the title on bug page

2022-06-03 04:22 UTC, rahulmalik87 commented on mysql-test/suite/innodb/t/discard_drop_tablespace.test
> +--echo # Bug PS#8190 ASSERT AFTER DISCARD TABLESPACE followed by Drop Table
done.

2022-06-03 08:36 UTC, satya-bodapati commented
@rahulmalik87 please add jenkins link (innodb suites are enough)

2022-06-07 08:36 UTC, satya-bodapati commented
> @rahulmalik87 please add jenkins link (innodb suites are enough)

@rahulmalik87 Please reply to this message

2022-06-15 09:07 UTC, rahulmalik87 commented
> > @rahulmalik87 please add jenkins link (innodb suites are enough)
> 
> @rahulmalik87 Please reply to this message

https://ps80.cd.percona.com/view/8.0/job/percona-server-8.0-param/1233/testReport/

All 4 different tests are regressions

2022-06-16 08:39 UTC, satya-bodapati approved these changes
Please comment on other PRs that they should be closed now

2022-06-16 08:44 UTC, merged