PS-8257 Failed upgrade attempt to 8.0.29 corrupts the data dictionary
percona/percona-server pull request #4815
Opened 2022-06-10 09:36 UTC by rahulmalik87

https://jira.percona.com/browse/PS-8257

Problem:
Failed upgrade attempt to 8.0.29 corrupts the data dictionary

Analysis:
8.0.29 has changed the redo log format and shuffle the redo type code,
so lower version can't parse redo log file in case of failed upgrade

Fix:
Recreate the empty redo log file during failed upgrade
so lower version does not need to parse redo file

2022-06-10 10:42 UTC, ldonoso requested changes

2022-06-10 10:42 UTC, ldonoso commented on storage/innobase/srv/srv0start.cc
> +    ut_ad(fil_space_t::s_redo_space != nullptr);
Please, @rahulmalik87 , could we extract this functionality in a independent function (i.e.`recreate_redo_log_files)?

This way, `srv_shutdown_log` is not so long and the functionality is easier to maintain.

2022-06-10 10:42 UTC, ldonoso commented on storage/innobase/srv/srv0start.cc
> +    }
These same lines appear on `srv_start`. Please, maybe we could create a function and using it both in `srv_start` and here. This way if the logic changes on the future we do not need to remember to update two places.

2022-06-10 12:32 UTC, altmannmarcelo requested changes
do we have any test case to stress this code path?

2022-06-10 12:32 UTC, altmannmarcelo commented on share/messages_to_error_log.txt
> +ER_IB_MSG_DOWNGRADING_LOG_FILE
Shouldn't this be part of PS section?

2022-06-10 12:32 UTC, altmannmarcelo commented on sql/mysqld.cc
> +      if (!dd::upgrade::no_server_upgrade_required()) {
Are we calling no_server_upgrade_required a second time?
Why not set dd_init_failed_during_upgrade when the original upgrade failed?

2022-06-10 12:32 UTC, altmannmarcelo commented on storage/innobase/log/log0chkp.cc
> -  ut_a(srv_is_being_started);
ut_a(srv_is_being_started || dd_init_failed_during_upgrade); ?

2022-06-10 12:32 UTC, altmannmarcelo commented on sql/mysqld.cc
> +      if (!dd::upgrade::no_server_upgrade_required()) {
```
  @retval false  ON SUCCESS
  @retval true   ON FAILURE
```

Those are the return values of that function, shouldn't we set `dd_init_failed_during_upgrade = true;` if no_server_upgrade_required returns true ?

2022-06-13 08:31 UTC, satya-bodapati requested changes

2022-06-13 08:31 UTC, satya-bodapati commented on storage/innobase/srv/srv0start.cc
> +static uint32_t server_log_format;
I would call log_format_before_upgrade and appropriate comment
/** Redo log format before upgrade, used to create redo log files of the same version on failed upgrades. */
Something along these lines

2022-06-13 08:31 UTC, satya-bodapati commented on storage/innobase/srv/srv0start.cc
> +    ut_a(lsn == log_get_lsn(*log_sys));
instead of removing assert for failed upgrade, shouldn't we reset LSNs?

2022-06-13 09:24 UTC, rahulmalik87 commented on storage/innobase/srv/srv0start.cc
> +    ut_ad(fil_space_t::s_redo_space != nullptr);
fixed

2022-06-13 09:24 UTC, rahulmalik87 commented on storage/innobase/srv/srv0start.cc
> +    }
fixed

2022-06-13 09:26 UTC, rahulmalik87 commented on share/messages_to_error_log.txt
> +ER_IB_MSG_DOWNGRADING_LOG_FILE
replaced it with ER_XB_MSG_DOWNGRADING_LOG_FILE

2022-06-13 10:05 UTC, rahulmalik87 commented on sql/mysqld.cc
> +      if (!dd::upgrade::no_server_upgrade_required()) {
these return values belongs to upgrade_system_schemas and not no_server_upgrade_required. 
we are doing it exactly after failed dd::int(). I think it should be okay

2022-06-13 10:12 UTC, rahulmalik87 commented on storage/innobase/log/log0chkp.cc
> -  ut_a(srv_is_being_started);
fixed

2022-06-13 10:15 UTC, rahulmalik87 commented on storage/innobase/srv/srv0start.cc
> +static uint32_t server_log_format;
fixed

2022-06-13 10:16 UTC, rahulmalik87 commented on storage/innobase/srv/srv0start.cc
> +    ut_a(lsn == log_get_lsn(*log_sys));
added, fixed

2022-06-14 09:53 UTC, rahulmalik87 commented
Guys, Please review https://github.com/percona/percona-server/pull/4818, which is based on 8.0.29

2022-06-15 14:01 UTC, closed without merging