Fixed (PS-7187) - (Assertion failure: zipdecompress.cc:1432:!memcmp(F…
percona/percona-server pull request #4837
Opened 2022-07-18 12:58 UTC by hagrid-the-developer

…IL_PAGE_TYPE + page, FIL_PAGE_TYPE + page_zip->data, PAGE_HEADER - FIL_PAGE_TYPE))

The issue happens when one page is copied to another during
decompression and one page is encrypted and the other is not
or versions of encryption keys differ.
This patch introduces a solution when the versions
of encryption keys are compared. If they differ
then the whole page is copied including the header that
is not skipped.

2022-10-04 08:39 UTC, kamil-holubicki commented
@satya-bodapati could you take a look, please?
@hagrid-the-developer this PR has merge conflicts. Rebase most probably will help.

2022-10-04 08:43 UTC, kamil-holubicki requested changes
Would it be possible to rename the test by giving it a meaningful name?

2022-10-06 10:12 UTC, satya-bodapati requested changes

2022-10-06 10:12 UTC, satya-bodapati commented on storage/innobase/page/page0cur.cc
> +          mach_read_from_4(page + FIL_PAGE_ENCRYPTION_KEY_VERSION);
@hagrid-the-developer This feature (keyring key encryption)  is currently unused in PS and so it should never be changed.

Please find out how the KEY_VERSION changed when the feature is disabled?

2022-10-06 10:12 UTC, satya-bodapati commented on mysql-test/suite/rocksdb/t/issue7187.test
> +
this should be in opt file along with keyring_file_data options

2022-10-06 10:12 UTC, satya-bodapati commented on mysql-test/suite/rocksdb/t/issue7187.test
> +CREATE TABLESPACE tab16k_e ADD DATAFILE 'tab16k_e.ibd'  FILE_BLOCK_SIZE 16k ENCRYPTION='Y' ;
how did this tablespace creation succeed? Keyring seems to be not initialized due to missing keyring_file_data.

2022-10-06 10:12 UTC, satya-bodapati commented on mysql-test/suite/rocksdb/t/issue7187.test
> +INSTALL PLUGIN keyring_file SONAME 'keyring_file.so';
test should be in innodb suite with a proper name?

page_zip_decompress.test?

2023-03-13 07:45 UTC, dutow commented
Closing this, as it fixes an issue with encryption ids, which we removed as part of the keyring encryption removal.

2023-03-13 07:45 UTC, closed without merging