PS-8275: Implement auto_evict_timeout
percona/percona-server pull request #4905
Opened 2022-10-17 14:04 UTC by dutow

This commit implement a new system variable,
group_replication_auto_evict_timeout, which automatically evicts members if they were in flow_control for more than the specified timeout.

By default this variable is 0, and doesn't change the existing behavior.

If it is set to a non zero value, any node that reaches the flow control threshold self evicts itself flom the cluster.

This change doesn't take into account the majority concept introduced in PS-8276: a single node is considered in flow control, and timeout calculation strarts, even if only a single node reaches the limit.

2022-10-25 14:08 UTC, venkatesh-prasad-v requested changes

2022-10-25 14:08 UTC, venkatesh-prasad-v commented on plugin/group_replication/include/plugin_variables.h
> +  uint auto_evict_timeout;
Can we use uint64 here as well?

2022-10-25 14:08 UTC, venkatesh-prasad-v commented on plugin/group_replication/src/pipeline_stats.cc
> +      auto ml = group_member_mgr->get_all_members();
`get_all_members()` uses `new`. We must delete the contents of the vector and delete the vector in the end. Please fix this as well.

2022-10-26 14:03 UTC, venkatesh-prasad-v approved these changes

2022-10-27 11:34 UTC, dutow commented
https://ps80.cd.percona.com/view/Parallel%20MTR/job/percona-server-8.0-pipeline-parallel-mtr/313/

2022-10-27 11:34 UTC, merged