PS-8442: Fix crash in buf_pool_invalidate_instance()
percona/percona-server pull request #4948
Opened 2022-12-02 10:18 UTC by oleksandr-kachan

https://jira.percona.com/browse/PS-8442

Previously buf_pool_invalidate() was invoked only once during server startup. At that point in server startup sequence it was guaranteed that only lru_list contains changed pages ant it was enough to wait for lru_list to flush by calling buf_flush_wait_LRU_batch_end() before actually invoking buf_pool_invalidate().

After changes in https://github.com/mysql/mysql-server/commit/b7a22c741f6920745d2a8f60e7f8aa856a998e39 buf_pool_invalidate() now is called second time during server startup and this time cleaning lru_list only is not enough.

Reverted part of recv_apply_hashed_log_recs() to upstream state to make sure both lru_list and flush_list are cleanned up before calling buf_pool_invalidate().

2022-12-07 19:31 UTC, satya-bodapati requested changes

2022-12-07 19:31 UTC, satya-bodapati commented on storage/innobase/log/log0recv.cc
> +
Please check about recv_writer_thread() in previous 8.0 versions. 

I think we made a Merge mistake in 8.0.30. We never rely on recv_writer_thread() to do LRU list flushing.
From 8.0.30, we brought upstream logic as is.

During recovery too, our LRU threads will do the flushing.

Please revert the entire recv_writer_thread logic and this change too and test.

If it still fails, the fix should be something else.

2022-12-13 14:27 UTC, oleksandr-kachan commented on storage/innobase/log/log0recv.cc
> +
Removed  recv_writer_thread() related code

2022-12-13 15:32 UTC, satya-bodapati commented
@oleksandr-kachan Can you please paste any result that confirms removal of this rec writer thread solves the buf_pool_validate_instance crash?

2022-12-13 16:52 UTC, oleksandr-kachan commented
> @oleksandr-kachan Can you please paste any result that confirms removal of this rec writer thread solves the buf_pool_validate_instance crash?

@satya-bodapati, just run previously failing test on Jenkins https://ps80.cd.percona.com/job/percona-server-8.0-pipeline/40888/

2022-12-20 21:10 UTC, percona-ysorokin approved these changes
LGTM

2022-12-21 09:15 UTC, merged