PS-8908: Mysqld crash when user forgets to set debug timeout
percona/percona-server pull request #5117
Opened 2023-09-05 14:09 UTC by kamil-holubicki

https://jira.percona.com/browse/PS-8908

Problem:
If 'debug_sync_timeout' parameter is not specified in my.cnf or as a command line argument, the usage of debug sync factility leads to the assertion.

Cause:
The default value of 'debug_sync_timeout' is 0, which means the debug sync factility is disabled. In such a case 'debug_sync_control' member of the THD is not initialized during THD initialization (debug_sync_init_thread()).
The callstack debug_sync_set_action => debug_sync_eval_action => debug_sync_get_action uses 'debug_sync_control' member unconditionally causing the assertion.

Solution:
There was a missing check for 'debug_sync_timeout' in the above-mentioned callstack. Similar checks are present in debug_sync_update() or debug_sync_init() functions. Added missing check.

2024-01-02 15:28 UTC, satya-bodapati requested changes

2024-01-02 15:28 UTC, satya-bodapati commented on sql/debug_sync.cc
> +  // A zero value keeps the facility disabled.
I guess MTR framework always has debug sync enabled? Is it possible to use different cnf or start mysqld without debug sync enabled and execute testcase provided in the bug report?

2024-01-19 12:33 UTC, kamil-holubicki commented on sql/debug_sync.cc
> +  // A zero value keeps the facility disabled.
Yes, probably MTR framework always sets `debug_sync_timeout`, so the problem is not visible. The problem is visible if you start the server standalone without specifying it and execute debug sync queries manually like it is in the bug report.

2026-09-09 12:34 UTC, hulyav commented
No longer needed

2026-09-09 12:34 UTC, closed without merging