PS-9017: Check OpenSSL FIPS mode status during server startup (8.0.35)
percona/percona-server pull request #5175
Opened 2023-12-11 18:57 UTC by oleksandr-kachan

https://jira.percona.com/browse/PS-9017

Added checkup during server startup if system OpenSSL is configured to use FIPS. Corresponding message will be printed to server error log.

2023-12-11 23:42 UTC, percona-ysorokin requested changes

2023-12-11 23:42 UTC, percona-ysorokin commented on share/messages_to_error_log.txt
> +  eng "We have detected a FIPS-approved version of OpenSSL library in your system. It has the default crypto provider set to use FIPS mode. Consequently Percona Server for MySQL will run in FIPS mode
```suggestion
  eng "A FIPS-approved version of OpenSSL cryptographic library has been detected in the operating system. It has a properly configured FIPS module available for loading. Consequently Percona Server for MySQL will run in FIPS mode as well."
```

2023-12-12 08:24 UTC, oleksandr-kachan commented on share/messages_to_error_log.txt
> +  eng "We have detected a FIPS-approved version of OpenSSL library in your system. It has the default crypto provider set to use FIPS mode. Consequently Percona Server for MySQL will run in FIPS mode
Done

2023-12-12 12:19 UTC, percona-ysorokin requested changes

2023-12-12 12:19 UTC, percona-ysorokin commented on share/messages_to_error_log.txt
> +  eng "A FIPS-approved version of OpenSSL cryptographic library has been detected in the operating system. It has a properly configured FIPS module available for loading. Consequently Percona Server
```suggestion
  eng "A FIPS-approved version of the OpenSSL cryptographic library has been detected in the operating system with a properly configured FIPS module available for loading. Percona Server for MySQL will load this module and run in FIPS mode."
```
Approved by @patrickbirch

2023-12-12 12:32 UTC, oleksandr-kachan commented on share/messages_to_error_log.txt
> +  eng "A FIPS-approved version of OpenSSL cryptographic library has been detected in the operating system. It has a properly configured FIPS module available for loading. Consequently Percona Server
Updated

2023-12-12 13:03 UTC, percona-ysorokin reviewed
LGTM

2023-12-12 14:35 UTC, merged