PS-9048 fix: Fixed problem with percent character in n-grams
percona/percona-server pull request #5230
Opened 2024-02-13 16:12 UTC by percona-ysorokin

https://perconadev.atlassian.net/browse/PS-9048

Fixed problem with 'fts_index_fetch_nodes()' function not being able to properly handle situations when 'word' parameter contained special characters used by 'LIKE' clauses ('%' and '_'). Introduced additional boolean parameter 'exact_match' that instructs this function to use either 'WHERE word = :word' or 'WHERE word LIKE :word' clauses when selecting records from internal FTS tables. We call 'fts_index_fetch_nodes()' with 'exact_match' set to 'true' only from 'fts_optimize_words()' (when we perform 'OPTIMIZE TABLE' under 'innodb_optimize_fulltext_only' enabled). In every other place
* fts_query_difference()
* fts_query_intersect()
* fts_query_union()
* fts_query_phrase_search() where we indeed need pattern matching we call this function with 'exact_match' set to 'false' (instructing the function to use the 'LIKE' clause).

Added two new MTR test cases:
* 'innodb_fts.percona_ft_ngram_special_chars_ewc_on'
* 'innodb_fts.percona_ft_ngram_special_chars_ewc_off' which reproduce original crash scenario under both 'ft_query_extra_word_chars' set to 'ON' and 'OFF'. These tests cases also check ngram parsing / querying strings containing various special characters. Please note that they have "result mismatch" status strings recorded in the '.result' files for certain combinations of special characters and this is expected behavior.

2024-02-14 07:12 UTC, oleksandr-kachan approved these changes

2024-02-15 12:21 UTC, percona-ysorokin commented
Jenkins build link
https://ps80.cd.percona.com/view/8.0%20parallel%20MTR/job/percona-server-8.0-param-parallel-mtr/36/

2024-02-16 08:02 UTC, oleksandr-kachan commented on mysql-test/suite/innodb_fts/t/percona_ft_special_chars_mecab_ewc_on.test
> +--source include/have_ngram.inc
have_mecab

2024-02-16 08:03 UTC, oleksandr-kachan commented on mysql-test/suite/innodb_fts/t/percona_ft_special_chars_mecab_ewc_on.test
> +--let $fts_parser =
Shall it be set to 'mecab' directly?

2024-02-16 08:04 UTC, oleksandr-kachan commented on mysql-test/suite/innodb_fts/t/percona_ft_special_chars_mecab_ewc_off.test
> +--source include/have_ngram.inc
have_mecab

2024-02-16 08:12 UTC, oleksandr-kachan requested changes
Please check comments in code

2024-02-16 13:13 UTC, percona-ysorokin commented on mysql-test/suite/innodb_fts/t/percona_ft_special_chars_mecab_ewc_on.test
> +--source include/have_ngram.inc
fixed

2024-02-16 13:13 UTC, percona-ysorokin commented on mysql-test/suite/innodb_fts/t/percona_ft_special_chars_mecab_ewc_on.test
> +--let $fts_parser =
fixed

2024-02-16 13:13 UTC, percona-ysorokin commented on mysql-test/suite/innodb_fts/t/percona_ft_special_chars_mecab_ewc_off.test
> +--source include/have_ngram.inc
fixed

2024-02-16 13:25 UTC, oleksandr-kachan approved these changes

2024-02-16 17:38 UTC, oleksandr-kachan approved these changes

2024-02-16 20:14 UTC, merged