PS-9219: MySQL converts collection of date data type in ibd but data dictionary
percona/percona-server pull request #5294
Opened 2024-05-20 09:59 UTC by venkatesh-prasad-v

Problem
=======
Import tablespace operation fails due to the incorrect table definition in the ibd file if the charset-collation was changed before the backup if the table had a column of temporal tpye (date, datetime, timestamp).

Analysis
========
In MySQL temporal types are always stored and compared using my_charset_latin1 charset.

During the execution of ALTER TABLE CONVERT TO CHARACTER SET, MySQL changes the charset and collation of temporal types resulting in different collation_id for temporal columns in SDI. However the field type is not changed in table->field structure.

When a new table is created with same definition using CREATE TABLE LIKE query, the character set for new field is taken from the table->field object of the source table. During the preparation of the fields, `Field_datetimef` object's pointer is passed to Create_field constructor and so that it uses the same charset as of the source column.

Since all temporal fields are always created with my_charset_latin1 charset, the new field is also created with my_charset_latin1 while the source table may have the different charset and collation.

It is for the above reason, even queries like ALTER TABLE ENGINE=INNODB reset the charset of the datetime column

1. create table a(dt datetime); $ ./bin/ibd2sdi ./var/mysqld.1/data/test/a.ibd "name": "dt", "collation_id": 8

2. alter table a CONVERT TO CHARACTER SET utf8mb4 collate utf8mb4_unicode_ci; $ ./bin/ibd2sdi ./var/mysqld.1/data/test/a.ibd "name": "dt", "collation_id": 224

3. alter table a engine = innodb; $ ./bin/ibd2sdi ./var/mysqld.1/data/test/a.ibd "name": "dt", "collation_id": 8

Such being a case when backup of the first table is imported to second table, it finds that the first table's charset and collation are not same as that of the target table and errors out with `Schema mismatch (Column a precise type mismatch.) `

Solution
========
This commit prohibits ALTER TABLE CONVERT TO CHARACTER SET command to alter the character set temporal types. In other words, we now force the server to always use my_charset_numeric for temporal types.

2024-06-04 12:40 UTC, dlenev requested changes
Hello Venkatesh!

The patch itself look good to me. I only have some comments about commit message
and comments.

1) First of all, could you please fix typo in commit message title and replace "collection" with "collation" ? Also "tpye" -> "type".

2) I also think that it is worth to rewrite the rest of commit message:

a) To avoid creating false impression that temporal
   columns can have collation different than my_charset_latin1
   - they really can't, it is only collation stored in
   data-dictionary/SDI for such columns that can be wrong.

b) To focus on how this wrong collation stored in DD/SDI
   causes problems during restoring of backup.

For example we can say something like:

Analysis
========
In MySQL temporal types are always stored and compared using
my_charset_latin1 charset.

During the execution of ALTER TABLE CONVERT TO CHARACTER SET, MySQL
changes the charset and collation stored in data-dictionary and SDI
for temporal columns to a different collation_id.
In practice, this new collation_id is ignored when such columns
are stored/compared. Corresponding Field objects are not updated to
use this new collation (Actually, Field objects for temporal types are
hardcoded to use my_charset_latin1).

This new collation is not visible in I_S and SHOW CREATE TABLE output.
It will be ignored by CREATE TABLE LIKE and rewritten by ALTER TABLE
since both these statements use info from Field objects of source table
to produce Create_field objects describing columns of new table/new
version of the table.

For example:

1. create table a(dt datetime);
   $ ./bin/ibd2sdi ./var/mysqld.1/data/test/a.ibd
   "name": "dt",
   "collation_id": 8

2. alter table a CONVERT TO CHARACTER SET utf8mb4 collate utf8mb4_unicode_ci;
   $ ./bin/ibd2sdi ./var/mysqld.1/data/test/a.ibd
   "name": "dt",
   "collation_id": 224

3. alter table a engine = innodb;
   $ ./bin/ibd2sdi ./var/mysqld.1/data/test/a.ibd
   "name": "dt",
   "collation_id": 8

However, this almost invisible incorrect collation_id causes problems when
we try to restore InnoDB table with such a column from the backup created
using Percona eXtraBackup tool.

This tool uses information from DD/SDI to produce .cfg file describing
InnoDB table being restored. Later information from this file is used
by ALTER TABLE IMPORT TABLESPACE that imports restored table.

Particularly, for new temporal types that support fractional seconds
collation_id from DD/SDI affects the InnoDB "precise type" describing
the column and stored in .cfg. Because of this, incorrect collation_id
in DD/SDI for such columns results in incorrect "precise type" in .cfg
file.

As consequence we get `Schema mismatch (Column a precise type mismatch.)`
error when ALTER TABLE IMPORT TABLESPACE compares the "precise type"
from such .cfg file with "precise type" for column in table version
being imported into. The latter is based on collation_id which ultimately
comes from Field object and always corresponds to my_charset_latin1 for
temporal types.

Note that this problem do not affect scenarios when we import table
with .cfg file that was generated by MySQL's FLUSH TABLE FOR EXPORT
command, as the latter doesn't use DD/SDI to calculate "precise type"
but gets information from Field object in table being exported instead.

Solution
========
This commit changes ALTER TABLE CONVERT TO CHARACTER SET command to
not alter the character set for temporal types stored in data-dictionary/SDI.
In other words, we now force the server to always use my_charset_latin1
in DD/SDI for temporal types.

There will be a separate fix to Percona eXtraBackup tool which will
change code generating .cfg to ignore collation_id stored in DD/SDI for
temporal columns like it is already done for some other types with fixed
collation_id.

2024-06-04 12:40 UTC, dlenev commented on sql/sql_table.cc
> +    Always use my_charset_numeric for temporal types.
Perhaps it is better to elaborate a bit and say something like:

Temporal types always use my_charset_numeric.
Ensure that it is not changed when altering table charset.

2024-06-05 07:29 UTC, venkatesh-prasad-v commented on sql/sql_table.cc
> +    Always use my_charset_numeric for temporal types.
Done

2024-06-05 07:30 UTC, venkatesh-prasad-v commented
@dlenev Thank you very much for the detailed and the insightful review. I have updated both the commit message and the code comment as per your suggestions.

2024-06-05 07:39 UTC, dlenev approved these changes
Hello Venki!

I think it is OK to push this patch.

2024-06-17 06:47 UTC, merged