PS-9379 Fix problem with "-latomic" on some platforms in uuid_vx (8.0)
percona/percona-server pull request #5407
Opened 2024-09-06 12:08 UTC by lukin-oleksiy

…nent

https://perconadev.atlassian.net/browse/PS-9379

Fix of problem with -latomic in uuid_vx component of some platofrms

2024-09-09 14:49 UTC, percona-ysorokin requested changes

2024-09-09 14:49 UTC, percona-ysorokin commented on components/uuid_vx_udf/CMakeLists.txt
> +# Check if -latomic is required or not
@lukin-oleksiy, I like this approach for detecting the same from `protobuf` more.
https://github.com/percona/percona-server/blob/646a7cf4b6874eb4a9163078febc13c7938328e1/extra/protobuf/protobuf-24.4/CMakeLists.txt#L184
1. They include `CheckCXXSourceCompiles` CMake include for `CHECK_CXX_SOURCE_COMPILES`
   `include(CheckCXXSourceCompiles)`
2. They save and restore `CMAKE_REQUIRED_FLAGS` before and after modifying it
   `set(OLD_CMAKE_REQUIRED_FLAGS ${CMAKE_REQUIRED_FLAGS})`
   ...
   `set(CMAKE_REQUIRED_FLAGS ${OLD_CMAKE_REQUIRED_FLAGS})`
3. they do single line
   `return static_cast<int>(std::atomic<int64_t>{});`
   so, no porential `unused variable` warnings that may affect compilation results.

2024-09-10 12:58 UTC, lukin-oleksiy commented on components/uuid_vx_udf/CMakeLists.txt
> +# Check if -latomic is required or not
Solution is somewhere in the middle, with probe code from rocsdb

2024-09-10 13:21 UTC, percona-ysorokin approved these changes
LGTM

2024-09-10 13:25 UTC, merged