PS-9148 feature: Dictionary caching for Masking Functions Component (8.0)
percona/percona-server pull request #5520
Opened 2024-12-09 01:01 UTC by percona-ysorokin

https://perconadev.atlassian.net/browse/PS-9148

2024-12-20 15:43 UTC, dlenev requested changes
Hello Yura!

Here are some comments about part of the patch I have reviewed so far.

2024-12-20 15:43 UTC, dlenev commented on components/masking_functions/src/masking_functions/registration_routines.cpp
> +        return cs_term_escaped;
So if term is not present in the dictionary our UDF returns its escaped version? And if it is present, we return some non-escaped random replacement term from the dictionary? This difference escaped - non-escaped sounds suspicious to me. Is this intentional change or a bug?

2024-12-20 15:43 UTC, dlenev commented on components/masking_functions/include/masking_functions/basic_sql_context_builder.hpp
> +class basic_sql_context_builder {
It took me some time to figure out class hierarchy for basic_sql_context_builder and its descendants. Perhaps it would be easier if use more standard "abstract_sql_context_builder" for this class, and perhaps add comments describing this class as well as its descendants? What do you think?

2024-12-20 15:43 UTC, dlenev commented on components/masking_functions/src/masking_functions/registration_routines.cpp
> +    ctx.mark_result_nullable(true);
I think it is worth to add a comment that will explain why this function is nullable/in which cases it can return NULL.

2024-12-20 15:43 UTC, dlenev commented on components/masking_functions/src/masking_functions/registration_routines.cpp
> +    const auto cs_term_escaped = escape_string(cs_term);
After a bit more thinking. IMO it is conceptually wrong to do escaping of dictionary and term names on this level (i.e. in UDF implementation). It is something which belongs to the level interacting with SQL. For example, if we will decide to change the implementation and start using prepared statements on the level below, such escaping on a high-level will become unnecessary and will only harm. So I'd like to propose move escaping back to query_builder.cpp layer.
What do you think?

2025-01-08 16:26 UTC, dlenev requested changes
Hello Yura!

Here are bit more comments/questions from me about the PR.

I am continuing my review meanwhile.

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/bookshelf.hpp
> +  bool remove(const std::string &dictionary_name) noexcept;
I think it is worth adding comment to mention what do return values for remove() and insert() mean.
For contains() the name is more or less self-explanatory, but for remove() and insert() it is not obvious, especially in MySQL context.

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/component_sys_variable_service_tuple.hpp
> +// A set of MySQL query services required to perform system variable
Perhaps remove word "query" from this description?

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/default_sql_context_builder.hpp
> +class default_sql_context_builder : public basic_sql_context_builder {
Perhaps it is worth to add a comment describing this class and its difference in comparison to static_sql_context_builder ?

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/dictionary.hpp
> +  bool insert(const std::string &term);
Again IMO it would be nice to document meaning of return values for insert and remove() as it is not obvious.

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/bookshelf.hpp
> +class bookshelf {
IMO it would be nice to add a comment describing what bookshelf class represents. So one won't have to look into its implementation to figure it out. Indeed bookshelf is place where books (in this case dictionaries) are stored, but still IMO it is worth to spell it out explicitly (e.g. we can say something like: "Bookshelf is a collection of objects representing dictionaries used for data-masking with dictionary name as an index").

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/dictionary.hpp
> +class dictionary {
Again, in my opinion, since you are adding new class representing data-masking dictionary it would be nice to add short comment explaining what it is (e.g. collection of terms) and how it is used by data masking functionality on a high-level.

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/dictionary_flusher_thread.hpp
> +//   cache. It can only spawn a background thread that will do this later.
Great comments! However, IMO, it would help if you have mentioned explicitly here that reload of dictionary will be done by this background thread OR by one of data masking UDFs trying to access it, whoever gets to the cache first.

In the end I have found this comment in another file, but having this information in this place would helped me a lot.

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/query_cache.hpp
> +class query_cache {
Hmm... "Query Cache" has pretty specific meaning in MySQL context, so using this name here might create some confusion, in my opinion. And technically, you are not caching queries in it or their results, but rather the whole dictionary.

So perhaps it is a good idea to use some other name for this and  query_cache_core classes? dictionaries_cache perhaps? Or masking_dict_cache ? or something else...

What do you think?

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/query_cache.hpp
> +  bool remove(const std::string &dictionary_name);
As I have said earlier I think it is good idea to document return values from remove() and insert() methods, since they are non-obvious.

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/query_cache.hpp
> +class query_cache {
After a bit more thinking... IMO it is definitely worth adding comment explaining relation between query_cache and query_cache_core, otherwise it is really not obvious why we have primitive singleton which stores pointer to query_cache, which stores pointer to query_cache_core, which stores pointer to bookshelf, where we cache things for real (too much indirection for my taste...).

It might help if we come up with a better names for these classes, after all, AFAICS query_cache class not only contains cache, but also sql_context_builder which controls the way UDFs and background thread work with data masking tables.

2025-01-08 16:26 UTC, dlenev commented on components/masking_functions/include/masking_functions/query_cache.hpp
> +  query_builder_ptr sql_query_builder_;
As far as I can see we have only one instance of query_builder class in the component.
Maybe instead of passing pointer to it around as member function parameter, it makes sense to make it global singleton or simply static member in some class? What do you think?

2025-01-09 12:37 UTC, dlenev requested changes
Hello Yura!

I have a bit more comments about your PR.

2025-01-09 12:37 UTC, dlenev commented on mysql-test/suite/component_masking_functions/t/wait_for_component_uninstall.inc
> +# When flusher thread is enabled in masking functions component,
Such approach looks OK to me for case when explicit UNINSTALL COMPONENT is issued. But I wonder what happens if component deinit happens implicitly as result of shutdown. I.e. what will happen if server starts up, inits component and creates background thread, and then immediately tries to shutdown (e.g. due to some other component init failing).

Will the component deinit work correctly in this case?

2025-01-09 12:37 UTC, dlenev commented on mysql-test/suite/component_masking_functions/r/dictionary_operations.result
>  # checking the case when there is no mysql.masking_dictionaries table
I think, that after changes in this PR you no longer test case here case when mysql.masking_dictionaries is missing, but instead case when mysql_session@localhost user has insufficient privileges on it... Perhaps the test needs to be extended to test both these scenarios, or at least comment should be adjusted?

2025-01-09 12:37 UTC, dlenev commented on mysql-test/suite/component_masking_functions/t/flusher_thread_immediate_restart.test
> +INSTALL COMPONENT 'file://component_masking_functions';
OK. I guess this test will occasionally trigger scenario with immediate shutdown and component deinit failure I have mentioned... But I wonder how often it will happen... Perhaps we can make situation more reproducible by adding debug sleep at various stages of flusher thread initialization? What do you think?

2025-01-09 12:37 UTC, dlenev commented on mysql-test/suite/component_masking_functions/t/flusher_thread_suspend_resume.test
> +SET debug_sync = 'now SIGNAL masking_functions_before_cache_reload_signal WAIT_FOR masking_functions_after_cache_reload_signal';
A good style is to do debug_sync = 'RESET' at the end of part of the test case using debug sync facility. Yes, in your case problems are unlikely due to presence of .opt file for test case, but IMO it is good idea to stick to good style anyway.

2025-01-09 12:37 UTC, dlenev commented on mysql-test/suite/component_masking_functions/t/flusher_thread_connection_reuse.test
> +SET GLOBAL debug = '-d,enable_masking_functions_flusher_create_sync,enable_masking_functions_flush_thread_sync,enable_masking_functions_flush_thread_double_pass';
I think it is a good idea to reset debug_sync facility at the end of the test as well.

2025-01-09 12:37 UTC, dlenev commented on mysql-test/suite/component_masking_functions/t/rpl_dictionaries_flush_interval.test
> +SET GLOBAL debug ='-d,enable_masking_functions_flush_thread_sync';
Ditto here. I think it is a good style to reset debug_sync facility at the end of the test as well for both master and slave (though we are not likely to see any problems for this specific test due to such resetting missing).

2025-01-11 01:58 UTC, percona-ysorokin commented
This PR is suspended. All its comment will be addressed in the new one
https://github.com/percona/percona-server/pull/5535
(rebased on 8.0.40, squashed commits, fixed clang-tidy warnings for `component_masking_functions` code).

2025-01-13 14:12 UTC, percona-ysorokin commented on components/masking_functions/src/masking_functions/registration_routines.cpp
> +        return cs_term_escaped;
This layer has been significantly reworked:

2025-01-13 14:34 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/basic_sql_context_builder.hpp
> +class basic_sql_context_builder {
`basic_sql_context_builder` renamed to `abstract_sql_context_builder`.
Added a comment describing class hierarchy and purpose of each class.

2025-01-13 14:35 UTC, percona-ysorokin commented on components/masking_functions/src/masking_functions/registration_routines.cpp
> +    ctx.mark_result_nullable(true);
No longer nullable

2025-01-13 14:36 UTC, percona-ysorokin commented on components/masking_functions/src/masking_functions/registration_routines.cpp
> +    const auto cs_term_escaped = escape_string(cs_term);
SQL escaping on that level was definitely a wrong decision - this has been reworked properly now.

2025-01-13 14:49 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/bookshelf.hpp
> +  bool remove(const std::string &dictionary_name) noexcept;
Done

2025-01-13 14:50 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/component_sys_variable_service_tuple.hpp
> +// A set of MySQL query services required to perform system variable
Done

2025-01-13 14:50 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/default_sql_context_builder.hpp
> +class default_sql_context_builder : public basic_sql_context_builder {
Done

2025-01-13 14:51 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/dictionary.hpp
> +  bool insert(const std::string &term);
Done

2025-01-13 14:54 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/bookshelf.hpp
> +class bookshelf {
Done

2025-01-13 16:20 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/dictionary.hpp
> +class dictionary {
Done

2025-01-13 16:37 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/dictionary_flusher_thread.hpp
> +//   cache. It can only spawn a background thread that will do this later.
Done

2025-01-13 23:00 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/query_cache.hpp
> +class query_cache {
`query_cache` renamed to `term_cache`
`query_cache_core` renamed to `term_cache_core`
Added class descriptions.

2025-01-13 23:01 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/query_cache.hpp
> +  bool remove(const std::string &dictionary_name);
Done

2025-01-14 00:30 UTC, percona-ysorokin commented on components/masking_functions/include/masking_functions/query_cache.hpp
> +  query_builder_ptr sql_query_builder_;
Good point. Reworked as a global singleton - this simplified a lot of interfaces.

2025-01-14 00:44 UTC, percona-ysorokin commented on mysql-test/suite/component_masking_functions/t/wait_for_component_uninstall.inc
> +# When flusher thread is enabled in masking functions component,
From what I saw during debugging MySQL server during shutdown completely ignores the statuses of the component `deinit()` functions. So, there is a change that after our `deinit()` function completes (with error code), our background thread will still be alive. However, becase we registered our thread in the session manager, another part of the MySQL Server shutdown logic will iterate over remaining active sessions and will make several attempts of gracefully killing them (by setting `THD->killed` flag). One of the most recent flusher thread modifications made sure thsat we react properly to the `THD->killed`. So, this scenario is covered as well.

2025-01-14 01:16 UTC, percona-ysorokin commented on mysql-test/suite/component_masking_functions/t/flusher_thread_suspend_resume.test
> +SET debug_sync = 'now SIGNAL masking_functions_before_cache_reload_signal WAIT_FOR masking_functions_after_cache_reload_signal';
Done

2025-01-14 01:16 UTC, percona-ysorokin commented on mysql-test/suite/component_masking_functions/t/flusher_thread_connection_reuse.test
> +SET GLOBAL debug = '-d,enable_masking_functions_flusher_create_sync,enable_masking_functions_flush_thread_sync,enable_masking_functions_flush_thread_double_pass';
Done

2025-01-14 01:16 UTC, percona-ysorokin commented on mysql-test/suite/component_masking_functions/t/rpl_dictionaries_flush_interval.test
> +SET GLOBAL debug ='-d,enable_masking_functions_flush_thread_sync';
Done

2025-01-14 01:17 UTC, percona-ysorokin commented on mysql-test/suite/component_masking_functions/r/dictionary_operations.result
>  # checking the case when there is no mysql.masking_dictionaries table
See previous response
https://github.com/percona/percona-server/pull/5520?timeline_per_page=10#discussion_r1913972030

2025-01-14 01:19 UTC, percona-ysorokin commented on mysql-test/suite/component_masking_functions/t/flusher_thread_immediate_restart.test
> +INSTALL COMPONENT 'file://component_masking_functions';
See previous response

2025-01-14 02:13 UTC, percona-ysorokin commented on mysql-test/suite/component_masking_functions/r/dictionary_operations.result
>  # checking the case when there is no mysql.masking_dictionaries table
MTR test case extended with both scenarios.

2025-01-21 02:59 UTC, closed without merging