PS-9391 Fixes replication break error because of HASH_SCAN
percona/percona-server pull request #5528
Opened 2024-12-26 10:22 UTC by VarunNagaraju

https://perconadev.atlassian.net/browse/PS-9391

Problem
=======
When a replica's slave_rows_search_algorithms is set to HASH_SCAN, the
replication may break with HA_ERR_KEY_NOT_FOUND.

Analysis
========
When a replica's slave_rows_search_algorithms is set to HASH_SCAN,
it prepares a unique key list for all the rows in a particular Row_event.
The same unique key list will later be used to retrieve all tuples associated
to each key in the list from storage engine. In the case of multiple updates
targeted at the same row like how it is shown in the testcase, it may happen
that this unique key list filled with entries which don't exist yet in the table.
This is a problem when there is an intermediate update which changes the value
of the index column to a lesser value than the original entry and that changed
value is used in another update as shown in the second part of the testcase.
It is an issue because the unique key list is a std::set which internally
sorts it's entries. When this sorting happens, the first entry of the list
could potentially be a value which doesn't exist in the table and the when
it is searched in next_record_scan() method, it fails returning
HA_ERR_KEY_NOT_FOUND error.

Solution
========
Instead of using std::set to store the distinct keys, a combination of
unordered_set and a list is used to preserve the original order of
updates and avoid duplicates at the same time which prevents the side
effects of sorting.

2024-12-27 04:15 UTC, VarunNagaraju commented
https://ps80.cd.percona.com/view/8.0/job/percona-server-8.0-pipeline-parallel-mtr/847/

2025-01-06 12:47 UTC, percona-ysorokin requested changes

2025-01-06 12:47 UTC, percona-ysorokin commented on sql/log_event.h
> +                      k2, (*m_key_info)->key_length) == 0;
Rename this helper class to `Key_equal`.
`Compare` may be misleading as it may mean `comparator` and in your scenario this is no longer the case. All you do now is checking for equality.

2025-01-06 12:47 UTC, percona-ysorokin commented on sql/log_event.h
> +      size_t operator()(uchar* ptr) const {
May be just create a `std::string_view` from `ptr` and `(*m_key_info)->key_length` and calculate a hash of this string_view using standard hash function.
```c++
std::string_view sv{ptr, (*m_key_info)->key_length};
return std::hash(sv);
```

2025-01-06 12:47 UTC, percona-ysorokin commented on sql/log_event.cc
> +  std::pair<std::unordered_set<uchar *, Key_hash, Key_compare>::iterator, bool> ret =
May be just `auto`?

2025-01-06 12:47 UTC, percona-ysorokin commented on sql/log_event.cc
> -      m_itr = m_distinct_keys.begin();
Shouldn't we change this to `m_distinct_key_id = 0`?

2025-01-06 12:47 UTC, percona-ysorokin commented on sql/log_event.cc
> +          sleep(10);
Is this intentional or just for debugging?

2025-01-07 07:20 UTC, VarunNagaraju commented on sql/log_event.h
> +                      k2, (*m_key_info)->key_length) == 0;
Done

2025-01-07 07:20 UTC, VarunNagaraju commented on sql/log_event.cc
> +          sleep(10);
It was just for debugging. Removed it.

2025-01-07 07:21 UTC, VarunNagaraju commented on sql/log_event.cc
> -      m_itr = m_distinct_keys.begin();
m_distinct_key_idx is already set to 0 when it is declared.

2025-01-07 07:21 UTC, VarunNagaraju commented on sql/log_event.cc
> +  std::pair<std::unordered_set<uchar *, Key_hash, Key_compare>::iterator, bool> ret =
Done

2025-01-07 07:22 UTC, VarunNagaraju commented on sql/log_event.h
> +      size_t operator()(uchar* ptr) const {
Thanks for the suggestion. Done.

2025-01-08 06:51 UTC, VarunNagaraju commented
https://ps80.cd.percona.com/view/8.0/job/percona-server-8.0-pipeline-parallel-mtr/849/

2025-01-13 11:35 UTC, percona-ysorokin approved these changes
LGTM with one `m_distinct_key_id = 0` comment addressed

2025-01-13 11:35 UTC, percona-ysorokin commented on sql/log_event.cc
> -      m_itr = m_distinct_keys.begin();
@VarunNagaraju my point here is that you do not have this initial initialization logic in the constructor of the `Rows_log_event` class but instead have a special function `open_record_scan()` in the interface of this class.
Which means that theoretically the user of this class is allowed to do
```
open_record_scan();
while(...) {
  next_record_scan();
  ...  
}
// and then start iteration for the second time
open_record_scan();
while(...) {
  next_record_scan();
  ...  
}
```
I understand that currently this is not happening - just want to be "future changes"-proof 🙂 here.
In other words, I would still put that `m_distinct_key_id = 0` here.

2025-01-20 14:11 UTC, VarunNagaraju commented
https://ps80.cd.percona.com/job/percona-server-8.0-param-parallel-mtr/78/

2025-01-20 14:15 UTC, merged